### ISSUE TITLE
Suggest donating to Let's Encrypt after successful issuance

### ISSUE THREAD

**Issue by bdaehlie** [letsencrypt/letsencrypt#1007]
We should ask people to donate to Let's Encrypt after successful issuance of a certificate through our client. Maybe present 1-2 sentences and a link to where they can donate. It should be easy to disable this via command-line flag (or some other mechanism).

**Comment by pde** [comment]
I think this is something we should prioritise as soon as we feel like we're free of showstoppers, which will hopefully be before GA :)
