### ISSUE TITLE
Fix intermittent failure when testing acme.standalone

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1021]
I'm unable to recreate the problem locally, but `cover` is failing intermittently on Travis. Here's a build where it [passes](https://travis-ci.org/letsencrypt/letsencrypt/jobs/85999096#L931) and [fails](https://travis-ci.org/letsencrypt/letsencrypt/jobs/85999090#L1399). Neither PR touches in anything in the `acme` module and both are up to date with `master`.

**Comment by kuba** [comment]
First occurrence of the problem is #895, https://travis-ci.org/letsencrypt/letsencrypt/jobs/84990239 (73ae361). https://github.com/kuba/letsencrypt/commit/c4042e6ce8c74e85854343b20350fb497d0232d6 was meant to fix it.
