### ISSUE TITLE
FYI: How is NSA breaking so much crypto?

### ISSUE THREAD

**Issue by DavidBruchmann** [letsencrypt/letsencrypt#1022]
https://freedom-to-tinker.com/blog/haldermanheninger/how-is-nsa-breaking-so-much-crypto/

**Comment by bmw** [comment]
Thanks for the link @DavidBruchmann, but we're well aware of the article. Alex Halderman, one of authors of the article you linked, is on our [board](https://letsencrypt.org/isrg/).

**Comment by DavidBruchmann** [comment]
Ok, thanks for the info!
