### ISSUE TITLE
Handle --redirect flag appropriately

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1030]
The client does not properly handle the case when `--redirect` is specified on the command line. The root of the problem is this argument is treated as a binary variable in `cli.py` (`True` or `False`) and a ternary variable in `client.py` (`True`, `False`, or `None`). The resulting behavior is if `--redirect` is not specified on the command line, `client.py` assumes the user does not want a redirect.

The simple fix is to prompt the user on whether or not they want a redirect if `--redirect` is not included on the command line. A better fix is to allow the user to specify whether or not they want a redirect on the command line and prompting them if nothing is specified.

**Comment by ilkka** [comment]
I'd like to contribute and was thinking that I'd start with this. Looking over the option parsing, there doesn't seem to be a consistent `--foo` + `--no-foo` pattern. This would be quite a good match though, or would `--redirect ARG` be more idiomatic?

**Comment by ilkka** [comment]
The `--foo` + `--no-foo` is pretty simple to implement as

```
parser.add_argument('--foo', dest='foo', action='store_true', help='Turn on foo')
parser.add_argument('--no-foo', dest='foo', action='store_false', help='Turn off foo')
parser.set_defaults(foo=None)
```

but the problem with that is a spurious "(default: None)" in the help text for both arguments.

**Comment by AdamBark** [comment]
It seems to me like @bmw was suggesting making cli.py use a ternary as well and then prompting if --redirect is not specified i.e. the variable holds None.

**Comment by bmw** [comment]
@ilkka, welcome to the project. If you'd be interested in trying to tackle this, we'd certainly appreciate the help. If you run into any issues, don't hesitate to contact us.

I think `--redirect` or `--no-redirect` is probably the preferred approach and can mimicked by enhancements in the future.
