### ISSUE TITLE
Subject of CSR

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1031]
There is a `TODO` item about what to include as the subject field of a CSR. Currently, we simply include the first domain specified as the `commonName` and leave all other fields blank. Is this the behavior we want?

**Comment by pde** [comment]
I think this behavior is fine. Perhaps we can document somewhere that you can tweak you common name by reordering the domain flags? But really, the order shouldn't matter except for aesthetic purposes.
