### ISSUE TITLE
Dev config example in user's guide might be confusing

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1045]
User reported that all his certs landed in `/tmp/le/conf`... Root cause? Blindly copying config file presented at http://letsencrypt.readthedocs.org/en/latest/using.html#configuration-file. Maybe it would be better not to show **dev** config as an example over there?

**Comment by laebshade** [comment]
Preceding each line with an octothorpe would solve the problem with users
blindly copying the config file; they'd have to uncomment to enable then.

**Comment by bmw** [comment]
@kuba, I agree that the dev example shouldn't be used as an example configuration file. We should take the time to write up one for normal users. Any ideas?
