### ISSUE TITLE
letsencrypt-auto doesn't work with Python 2.6

### ISSUE THREAD

**Issue by NoodlesNZ** [letsencrypt/letsencrypt#1046]
When running letsencrypt-auto I get the following:

```
Creating virtual environment...
Updating letsencrypt and virtual environment dependencies...../root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TVlyY0/ConfigArgParse
/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```
I think this relates to the ConfigArgParse problem that @kuba was trying to fix.

**Comment by kuba** [comment]
I seems to relate to `ConfigArgParse`, but not to the problem I was trying to solve. `letsencrypt-auto` gets stuff from PyPI only, including https://pypi.python.org/pypi/ConfigArgParse/0.9.3.

Could you look around `/tmp/pip-build-TVlyY0` and pastebin relevant files?

**Comment by NoodlesNZ** [comment]
I can't see that directory on my filesystem, I'm not familiar with virtualenv, is it hidden away somewhere else?

**Comment by ChrisOrlando** [comment]
This is happening for me too. The /tmp/pip-build-XXXXX directory doesn't seem to exist afterward, so I can't send the contents.

**Comment by dwyer** [comment]
I removed the `> /dev/null`s so I can catch the error.

    Collecting letsencrypt
      Using cached letsencrypt-0.0.0.dev20151020-py2-none-any.whl
    Collecting zope.interface (from letsencrypt)
      Using cached zope.interface-4.1.3.tar.gz
    Requirement already up-to-date: setuptools in /home/kc/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
    Collecting python2-pythondialog>=3.2.2rc1 (from letsencrypt)
      Using cached python2-pythondialog-3.3.0.tar.bz2
    Collecting PyOpenSSL (from letsencrypt)
      Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
    Collecting requests (from letsencrypt)
      Using cached requests-2.8.1-py2.py3-none-any.whl
    Collecting pyrfc3339 (from letsencrypt)
      Using cached pyRFC3339-0.2.tar.gz
    Collecting parsedatetime (from letsencrypt)
      Using cached parsedatetime-1.5-py2-none-any.whl
    Collecting configobj (from letsencrypt)
      Using cached configobj-5.0.6.tar.gz
    Collecting pytz (from letsencrypt)
      Using cached pytz-2015.6-py2.py3-none-any.whl
    Collecting psutil>=2.1.0 (from letsencrypt)
      Using cached psutil-3.2.2.tar.gz
    Collecting six (from letsencrypt)
      Using cached six-1.10.0-py2.py3-none-any.whl
    Collecting cryptography>=0.7 (from letsencrypt)
      Using cached cryptography-1.0.2.tar.gz
    Collecting zope.component (from letsencrypt)
      Using cached zope.component-4.2.2.tar.gz
    Collecting mock (from letsencrypt)
      Using cached mock-1.3.0-py2.py3-none-any.whl
    Collecting ConfigArgParse (from letsencrypt)
      Using cached ConfigArgParse-0.9.3.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-C7iwhM/ConfigArgParse/setup.py", line 1, in <module>
            import configargparse
          File "configargparse.py", line 16
            ACTION_TYPES_THAT_DONT_NEED_A_VALUE = {argparse._StoreTrueAction,
                                                                            ^
        SyntaxError: invalid syntax
        
        ----------------------------------------

It appears that `python2` is symlinked to `python2.6` which doesn't support the set syntax.

My workaround:

  rm -rf ~/.local/share/letsencrypt
  sed -i 's/python2/python2.7/g' letsencrypt-auto
  ./letsencrypt-auto

**Comment by NoodlesNZ** [comment]
That seems to fix the letsencrypt-auto, but when trying to run letsencrypt I get this:
```
# /usr/bin/letsencrypt
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ConfigArgParse
```

**Comment by kuba** [comment]
Why are you installing stuff to `/usr/bin`? Please use `letsencrypt-auto`, other modes of operation are not supported.

**Comment by NoodlesNZ** [comment]
Sorry, my bad. I think I accidentally ran the setup.py when playing around with it. I got a fresh VM and tried again with ```letsencrypt-auto``` and this is what I got:

```
...
Creating virtual environment...
The executable python2.7 (from --python=python2.7) does not exist
```
So the fix from @dwyer doesn't seem to work. Would it be possible to pin ConfigArgParse to an earlier version that works with python 2.6.x?

**Comment by kuba** [comment]
Can you please update title to "letsencrypt-auto doesn't work with Python 2.6"?

It was decided at some point of the development to discount Python 2.6 support. https://github.com/letsencrypt/letsencrypt/pull/957 is meant to bring back this support and is targeted for the General Availability. No support for Centos 6 might bring it even closer.

**Comment by NoodlesNZ** [comment]
Done. I'll have a play and see if I can find a work around.

**Comment by kuba** [comment]
(That being said, client should work in Python 2.6, if you use some magic tricks, such as https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151020/requirements.txt - a file which is a part of the process further described in http://letsencrypt.readthedocs.org/en/latest/contributing.html. But, as I said, we don't support Python 2.6 at this stage!)

**Comment by bmw** [comment]
Closing since Python 2.6 isn't currently supported. Expect this to change around our official launch date (week of November 16th).

**Comment by bmw** [comment]
And we're supporting Python 2.6 again! We're looking into resolving these problems.

**Comment by durian808** [comment]
Joining thread to find out when Python 2.6 is completed.  Thanks!

**Comment by mentor2k1** [comment]
Joining thread to get updates.

**Comment by linickx** [comment]
For CentOS 6 users, Python 2.7 is part of [SCL](https://wiki.centos.org/AdditionalResources/Repositories/SCL), the gotcha being that you have to `scl enable python27` to enable, prior to running any commands. I am poking at the bootstrap scripts to see if I can make this work. HTH.

**Comment by WarpinWolf** [comment]
Joining to get updates....

**Comment by kuba** [comment]
This will be fixed in #1257.

**Comment by f0086** [comment]
Thanks! I've tried your branch/repo and it worked!
Waiting to merge into master ...

**Comment by durian808** [comment]
running letsencrypt-auto, I get this...

"WARNING: Python 2.6 support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!"

Where can I sign up for updates so that I'll know when Python 2.6 is fully supported?

thanks

**Comment by mayasl** [comment]
Devs! Please take a look at this. http://pastebin.com/Gn70tyKK

**Comment by NoodlesNZ** [comment]
For what it's worth python-configargparse is now in EPEL 6/7 with @kuba 's patch for python 2.6
