### ISSUE TITLE
Apply Coverity static security scanning 

### ISSUE THREAD

**Issue by javabeanz** [letsencrypt/letsencrypt#1051]
Coverity offers free static security analysis for open source projects, with reasonable results from my experience.

**Comment by ArchimedesPi** [comment]
@javabeanz AFAIK, Coverity doesn't support Python (what the client is written in). Or Go (what Boulder, the CA/ACME server, is written in).

**Comment by bmw** [comment]
[Confirmed](http://www.coverity.com/why-coverity/#Developers). Thanks for the suggestion though @javabeanz.
