### ISSUE TITLE
Auth command with --csr flag fails

### ISSUE THREAD

**Issue by phpmypython** [letsencrypt/letsencrypt#1052]
Example command would be 
```bash
sudo -H ./letsencrypt-auto auth --csr ../dev.example.com.csr
```
where the path to the CSR is a csr that you have generated.

**Comment by kuba** [comment]
The real problem is that --csr accepts a "[p]ath to a Certificate Signing Request (CSR) in DER format.". But it bails on PEM CSRs.

**Comment by bmw** [comment]
The real real problem is the code reads from the SANs extension of which names to use. If this extension isn't included, you get `AssertionError: Authorizations list is empty`.

**Comment by phpmypython** [comment]
If the CSR is only for one domain though is that still there?

**Comment by bmw** [comment]
Yep. With the current setup, even if the CSR is only for one domain, the SANs extension has to be there.

**Comment by pde** [comment]
Let's document that in the help for the --csr flag.

**Comment by phpmypython** [comment]
Would we be open to making where it can accept either type of CSR and make it where it will use a CSR with a single domain even without the SANs extension.

My expertise are not in the python arena but i would be to try and take a crack at it.

**Comment by bmw** [comment]
I created #1075 and #1076 to better track issues discussed here.

@phpmypython, if you'd like to have a go at #1076, that'd be great. Unfortunately, I don't think it will be a trivial fix, but we'd appreciate the help!

**Comment by pde** [comment]
I'm in two minds about this.  On one hand, it might help with integration of some existing systems that produce CSRs.  On the other hand, the server is going to *insist* that the SAN be present for spec compliance reasons.  In any case, I don't think there's a sane path to fixing it in the client (you'd need the private key to make a new CSR); this behaviour could be altered in [boulder](/letsencrypt/boulder) but I suspect the developers will be somewhat reluctant to do do.

**Comment by pde** [comment]
I think the ACME spec says this should be allowed, but the X.509 specs say that all names should be SANs now.

**Comment by kuba** [comment]
@pde, we don't forward CSRs, so I think it's OK to read CN + SAN in the client and turn it into a cert with CN + SAN

**Comment by sunnybear** [comment]
Hello. Any working solution? --csr signreq.der fails with AssertionError: Authorizations list is empty

**Comment by bmw** [comment]
@sunnybear, https://github.com/letsencrypt/letsencrypt/issues/1052#issuecomment-149739864

**Comment by sunnybear** [comment]
Thank you. How to include SAN extension?
