### ISSUE TITLE
Server certificate validation failure on Centos 7.1

### ISSUE THREAD

**Issue by oneumyvakin** [letsencrypt/letsencrypt#1060]
Centos 7.1

*STEPS*
./letsencrypt-auto
./letsencrypt-auto auth

*RESULT*
In /var/log/letsencrypt/letsencrypt.log:

2015-04-30 12:52:01,265:DEBUG:root:Sending GET request to https://acme-staging.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-04-30 12:52:01,279:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2015-04-30 12:52:03,132:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1085, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 450, in auth
    le_client = _init_le_client(args, config, authenticator, installer)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 160, in _init_le_client
    acc, acme = _determine_account(args, config)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 147, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 87, in register
    acme = _acme_from_config_key(config, key)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 35, in _acme_from_config_key
    verify_ssl=(not config.no_verify_ssl))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 60, in __init__
    self.net.get(directory).json())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 599, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 581, in _send_request
    response = requests.request(method, url, *args, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

**Comment by kuba** [comment]
Hm, `ca-certificates` package is being installed in bootstrap, so we should be fine...

**Comment by oneumyvakin** [comment]
I can confirm that ca-certificates was updated at ./letsencrypt-auto execution

**Comment by kuba** [comment]
None of the devs works on Centos, so we can't help you much at this stage. But this looks as if you were missing appropriate CA bundles or.... you're under MITM attack. What does `curl https://acme-staging.api.letsencrypt.org/directory` show?

**Comment by pde** [comment]
@jcjones is running CentOS...

**Comment by jcjones** [comment]
I have not had this issue on CentOS `6.7` or `7.1.1503`, the two platforms I've run the client on.

**Comment by skpy** [comment]
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```
```
$ curl -v https://acme-staging.api.letsencrypt.org/directory
* About to connect() to acme-staging.api.letsencrypt.org port 443 (#0)
*   Trying 23.202.196.37...
* Connected to acme-staging.api.letsencrypt.org (23.202.196.37) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_RSA_WITH_3DES_EDE_CBC_SHA
* Server certificate:
* 	subject: C=US,ST=California,L=Mountain View,O=INTERNET SECURITY RESEARCH GROUP,CN=*.api.letsencrypt.org
* 	start date: Jun 26 17:05:45 2015 GMT
* 	expire date: Jun 25 17:05:45 2018 GMT
* 	common name: *.api.letsencrypt.org
* 	issuer: CN=TrustID Server CA A52,OU=TrustID Server,O=IdenTrust,C=US
> GET /directory HTTP/1.1
> User-Agent: curl/7.29.0
> Host: acme-staging.api.letsencrypt.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/json
< Content-Length: 279
< Replay-Nonce: L25vRz69SYw6wbOB-MbZ5wpXNF7HzWBMpWe0aIVsthU
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=604800
< Access-Control-Allow-Origin: *
< Expires: Thu, 22 Oct 2015 02:50:10 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Thu, 22 Oct 2015 02:50:10 GMT
< Connection: keep-alive
<
* Connection #0 to host acme-staging.api.letsencrypt.org left intact
{"new-authz":"https://acme-staging.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-staging.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-staging.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-staging.api.letsencrypt.org/acme/revoke-cert"}
```

**Comment by pde** [comment]
I tried to repro with an AWS RHEL 7.1 image, but didn't encounter the problem.

**Comment by pde** [comment]
@oneumyvakin two things that could help us with diagnostics:

1. Paste the output of this command `echo | openssl s_client -connect acme-staging.api.letsencrypt.org:443`

2. Send us a copy of the contents of your ca-certificates package!

**Comment by oneumyvakin** [comment]
I've checked on another Centos 7.1 - issue still persist for me

[root@cos71x64-plesk12 letsencrypt-master]# echo | openssl s_client -connect acme-staging.api.letsencrypt.org:443
CONNECTED(00000003)
depth=3 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=2 C = US, O = IdenTrust, CN = IdenTrust Commercial Root CA 1
verify return:1
depth=1 C = US, O = IdenTrust, OU = TrustID Server, CN = TrustID Server CA A52
verify return:1
depth=0 CN = *.api.letsencrypt.org, O = INTERNET SECURITY RESEARCH GROUP, L = Mountain View, ST = California, C = US
verify error:num=9:certificate is not yet valid
notBefore=Jun 26 17:05:45 2015 GMT
verify return:1
depth=0 CN = *.api.letsencrypt.org, O = INTERNET SECURITY RESEARCH GROUP, L = Mountain View, ST = California, C = US
notBefore=Jun 26 17:05:45 2015 GMT
verify return:1
---
Certificate chain
 0 s:/CN=*.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US
   i:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
 1 s:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
   i:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
 2 s:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHDzCCBfegAwIBAgIQfwAAAQAAAU4w1QtkQskueDANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJVUzESMBAGA1UEChMJSWRlblRydXN0MRcwFQYDVQQLEw5UcnVz
dElEIFNlcnZlcjEeMBwGA1UEAxMVVHJ1c3RJRCBTZXJ2ZXIgQ0EgQTUyMB4XDTE1
MDYyNjE3MDU0NVoXDTE4MDYyNTE3MDU0NVowgYUxHjAcBgNVBAMTFSouYXBpLmxl
dHNlbmNyeXB0Lm9yZzEpMCcGA1UEChMgSU5URVJORVQgU0VDVVJJVFkgUkVTRUFS
Q0ggR1JPVVAxFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxEzARBgNVBAgTCkNhbGlm
b3JuaWExCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAlkLBpvVuOTZrpaPkzmAx+5OcK6gffKPon8E6ktJmNsjfrh3ATdgKt121ccD+
7I3gBcZu5euG1ldynO/wx29oeGhBiiWx9Bkm1brFKDLvH56ztO29xEo5ZQnxV7w0
25NvjBca5J2tRiAIjcdjMITE1usp5rrNLNM2LIs1RutP7bexvuNv2dGyJ0uNIWI4
Ym2Tt5rnUTx7Vsz0M4nz2i6sSB9ajrSa1h4hFrZYqIU/zpl20f7So8oZDYCZN4WY
xYgbUuEneWxFigElkJbNk0UeVN26tdMGHdIWCabgoZSy80X+pFvxCgdbLQzS0LXQ
orqkGsMYO0+fjjmLj0742IHYswIDAQABo4IDozCCA58wDgYDVR0PAQH/BAQDAgWg
MIICJwYDVR0gBIICHjCCAhowggELBgpghkgBhvkvAAYDMIH8MEAGCCsGAQUFBwIB
FjRodHRwczovL3NlY3VyZS5pZGVudHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xp
Y3kvdHMvMIG3BggrBgEFBQcCAjCBqhqBp1RoaXMgVHJ1c3RJRCBTZXJ2ZXIgQ2Vy
dGlmaWNhdGUgaGFzIGJlZW4gaXNzdWVkIGluIGFjY29yZGFuY2Ugd2l0aCBJZGVu
VHJ1c3QncyBUcnVzdElEIENlcnRpZmljYXRlIFBvbGljeSBmb3VuZCBhdCBodHRw
czovL3NlY3VyZS5pZGVudHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMv
MIIBBwYGZ4EMAQICMIH8MEAGCCsGAQUFBwIBFjRodHRwczovL3NlY3VyZS5pZGVu
dHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMvMIG3BggrBgEFBQcCAjCB
qhqBp1RoaXMgVHJ1c3RJRCBTZXJ2ZXIgQ2VydGlmaWNhdGUgaGFzIGJlZW4gaXNz
dWVkIGluIGFjY29yZGFuY2Ugd2l0aCBJZGVuVHJ1c3QncyBUcnVzdElEIENlcnRp
ZmljYXRlIFBvbGljeSBmb3VuZCBhdCBodHRwczovL3NlY3VyZS5pZGVudHJ1c3Qu
Y29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMvMB0GA1UdDgQWBBQvAQatcXq62MSt
v2WLHPKwErqzgDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vdmFsaWRhdGlvbi5p
ZGVudHJ1c3QuY29tL2NybC90cnVzdGlkY2FhNTIuY3JsMIGEBggrBgEFBQcBAQR4
MHYwMAYIKwYBBQUHMAGGJGh0dHA6Ly9jb21tZXJjaWFsLm9jc3AuaWRlbnRydXN0
LmNvbTBCBggrBgEFBQcwAoY2aHR0cDovL3ZhbGlkYXRpb24uaWRlbnRydXN0LmNv
bS9jZXJ0cy90cnVzdGlkY2FhNTIucDdjMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
BgEFBQcDAjAfBgNVHSMEGDAWgBSiViQ80NQVuei/eKMTEFhILhZU4TA1BgNVHREE
LjAsghUqLmFwaS5sZXRzZW5jcnlwdC5vcmeCE2FwaS5sZXRzZW5jcnlwdC5vcmcw
DQYJKoZIhvcNAQELBQADggEBAIgV29HRYYk2RfrkE6KOeAT6K3AJsKgNe+i9Pdo7
YLdiDGMv/kKyyTNsq4l8IEaY1kw3aqkyT44D8vp6yGbbNl1uAE4VnaPeChLOBK0G
xz3CjtoZPqLxmieft8jybIVWZKZlIIsZrSMaEvrmRTGYartBSuxqOzIjCNxvkkRt
MYDNYRhiy6NPMtA0kpDQCN6tOggXdCm19kmzKI8pUvQGCnGscXJvlQIeaZva0GWf
UOuPael/zohUUsm2lJowlIli939RdxUal0hwv8tD12qAyZAF2/+4y61ds4svGD9B
ukNnsAzS3EXNqq5qWFqRQyiTZfCcjaXEdtySyNAUiM6eFTY=
-----END CERTIFICATE-----
subject=/CN=*.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US
issuer=/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 5917 bytes and written 375 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 1092FBECC5F619CDB3D15540A1DBC38D39123B3D0ACD6856B57EF8D6B79C251C
    Session-ID-ctx:
    Master-Key: 48BCBACA30B9D3847A608B69A26B75766FA64080B479108DF8B527B8C72D376A17CF48A9BC6DBC69C67EB9F53D7B65CC
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - d9 86 1e 5b 90 a6 11 90-2b 11 9e 60 66 0f 18 80   ...[....+..`f...
    0010 - 4d 9a 15 52 68 66 5a 46-70 76 26 14 bb be 88 ea   M..RhfZFpv&.....
    0020 - 37 75 b9 86 e6 6c 11 9f-32 95 1c 4d 80 1e f7 22   7u...l..2..M..."
    0030 - 3b b0 10 79 ad 7b c7 f0-67 d3 3e 54 e3 ab 47 29   ;..y.{..g.>T..G)
    0040 - d6 8a 72 ed 66 6e aa c5-74 1f 8a d9 81 dd b6 cc   ..r.fn..t.......
    0050 - 22 ae b2 81 0a 70 fc e1-2c 91 33 8b 5a 94 76 3a   "....p..,.3.Z.v:
    0060 - 11 68 b7 0f a1 5a a9 b2-ad 5b 6a a9 6b 32 bd d0   .h...Z...[j.k2..
    0070 - 63 4b af 49 15 12 e8 8f-d1 6c 5e d2 d2 3d 43 4b   cK.I.....l^..=CK
    0080 - 9c 6f 03 86 a4 0f 39 6c-05 3f 5e 60 8f 06 8b 92   .o....9l.?^`....
    0090 - e7 83 92 04 12 94 34 1f-e8 f3 93 d4 bd ba c3 7c   ......4........|

    Start Time: 1432950264
    Timeout   : 300 (sec)
    Verify return code: 9 (certificate is not yet valid)
---
DONE

**Comment by oneumyvakin** [comment]
I've gather files from installed ca-certificates package to https://github.com/oneumyvakin/misc/blob/master/ca-certificates.tar.gz

**Comment by kuba** [comment]
Wrong date on your system? Indeed, `2015-04-30` doesn't look good! :)

I'll close this issue for now, please yell at me if you think it should be re-opened.

**Comment by pde** [comment]
@oneumyvakin not your fault; it once took me three days to work out that my Android phone was misbehaving terribly because the clock being wrong was breaking outbound TLS.  We should possibly add a date sanity check to the client somewhere, or at least some code to suggest that explanation to the user in case this error occurs.
