### ISSUE TITLE
Debian 7, build with letsencrypt-auto fails -- virtualenv not found

### ISSUE THREAD

**Issue by akamensky** [letsencrypt/letsencrypt#1061]
Here is the log:

```
0 upgraded, 0 newly installed, 0 to remove and 228 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libaugeas0 is already the newest version.
ca-certificates is already the newest version.
dialog is already the newest version.
gcc is already the newest version.
git-core is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
The following package was automatically installed and is no longer required:
  libgssglue1
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 228 not upgraded.
Creating virtual environment...
./letsencrypt-auto: 63: ./letsencrypt-auto: virtualenv: not found
```

Also on annoying side -- it does not need to attempt to reinstall packages if they are already present in system...

**Comment by kuba** [comment]
You should be able to call `virtualenv` on your own. `/usr/bin/virtualenv` is part of https://packages.debian.org/wheezy/all/python-virtualenv/filelist... That being said, are you by any chance using backports?

Problematic line: https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151020/bootstrap/_deb_common.sh#L27.

**Comment by pde** [comment]
@kuba, rather than trying to correctly predict the name of the virtualenv package, my instinct would be to try to install one and then fallback to the other if the first doesn't work.  The ordering could be predicted...

**Comment by kuba** [comment]
Initial idea was to have a self contained list of required packages that fit into single call to `$package_manager`. Your idea might be worth considering, though. However, it's not about the order: `python-virtualenv` was at some point split into `python-virtualenv` and `virtualenv` - we always need `virtualenv` and if it's not present, then try `python-virtualenv`. Logic gets quite complicated this way...

Nevertheless, let's wait for user's feedback, because I'm slightly surprised by this behavior.

**Comment by pde** [comment]
OK.  I'm drafting a PR that will make one assumption, which is simply that if these packages are available, it's never bad to install them.

**Comment by bmw** [comment]
I just tested this on a Wheezy Digital Ocean droplet. Both with and without backports, I experienced no issue.

**Comment by pde** [comment]
I suspect this bug will arise from the use of `lsb_release` to decide what packages virtualenv is available in. From the lsb_release man page:
> Detection of systems using a mix of packages from various distributions or releases  is  something  of  a  black  art; the current heuristic tends to assume that the installation is of  the  earliest  distribution  which  is still being used by apt but that heuristic is subject to error.
