### ISSUE TITLE
letsencrypt-auto pip installation fails, since pypi package is marked as pre-release

### ISSUE THREAD

**Issue by veox** [letsencrypt/letsencrypt#1064]
Using [v0.0.0.dev20151020](https://github.com/letsencrypt/letsencrypt/releases/tag/v0.0.0.dev20151020) and its `letsencrypt-auto` script on `Ubuntu 14.04.3 LTS`, installation fails because of `subj`.

Adding `--pre` as suggested in `$HOME/.pip/pip.log` like so fixes the issue:

``` sh
  # nginx is buggy / disabled for now...
  $VENV_BIN/pip install --pre -U letsencrypt > /dev/null
  echo -n .
  $VENV_BIN/pip install --pre -U letsencrypt-apache > /dev/null
```

**Comment by kuba** [comment]
That shouldn't happen, because we upgrade to latest version of pip that doesn't need `--pre`.

Please paste the output of `git reset --hard v0.0.0.dev20151020; rm -rf ~/.local/share/letsencrypt; ./letsencrypt-auto --version >/dev/null; ~/.local/share/letsencrypt/bin/pip -V`.

**Comment by kuba** [comment]
I wasn't able to reproduce on a fresh DigitalOcean instance. No changes to v0.0.0.dev20151020 were necessary, no `--pre` etc. Logs in https://gist.github.com/kuba/f7f03e0abfba7391e7e7.

**Comment by veox** [comment]
Should clarify, not using git here, but downloaded the archive from release page. So:

```
fatal: Not a git repository (or any of the parent directories): .git
[sudo] password for veox: 
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by kuba** [comment]
1. Why did you not follow documentation and use `git clone`? Please follow documentation. Other modes of operation are not supported.

2. I have no idea how did you get that output. Please paste entire command and full output. I have a strange suspicion that you're not running `./letsencrypt-auto` at all, especially after you confirmed that you're not following docs. :(

**Comment by kuba** [comment]
@veox, could you please update this ticket with the requested info? :)

**Comment by veox** [comment]
The [install page](https://letsencrypt.readthedocs.org/en/latest/using.html) reads:

> Alternatively you could download the ZIP archive and extract the snapshot of our repository, but it’s strongly recommended to use the above method instead.

You are correct, I'm not following the docs, and used a tagged release archive (0.0.0.dev20151020).

IMO issue invalid, so closing.

P.S. The VM instance I tried this on seems borked.
