### ISSUE TITLE
Point users at fullchain.pem rather than cert.pem?

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1074]
Users who run standalone or manual get a message pointing them at a cert.pem file.  But actually, most users running modern webservers want fullchain.pem.

**Comment by bmw** [comment]
A fairly large exception here is Apache (at least in the way we are configuring it). It uses `cert.pem`, `privkey.pem`, and `chain.pem`, but not `fullchain.pem`.
