### ISSUE TITLE
letsencrypt-auto could handle the Python packages in debian squeeze/oldstable

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1078]
Currently things [error out](https://gist.github.com/bmw/ac4f1364062b0f4af8ef) because that OS does not default to python2.7.

**Comment by bmw** [comment]
Current [documentation](https://letsencrypt.readthedocs.org/en/latest/contributing.html#debian) says to use `--python python` with `virtualenv` on squeeze instead of `--python python2`. Unfortunately, this is Python 2.6 which isn't currently supported.

**Comment by kuba** [comment]
This will be fixed in #1257.
