### ISSUE TITLE
RTD builds fail for plugins and subpackages

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1086]
```
 Could not find a version that satisfies the requirement acme==0.1.0.dev0 (from letsencrypt-apache==0.1.0.dev0->-r letsencrypt-apache/readthedocs.org.requirements.txt (line 1)) (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021)
No matching distribution found for acme==0.1.0.dev0 (from letsencrypt-apache==0.1.0.dev0->-r letsencrypt-apache/readthedocs.org.requirements.txt (line 1))
```

- https://readthedocs.org/projects/letsencrypt-apache/builds/3422339/
- https://readthedocs.org/projects/letsencrypt-compatibility-test/builds/3422340/
- https://readthedocs.org/projects/letsencrypt-nginx/builds/3422341/
- https://readthedocs.org/projects/letshelp-letsencrypt/builds/3422342/

**Comment by chatainsim** [comment]
I still have the same issue:
```
Searching for acme==0.1.0.dev0
Reading https://pypi.python.org/simple/acme/
No local packages or download links found for acme==0.1.0.dev0
error: Could not find suitable distribution for Requirement.parse('acme==0.1.0.dev0')
```

**Comment by ekoome** [comment]
Getting same issue on Centos 6.6.

**Comment by bmw** [comment]
Please take a look at the warning [here](https://letsencrypt.readthedocs.org/en/latest/using.html#from-source).

**Comment by maxmitch** [comment]
How else are we supposed to use `--nginx` then?
