### ISSUE TITLE
Manual should be hidden from dialog, and require --manual to activate

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1087]

**Comment by bmw** [comment]
I don't think the `--manual` flag is really necessary. Allowing users to specify `-a manual` or `--authenticator manual` is good enough for now.

**Comment by pde** [comment]
Assigned to @swartzcr?

**Comment by SwartzCr** [comment]
yes

**Comment by nagisa** [comment]
Shouldn’t be implemented before nginx and apache plugins properly work. Also dialog should still contain a note that not all options are presented (plugins not installed/manual is hidden etc)

**Comment by bmw** [comment]
@nagisa, the Apache plugin has a couple known issues, but we feel confident enough it's performance that we are recommending people use it.

`manual` was created  for the paranoid and those who want to run Let's Encrypt on one machine, but obtain a cert for another. While it works great from a technical perspective, we're hiding the plugin because the UX needs work and it isn't ready for use by the average sysadmin. This change points people towards `standalone` which is by far the simplest way to obtain a certificate if you're not using Apache. If for some reason you `standalone` doesn't work for you (i.e. port 80 and 443 are bound), we recommend users use `webroot` which is not hidden from the UI.

**Comment by nagisa** [comment]
> the Apache plugin has a couple known issues

The Nginx one supposedly is not to be used at all, however.

> This change points people towards standalone which is by far the simplest way to obtain a certificate if you're not using Apache. 

I don’t see that option used, ever. Do you expect people to turn off their webserver first to run the standalone authenticator and then turn off the webserver again? That’s unacceptable. I don’t see how the authenticator can run alongside the already running server, except maybe the standalone server binding to a random port and sending that port over to the authenticator after requesting to “unfirewall” it. (Note: that sounds like a somewhat viable option which would allow to get rid of all those non-standalone and non-manual authenticators)

> If for some reason standalone doesn't work for you (i.e. port 80 and 443 are bound), we recommend users use webroot which is not hidden from the UI.

Oh, so you’re saying `webroot` will somehow bind to port 80/443 even if there’s a nginx/apache/something else on it already?

Either way, it is not entirely clear what use cases each of the options cater to. It would be nice to have something like an explanation text for at least the currently focused option or something like that.

**Comment by bmw** [comment]
Correct. Our `nginx` plugin should not be used at this time.

That is the major drawback of `standalone`. I'd like to point out that `manual` has exactly the same problem though. `manual` gives you instructions to create the files requested by the ACME protocol and then start a `SimpleHTTPServer` in Python to serve them. If you have a web server bound to port 80, it won't work.

The idea of using a port other than 80/443 is something we've discussed a lot. It's still being considered, but we unfortunately won't be able to do anything like that for the time being.

`webroot` doesn't bind to a port at all. The idea behind `webroot` is that if you already have a web server running, you can use Let's Encrypt to create the files specified by the ACME protocol for domain validation and have your web server will serve them. You give the Let's Encrypt client the path to your "webroot" (for example, `/var/www/html` or `/usr/share/nginx/html`) and Let's Encrypt will provision the necessary files there. [Boulder](https://github.com/letsencrypt/boulder), the server side of Let's Encrypt, will request these files and if everything goes according to plan, domain validation will be completed.

The `Content-Type` header is a problem, but we have fixes in the works to help mitigate them. Regardless of what we do, a specific `Content-Type` is required and it won't be a perfect solution. It may, however, be a better solution for many sysadmins to set the `Content-Type` than it is for them to bring down there server to use `manual` or `standalone`.

And I agree there is an issue of documenting these plugins. One has little idea from the names `manual`, `standalone`, and `webroot` what these plugins actually do. There's a PR in the works that gives each plugin a short description, but we also plan to create thorough, narrative documentation for each plugin before we launch.

**Comment by pde** [comment]
@nagisa The problem is that `--manual` is itself not really ready for prime time; we've watched even fairly sophisticated users struggle to follow its instructions.  That's not the case for standalone; it does a pretty clear job of telling the user what to do next. Manual could be improved, but right now our highest priorities are apache followed by nginx.

**Comment by bmw** [comment]
Closed in #1079.

**Comment by My1** [comment]
I think manual should get the highest priority because if manual is not done for a long time many systems (especially shared hosting or systems that cant run LE, where with manual we could get the cert from another computer and push it over) wont be able to get a cert while manual does not depend on anything except that you can do the validation.
