### ISSUE TITLE
Bootstrap scripts for Manjaro Linux

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1132]
https://github.com/letsencrypt/letsencrypt/pull/1131#issuecomment-150925025

cc @Duesentrieb-Incorporation

**Comment by Duesentrieb-Incorporation** [comment]
Solved with #1133.

**Comment by kuba** [comment]
#1133 was pulled in. Thanks for your help, @Duesentrieb-Incorporation :)
