### ISSUE TITLE
Narrative documentation for plugins

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1137]
While changes proposed in #1079 help, it is very hard to tell from the names `manual`, `standalone`, and `webroot` what our plugins actually do. We need to add narrative documentation for each plugin to help people understand the purpose of each plugin and when they should be used.

**Comment by bmw** [comment]
@kuba, @pde: Do you feel this has been fixed enough by #1121 to either close this issue or kick it out of the "1.0 for launch" milestone?

**Comment by kuba** [comment]
I think we should still work on improving docs (including narrative plugins explanation) before launch.

**Comment by kuba** [comment]
https://github.com/letsencrypt/letsencrypt/issues/1190 is one of the examples why clear narrative docs is necessary.

**Comment by kuba** [comment]
Since I personally find it very high priority, I will work on this during weekend.

**Comment by pde** [comment]
From the latest Beta Program email:

# How to use the client

The Let's Encrypt client supports a number of different "plugins" that can be used to obtain and/or install certificates.  A few examples of the options are included below:

If you're running Apache on a recent Debian-based OS, you can try the Apache plugin, which automates both obtaining and installing certs:

  ./letsencrypt-auto --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview 

To obtain a cert using a "standalone" webserver (you may need to temporarily stop your exising webserver) for example.com and www.example.com:

  ./letsencrypt-auto certonly -a standalone -d example.com -d www.example.com --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview 

To obtain a cert using the "webroot" plugin, which can work with the webroot of any webserver software:

  ./letsencrypt-auto certonly -a webroot --webroot-path /var/www/example -d example.com -d www.example.com -server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview 

NB: curretly the webroot plugin can only obtain certs for several domains simultaneously if they share a webroot.

**Comment by bmw** [comment]
@kuba, are you still working on this? If not, I'll take it over.
