### ISSUE TITLE
letsencrypt-auto hangs during authentication

### ISSUE THREAD

**Issue by jleclanche** [letsencrypt/letsencrypt#1141]
On arch linux. Tried text mode, manual/standalone authenticators, they all hang during authentication after it's shown that an IP queried the token:

```
How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Manual Authenticator (manual)
2: Standalone Authenticator (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
to cancel):leclan.ch www.leclan.ch
66.133.109.36 - - [26/Oct/2015 21:44:21] "GET /.well-known/acme-challenge/... HTTP/1.1" 200 -
```

**Comment by jleclanche** [comment]
Seems im not the only one (from irc):

```

**Comment by jleclanche** [comment]
Seems im not the only one (from irc):

```
[19:58:36] <Exagone313> Hi, I received a beta email, so I tried to set up for my domain, let's say www.example.com (but not example.com for now until it works). I first tried to set up with apache2, but it gave incorrect config (for example insert_cert_file_path instead of a path, don't know what to write, and the client quitted with a python error) and apache2 didn't start. so I removed everything, then I tried with "standalone server" option, but the lets encrypt client froze
[19:58:36] <Exagone313> after I entered the domain. What can I do? I waited about 15 minutes...
```

**Comment by kuba** [comment]
For standalone there is a known bug: #1085. For manual: it should never hang. So... if you have logs that show how manual plugin hangs, please paste it here.

**Comment by jleclanche** [comment]
How do I obtain those logs? didnt find any verbose option

**Comment by kuba** [comment]
Sorry. Debug logs are unconditionally stored in `/var/log/letsencrypt`. You can watch them being produced live if you specify `-vvvvvvv` on the command line, but for now you're fine to copy here one of the logs that corresponds to you session with manual plugin.

**Comment by jleclanche** [comment]
Alright, with that I managed to get it to work. Couldn't find any log with relevant info, I'm guessing this is the same as #1085 then.

**Comment by kuba** [comment]
Okay, closing for now. Let us know if you find anything interesting.
