### ISSUE TITLE
Handle IPv6 adresses in Apache vhost entries

### ISSUE THREAD

**Issue by NoodlesNZ** [letsencrypt/letsencrypt#1143]
When running ```./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth``` it crashes out with this:

```
Error while restarting Apache:
Restarting apache2 (via systemctl): apache2.service failed!

Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
```
Upon further investigation via ```journalctl -xn``` I get this:

```
-- Logs begin at Tue 2015-09-08 20:40:09 CDT, end at Mon 2015-10-26 17:16:13 CDT. --
Oct 26 17:16:12 dag apache2[581]: AH00526: Syntax error on line 2 of /etc/apache2/le_dvsni_cert_challenge.conf:
Oct 26 17:16:12 dag apache2[581]: The address or port is invalid
Oct 26 17:16:12 dag apache2[581]: Action 'configtest' failed.
Oct 26 17:16:12 dag apache2[581]: The Apache error log may have more information.
Oct 26 17:16:12 dag systemd[1]: apache2.service: control process exited, code=exited status=1
Oct 26 17:16:12 dag systemd[1]: Failed to start LSB: Apache2 web server.
```

Unfortunately the file in question /etc/apache2/le_dvsni_cert_challenge.conf is not available after letsencrypt-auto crashes out.

Running on Debian jessie x86_64

**Comment by jdkasten** [comment]
Yes, the configuration changes and challenge files are cleaned up/reverted in the result of a failure.  (Note for future work: We should have an available debug flag to avoid this and make debugging easier)

Looking at the template of the dvsni challenge file found here... https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/dvsni.py#L32

It looks like the syntax error probably occurred when trying to include the vhost address.  Given the ```address or port is invalid``` error.

Could you provide the VirtualHost block of the domain you selected to upgrade?

The challenge configuration file attempts to copy over the addresses of the selected VirtualHost while changing the port to 443.

**Comment by NoodlesNZ** [comment]
This is the vhost I was trying to add let's encrypt to:
```
<VirtualHost 173.192.30.7:80 [2607:f0d0:1005:99::3:1337]:80>
DocumentRoot /xxxx/
ServerName noodles.net.nz
ServerAlias www.noodles.net.nz
CustomLog ${APACHE_LOG_DIR}/domlogs/noodles.log combined
<Directory "/xxxx/">
  AllowOverride All
</Directory>
</VirtualHost>

<VirtualHost 173.192.30.7:443 [2607:f0d0:1005:99::3:1337]:443>
DocumentRoot /xxxx/
ServerName noodles.net.nz
ServerAlias www.noodles.net.nz
CustomLog ${APACHE_LOG_DIR}/domlogs/noodles.log combined
<Directory "xxxx">
  AllowOverride All
</Directory>

  SSLEngine on

  SSLHonorCipherOrder On
  SSLProtocol all -SSLv2 -SSLv3
  SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH +aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS"

   SSLCertificateFile /xxxx/noodles.net.nz.crt
   SSLCertificateKeyFile /xxxx/noodles.net.nz.key

   Header set Strict-Transport-Security "max-age=31536000; preload"
</VirtualHost>
```

I guess the apache letsencrypt-auto only works with simple configs?

**Comment by jdkasten** [comment]
No, it is just that the Apache plugin is very much in alpha/beta right now.  It shouldn't be difficult to handle this.  I am guessing that IPv6 addresses aren't parsed appropriately.

I did my development and testing on EC2, (and Boulder isn't currently connecting to IPv6) and didn't get a chance to test IPv6 configurations.

Thanks for the help!  We will make sure that the plugin can handle this soon and also add in appropriate test cases to make sure we don't have regressions.

In the meantime, you can run the Standalone plugin, Web-root plugin, or Manual plugin to attain a certificate.

**Comment by kroeckx** [comment]
I can confirm that after removing the IPv6 address from the VirtualHost line that it works.

**Comment by nils-ohlmeier** [comment]
Just to make sure it does not fall off the table once IPv6 support gets added:

The reverse order of IPv4 and IPv6 address in the vhost line should be supported as well, e.g.

`<VirtualHost [2a01:238:429e:6b00:6188:46:8080:e1b4]:80 85.214.41.172:80>`

**Comment by andydavidson** [comment]
The clean up isn't quite perfect either - the le_dvsni_cert_challenge.conf file certainly seems to be removed but 000-default-le-ssl.conf is left laying around.  Please make sure ipv6 works on the public launch, we don't need people to have another reason to drop v6 support. :-)

**Comment by bmw** [comment]
The cleanup problem is almost certainly due to #808 which there is a work in progress PR for (#1582).

**Comment by pde** [comment]
@andydavidson IPv6 support won't be in the Public Beta release of Let's Encrypt, though there's a chance it'll be on the list for 1.0.

**Comment by kroeckx** [comment]
What do you mean with no IPv6 support?  It's really annoying that
each time you run it you have to go and edit the config files
first to remove the IPv6 addresses in it.  All that we want is
that it doesn't break parsing a file with IPv6 addresses in it.

**Comment by nils-ohlmeier** [comment]
I totally agree with @kroeckx.
Full IPv6 support would mean to me that LE supports also IPv6 only hosts. I'm pretty sure almost everyone agrees that that is something which can wait after the 1.0.
But there are a lot of dual hosted machines out there. And as long as LE ignores the v6 part of the vhost and runs its verification successfully over v4 only I would assume the owners of these hosts would be happy. That is something which should be in scope for 1.0.

**Comment by pde** [comment]
@kroeckx ok that makes sense.  We'll put this on the list of things needed for 1.0 Apache support.

**Comment by kroeckx** [comment]
Any update on this?

**Comment by gfairchild** [comment]
Just encountered this issue myself. Looking forward to this being fixed!

**Comment by SnakeO** [comment]
+1, google sent me here

**Comment by dpocock** [comment]
In my ```/etc/apache2/le_tls_sni_01_cert_challenge.conf```

```
<VirtualHost 195.8.117.51:443 [2001:443>
    ServerName 
```

The IPv6 address has been very badly truncated.
