### ISSUE TITLE
Standalone should verify ports for suported challenges only

### ISSUE THREAD

**Issue by brunoqc** [letsencrypt/letsencrypt#1149]
I ran the following commands and both complained that nginx was already using port 80.
`./letsencrypt-auto --standalone --dvsni-port 63443 --server https://acme-v01.api.letsencrypt.org/directory auth`
`./letsencrypt-auto --standalone --dvsni-port 63443 --server https://acme-v01.api.letsencrypt.org/directory --standalone-supported-challenges dvsni auth`

I was under the impression that using `--dvsni-port` would force dvsni only.

I had to supply a fake port with `--simple-http-port 9999` with the second commad to get a certificate.

I'm using haproxy in the front to redirect *.acme.invalid to port 63443.

**Comment by kuba** [comment]
Using `--dvsni-port` does not force DVSNI, `--standalone-supported-challenges dvsni` does (this is explained in http://letsencrypt.readthedocs.org/en/latest/using.html#plugins). And you should not need to specify `--simple-http-port`.

Anyhow, thanks for reporting. I can verify this is a bug in https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151024/letsencrypt/plugins/standalone.py#L197-L198. This function should only verify ports that correspond to `self.supported_challenges`.
