### ISSUE TITLE
ACME client for Windows/IIS

### ISSUE THREAD

**Issue by ebekker** [letsencrypt/letsencrypt#116]
I propose developing an ACME client for Windows + IIS.

Here are some of my thoughts:

* Create a PowerShell-based solution, this would be comparable to the Python-based one already in the works for Linux/Apache ([letsencrypt.py](https://github.com/letsencrypt/lets-encrypt-preview)): 
  * This will also be allow more compatibility with more environments, such as Windows Core, and even remote execution 
* Leverage the existing Windows components for any dependencies, for example under the hood, letsencrypt.py uses OpenSSL for all the cert management stuff, whereas on Windows you could use the certreq CLI or the CertEnroll API. 
* By structuring the code/libs nicely, we can make parts reusable outside of the main script, for example API/library for the ACME protocol itself to be used in other implementations or projects.
* Try to mimic the letsencrypt.py command-line usage as much as possible/practical so that there is consistency across platforms [letsencrypt.py CLI usage](https://github.com/letsencrypt/lets-encrypt-preview#command-line-usage)

**Comment by ThomasWaldmann** [comment]
hmm, this is the repository and issue tracker of the python-based lets-encrypt client.

you are suggesting a non-python based one.

so I guess this issue can never be closed within THIS project except as out of scope / invalid, right?

**Comment by artknight** [comment]
sorry, from reading the above it is not apparent to me that windows will be supported from get-go!

**Comment by kuba** [comment]
- https://github.com/natemrice/letsencrypt-powershell
- #390
- https://github.com/felixrieseberg/lets-encrypt-iis

**Comment by pde** [comment]
This is in progress.

**Comment by ebekker** [comment]
OK, after kicking off this issue and putting out some ideas, I intended to start an implementation, but that didn't happen...until now.

I've committed the start of this at https://github.com/ebekker/letsencrypt-win

Now, I know there's been some related development:
* Looks like a pure POSH implementation, a little slow going as of late:  https://github.com/natemrice/letsencrypt-powershell
* A Python-based [IIS configurator](https://github.com/felixrieseberg/lets-encrypt-iis) which as been merged into...
* An [IIS configurator submodule](https://github.com/felixrieseberg/lets-encrypt-preview) of the letsencrypt python client

These look like good efforts, but I think there is a good bit of value in the approach I'm following, which is:
* a pure CLR implementation of the ACME protocol (at least the client side) as a lib.
* a POSH module using the ACME client lib that can be used to manage and configure IIS 7+.

**Comment by ebekker** [comment]
I'm closing this issue as there's now a functioning [client for Windows](https://github.com/ebekker/letsencrypt-win) that can inter-operate with the LE Boulder CA and can configure IIS.

I've written up a description of the general use -- feedback on the interfaces and usability would be appreciated.
