### ISSUE TITLE
jwk thumbprint is mismade

### ISSUE THREAD

**Issue by jmhodges** [letsencrypt/letsencrypt#1165]
The JWK.thumbprint method isn't quite right. 

I think the problem is that the `json.dumps` the thumbprint method uses can mis-order the keys in the JSON hash. There is an order that [RFC7638](https://tools.ietf.org/html/rfc7638#section-3.3) says the keys must be in. The go-jose code does that with this line of code: https://github.com/square/go-jose/blob/4ddd71883fa547d37fbf598071f04512d8bafee3/jwk.go#L155

Going off the go-jose test vectors, this RSA public key JWK: 

    {
        "kty": "RSA",
        "kid": "bilbo.baggins@hobbiton.example",
        "use": "sig",
        "n": "n4EPtAOCc9AlkeQHPzHStgAbgs7bTZLwUBZdR8_KuKPEHLd4rHVTeT-O-XV2jRojdNhxJWTDvNd7nqQ0VEiZQHz_AJmSCpMaJMRBSFKrKb2wqVwGU_NsYOYL-QtiWN2lbzcEe6XC0dApr5ydQLrHqkHHig3RBordaZ6Aj-oBHqFEHYpPe7Tpe-OfVfHd1E6cS6M1FZcD1NNLYD5lFHpPI9bTwJlsde3uhGqC0ZCuEHg8lhzwOHrtIQbS0FVbb9k3-tVTU4fg_3L_vniUFAKwuCLqKnS2BYwdq_mzSnbLY7h_qixoR7jig3__kRhuaxwUkRz5iaiQkqgc5gHdrNP5zw",
     "e": "AQAB"
    }

must be thumbprinted into `f63838e96077ad1fc01c3f8405774dedc0641f558ebb4b40dccf5f9b6d66a932`.

In case I fat-fingered the key or its hash, here they are in the go-jose tests: https://github.com/square/go-jose/blob/4ddd71883fa547d37fbf598071f04512d8bafee3/jwk_test.go#L331-L344 and https://github.com/square/go-jose/blob/4ddd71883fa547d37fbf598071f04512d8bafee3/jwk_test.go#L384

**Comment by jmhodges** [comment]
I believe this should be a launch ticket.

**Comment by jmhodges** [comment]
Also, here's the test I used. The _strip_whitespace method is just the trivial regex substitution for `\s+`.

    def test_like_go_jose(self):
        # RSA public key
        jsonKey = _strip_whitespace("""{
        "kty": "RSA",
        "kid": "bilbo.baggins@hobbiton.example",
        "use": "sig",
        "n": "n4EPtAOCc9AlkeQHPzHStgAbgs7bTZLwUBZdR8_KuKPEHLd4rHVTeT
        -O-XV2jRojdNhxJWTDvNd7nqQ0VEiZQHz_AJmSCpMaJMRBSFKrKb2wqV
        wGU_NsYOYL-QtiWN2lbzcEe6XC0dApr5ydQLrHqkHHig3RBordaZ6Aj-
    oBHqFEHYpPe7Tpe-OfVfHd1E6cS6M1FZcD1NNLYD5lFHpPI9bTwJlsde
        3uhGqC0ZCuEHg8lhzwOHrtIQbS0FVbb9k3-tVTU4fg_3L_vniUFAKwuC
        LqKnS2BYwdq_mzSnbLY7h_qixoR7jig3__kRhuaxwUkRz5iaiQkqgc5g
        HdrNP5zw",
     "e": "AQAB"
    }""")
        
        key = JWKRSA.load(jsonKey)
        import binascii
        hex_tp = binascii.hexlify(key.thumbprint())
        self.assertEqual("f63838e96077ad1fc01c3f8405774dedc0641f558ebb4b40dccf5f9b6d66a932", hex_tp)

In case I screwed up _strip_whitespace, here it is:

    whitespace_regex = re.compile(r'\s+')
    def _strip_whitespace(str):
        return re.sub(whitespace_regex, '', str)

**Comment by jmhodges** [comment]
Okay, I got the go ahead to put this in the launch milestone. It's being added to the launch milestone on the thought that we are only going to use the new challenges for the GA launch. If we aren't, the ticket will come back out.

**Comment by bifurcation** [comment]
+1 to having this in launch.

The way I've seen every other implementation implement thumbprints is to do template filling, since JSON libraries don't give you the control you need.  See, e.g., the [go-jose implementation](https://github.com/square/go-jose/blob/master/jwk.go#L140).

**Comment by kuba** [comment]
Indeed, we hash the following:
```
{
"e":"AQAB",
"kty":"RSA",
"n":"m2Fylv-Uz7trgTW8EBHP3FQSMeZs2GNQ6VRo1sIVJEk"
}
```

Obviously, we need to get rid of the newlines.
