### ISSUE TITLE
Support "http-01" ACME challenge

### ISSUE THREAD

**Issue by bifurcation** [letsencrypt/letsencrypt#1166]
The existing "simpleHttp" and "dvsni" challenges are insecure, and boulder will be disabling them shortly.  The client needs to implement the new "http-01" challenge in order to be compatible with future boulder.

**Comment by bifurcation** [comment]
Propose adding this to the launch milestone.

**Comment by bmw** [comment]
Dupe of #914 which is a launch milestone.
