### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by sboyettedh** [letsencrypt/letsencrypt#1174]
I began work on porting the client to obsd, with an eye toward integration with the openbsd httpd, but ran into an issue in the venv setup step.
```
Collecting psutil>=2.1.0 (from letsencrypt==0.1.0.dev0)
  Downloading psutil-3.2.2.tar.gz (253kB)
    100% |████████████████████████████████| 253kB 340kB/s 
    Complete output from command python setup.py egg_info:
    platform openbsd5 is not supported
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yXfYkU/psutil
```
psutil does not support OpenBSD. There is an issue open with psutil about this (https://github.com/giampaolo/psutil/issues/562) but work on it seems to have stalled about 6 months ago.

There are only 2 calls to the psutil module in the client:
```
$ grep -r psutil *
letsencrypt/plugins/util.py:import psutil
letsencrypt/plugins/util.py:        net_connections = psutil.net_connections()
letsencrypt/plugins/util.py:    except psutil.AccessDenied as error:
letsencrypt/plugins/util.py:            name = psutil.Process(pid).name()
letsencrypt/plugins/util.py:    except (psutil.NoSuchProcess, psutil.AccessDenied):
```
Though I certainly understand wanting to use a pre-rolled mechanism for interface discovery.

I'd love to help in any way possible with this. Thanks for all the work already done!

**Comment by kuba** [comment]
Great! Cool to see us packaged for OpenBSD!

In long run we could try to:
- search for alternative that works on OpenBSD
- make this dependency optional

Unfortunately, I'm not sure if we can fix it soon due to the time constraints. For the time being you can patch our code in you package and mock out the `already_listening` function to always return `True`. We will fail gracefully later, when binding to the port. Would this work for you temporarily?

If you have any other question regarding packaging, please let me know! I'm very happy to help.

**Comment by sboyettedh** [comment]
I'm fine with patching over things in the port to get things working quickly. I'll work on that in the next few days and report back. Thanks!

**Comment by landryb** [comment]
Fwiw (and i'm the one that started working on psutil on OpenBSD), when i encounter code that depends on psutils for 'small things' i just patch it out - see for example http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/sysutils/menulibre/patches/patch-menulibre_util_py?rev=1.2&content-type=text/x-cvsweb-markup

**Comment by jedisct1** [comment]
Any progress on this, @sboyettedh ?

**Comment by eripa** [comment]
FYI, looks like psutil now supports OpenBSD 
http://grodola.blogspot.com/2015/11/openbsd-support-for-psutil.html

**Comment by landryb** [comment]
For those not following the lists, letsencrypt client is already available in -current : http://marc.info/?l=openbsd-ports-cvs&m=144776395631121&w=2

**Comment by nafigator** [comment]
> For those not following the lists, letsencrypt client is already available in -current : http://marc.info/?l=openbsd-ports-cvs&m=144776395631121&w=2

Thanks for good news! :thumbsup:

**Comment by jedisct1** [comment]
Awesome, thanks!

**Comment by 22decembre** [comment]
I am trying to build this port for days and fail with a dep' (py-cryptography or its own dep', not sure).

Has anyone succeed to build it ?

**Comment by hobarrera** [comment]
@22decembre I built perfect for me on a clean ports tree on -current. It also built `py-cryptography` and a rather long dependency tree during the process, but with no errors.

**Comment by 22decembre** [comment]
ok, thanks.

**Comment by 22decembre** [comment]
I am actually having a problem with pypy, which is a dep of cffi, which itself is a dep' of LE… Lot's of things.

**Comment by bmw** [comment]
Since OpenBSD has an official port, I'm closing this issue.
