### ISSUE TITLE
Provide instruction for migrating from staging to production

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1184]
A lot of our users are using staging and they ask what should they do when we go to GA. We need to explicitly document the process. Something along the lines of: `rm -rf /etc/letsencrypt /var/lib/letsencrypt; git pull; letsencrypt-auto`.

I believe this should be in the 1.0 milestone.

**Comment by bmw** [comment]
After talking about this with @pde, we're kicking this out of the "1.0 for launch" milestone. If we do nothing here, the only problem that can occur is mixed lineages. The plan is to implement `--staging` in the future with a warning that this might update symlinks from production certs to staging certs.

**Comment by pde** [comment]
Closing this in favour of #1667.
