### ISSUE TITLE
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Name is not whitelisted

### ISSUE THREAD

**Issue by tanrax** [letsencrypt/letsencrypt#1189]

**Comment by schoen** [comment]
Hi @tanrax, are you sure that you're part of the beta program and that all names that you're trying to get certs for were listed (and spelled correctly) in your beta application, including subdomains?

**Comment by tanrax** [comment]
Sorry, I'm not part of the beta.
How I can participate?

**Comment by schoen** [comment]
Only users who have been accepted into the beta program can use that endpoint.

Right now there are separate ACME protocol resources for the test CA (that issues "happy hacker fake CA" certificates that aren't publicly trusted and will cause a browser error) and the production CA (that issues publicly-trusted certificates). If you need a CA that will be accepted by browsers, you should apply to the beta program and wait for your domains to be whitelisted. If you just want to see how the technology works or help us find bugs, you can use the testing CA resource instead (which will result in getting a cert right away, but not a publicly trusted one).

**Comment by kuba** [comment]
This is not really actionable, allow me to close it for now. You should still be able to post comments if you have any questions, @tanrax :)
