### ISSUE TITLE
Provide a more meaningful error if the user requests a punycode domain

### ISSUE THREAD

**Issue by ge0rg** [letsencrypt/letsencrypt#1212]
Hi,

I tried to request a cert for a punycode subdomain for 😸.op-co.de (`xn--z38h.op-co.de` as DNS-ID SAN and CN in the CSR) today, and the resulting response was:

> Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Syntax error

While that host is not whitelisted, there should be a more appropriate response.

CSR (shortened):
```
# openssl req -noout -text -inform der < catface.op-co.de-2015.csr
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: C=DE, CN=xn--z38h.op-co.de
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    [...]
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:xn--z38h.op-co.de
    Signature Algorithm: sha256WithRSAEncryption
         [...]
```

I'm skipping the log as @jcjones made me aware on IRC that punycode is currently [forbidden in the code](https://github.com/letsencrypt/boulder/search?utf8=%E2%9C%93&q=punycode&type=Code).

This ticket is therefore mainly for documentation purposes and to track the implementation status, should it be subject to change.

**Comment by ge0rg** [comment]
Now this has become a merely cosmetic issue. Should I create a new issue (here or in boulder) for actually supporting IDNAs?

**Comment by bmw** [comment]
Not supporting IDNs is a Boulder issue which it appears they already have an issue for (see letsencrypt/boulder#597)

**Comment by kuba** [comment]
@ge0rg and we probably want to keep this issue open to fix error reporting on the client side
