### ISSUE TITLE
letsencrypt-auto install didn't remove SSLCertificateChainFile statement

### ISSUE THREAD

**Issue by fxkr** [letsencrypt/letsencrypt#1213]
I'm using Apache on Debian. I already had TLS configured, and thus had `SSLCertificateFile`, `SSLCertificateKeyFile` and `SSLCertificateChainFile` statements in my Apache site config.

letsencrypt-auto correctly replaced the values of the first two, but failed to change `SSLCertificateChainFile`, resulting in breakage.

Invocation:

```
./letsencrypt-auto install --apache -d example.com -d www.example.com --cert-path /etc/letsencrypt/live/example.com/fullchain.pem --key-path /etc/letsencrypt/keys/0000_key-letsencrypt.pem --agree-dev-preview 
```

Site config before invocation:

```
<VirtualHost *:80>
        ServerName example.com
        ServerAlias www.example.com
        DocumentRoot ...

        ErrorLog ...
        CustomLog ...
</VirtualHost>

<VirtualHost *:443>
        ServerName example.com
        ServerAlias www.example.com
        DocumentRoot ...

        ErrorLog ...
        CustomLog ...

        SSLEngine on
        SSLCertificateFile ...
        SSLCertificateKeyFile ...
        SSLCertificateChainFile ...
</VirtualHost>
```

Apart from that, it worked nicely, and so we now finally have what CACert has kept promising for "next year" for the past 10 years or so. So thanks for all the work, letsencrypt is amazing! ❤

**Comment by xamnesiax-sx** [comment]
Semi-confident that I've found the problem. Will write a patch and issue a pull request when I get home from work
