### ISSUE TITLE
Inaccurate Documentation for "manual" Plugin

### ISSUE THREAD

**Issue by the-real-tokai** [letsencrypt/letsencrypt#1217]
I'm not sure, if the GitHub issue tracker is the correct place to report this, but I noticed a small inaccuracy in the documentation at the following URL:
https://letsencrypt.readthedocs.org/en/latest/using.html#plugins

It states that the "manual" plugin must be used/ activated with `--a manual`. This triggers an error stating that the `--a` parameter is ambiguous. I guess, the documentation should be updated to show `--authenticator manual` (at least that's what I used in the end and worked for me. :smile: )

Additionally it is not very obvious what the "A" and "I" table columns are about (at least I can only do wild guesses). Perhaps the table headers could have some hover tip with the full meaning of "A" and "I"?

**Comment by kuba** [comment]
Thanks for reporting, much appreciated! :) It should be `-a manual` instead of `--a manual`. I will work on better docs over weekend (#1137). I've already recognized the `A`/`I` ambiguity problem. I'll allow myself to close this issue as duplicate, so that we have a bit cleaner GitHub space.
