### ISSUE TITLE
Why not Python 3?

### ISSUE THREAD

**Issue by hjacobs** [letsencrypt/letsencrypt#1220]
Why is letsencrypt (as a new project) still using Python 2? Python 2 support will be dropped in major distributions like Debian/Ubuntu (https://lists.debian.org/debian-python/2014/05/msg00037.html) and migrating is always harder than doing it right the first time :wink:

**Comment by centminmod** [comment]
i believe support will be back https://github.com/letsencrypt/letsencrypt/pull/957

**Comment by kuba** [comment]
Only `acme` module (https://pypi.python.org/pypi/acme) supports Python3. Rest of the code is not compatible because it requires significant engineering effort: we try to cover as many platforms as possible, including dinosaurs with Python 2.6. I hope myself that support for Python 3 will land not so long after General Availability. I'm sure contributions after GA will be welcome. Now it's just too busy.

**Comment by pde** [comment]
Because we have to be installable on older systems that don't support Python 2, and coding for python 2 is the fastest way to get there.

**Comment by schoen** [comment]
I would also add that we historically had tests for Python 3 and we were passing them so we will probably be relatively close to Python 3 compatibility in practice at launch, unless Python 2-only dependencies have come in since then.

**Comment by kuba** [comment]
That is not correct, @schoen. We never had tests for Python 3 apart from `acme`. For some time those `acme` tests were disabled, but they are enabled back in current `master`.

**Comment by hjacobs** [comment]
Thanks for all the answers, I will be happy to contribute to move Python 3 forward :smile: 

Yeah, got my first certs today :tada:

**Comment by EminezArtus** [comment]
I know this is an old post but I just wanted to comment that I hope you make the packages in repositories compatible with both versions so that I don't have to download and install python 2 when everything else on my server is using python 3. Less files happy server.

**Comment by bmw** [comment]
The current issue for this is #3179. You can look through that thread and the issues/PRs referenced there if you want more info, but for a short update on the current status: we're very close :smile:
