### ISSUE TITLE
Syntax error parsing apache configuration file (roundcube.conf stock)

### ISSUE THREAD

**Issue by eudoxos** [letsencrypt/letsencrypt#1222]
I encountered 

     PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/conf-enabled/roundcube.conf', u'Syntax error'),)

when running `letsencrypt-auto --installer apache` which was solved by moving the offensive `roundcube.conf` away temporarily. IIRC it is a stock config file for roundcube on Debian.  The file is as follows (can't attach, sorry):

    # Those aliases do not work properly with several hosts on your apache server
    # Uncomment them to use it or adapt them to your configuration
    #    Alias /roundcube/program/js/tiny_mce/ /usr/share/tinymce/www/
    #    Alias /roundcube /var/lib/roundcube

    # Access to tinymce files
    <Directory "/usr/share/tinymce/www/">
          Options Indexes MultiViews FollowSymLinks
          AllowOverride None
          <IfVersion >= 2.3>
            Require all granted
          </IfVersion> 
          <IfVersion < 2.3>
            Order allow,deny
            Allow from all
          </IfVersion>
    </Directory>

    <Directory /var/lib/roundcube/>
      Options +FollowSymLinks
      # This is needed to parse /var/lib/roundcube/.htaccess. See its
      # content before setting AllowOverride to None.
      AllowOverride All
      <IfVersion >= 2.3>
        Require all granted
      </IfVersion> 
      <IfVersion < 2.3>
        Order allow,deny
        Allow from all
      </IfVersion>
    </Directory>

    # Protecting basic directories:
    <Directory /var/lib/roundcube/config>
            Options -FollowSymLinks
            AllowOverride None
    </Directory>

    <Directory /var/lib/roundcube/temp>
            Options -FollowSymLinks
            AllowOverride None
            <IfVersion >= 2.3>
              Require all denied
            </IfVersion> 
            <IfVersion < 2.3>
              Order allow,deny
              Deny from all
            </IfVersion>
    </Directory>

    <Directory /var/lib/roundcube/logs>
            Options -FollowSymLinks
            AllowOverride None
            <IfVersion >= 2.3>
              Require all denied
            </IfVersion> 
            <IfVersion < 2.3>
              Order allow,deny
              Deny from all
            </IfVersion>
    </Directory>

Feel free to reassign to augeas, if not relevant to letsencrypt.

**Comment by pde** [comment]
Fixed by #1291.
