### ISSUE TITLE
Letsencrypt Certificate Manager used for deploying SSL certs

### ISSUE THREAD

**Issue by centminmod** [letsencrypt/letsencrypt#1223]
With limited or no SSH access users https://community.letsencrypt.org/t/elementary-procedure/2534 who want to use Letsencrypt SSL certificates, they would need access to a server with SSH. What if they can generate the SSL certificate one 1 SSH enabled server and use Letsencrypt Certificate Manager to backup those SSL certs/keys and then use the Manager to redeploy them on another server ?

or would Letsencrypt Certificate Manager also require SSH access to use it ?

**Comment by kuba** [comment]
I don't understand your question :( Can you please rephrase it? Also, what Certificate Manager are you talking about?

**Comment by centminmod** [comment]
The Certificate Manager mentioned at https://github.com/letsencrypt/letsencrypt/issues/729 and https://community.letsencrypt.org/t/tools-for-ssl-key-management/536

Basically, a mechanism for facilitating the transfer of LE SSL certificate/files from a ssh enabled VPS to a server without ssh enabled/shared hosting. That is assuming such Letsencrypt Certificate Manager doesn't require ssh access too. If it does, then my suggestion isn't relevant :)

**Comment by kuba** [comment]
Certificate manager that @jdkasten is working on will require you to run `letsencrypt-auto` command which implies SSH access.

**Comment by centminmod** [comment]
ah i see.. so this not relevant :)
