### ISSUE TITLE
CentOS 6.7 issue: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see 

### ISSUE THREAD

**Issue by zopyx** [letsencrypt/letsencrypt#1247]
CentOS release 6.7 (Final)
Kernel \r on an \m

Creating virtual environment...
Updating letsencrypt and virtual environment dependencies...../home/ajung/.local/share/letsencrypt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oUzkJg/ConfigArgParse
/home/ajung/.local/share/letsencrypt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by centminmod** [comment]
you need Python 2.7 https://community.letsencrypt.org/t/redhat-centos-6-x-users-need-python-2-7/2190/

**Comment by kuba** [comment]
"A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see" is only a **warnining** as far as I can see, so it should not stop the installation from proceeding further.

Do you have any other errors, @zopyx?

@centminmod You should not need to install Python2.7. This will be fully fixed with #1257. Can you please join me on IRC and discuss it?

**Comment by zopyx** [comment]
Got it.

It would be nice if you could pass the path to virtualenv through the
commandline.



2015-10-31 13:57 GMT+01:00 George Liu (eva2000) <notifications@github.com>:

**Comment by kuba** [comment]
You can: https://github.com/letsencrypt/letsencrypt/blob/c39bc12b18bd0c6cf2058c2c2b9ff6dba6bf4ff1/letsencrypt-auto#L13 (`VENV_PATH=foo letsencrypt-auto`).

If you don't have any further problems, please close this bug. Thanks!

**Comment by zopyx** [comment]
With Python 2.6 I see an additional problem (I am not bound to Python
2.6...just reporting what I see on an old
heavily customized CentOS 6.7 system).

./letsencrypt-auto   --verbose
Updating letsencrypt and virtual environment dependencies...
Requirement already up-to-date: setuptools in
/home/ajung/.local/share/letsencrypt/lib/python2.6/site-packages
Requirement already up-to-date: pip in
/home/ajung/.local/share/letsencrypt/lib/python2.6/site-packages
Collecting letsencrypt
  Using cached letsencrypt-0.0.0.dev20151030-py2-none-any.whl
Collecting letsencrypt-apache
/home/ajung/.local/share/letsencrypt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90:
InsecurePlatformWarning: A true SSLContext object is not available. This
prevents urllib3 from configuring SSL appropriately and may cause certain
SSL connections to fail. For more information, see
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
.
  InsecurePlatformWarning
  Downloading letsencrypt_apache-0.0.0.dev20151030-py2-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 3.6MB/s
Collecting zope.interface (from letsencrypt)
  Using cached zope.interface-4.1.3.tar.gz
Requirement already up-to-date: setuptools in
/home/ajung/.local/share/letsencrypt/lib/python2.6/site-packages (from
letsencrypt)
Collecting python2-pythondialog>=3.2.2rc1 (from letsencrypt)
  Using cached python2-pythondialog-3.3.0.tar.bz2
Collecting PyOpenSSL (from letsencrypt)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting requests (from letsencrypt)
  Using cached requests-2.8.1-py2.py3-none-any.whl
Collecting parsedatetime (from letsencrypt)
  Using cached parsedatetime-1.5-py2-none-any.whl
Collecting configobj (from letsencrypt)
  Using cached configobj-5.0.6.tar.gz
Collecting pytz (from letsencrypt)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting psutil>=2.1.0 (from letsencrypt)
  Using cached psutil-3.2.2.tar.gz
Collecting six (from letsencrypt)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting acme==0.0.0.dev20151030 (from letsencrypt)
  Using cached acme-0.0.0.dev20151030-py2-none-any.whl
Collecting cryptography>=0.7 (from letsencrypt)
  Using cached cryptography-1.1.tar.gz
Collecting zope.component (from letsencrypt)
  Using cached zope.component-4.2.2.tar.gz
Collecting mock (from letsencrypt)
  Using cached mock-1.3.0-py2.py3-none-any.whl
Collecting ConfigArgParse (from letsencrypt)
  Using cached ConfigArgParse-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-EhInzb/ConfigArgParse/setup.py", line 1, in
<module>
        import configargparse
      File "configargparse.py", line 16
        ACTION_TYPES_THAT_DONT_NEED_A_VALUE = {argparse._StoreTrueAction,
                                                                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-EhInzb/ConfigArgParse

2015-10-31 14:00 GMT+01:00 Jakub Warmuz <notifications@github.com>:

**Comment by kuba** [comment]
This is also fixed with #1257.

**Comment by kuba** [comment]
Okay, I'm gonna close it, because we want off topic anyway. To summarize: problem from issue topic is only a warning, not an error.
