### ISSUE TITLE
Name is not whitelisted?

### ISSUE THREAD

**Issue by zopyx** [letsencrypt/letsencrypt#1248]
what does this mean?

An unexpected error occurred.
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Name is not whitelisted
Please see the logfiles in /var/log/letsencrypt for more details.

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to info@zopyx.com.
 - Your account credentials have been saved in your Let's Encrypt
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Let's
   Encrypt so making regular backups of this folder is ideal.

**Comment by n3roGit** [comment]
i Have the same problem with my whitelisted domains... any ideas?



An unexpected error occurred.
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Name is not whitelisted
Please see the logfiles in /var/log/letsencrypt for more details.
root@rbserver:/opt/letsencrypt# ./letsencrypt-auto --agree-dev-preview --server \https://acme-v01.api.letsencrypt.org/directory auth

**Comment by bmw** [comment]
@n3roGit, there was a problem with our whitelist that affected a few domains that has now been fixed. Give it another shot and let me know if you're still experiencing the problem.

**Comment by n3roGit** [comment]
perfekt. now it works!!!

**Comment by kyluke** [comment]
Hey guys, I just received the same error. I am currently trying to set it up on a sub domain of the domain which is supposedly white listed, can this be causing a problem?

**Comment by bmw** [comment]
@kyluke, yes. That would cause a problem.

The only names that are whitelisted are the fully qualified domain names which you requested when you filled out the beta participation request. If you'd like to obtain a cert for a subdomain other than what you included in that form, you'd need to fill out another request (or wait for public beta on December 3rd).

**Comment by kyluke** [comment]
@bmw thanks, I will wait, it's only next week. Thanks for the response!
