### ISSUE TITLE
explicitly disallow pip install -r requirements.txt

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1252]
We list almost everything, but `pip install -r requirements.txt`: https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151030/docs/using.rst#from-source. IRC logs suggest we need to explicitly disallow this as well.

**Comment by cowlicks** [comment]
@kuba is this still necessary since there is no longer a `requirements.txt` file?

**Comment by bmw** [comment]
I don't think this is still necessary. I suppose a user could create their own `requirements.txt` file, but that seems unlikely.
