### ISSUE TITLE
./letsencrypt-auto --help begins installing, does not do "--help"

### ISSUE THREAD

**Issue by clayt0nk** [letsencrypt/letsencrypt#1286]
I am at commit cbb0e397e99a02a4ea93c406d067f182db5ea6a7

I went there looking for an explanation of how to simply generate a certificate while avoiding having this utility messing with my Apache config, which I would think would be the base case. After all, how many people run a web server and don't know how to configure (and want to maintain control of!!) their SSL configuration?

**Comment by kuba** [comment]
We need to install our dependencies before we can install ourselves and be able to produce output for `--help`.

`letsencrypt certonly` will issue certificates only. `letsencrypt certonly -a webroot --webroot-path /var/www/html`, `letsencrypt certonly -a standalone`, and `letsencrypt certonly -a manual` will not touch your Apache configs.

There are plenty of people that find it very hard to configure their webservers properly. While specifying a path to certificate might not be that hard (although you would be surprised), properly configuring cipher suites is a very complicated process.

**Comment by clayt0nk** [comment]
On Mon, 02 Nov 2015 12:22:49 -0800
Jakub Warmuz <notifications@github.com> wrote:

> We need to install our dependencies before we can install ourselves
> and be able to produce output for `--help`.

That is a little unexpected. If there is no way of separating
"installation" from "running", perhaps that needs to be very clearly
called out in the documentation for first-timers. Maybe even prompt
for permission. When I see applications installing things without my
permission, I get more than a little twitchy.....

> `letsencrypt certonly` will issue certificates only. `letsencrypt
> certonly -a webroot --webroot-path /var/www/html`, `letsencrypt
> certonly -a standalone`, and `letsencrypt certonly -a manual` will
> not touch your Apache configs.

Let's go with:

	./letsencrypt-auto certonly -a manual --server
	https://acme-v01.api.letsencrypt.org/directory

This

	http://blog.expat-it.net/.well-known/acme-challenge/rSYY6gPrQ3z8lX5WcN4XkQkHGQ3NoxKqssLDbeKZ3GU

exists, but I still get "self-verify of challenge failed" (see
attachment).

Thanks,
Clayton
