### ISSUE TITLE
Produced certs still not trusted?

### ISSUE THREAD

**Issue by krieger-od** [letsencrypt/letsencrypt#1289]
I'm happy with the fact that you have received signature from IdenTrust https://letsencrypt.org/2015/10/19/lets-encrypt-is-trusted.html
When to expect this tool to give us certs which are trusted by common browsers/devices?

**Comment by krieger-od** [comment]
Thanks for great easiness of cert generation anyway!

**Comment by xamnesiax-sx** [comment]
The expected release date is this month. At the moment letsencrypt will not provide trusted certificates to those whose domains are not on the Boulder whitelist, which consists of domains owned by selected beta testers. This will be the case until 1.0 is released later this month.
