### ISSUE TITLE
add subdomain

### ISSUE THREAD

**Issue by n3roGit** [letsencrypt/letsencrypt#1306]
Hey folks,

is it possible to add a subdomain to my whitelisted domain?

test.MyDomain.com or stuff

**Comment by bmw** [comment]
Unfortunately, if you want subdomains whitelisted, you have to request them for the beta as well (see [this](
https://community.letsencrypt.org/t/subdomains-during-beta/2062)).

I'm closing this issue as it's not a problem with the Python client which this repo is for.
