### ISSUE TITLE
SSL Labs Chain Issue with fullchain.pem (Beta)

### ISSUE THREAD

**Issue by PatrickHeppler** [letsencrypt/letsencrypt#1307]
I just signed with the Beta CA and got this from SSL Labs Server Test:

Certification Paths
Path #1: Trusted
1	Sent by server	heppler.net 
Fingerprint: f3a2a3b2953eb91680dc0381d9f399c81053da31 
RSA 2048 bits (e 65537)	/ SHA256withRSA
2	Sent by server	Let's Encrypt Authority X1 
Fingerprint: 3eae91937ec85d74483ff4b77b07b43e2af36bf4 
RSA 2048 bits (e 65537)	/ SHA256withRSA
3	In trust store	DST Root CA X3   Self-signed	
Fingerprint: dac9024f54d8f6df94935fb1732638ca6ad77c13 
RSA 2048 bits (e 65537)	/ SHA1withRSA 
Weak or insecure signature, but no impact on root certificate
Path #2: Not trusted (path does not chain to a trusted anchor)
1	Sent by server	heppler.net 
Fingerprint: f3a2a3b2953eb91680dc0381d9f399c81053da31 
RSA 2048 bits (e 65537)	/ SHA256withRSA
2	Extra download	Let's Encrypt Authority X1 
Fingerprint: e045a5a959f42780fa5bd7623512af276cf42f20 
RSA 2048 bits (e 65537)	/ SHA256withRSA
3	Extra download 
  Not in trust store	ISRG Root X1   Self-signed	
Fingerprint: cabd2a79a1076a31f21d253635cb039d4329a5e8 
RSA 4096 bits (e 65537)	/ SHA256withRSA

**Comment by pde** [comment]
There isn't a problem here.  We don't expect Path 2 to be used by many clients in the near future -- it'll require lots of clients to include the Let's Encrypt root, which will take time, and then the introduction of second intermediate CA (the "extra download") one.
