### ISSUE TITLE
Can I use the universal domain it?

### ISSUE THREAD

**Issue by DylanLyu** [letsencrypt/letsencrypt#1312]
Can I use the universal domain it?

Ex:
I applied for domain ssl,"wisfish.com".
Subdomains,"test.wisfish.com",can also use "wisfish.com" authenticate?

**Comment by bluecmd** [comment]
Yes, but for the beta you have to submit individual requests for every subdomain. See https://github.com/letsencrypt/letsencrypt/issues/1306 and https://github.com/letsencrypt/letsencrypt/issues/355

**Comment by kuba** [comment]
This was answered by @bluecmd.
