### ISSUE TITLE
letsencrypt-auto: Uses #!/bin/sh but requires bash

### ISSUE THREAD

**Issue by sdroege** [letsencrypt/letsencrypt#1313]
E.g. with fish:

$ fish ./letsencrypt-auto
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
~/Projects/letsencrypt/letsencrypt-auto (line 24):   if [ "$arg" = "-v" ] || [ "$arg" = "--verbose" ] || echo "$arg" | grep -E -- "-v+$" ; then

Workaround would be to use #!/bin/bash instead

**Comment by pde** [comment]
|| is not a bash-ism.  It's part of the [POSIX shell standard](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html).  The letsencrypt-auto shell is tested with [dash](https://en.wikipedia.org/wiki/Almquist_shell), and should in theory work with any POSIX shell.

However fish is apparently [not POSIX compliant](https://github.com/fish-shell/fish-shell/wiki/POSIX-compatibility-thoughts), which means you shouldn't expect to use it as /bin/sh and have everything work.

**Comment by sdroege** [comment]
Alright, thanks :)
