### ISSUE TITLE
Use a shorter DNS cache on the server-side

### ISSUE THREAD

**Issue by bluecmd** [letsencrypt/letsencrypt#1317]
Hi,

I tried using my letsencrypt on an unconfigured domain and got back that the domain couldn't be resolved. Fair enough. I configured the domain and "dig +trace domain.tld" looks fine, however I still receive the following error:

```
...
FailedChallenges: Failed authorization procedure. domain.tld (simpleHttp): unknownHost :: The server could not resolve a domain name :: No IPv4 addresses found for domain.tld


IMPORTANT NOTES:
 - The following 'unknownHost' errors were reported by the server:

   Domains: domain.tld
   Error: The server could not resolve a domain name

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain contains
   the right IP address.
```

Note: domain.tld isn't the real domain.

My guess is that the previous (negative) response remains cached on the server side.

**Comment by kuba** [comment]
That should be reported on the Boulder repo: https://github.com/letsencrypt/boulder. I don't think we can do much on the client side.

**Comment by kuba** [comment]
Issue on Boulder was opened, closing here. Thanks @MiaP97.
