### ISSUE TITLE
http-01 provisioned resources and newlines

### ISSUE THREAD

**Issue by MiaP97** [letsencrypt/letsencrypt#1322]
For some reason the Litespeed Webserver for my shared hosting appears to add new-lines to text/plain files meaning that the acme challenge fails due to there being a "\n" at the end, it'd be great if LE accepted the \n or knew to remove the \n as I can't find a way to stop it having a \n in the HTTP response (I tried nano -L and echo).
It was returned as a text/plain file (ForceType text/plain in .htaccess) which I checked with HttpFox.
[Relevant section of log](http://pastebin.com/9g0MNYSS)

**Comment by kuba** [comment]
@jsha, how should the spec be interpreted here?

**Comment by jasiek** [comment]
The same problem occurs with nginx.

**Comment by jsha** [comment]
@kuba: I think it makes sense to allow a single newline at the end of the value. If the spec is ambiguous on the topic, would you mind making a pull request at https://github.com/ietf-wg-acme/acme/ improving it?

I haven't tested what the current Boulder behavior is: is this issue about the client's self-verify, or Boulder's verify, or both?

**Comment by kuba** [comment]
Client's `self_verify` is affected. I haven't checked Boulder.

**Comment by tedb** [comment]
@MiaP97 For this to work for me, I had to generate my verification file using "echo -n" to not append the newline, as in:

echo -n "abcd-etc-xyz" > filename

Does that work for you with your Litespeed based host?

**Comment by MiaP97** [comment]
@tedb 
> For this to work for me, I had to generate my verification file using "echo -n" to not append the newline, as in:
> echo -n "abcd-etc-xyz" > filename
> Does that work for you with your Litespeed based host?
It does, which is strange because I used nano -N and still got the error.
It still might be useful to allow a newline at the end because:
a) It's a common error, and
b) Some people may only have access to a web-based text editor that automatically adds new lines

**Comment by adam1010** [comment]
I just had this newline problem as well when using the Linux editor Nano (in addition to having the charset in the Content-Type). Sounds like calling strip() on the file before the comparison would solve the newline problem  (and using a substring search on Content-type instead of == would solve that issue).
