### ISSUE TITLE
./letsencrypt-auto: line 88: /root/.local/share/letsencrypt/bin/pip: No such file or directory

### ISSUE THREAD

**Issue by TheBigBear** [letsencrypt/letsencrypt#1330]
If I run the ```letsencrypt-auto``` after I had run the install cmd which ran fine and with no errors afaict. I now get:

```
./letsencrypt-auto 
Updating letsencrypt and virtual environment dependencies..../letsencrypt-auto: line 88: /root/.local/share/letsencrypt/bin/pip: No such file or directory
```

**Comment by TheBigBear** [comment]
OK, I was/am runing on rhel and needed to upgrade python to 2.7 first. as suggested by: 
https://community.letsencrypt.org/t/redhat-centos-6-x-users-need-python-2-7/2190
and after that i also needed to install gcc44 for the install to succeed.

Now that I have done that I am past this error in this issue, but now I get the following: https://github.com/letsencrypt/letsencrypt/issues/1333

**Comment by kuba** [comment]
You shouldn't need to install Python 2.7. There is some other error out there.

**Comment by ktiedt** [comment]
On a Debian install with 1.7G ram (even killed the only service running) I get this error... I have python 2.7.11 installed already so it isnt a Python problem...

**Comment by ktiedt** [comment]
After digging in even farther to the above link, I found this link: https://wiki.bitnami.com/Mac_Store_Apps/BitNami_Django#virtualenv_restrictions

Related, because I am also using a bitnami image... so found my problem, and it is definitely not a LE issue for me :/ Now to do this the a slightly more difficult way.

**Comment by bmw** [comment]
Is anyone still having this issue? If so, please comment and I'll reopen.
