### ISSUE TITLE
letsencrypt-auto: depends on home directory / running as root is bad / no PREFIX support

### ISSUE THREAD

**Issue by indrora** [letsencrypt/letsencrypt#1334]
(Or, "Dude, where's my sudo?")

As it stands, if you don't have `sudo`, you're toasted. The default in Debian is to not install `sudo` for bare-metal installations. As such, a Debian Jesse/stable minimalist installation doesn't have `sudo`, because there's a password set for `root`.

Should `letsencrypt-auto` depend on sudo? Or just say "Run me as root"? Or, optionally list the packages that need to be installed?

For completeness, this is the entire output from `letsencrypt-auto`:

```
indrora@zaibatsutel:~/letsencrypt$ ./letsencrypt-auto 
Bootstrapping dependencies for Debian-based OSes...
./letsencrypt-auto: 40: ./letsencrypt-auto: sudo: not found
```

Alternately, would a message of "sudo isn't there, using su -c '...'" be appropriate?

**Comment by devnsec-com** [comment]
dups to #1148 ?
BTW, we have got 2 PRs for this issue: #1282 and #1191

**Comment by indrora** [comment]
Looks like a dupe. Tried to find an appropriate ticket to add onto but didn't see that one.

**Comment by indrora** [comment]
The original topic kindof stands (I'll open a new one if needed): If I do run as root, `/root/.local/share/` is where letsencrypt is installed. Following standards, `/opt/letsencrypt/` should probably be where we install things. 

this means letsencrypt-auto shouldn't care that it's not being run as root. letsencrypt-auto seems like it should be more letsencrypt-bootstrap

**Comment by devnsec-com** [comment]
`letsencrypt-auto` is not mean to be run as root. It's not a system wide installer, it only creates a python virtualenv, and install everything into the venv, then run the actual `letsencrypt` from the venv (as root).

**Comment by indrora** [comment]
It shouldn't matter who I run letsencrypt-auto as. It acts like an installer, with the sole point seeming to be "set up the things that letsencrypt needs". I don't want letsencrypt living in someone's home directory -- I want it in `/opt/letsencrypt/` like the [standard says](http://linux.die.net/man/7/hier) it should be.

**Comment by devnsec-com** [comment]
Maybe you think it's an installer, but no, it is not an installer, it bootstraps the `letsencrypt`, not install it.
Each time you want to run `letsencrypt`, you will run `letsencrypt-auto --parameters` (instead of run `letsencrypt --parameters`)

**Comment by indrora** [comment]
So why can't I choose where I want to put the virtualenv? Should I run `letsencrypt` as a completely standalone user?

**Comment by devnsec-com** [comment]
Well, good point, user should have the choice where to put the venv.

**Comment by indrora** [comment]
I propose that `letsencrypt-auto` should be called `letsencrypt-bootstrap`, which does the installation part, then a `letsencrypt` binary placed in `VENV_PATH` which is pushed into `/usr/bin` that does the neccesary actions to make the real `letsencrypt` work.

**Comment by pde** [comment]
@indora letsencrypt-auto is really a hack to get people a simple way to run letsencrypt before their OSes have packaged it in a fully appropriate way.  We aren't going to rename it or split it because it basically does it's job for now, and if people want things to be more "correct" they have several options: (1) edit letsencrypt-auto to totally customise it for their systems; (2) control letsencrypt-auto by setting environmental variables like VENV_PATH before running the script; (3) following the [developer instructions](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client) to have more control over the process; (4) waiting for packages for their OS.

**Comment by pde** [comment]
#1282 fixed the sudo problem, so closing the overall ticket.
