### ISSUE TITLE
Should not stop the apache server

### ISSUE THREAD

**Issue by kroeckx** [letsencrypt/letsencrypt#1339]
It seems that as part of running letsencrypt the apache server is stopped and started again.  I see no good reason to stop it.

**Comment by pde** [comment]
Closing as a duplicate of #954.

**Comment by pde** [comment]
btw @kroeckx I don't think anyone has volunteered to take that ticket.  It's a little tricky, because of the need to wait and test whether the reload has produced the desired results, but should be doable.
