### ISSUE TITLE
Don't use the default UA when verifying challenges

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1351]
While related to #858, I feel like this is a slightly different issue. We have had reports of people running into problems with the User-Agent when using the `manual` plugin. `manual` uses `acme` to validate that the challenge has been set up correctly before responding to the server. This is done using the `requests` library whose default UA as of writing this e-mail is `python-requests/2.8.1`. Some webservers are rejecting requests with this UA, causing self validation to fail, and `letsencrypt` to exit.

**Comment by devnsec-com** [comment]
Perhaps, we should use the UA `acme-client/ver`?

**Comment by bmw** [comment]
Another suggestion I've received was `Mozilla/5.0 (compatible; Let's Encrypt client self-validation; +https://www.letsencrypt.org)`.

**Comment by bowensong** [comment]
Do we need to pretend to be "Mozilla"? I don't think so.
Web browsers say "Mozilla" for the historical reason, because they want the "modern" version of the web pages, but we are not a web browser, and we do not need the "modern" web pages.

**Comment by devnsec-com** [comment]
Do we need to pretend to be `Mozilla`? I don't think so.
Web browsers say `Mozilla` for the historical reason, because they want the "modern" version of the web pages, but we are not a web browser, and we do not need the "modern" web pages.
