### ISSUE TITLE
Removes config file during renewal resulting in error

### ISSUE THREAD

**Issue by kroeckx** [letsencrypt/letsencrypt#1354]
I'm on a Debian system and I have the config files /etc/apache2/sites-available/  This is also where it's writing the new config file.  But to enable it I need to create a symlink in /etc/apache2/sites-enabled/.

It seems that somewhere during the renewal it removes the file in sites-available creating a dangling symlink which then results in an error trying to restart apache2, breaking the whole process.

I also don't think it's a good idea to remove that file in any case, it will cause the site to go down even if you remove the symlink too.  Also, since I had to edit the file because of other bugs I would appreciate that you didn't revert my changes.

One thing I noticed that it says that my configuration was broken or something, not sure why it says that.  It was working perfectly.

**Comment by pde** [comment]
@kroeckx can you send us a copy of the config files that triggered this?

**Comment by kroeckx** [comment]
So I upgraded to 6fbcebd4ab8cb356de92c80c976c9bf0fefb13b4 before trying any of this again to see if I can reproduce it.

It seems to be acting strange, and I can't always reproduce it.  I think I could reproduce twice that it showed me the "1  Apache Web Server - Alpha (apache) [Misconfigured]" again, and I think at that time it already deleted my config file.  I'm just going to have to guess that it saying it's misconfigured because the config file is missing.

At other times when I deleted the file it seems to be restoring to the state the file like I edited it.

It's currently not making much sense to me.

**Comment by bmw** [comment]
The Apache plugin lists itself as misconfigured if it believes there is a problem with your server configuration. It's important to note that the Apache plugin does not currently work on all Apache setups. If our plugin cannot understand your config, it will list itself as misconfigured and it will almost certainly not work.

@kroeckx, is it possible the Apache plugin listed itself as misconfigured before you ran it? The subtleties of what I just described are not at all made clear to the user so it seems perfectly reasonable that you would have done so.

If this is the case, this suggests we should bump the priority of #990 into the "1.0 for launch" (I just did) and close this issue. If Apache can't parse your config, it is reasonable to expect it won't edit it properly

**Comment by kroeckx** [comment]
I think the removal part is probably just the #1394 thing where I pressed ^C during a previous call, so maybe this can just be closed.

**Comment by bmw** [comment]
From a configuration that is not "misconfigured", can you recreate the problem?

**Comment by pde** [comment]
Sounds like this was probably fixed by #1394; if anyone can repro please reopen (or more realistically, file a new ticket).
