### ISSUE TITLE
Fetch cert to current directory

### ISSUE THREAD

**Issue by victorhaggqvist** [letsencrypt/letsencrypt#1355]
I am possibly missing something here.. But I would be nice to be able to fetch a cert on my local machine to current directory, without root. I would believe the run bellow only wants permission to put the cert in `/etc/letsencrypt`, right?

Running `letsencrypt` without root yeals this.
```
$ letsencrypt certonly --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory -d mydomain.com
An unexpected error occurred.
OSError: [Errno 13] Permission denied: '/etc/letsencrypt'
Please see the logfile 'letsencrypt.log' for more details.
```

Don't know if it makes any difference, but I installed via https://aur.archlinux.org/packages/letsencrypt-git/

**Comment by devnsec-com** [comment]
> But I would be nice to be able to fetch a cert on my local machine to current directory, without root.

If by saying "fetch a cert", you mean "copy from `/etc/letsencrpyt/somewhere`", and _**without root**_, you must be kidding me. That's definitely no way! 

If you mean "fetch a cert from the acme server", maybe yes, but only if the "current directory" is not readable by anyone else on the server.

**Comment by victorhaggqvist** [comment]
I might have been unclear. But yes I'm mean the "fetch a cert from the acme server" scenario.

**Comment by kuba** [comment]
This was partially addressed in #843.

**Comment by bmw** [comment]
@victorhaggqvist, there is currently no way to do exactly what you want. The client needs root for two things:

1. To access the default directories.
2. To bind to port 80/443.

You can fix 1 on the command line. `--config-dir`, `--work-dir`, and `--logs-dir`, can all be changed to directories that the current user can access to mitigate that problem. The certificates are stored in directories under `config-dir`.

You can fix 2 by using the `webroot` or `manual` plugins (see [this](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins)).

To get the cert in your current directory, there is one thing you can do but it requires some extra work. You can pass the client a CSR with `--csr` that will be used to generate your certificate (see `letsencrypt --help certonly` for more info). If you do this and don't specify any other paths than the ones mentioned above, the resulting certificate will be saved in your current directory by default.

I'm sorry there's no way to do exactly what you're looking for, but I hope these suggestions help.

**Comment by kuba** [comment]
@victorhaggqvist you can try using https://github.com/kuba/simp_le - it fetches certs to current directory
