### ISSUE TITLE
HTTP01 simple_verify doesn't allow empty Content-Type

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#1356]
Per spec, an http-01 challenge can be served with no Content-Type, or a Content-Type of `text/plain`. By my reading of the code, `simple_verify` only allows `text/plain`, not an empty Content-Type.

**Comment by pde** [comment]
Fixed for webroot in #1336?  But we need to ensure Apache and standalone are okay?

**Comment by bmw** [comment]
This inaccurate but perhaps the code could be made more clear. The relevant line of code is: https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/challenges.py#L262

The call to `get` is given a default value. The result is if `Content-Type` is absent, `found_ct` is given the value `text/plain` and is verified successfully.

**Comment by kuba** [comment]
@jsha: `simple_verify` will succeed if 'Content-Type' header is not present. Is it even possible that client serves **empty** Content-Type header?

**Comment by jsha** [comment]
Thanks for correcting me, @bmw, and sorry for not testing my assumptions. Makes sense that it has a default value.

It is possible for a web server to give an empty Content-Type header, but I don't think we need to accommodate that case. Perhaps a more likely possibility is multiple, conflicting Content-Type headers, but that doesn't belong under this issue.
