### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#136]
![command-line](https://cloud.githubusercontent.com/assets/1581662/5482522/dde0a4aa-8617-11e4-830e-814fcc473392.jpg)

Potential changes to command line

**Comment by ThomasWaldmann** [comment]
do you really want to have 1 separate script command per supported software (letsencrypt-apache, letsencrypt-nginx, ...)?

how about: letsencrypt apache --getcert/--revoke/...

**Comment by kuba** [comment]
I'm working on that in https://github.com/kuba/lets-encrypt-preview/tree/cli

This looks like a duplicate of #285. Can we close one?

**Comment by pde** [comment]
@saschaf is considering doing some user studies with a mockup of this ...

**Comment by bmw** [comment]
Closing as picture is largely outdated.
