### ISSUE TITLE
Use peep to verify the ConfigArgParse import.

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1363]
(1) This means everyone's fetching code from Kuba's repo, which is ok for experimental beta hacking but not for release
(2) The version pin produces an annoying message in the middle of -auto runs:

`Requirement already satisfied (use --upgrade to upgrade): ConfigArgParse from git+https://github.com/kuba/ConfigArgParse.git@python2.6-0.9.3#egg=ConfigArgParse in /tmp/throwaway/lib/python2.7/site-packages (from -r py26reqs.txt (line 1))`.

**Comment by kuba** [comment]
What's wrong with fetching stuff from my repo? How is vendorizing better?

I'm strongly (!) against proposed changes.

**Comment by pde** [comment]
Per our call today, we can work around this by pinning a hash of this dependency with [peep](https://pypi.python.org/pypi/peep/).

We should also silence the loud message during that run.

**Comment by erikrose** [comment]
Feel free to ping me with questions on peep-ish practices. A good parallel example is https://github.com/mozilla/dxr/blob/master/requirements.txt#L49-L50.

**Comment by pde** [comment]
@erikrose is working on this.
