### ISSUE TITLE
Only require user to agree to user agreement once

### ISSUE THREAD

**Issue by paulschreiber** [letsencrypt/letsencrypt#1365]
Only require users to agree to user agreement once.

Do not require the user to agree every run, either by selecting "Yes" in the UI or by passing `--agree-dev-preview` as argument.

**Comment by pde** [comment]
I believe this is a duplicate of #887.

One of these things is a warning about the client being experimental (and not getting valid certs by default).  The other is an actual agreement with the CA

**Comment by bmw** [comment]
While not exactly a dupe, this annoyance with `--agree-dev-preview` is only temporary and will be fixed with #887. Once we've launched, you won't need to agree to this developer preview at all.
