### ISSUE TITLE
Cname record will cause challenge to fail

### ISSUE THREAD

**Issue by Microsheep** [letsencrypt/letsencrypt#1367]
I am possibly missing something here, but will try to point out my issue.
I used to have a cname record for www.twmicrosheep.com to twmicrosheep.com.
As invited to the closed beta test, I tried to get a ssl certificate for www.twmicrosheep.com.
It has the following errors. 

<b>Failed authorization procedure. www.twmicrosheep.com (dvsni): tls :: The server experienced a TLS error during DV :: Failed to connect to host for DVSNI challenge</b>

After some trials, I manage to get it to work by setting an A record to www.twmicrosheep.com then it can pass the challenge. I can then change it back to a cname record.

BTW, I am using cloudflare as my DNS provider.

**Comment by Eeems** [comment]
+1
Also on cloudflare.

**Comment by mk-pmb** [comment]
Thanks for offering the public beta! I tried and got this SNI error:
```text
Running with virtualenv: /home/***/.local/share/letsencrypt/bin/letsen
crypt --apache -d service.******.de
Failed authorization procedure. service.******.de (tls-sni-01):
urn:acme:error:unauthorized :: The client lacks sufficient
authorization :: Correct zName not found for TLS SNI challenge. Found

IMPORTANT NOTES:
- The following 'urn:acme:error:unauthorized' errors were reported by
the server:

Domains: service.******.de
Error: The client lacks sufficient authorization
```

Case details:

```text
$ host service.******.de
service.******.de is an alias for machine.******.de.
machine.******.de has address 8*.1*.2*.4*

$ apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Oct 14 2015 14:20:21

$ plesk version
Product version: 12.0.18 Update #71
    Update date: 2015/12/05 01:33
     Build date: 2015/10/14 14:00
   Build target: Ubuntu 14.04
       Revision: 333119
   Architecture: 64-bit
Wrapper version: 1.1
```

**Comment by Eeems** [comment]
Has anybody looked into this? I would like to be able to get certificates for all my domains, but I'd rather not change the CNAME records on them all into A records due to how much of a pain that would be to update if I switch IPs in the future.

**Comment by fallanic** [comment]
+1

**Comment by jsha** [comment]
Boulder definitely supports CNAMEs. It does DNS lookups via Unbound, which resolves CNAMES internally. There may be another problem causing these validation failures. I'd encourage you to post at https://community.letsencrypt.org/ with full details including all hostnames on the certificate, and we can help debug over there.

**Comment by bjacke** [comment]
I stumbled also over this problem. A network trace showed that the letsencrypt server is correclty coming to ask for the validation token our server didn't respond to the SYN packet for the second domain request at at. It turned out that net.ipv4.tcp_tw_recycle was enabled and cause the problem. Disabling tcp_tw_recycle made the letsencrypt domain validation for all domains names work again.

**Comment by mk-pmb** [comment]
Problem seems fixed in the current version of [certbot](https://certbot.eff.org/docs/) (version "letsencrypt 0.8.1"), tested on Ubuntu 14.04.4 LTS (trusty). The problem now has evolved into
> Currently, we only support configurations with one vhost per file
