### ISSUE TITLE
Error creating new registration without MX-record.

### ISSUE THREAD

**Issue by duckdalbe** [letsencrypt/letsencrypt#1371]
My domain hasn't got an MX-record in DNS but accepts Email at the A-record. This is conforming to standards, AFAIK.

The ACME-clients apparently mandatorily expects an MX-record. It fails with this:
```
An unexpected error occurred.                                                                                   
Error: malformed :: The request message was malformed :: Error creating new registration :: No MX record for domain $domain.
```

Is there any way around this other than adding an MX-record?

**Comment by andreasf** [comment]
https://github.com/letsencrypt/boulder/commit/3ccc79e49d42dcbbfba27e3f2547111f453b23c2 should have fixed this, as it replaced the call to `LookupMX` with `LookupHost`. `LookupMX` is no longer called anywhere in boulder.

**Comment by andreasf** [comment]
Works for me now. Thanks!

**Comment by bmw** [comment]
Yes. I believe this has been fixed in Boulder so I'm closing this issue. If this problem persists for someone, please comment and I'll reopen.

**Comment by duckdalbe** [comment]
Works for me, too! Thank's a lot!
