### ISSUE TITLE
letsencrypt-auto could suggest/enable the augeas 1.2 backport on wheezy

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1373]
That would allow ongoing apache plugin support on that platform.

**Comment by pde** [comment]
Silently enabling is probably a bad idea, but suggesting or asking (Y/N) could be fine.

**Comment by pde** [comment]
There's code in the apache22-hack branch to do this.  It's waiting on a fix for #1208 before it's worth landing.

**Comment by bmw** [comment]
Yes. I oppose silently enabling the backport, but prompting the user and automating the process if they agree seems reasonable. The easy fix is to just give them instructions on how to enable the backport themselves, but it would obviously be nice if we could do it for them.

**Comment by bmw** [comment]
Our bootstrap scripts enable the backport so I'm closing this issue.
