### ISSUE TITLE
Manual authentication should permit the server to use https

### ISSUE THREAD

**Issue by jasiek** [letsencrypt/letsencrypt#1378]
I've got a server with an existing certificate, and I'd like to be able to complete the authentication procedure over HTTPS (for convenience). Why not let the client request the challenge file over HTTPS first, and then, if that fails - HTTP?

**Comment by pde** [comment]
Because of this vulnerability:

https://mailarchive.ietf.org/arch/msg/acme/B9vhPSMm9tcNoPrTE_LNhnt0d8U

If your server listens on port 80 but redirects to 443, the validation will occur safely after the redirect.
