### ISSUE TITLE
Letsencrypt-auto fails with invalid syntax

### ISSUE THREAD

**Issue by xanni** [letsencrypt/letsencrypt#1379]
Debian Squeeze, Python 2.6.6-8

$ VERBOSE=1 ./letsencrypt-auto --help

[...]

```
Collecting letsencrypt
  Using cached letsencrypt-0.0.0.dev20151104-py2-none-any.whl
Collecting letsencrypt-apache
  Using cached letsencrypt_apache-0.0.0.dev20151104-py2-none-any.whl
Collecting zope.interface (from letsencrypt)
  Using cached zope.interface-4.1.3.tar.gz
Requirement already up-to-date: setuptools in /home/xanni/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Collecting python2-pythondialog>=3.2.2rc1 (from letsencrypt)
  Using cached python2-pythondialog-3.3.0.tar.bz2
Collecting PyOpenSSL (from letsencrypt)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting requests (from letsencrypt)
  Using cached requests-2.8.1-py2.py3-none-any.whl
Collecting ConfigArgParse (from letsencrypt)
  Using cached ConfigArgParse-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-mtd8A5/ConfigArgParse/setup.py", line 1, in <module>
        import configargparse
      File "configargparse.py", line 16
        ACTION_TYPES_THAT_DONT_NEED_A_VALUE = {argparse._StoreTrueAction,
                                                                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mtd8A5/ConfigArgParse
```

**Comment by bmw** [comment]
These problems should have been fixed in #1361, which has landed in `master` but has not yet been pushed to PyPI so that it affects `letsencrypt-auto`.

**Comment by pde** [comment]
@xanni Hi Andrew!  We should have another release out shortly to fix this; in the mean time you can follow the [developer instructions](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client) to run from git master.

**Comment by xanni** [comment]
On 07/11/15 08:22, Peter Eckersley wrote:
> @xanni <https://github.com/xanni> Hi Andrew! We should have another
> release out shortly to fix this; in the mean time you can follow the
> developer instructions
> <https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client>
> to run from git master.

Yep, already did a git pull and got it working last night.  The only
problem is that I asked for mail.glasswings.com.au but only got
glasswings.com.au so far, so I had to reconfigure not only my webmail
but also dovecot and qpsmtpd to use the parent domain - and then change
the server settings on my clients to match.  It's working fine, but I
would still like mail.glasswings.com.au so I don't have to get all my
customers to change the settings on their mail clients!

Thanks,
	Andrew
