### ISSUE TITLE
Webroot plugin should override permisions of files / dirs created

### ISSUE THREAD

**Issue by Zash** [letsencrypt/letsencrypt#1389]
Running with --webroot-path and umask 0027 creates .well-known/acme-challenge/... with no global read permissions, causing the verification to fail because the HTTP server can't read the files (at least not in my setup).

Either overriding permissions during/after creation or making the directories and challenge file have similar permissions as the webroot itself should probably work in most cases.

**Comment by lbeltrame** [comment]
Indeed. Where in the code is this handled? I may take a look at this.

**Comment by bmw** [comment]
@lbeltrame, the code for this is in `letsencrypt/plugins/webroot.py` in the `prepare` function.

**Comment by pde** [comment]
@lbeltrame if you're getting started on this now, I suggest working on top of the [webroot](https://github.com/letsencrypt/letsencrypt/tree/webroot) branch being discussed over in #1594, since it somewhat alters that `prepare` function.

**Comment by lbeltrame** [comment]
I started doing some work https://github.com/lbeltrame/letsencrypt/tree/webroot, however GH is not allowing me to do a PR yet...

**Comment by lbeltrame** [comment]
As you can see, a WIP PR landed. Please let me know how I can improve it.

**Comment by pde** [comment]
Thanks for fixing this @lbeltrame !

**Comment by yaccin** [comment]
This issue seems to have reappeared in certbot 0.14.0
