### ISSUE TITLE
pythondialog is no longer available for Python 2

### ISSUE THREAD

**Issue by fmarier** [letsencrypt/letsencrypt#139]
From the [upstream page](https://pypi.python.org/pypi/pythondialog):

> As of version 2.12, the reference implementation of pythondialog (which this file belongs to) requires Python 3.0 or later in the 3.x series.

This means that the pythondialog dependency cannot be fulfilled on Debian jessie and later.

There is an out of date [backport](https://pypi.python.org/pypi/python2-pythondialog/3.0.1), but it comes with this warning:

> This version is only here to help users who are somehow forced to still use Python 2, even though Python 3.0 was released on December 3, 2008. It may be the last update for Python 2. In addition, the reference implementation is less likely to have bugs.

and it's not in Debian, nor is it likely to ever be in Debian.

**Comment by ThomasWaldmann** [comment]
I think letsencrypt should work on py3 (>=3.3) and py2 (2.7) for now. This can be done using the same source code and some _compat.py lib that has some needed compatibility code (see pocoo projects porting).

But first dependencies have to be checked (do all support py3?) and test coverage has to be increased.
Also, if python3 support is wanted, a separate ticket should be opened for this.

**Comment by pde** [comment]
Python3 support is definitely a different issue to python2 dialog on Debian!  One thing to be clear about is that we will not be able to ship a Python3-only project anytime in the foreseeable future; there are two many systems that are py2 only (eg, old Macs), and we need to support those. 

So @fmarier let me add another option:

4. we ship our own clean, up-to-date Debian backport of python2-dialog

So my instincts are option 4 > option 3 >  option 1.  If someone really believes that coding for py2 and py3 (perhaps with [six](https://pythonhosted.org/six/)?) is really easier than just coding for py2, I'd consider reordering but it just isn't intuitive to me to to do work to support a version we can't depend on.

I don't know what to say about option 2.  Which alternative library would we use and why?

**Comment by fmarier** [comment]
What's the target for the letsencrypt client? Servers? What's the oldest version of RHEL you want to support? In Debian land, both squeeze and lucid LTS have Python 2.6 and 3.1.

If I understand you correctly, I think your option 4 is what I meant by option 3:
* by "we ship" I assume you mean "we bundle into the letsencrypt source package" and
* by "up-to-date" I assume you mean the latest (outdated and no longer maintained compared to the Python 3 version) upstream release of python2-dialog?

It's certainly not a deal breaker, which I why I included it in the list of reasonable options, but a Python 3 version would be much nicer. Anyways, we can solve the immediate problem with option 3 and then work towards making it better in a later release.

**Comment by ThomasWaldmann** [comment]
@pde noone ever said that coding for py2 AND py3 is easier than for py2 only. or that py3-only is an option for now.

about "six": back when the pocoo stuff was ported, six was not complete enough and own compat code had to be added. also, for timing reasons, we wouldn't want to wait until the missing stuff was added to six, so the way that was chosen (by armin ronacher) was to have an own _compat.py module that is part of the project that has all the needed stuff. One outside dependency / version dependency less.

@fmarrier: if one wants to support py3 < 3.3, one has to add lots of wrappers around "text" literals (unicode in py2, str in py3) as only 3.3+ supports u"" and these wrappers make the src rather ugly.

**Comment by fmarier** [comment]
I'm currently pursuing option 5:

<code>5. maintain the python2-pythondialog backport in Debian until we can move away from it</code>

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780929

There is of course no guarantee that my upload will be approved.

**Comment by pde** [comment]
Should we do anything to encourage acceptance of that upload?

**Comment by fmarier** [comment]
@pde I would give it a bit more time because sometimes these things take a while. I've just added a comment on the bug though in case that's useful.
