### ISSUE TITLE
Ignore Mimetype of the challenge file

### ISSUE THREAD

**Issue by allo-** [letsencrypt/letsencrypt#1398]
When the mimetype of the .well-known/acme-challenge file is not text/plain, the client fails.
I noticed that, because nginx seems to treat the file as binary/octet-stream by default.
Mimetype should not matter for the challenge authentication, so the client (or server?) should just ignore the Content-Type field of the response.

**Comment by BurakDev** [comment]
Ignoring Content-Type will be a security issue

**Comment by allo-** [comment]
Why? You fetch a file and look at the content.
The file got fetched despite its wrong content-type. I guess the server side does nothing else than matching the content with a string in the database, or does it? Anyway, the server could serve anything, even with text/plain content-type, if there are any security issues, i see not how they depend on the content-type header.

**Comment by mitnk** [comment]
+1 for allo, don't see any issue by ignoring the content-type.

**Comment by kuba** [comment]
`Content-Type: text/plain` is mandated by the spec: https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#http. Relevant discussion in the right issue tracker: https://github.com/ietf-wg-acme/acme/issues/9
