### ISSUE TITLE
Production server stopped delivring certs

### ISSUE THREAD

**Issue by BurakDev** [letsencrypt/letsencrypt#1399]
Hello, letsencrypt production server stopped working.

When the validation is done, letsencrypt-auto return this error :

Error: serverInternal :: The server experienced an internal error :: Error creating new cert

Sincerely,
Burak

**Comment by EliteTK** [comment]
Same issue here. And I only just got accepted into the beta :(

**Comment by pde** [comment]
Not a client bug.  Also, should now be resolved :)
