### ISSUE TITLE
Add .txt extension to ACME challenge URL for automatic Content-Type

### ISSUE THREAD

**Issue by intgr** [letsencrypt/letsencrypt#1405]
Currently when performing manual authentication, you ask the user to create a file with a certain file name, and then reconfigure their webserver to serve that with `Content-Type: text/plain`. For example `http://example.org/.well-known/acme-challenge/GUu94CoL-MRy4Lr4VpCLV4uG4kEqm4hDQ_9i8XMOixo`

You could make it a lot easier by appending `.txt` to the challenge URL (filename), so no reconfiguration needs to take place.

**Comment by kuba** [comment]
Relevant discussion in the right issue tracker: ietf-wg-acme/acme#9.
