### ISSUE TITLE
Simple-verify for all plugins. Log, do not fail.

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1409]
Let's use `logger.warning` instead of stopping the client when `self_verify` has failed. Also, let's do it for all plugins, not just manual authenticator. It might be opt-out, but I don't see a clear reason why it should be.

**Comment by kuba** [comment]
@bmw, I believe "Log, do not fail" part of this issue should be bumped to 1.0 milestone. It causes a lot of problems for `manual` users.

**Comment by bmw** [comment]
The main reason it's causing people problems though is the recently removed restrictions on Content-Type correct? Once that is fixed, I suspect this issue will have a much lower priority.

**Comment by bmw** [comment]
I'm breaking this into two issues: #1585 and #1586.
