### ISSUE TITLE
"--webroot --webroot-path $root": confusing error message

### ISSUE THREAD

**Issue by flwyd** [letsencrypt/letsencrypt#1416]
The following error output is confusing.  It complains that --webroot-path expected one argument, but that argument was provided.  The same error occurs with `--webroot-path=~/public_html` and `--webroot-path ~/public_html`
This seems like either a bug in flag parsing or a very misleading error message.  Setting the same path in a cli.ini file works fine.
```
Updating letsencrypt and virtual environment dependencies.....Requirement already satisfied (use --upgrade to upgrade): ConfigArgParse from git+https://github.com/kuba/ConfigArgParse.git@python2.6-0.9.3#egg=ConfigArgParse in /home/tstone/.local/share/letsencrypt/lib/python2.7/site-packages (from -r py26reqs.txt (line 1))
..
Running with virtualenv: sudo /home/tstone/.local/share/letsencrypt/bin/letsencrypt --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory --webroot --webroot-path /home/tstone/public_html -d trevorstone.org -d www.trevorstone.org certonly
usage: 
  letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ...
  <snip>
letsencrypt: error: argument --webroot-path: expected one argument
```

**Comment by kuba** [comment]
I don't think `--webroot` is implemented, you should use `-a webroot` instead.

However, this error message is extremely confusing and I think it's valid bug.

Related: #892
