### ISSUE TITLE
Do not require me to stop my web server

### ISSUE THREAD

**Issue by cweiske** [letsencrypt/letsencrypt#1424]
When running `letsencrypt-auto`, I get the following message:

> The program apache2 (process ID 23326) is already listening on TCP port 80. This will prevent us from binding to that port. Please stop the apache2 program temporarily and then try again. 

I do not want this. My web server is important, and taking it down for I-do-not-know-why long isn't an option for me.

I guess this is done for proving the posession of the domain.

Can't this be done on a free port and not port 80?

**Comment by analogic** [comment]
https://github.com/letsencrypt/acme-spec/issues/33

**Comment by My1** [comment]
you also could try manual auth or webroot which also shouldnt require stopping your server instead you have to put certain files to certain paths in your domain. that might look like this:
http://my1xt.tk/.well-known/acme-challenge/jtjmeR1xz7CoAT7nkvsXa1mF2vROThNlTY31ZUuJg4E
you have the url and in that you have a certain text accessible.

**Comment by cweiske** [comment]
@My1: The client advised me to do it and did not go any further without it. While it might be true that I can solve this problem somehow, it isn't straightforward.

**Comment by My1** [comment]
that's why you should try manual mode (-a manual) it might work that way.

**Comment by bmw** [comment]
This is actually a dupe #1370. @cweiske, if you're running Let's Encrypt on your server, I would use `webroot`, otherwise I would use `manual`. More information is available [here](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins).
