### ISSUE TITLE
Asks about HTTPS redirect despite installer not supporting it

### ISSUE THREAD

**Issue by sesse** [letsencrypt/letsencrypt#1432]
Hi,

I'm writing an installer plugin that will not support enhancements, and thus returns none:

    def supported_enhancements(self):
        return []

Nevertheless, on letsencrypt install (with this plugin), I get the choice “Please choose whether HTTPS access is required or optional.”, and then I can choose between Easy or Secure. Shouldn't it check with the installer if it can do the “redirect” enhancement before it asks? It just calls enhance() with no more ifs and buts, which fails.

**Comment by bmw** [comment]
There's actually a TODO about this in the `enhance_config` function in `client.py`. Thanks for creating this issue though. Github is certainly a better place to track the issue than a TODO comment.

The relevant change needs to be made in `enhance_config`.
