### ISSUE TITLE
letsencrypt-auto only checks for packages?

### ISSUE THREAD

**Issue by acastaner** [letsencrypt/letsencrypt#1441]
I just got invited in the beta and tried to run Let's Encrypt on a CentOS 6.7 VPS machine. I have cloned the repo and ran the following command:

``sudo ./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth``

The dependencies were correctly installed and I didn't get any error message. However the /etc/letsencrypt folder wasn't created, and every time I rerun ``./letsencrypt-auto`` it just checks against yum again. Even if I try to generate a certificate (for instance `sudo letsencrypt -d www.example.org auth`).

I'm not sure what I'm doing wrong. The documentation isn't clear on this - just says to substitute all the "letsencrypt" with "letsencrypt-auto" but that's it. Not sure what else to do.

**Comment by acastaner** [comment]
Ok it seems that on CentOS you need to add the --debug argument because Python 2.6 is deprecated on this platform.

**Comment by pde** [comment]
@acastaner it sounds like this is working for you now?  Please reopen if not.
