### ISSUE TITLE
Virtual env. creation failed on Debian

### ISSUE THREAD

**Issue by bemyak** [letsencrypt/letsencrypt#1444]
I'm running letsencrypt on debian jessie server with enabled backports and proposed-updates
Dependencies installation is OK, but After that I get:
```
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2378, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 830, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1032, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 975, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 917, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```
I can't find any similar bug here, so I decide to create a new one.
Is there any solution?

**Comment by pritambaral** [comment]
Haven't been able to reproduce it on a fresh, updated install of jessie with backports and proposed-updates enabled. A fresh clone from master and a `./letsencrypt-auto` works well enough to be able to successfully create a virtualenv.

@bemyak Can you reproduce it? Are there any specific steps?

**Comment by bemyak** [comment]
Yes, I can.
Here is full log:
http://pastebin.com/8U3WzbRW

**Comment by pde** [comment]
It looks like you're winding up with a python3 virtualenv trying to run python 2 things.  What's the output of `dpkg -l *virtualenv*` and `pip --version`?  Also, can you pastebin a log with `--verbose` added to the `letsencrypt-auto` command please?

**Comment by bemyak** [comment]
Shure, here it is:
```
# dpkg -l *virtualenv*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version      Architecture Description
+++-==================-============-============-==================================
ii  python-virtualenv  1.11.6+ds-1  all          Python virtual environment creator
ii  python3-virtualenv 1.11.6+ds-1  all          Python virtual environment creator
ii  virtualenv         1.11.6+ds-1  all          Python virtual environment creator
```
```
# pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
```
```
# ./letsencrypt-auto --agree-dev-preview --server \https://acme-v01.api.letsencrypt.org/directory --verbose
```
output here: http://pastebin.com/6CyS6cA5
(I've changed default locale to en_EN. With my default locale there is no perl warnings but python error is the same)

**Comment by pritambaral** [comment]
I found something odd in your log:

>   File "/usr/lib<b>64</b>/python2.7/sysconfig.py"

What does `dpkg -S /usr/lib64/python2.7` say?

I tried to reproduce this on a fresh 32-bit instance, and there was no /usr/lib64 directory. I suspect your python2.7 installation is non-standard.

@pde the `virtualenv` command in debian now runs on python3 and is capable of creating both python2 and python3 virtualenvs.

**Comment by bemyak** [comment]
"lib64" directory appears only on 64-bit installation.
Inside "lib" only 32-bit libs are located. I'm using 64-bit system, so that's OK I guess.
```
# dpkg -S /usr/lib64/python2.7
dpkg-query: no path found matching pattern /usr/lib64/python2.7
```
That's strange!
So I've moved that folder to /tmp (just for test) and letsencrypt command passed successfully.
Thank you!
I think the bug appears because the installation of my debian is really old, it was installed as Squeeze and upgraded first to Wheeze and then to Jessie. I guess the python was located at that place once.
