### ISSUE TITLE
Document use of hidden directories in webroot/manual

### ISSUE THREAD

**Issue by thenktor** [letsencrypt/letsencrypt#1445]
The webroot domain verification method fails with Hiawatha web server because Hiawatha blocks all access to hidden directories (directories beginning with a dot) for security reasons. It will always return a 403 when /.well-known/acme-challenge/ is accessed.
See this discussion: https://www.hiawatha-webserver.org/forum/topic/623

**Comment by bmw** [comment]
This is also the default behavior on Nginx, but like Nginx, it looks like this behavior can be configured. See `AllowDotFiles` [here](https://www.hiawatha-webserver.org/manpages/hiawatha).

**Comment by thenktor** [comment]
You are right. My yesterday's test with this option failed, but now I could pin down the problem to something else in Hiawatha's configuration.

**Comment by bmw** [comment]
I'm glad you were able to resolve the problem @thenktor. In response to this problem for Hiawatha, Nginx, and other webservers, we should document that to use `webroot`, your server needs to be serving files in hidden directories. I'll modify the title of this issue to reflect this.
