### ISSUE TITLE
what is a good tiny (or minimum) system to fire up and fetch the LE SSL certs to a file? 

### ISSUE THREAD

**Issue by TheBigBear** [letsencrypt/letsencrypt#1449]
My RHEL 5 box is not able to actually fetch the certificates and the support issues raised don't seem to progress, so I am wondering if I can instead ( and only as a short term relieve ,or work-around, - get the SSL certs that will otherwise need to be bought - as the current ones expire in days )

RHEL 5 is also not suitable for runnig docker on it. So I am thinking of installing a small and simple linu distro that has enough SSL and python bits and pieces to allow me to interact with letsencrypt.org and fetch my new SSL certs to file?

What smallest or tiny linux distro would be guaranteed to work for this purpose?

**Comment by TheBigBear** [comment]
The issue that I am stuck on and that doesn;t get resolved is: https://github.com/letsencrypt/letsencrypt/issues/1333 , so this one is just to come up with a 'quicker' work-around, which I presume would be interesting to toehrs as well. 
Maybe there is a suitable 'vagrant' file available that will do what you would ordinarily do with your docker file provided?

**Comment by bmw** [comment]
The current Linux distros that are officially supported are Debian or Red Hat based distros with Python 2.7 and Arch Linux.

If your main concern is size, you could give Arch a shot. While there is certainly a smaller variant of Debian/Red Hat out there that I'm not aware of, `letsencrypt` as likely not been tested on it.
LE is known to work well on Arch. The one problem you may run into here is installation/setup time.

**Comment by TheBigBear** [comment]
@bmw thanks for your help. I now got the first LE certificate thanks to your help.

Do you know or can you comment on how LE reacts or works ir interacts on a shared hosting setup? I have a dedicated rhel 5 server that uses the Plesk control panel and have a number of SSL enabled domains that all have their own dedicated fixed IP (no SNI and the like).

I have now fired up a vagrant ubuntu-trusty to get my first LE cert for the main dedicated server, thanks to you. 

Should I now copy/sync the '/etc/letsencrypt' contents from the 'client' vagrant virtual guest to the main host?

And can I 'safely' start up the same vagrant virtual ubuntu-trust vm to fetch the other SSL certificates for the other domains whilst in the relevant hosting shell with the correct IP etc? And keep syncing the master '/etc/letsencrypt' files with the ones on the virtual vagrant ubuntu-trusty client vm?

Or will this confuse/break the '/etc/letsencrypt' on the main host? Or in other words do I need to track the changes and files for each domain I host separately in it's own '/etc/letsencrypt' folder structure, or does letsencryot not care and not get confused by me using a single client machine to go and collect keys for a multitude of domains all with their own separate IPs?

**Comment by pde** [comment]
Glad you got a cert!  Probably community.letsencrypt.org is the place where we're best equipped to give you detailed help on what might and might not work on your infrastructure.  So please ask your vhosts question over there, where others will also learn from the answer.

We also need to write better docs for everything inside /etc/letsencrypt.  Another todo item!
