### ISSUE TITLE
domain string in user config limited to 64 chars

### ISSUE THREAD

**Issue by IzzySoft** [letsencrypt/letsencrypt#1452]
I've initially posted it at the wrong place ([see here](https://github.com/letsencrypt/acme-spec/issues/232)), from where I was sent to [another wrong place](https://github.com/letsencrypt/boulder/issues/1117) – so I hope try number 3 hits the right place now:

The client accepts a config file using the `-c <filename>` parameter. I'm using this to setup things. With new domains whitelisted, I had to create a new certificate – so I've setup my config file, putting the host names in the `domain = name, altname1, altname2` line. On call, the [client crashed](http://pastebin.com/vs60WXn2):

    Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]

Bad thing, as wildcards are not permitted and the cert (in this case) *must* hold all the names. Figured I can work around this via the `-d` command-line parameter (`-d name -d altname1 -d altname2`), and the cert was created fine. Checked the `.conf` file in `/etc/letsencrypt/renewal` – and found the `domain =` line being exactly as quoted above.

**Verdict:** this limitation just applies to the `-c <config>` file, but not to the renewal config file. Work-around exists as described – but it still would be nice to see this fixed.

**Comment by bmw** [comment]
Third times a charm. You've found the right repo. This actually a known problem though. See #1180 for discussion of the issue.

**Comment by IzzySoft** [comment]
Thanks for the pointer, @bmw – different error message, but similar issue. The key answer is (quoted from there):

> Setting values in the configuration file is like setting them on the command line. On the command line, you have to specify the domain flag for each domain.

I already noticed that in another context (no underscores, but dashes in e.g. `standalone-supported-challenges`). The quoted line should be placed in the head of the sample configs :)

**Comment by kuba** [comment]
Plase submit PR, @IzzySoft to change `example/cli.ini`?

**Comment by IzzySoft** [comment]
@kuba Shall I really fork the entire repo and submit a PR just to add a comment at top of `examples/cli.ini`? If you insist I do (but I feel that a bit overkill) – otherwise feel free to copy-paste from here:

~~~
# This is an example of the kind of things you can do in a configuration file.
# All flags used by the client can be configured here. Run Let's Encrypt with
# "--help" to learn more about the available options.
# Note that you have to specify the options in this configuration file as they
# are shown in that help message (not as they appear in the config files located
# in /etc/letsencrypt/renewal). If at the command line you need to specify an
# option multiple times (e.g. domains using the "-d" switch), you need to do so
# here as well (e.g. multiple "domains =" lines, one per domain).
~~~

First 3 lines are those already present – subsequent lines I'd suggest to add.

**Comment by bmw** [comment]
@IzzySoft, read the rest of my comment from #1180 that you quoted. Specifying `domains` multiple times in the config file doesn't work:

>... This is what you would have to do in the configuration file BUT this doesn't quite work. If you do something like:
>```
>domains = example1.com
>domains = example2.org
>```
>The value of `domains` is overwritten by "example2.org". I agree the use of `domains` is misleading and this limitation isn't ideal. Perhaps we could consider using a comma separated list for `--domains` in the future which would fix the problem.

**Comment by IzzySoft** [comment]
@bmw Oh – I see. In that case, I'd raise the priority of fixing the issue (instead of adding a comment). Work-around with "string too long" is specifying everything by `-d` at the command line; does the job, but is not really user-friendly. I agree on "comma separated list", as that again matches the syntax of the config files in `/etc/letsencrypt/renewal/`.

Thanks for correcting my wrong assumption! I otherwise would have wondered on the next run what's wrong now :)
