### ISSUE TITLE
Start a testing farm.

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1459]
We should have a script that spins up a bunch of VMs running whatever OSes & versions we think we support, and:

* runs unit tests
* runs integration tests
* field tests against the staging API
* runs plugin compatibility tests

It could report results in the IRC channel, and/or be a required step for releases.

**Comment by kuba** [comment]
The same farm could've been used for #715, lol...

**Comment by pde** [comment]
@kuba the same non-existent farm, yes :)

**Comment by pde** [comment]
Thanks @levskaya! https://github.com/levskaya/letstest
