### ISSUE TITLE
Apache vhost selection with install

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1482]
As reported by @nils-ohlmeier, when you use the Apache plugin with the `install` verb, it defaults to installing the certificate to all found vhosts. This is true even if the certificate is only valid for a subset of these vhosts.

Apache should parse the certificate and only offer to install it for vhosts whose domain names are in the certificate or whose domain names are unknown.

**Comment by nils-ohlmeier** [comment]
Originally I created #1433  to report this, which then got referenced to #1231. I guess we can at least one of them. #1433 I guess?

**Comment by bmw** [comment]
I somehow missed #1433 entirely. Closing this issue in favor of that. Thanks for pointing that out.
