### ISSUE TITLE
Renewal Method?

### ISSUE THREAD

**Issue by liqi328** [letsencrypt/letsencrypt#1492]
Your ACME spec in the issuance section explains that a renewed certificate can be obtained by performing an unauthenticated GET request at the URI created when the cert is generated, but I can't find any evidence of this in this repo or others. Is the spec correct?

Having to use user key for a simple renewal weakens the security model, and a full authenticated renewal is also not very convenient for websites behind load balancers or with unique setups.

Clarification on what the actual renewal situation is or will be during the public beta or launch would be helpful.

Thank you.

**Comment by kuba** [comment]
We implement it in https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151108/acme/acme/client.py#L417, but it's not used anywhere in the code base because Boulder is not yet ready: https://github.com/letsencrypt/boulder/issues/359.
