### ISSUE TITLE
Сommand "certonly" without requesting the authentication mode or add a selection mode startup options.

### ISSUE THREAD

**Issue by maxrip** [letsencrypt/letsencrypt#1497]
Сommand "certonly" without requesting the authentication mode or add a selection mode startup options.
<pre>
How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Webroot Authenticator (webroot)
2: Automatically use a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1

</pre>
And also add the option to renew an existing certificate
<pre>
Do you want to renew and replace this certificate with a newly-issued one?
-------------------------------------------------------------------------------
(R)eplace/(C)ancel: r

</pre>

**Comment by bmw** [comment]
I'm sorry, but I don't understand the issue you're reporting here. Is the problem that you don't see the screen where you can select between `webroot` and `standalone`? This is due to #1157. Without `webroot` appearing in the menu, you only have one option, so it is chosen for you. When #1157 is fixed, you'll see the exact menu you posted when you run `letsencrypt certonly`.

As for the option to renew the certificate, I don't understand the problem. We give you the exact prompt you pasted, asking if you'd like to renew a certificate. Is the complaint the lack of a CLI flag for this question?

**Comment by maxrip** [comment]
Maybe not the accuracy of the translation
<pre>certonly -t --agree-dev-preview -d example.com --debug --server https://acme-v01.api.letsencrypt.org/directory --webroot-path /var/www/kuziev/data/www/example.com/</pre>
<pre>
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly -t --agree-dev-preview -d reg.burogs.com --debug --server https://acme-v01.api.letsencrypt.org/directory --webroot-path /var/www/kuziev/data/www/example.com/ --fullchain-path /var/www/kuziev/data/crt

How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Webroot Authenticator (webroot)
2: Automatically use a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):

</pre>
I have to choose a method *Webroot Authenticator*
And I want to get fully automatic receipt without manual input of queries in step

Same thing with the second part of the question.
If the certificate has been received, the question is asked to overwrite: yes or no.
Please add the command line option to overwrite certificate.

**Comment by maxrip** [comment]
The second issue is solved through option --renew-by-default

**Comment by maxrip** [comment]
I found a solution.
<pre>-a webroot</pre>
