### ISSUE TITLE
letsencrypt-apache is versioned "0" in PyPI json output

### ISSUE THREAD

**Issue by felixonmars** [letsencrypt/letsencrypt#1500]
The version of letsencrypt-apache is "0" from PyPI json output currently whilst other letsencrypt packages isn't. There is also an empty "0" release inside the releases array of letsencrypt-apache only. This confused my version check script :/

Any chance that this could be fixed?

FYI: https://pypi.python.org/pypi/letsencrypt-apache/json

**Comment by kuba** [comment]
I've removed version 0 for both `letsencrypt-apache` and `letshelp-letsencrypt`. Thanks for noticing!

https://pypi.python.org/pypi/letsencrypt-apache/json
https://pypi.python.org/pypi/letshelp-letsencrypt/json

**Comment by felixonmars** [comment]
Works now. Thanks!
