### ISSUE TITLE
Can't get Manual Provider to work

### ISSUE THREAD

**Issue by gitlubba** [letsencrypt/letsencrypt#1501]
Following the wiki I was not able to complete the process

After configuring the Manual Provider with the last successful command:
New-ACMEProviderConfig -DnsProvider Manual            -Alias manualDnsProvider
the command Edit-ACMEProviderConfig -List

returned:

Id                : xxx
Alias             : manualDnsProvider
Label             :
Memo              :
DnsProvider       : Manual
WebServerProvider :

Now I got stuck, because every attempt for the command : "Complete-ACMEChallenge" failed with:
Complete-ACMEChallenge : The given key was not present in the dictionary.

How to continue ?

**Comment by kuba** [comment]
It doesn't look like you're using official client. Please report your problem at https://github.com/ebekker/letsencrypt-win.
