### ISSUE TITLE
OpenBSD 5.7 error

### ISSUE THREAD

**Issue by nafigator** [letsencrypt/letsencrypt#1502]
For OpenBSD 5.7 dependencies I wrote script:

    #!/bin/sh -xe
    pkg_add -v \
      git \
      python-2.7.9p0 \
      py-pip-1.5.6 \
      py-virtualenv-1.11.6 \
      augeas \
      libffi

But when i tried to run the command i got an error:

    # bootstrap/openbsd.sh && \
    > ./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth
    + pkg_add -v git python-2.7.9p0 py-pip-1.5.6 py-virtualenv-1.11.6 augeas libffi
    Update candidates: quirks-2.54 -> quirks-2.54
    quirks-2.54 signed on 2015-03-08T12:33:05Z
    Updating letsencrypt and virtual environment dependencies......Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-C2qTpt/psutil

**Comment by kuba** [comment]
We don't provide support for OpenBSD. You can try pining people that work on such support in #1174. `psutil` not working on OpenBSD has already been recognized there as a problem.
