### ISSUE TITLE
letsencrypt on a Cloudlinux 6.6 (CentOS/RHEL packages)

### ISSUE THREAD

**Issue by huggi** [letsencrypt/letsencrypt#1528]
I would like to try out letsencrypt on my webhosting reseller plattform (CP11) and some basic knowledge about my server so far:

- I don't know what linux it is: uname -a says: Linux 2.6.32-604.30.3.lve1.3.63.el6.x86_64
- Via WHM I saw a note that it's a Cloudlinux 6.6, https://en.wikipedia.org/wiki/CloudLinux_OS
- I have access via SSH
- There is Python
- The setup does not know how to handle this kind of Linux

Where do I start? 

I'm reading: https://letsencrypt.readthedocs.org/en/latest/contributing.html#prerequisites now :) 

And now I ended up at: https://community.letsencrypt.org/t/complete-no-sudo-version/4054 

DEAD END so far...

I'm trying now with another host which has a Ubuntu 12.04.5 LTS for me running. If that works, I will provide the name of the provider and also the service.

**Comment by huggi** [comment]
I think that's okay for the moment here. I'm going now to: https://community.letsencrypt.org/t/complete-no-sudo-version/4054

**Comment by AlexEdimensionz** [comment]
if you edit  the following version of let's encrypt:
https://bitbucket.org/webstandardcss/lets-encrypt-for-cpanel-centos-6.x

change the 1st line in **letsencrypt-cpanel-install.sh**

to 

> export OS_RELEASE=$(rpm -qa '(oraclelinux|sl|redhat|centos|cloudlinux)-release(|-server)')

Then the installer will run properly.
