### ISSUE TITLE
Does not recognize legitimate FQDNs

### ISSUE THREAD

**Issue by mrak** [letsencrypt/letsencrypt#1529]
I own a `.graphics` domain, but the `letsencrypt` client gives the following error: 

```
Requested domain is not a FQDN
```

I think this is from [configuration.py#L160](https://github.com/letsencrypt/letsencrypt/blob/5d9c32b583972e7581cecb5b2b51f0f73d509d6e/letsencrypt/configuration.py#L160) using an out-dated regex for the domain names. It limits the TLD to 6 characters, and `.graphics` is 8.

**Comment by SuperMatt** [comment]
This bug is affecting me too with .digital

**Comment by SuperMatt** [comment]
I managed to get around this by editing line 160 in file. Issue still needs fixing.
/home/user/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/

I have created a pull request for this.

**Comment by mrak** [comment]
Discussion and solutions being discussed in #1536
