### ISSUE TITLE
Allow application/octet-stream instead of text/plain

### ISSUE THREAD

**Issue by raboof** [letsencrypt/letsencrypt#1532]
Especially when using `--authenticator manual auth`, it could be convenient to allow the challenge to be available under the MIME type `application/octet-stream` instead of `text-plain`.

**Comment by raboof** [comment]
Wait, this is of course not an issue in the letsencrypt client tool :)

**Comment by kuba** [comment]
Actually, it is an issue of the client, because the verification fails on the client side: we perform self-validation before contacting CA. Nevertheless, it's dupe of https://github.com/letsencrypt/letsencrypt/issues/1409.
