### ISSUE TITLE
Let's encrypt apache 2.4 depreciated syntax

### ISSUE THREAD

**Issue by jpptinsley** [letsencrypt/letsencrypt#1541]
When auto-deploying to apache2.4, (Debian Jessie), the generated apache configuration throws the following error:

```AH02559: The SSLCertificateChainFile directive (/etc/apache2/sites-enabled/001-site.com-le-ssl.conf:24) is deprecated, SSLCertificateFile should be used instead```

**Comment by TheNavigat** [comment]
@pde I guess this issue should be closed, https://github.com/letsencrypt/letsencrypt/pull/1423#issuecomment-157549200

**Comment by jpptinsley** [comment]
Can confirm this is fixed. Closing.
