### ISSUE TITLE
set timeouts for http requests

### ISSUE THREAD

**Issue by jmhodges** [letsencrypt/letsencrypt#1543]
With the recent staging timeouts (which we think we found the cause of and are testing a fix), the letsencrypt client hangs instead of erroring out early.

It'd be nice for the client to not hang for a long time and instead timeout itself, and retry those things that are retryable.

**Comment by pde** [comment]
IME the client was actually getting a useful response after 60 seconds...

**Comment by jsha** [comment]
Closing in favor of #2148, which has more info.
