### ISSUE TITLE
undefined symbol EC_GFp_nistp224_method on ubuntu server 14.04 LTS

### ISSUE THREAD

**Issue by trgosnell** [letsencrypt/letsencrypt#1548]
Gentlepersons:

Just getting started and encountered this error on running letsencrypt-auto, transcript attached from second attempt.

The working python installation is the Anaconda2-generated default virtual environment and not the system python.

[transcript.txt](https://github.com/letsencrypt/letsencrypt/files/37387/transcript.txt)

**Comment by iggyvolz** [comment]
Having this error as well - I also tried doing a manual installation through virtualenv and using a python from apt, but it made no difference.

**Comment by iggyvolz** [comment]
Possibly relevant paragraph from the OpenSSL docs (emphasis mine):
>The functions **EC_GFp_nistp224_method**, EC_GFp_nistp256_method and EC_GFp_nistp521_method offer 64 bit optimised implementations for the NIST P224, P256 and P521 curves respectively. Note, however, that **these implementations are not available on all platforms**.

Could this mean that EC_GFp_nistp224_method is simply not available to Ubuntu?

**Comment by trgosnell** [comment]
Quick look around and found this in Ubuntu manuals on EC_GFp_nistp224_method:

http://manpages.ubuntu.com/manpages/wily/man3/ec.3ssl.html

**Comment by trgosnell** [comment]
Listing of symbols (nm command) defined in /<home directory>/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so on Ubuntu server yields this subset:

000000000007e690 t _cffi_d_EC_GFp_mont_method
000000000007e630 t _cffi_d_EC_GFp_nist_method
000000000007e5d0 t _cffi_d_EC_GFp_nistp224_method
000000000007e570 t _cffi_d_EC_GFp_nistp256_method
000000000007e510 t _cffi_d_EC_GFp_nistp521_method
000000000007e4b0 t _cffi_d_EC_GFp_simple_method
000000000007e6a0 t _cffi_f_EC_GFp_mont_method
000000000007e640 t _cffi_f_EC_GFp_nist_method
000000000007e5e0 t _cffi_f_EC_GFp_nistp224_method
000000000007e580 t _cffi_f_EC_GFp_nistp256_method
000000000007e520 t _cffi_f_EC_GFp_nistp521_method
000000000007e4c0 t _cffi_f_EC_GFp_simple_method
                 U EC_GFp_mont_method
                 U EC_GFp_nist_method
                 U EC_GFp_nistp224_method
                 U EC_GFp_nistp256_method
                 U EC_GFp_nistp521_method
                 U EC_GFp_simple_method

The "t" designation means "local text symbol," and, tellingly, "U" means undefined. So the _openssl shared object is wanting to make use of the EC_GFp_nist224_method symbol and has no definition. Methinks there is a mis-specified library path.

**Comment by antonym** [comment]
Getting this on a fresh Fedora 23 instance:

# ./letsencrypt-auto
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 17, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GFp_nistp224_method

**Comment by leftmostcat** [comment]
This appears be related to pyca/cryptography#2503, which is solved with reaperhulk/cryptography@e702453665bcd85ef6c0ffe931db559ad8c184d8. As a workaround, you can run the following:

    $ source ~/.local/share/letsencrypt/bin/activate
    $ pip install git+git://github.com/reaperhulk/cryptography.git@e702453665bcd85ef6c0ffe931db559ad8c184d8
    $ deactivate

This should solve the problem until the next cryptography release is out.

**Comment by antonym** [comment]
I can confirm that this solution works, thanks!

**Comment by Swift-R** [comment]
Is that workaround supposed to fix the EC_GFp_nistp224_method error when I run `sudo ./letsencrypt-auto --nginx`? I am still receiving the same message when I run that line in Fedora 23 (fresh install with nginx and updates).

**Comment by leftmostcat** [comment]
I don't believe you need to add sudo before `./letsencrypt-auto` (it seems to do it itself) and doing so might mean that your letsencrypt virtualenv is located somewhere other than the directory listed above. You'll have to locate your actual virtualenv in order to ensure that the dev version of cryptography is installed there.

**Comment by albertotb** [comment]
I had the same problem. It seems that the workaround is already in master https://github.com/pyca/cryptography/pull/2515 so this no longer works:

    $ source ~/.local/share/letsencrypt/bin/activate
    $ pip install git+git://github.com/reaperhulk/cryptography.git@e702453665bcd85ef6c0ffe931db559ad8c184d8
    $ deactivate

**Comment by reaperhulk** [comment]
This should now be resolved in the 1.1.2 release.

**Comment by Swift-R** [comment]
It's all working fine now on Fedora 23, even without that workaround.

**Comment by bmw** [comment]
Closing as I believe this has been resolved.

If this problem persists for anyone, comment and I'll reopen.

**Comment by hl-owenb** [comment]
test comment

**Comment by hl-owenb** [comment]
Fairly clean install of Fedora24, following letcrypt gist https://gist.github.com/leommoore/1e773a7d230ca4bbe1c2
I get 
ImportError: /home/owenb/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GROUP_new_curve_GF2m
and stack trace.  No previous Python on this machine.

Note different function to what is listed at the top of this ticket.

**Comment by jcberthon** [comment]
Same problem here as @hl-owenb 

However 2+ months ago I was able to use certbot-auto on my machine (openSuse 42.2 64bit) to get a certificate. Now, I'm trying to renew it and I get the same error with the `EC_GROUP_new_curve_GF2m` undefined symbol. (same error when I execute `~/.local/share/letsencrypt/bin/letsencrypt --version`
