### ISSUE TITLE
Install failure on Ubuntu 14.04.1: virtualenv version, then OSError of some sort

### ISSUE THREAD

**Issue by gunsch** [letsencrypt/letsencrypt#1556]
First time I ran the script:

$ ./letsencrypt-auto --agree-dev-preview --server \
>       https://acme-v01.api.letsencrypt.org/directory auth
Bootstrapping dependencies for Debian-based OSes...
[sudo] password for gunsch:
Get:1 http://security.ubuntu.com trusty-updates InRelease [64.4 kB]
Ign http://us.archive.ubuntu.com trusty InRelease
Get:2 http://us.archive.ubuntu.com trusty-updates InRelease [64.4 kB]
Hit http://us.archive.ubuntu.com trusty Release.gpg
Get:3 http://us.archive.ubuntu.com trusty-updates/universe Sources [143 kB]
Get:4 http://us.archive.ubuntu.com trusty-updates/universe i386 Packages [328 kB]
Get:5 http://security.ubuntu.com trusty-security InRelease [64.4 kB]
Get:6 http://us.archive.ubuntu.com trusty-updates/universe Translation-en [172 kB]
Hit http://us.archive.ubuntu.com trusty Release
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Get:7 http://security.ubuntu.com trusty-updates/main Sources [244 kB]
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Get:8 http://security.ubuntu.com trusty-updates/restricted Sources [4722 B]
Get:9 http://security.ubuntu.com trusty-updates/main i386 Packages [631 kB]
Get:10 http://security.ubuntu.com trusty-updates/restricted i386 Packages [15.1 kB]
Get:11 http://security.ubuntu.com trusty-updates/main Translation-en [319 kB]
Get:12 http://security.ubuntu.com trusty-updates/restricted Translation-en [3569 B]
Get:13 http://security.ubuntu.com trusty-security/main Sources [99.2 kB]
Get:14 http://security.ubuntu.com trusty-security/restricted Sources [3357 B]
Get:15 http://security.ubuntu.com trusty-security/universe Sources [31.5 kB]
Get:16 http://security.ubuntu.com trusty-security/main i386 Packages [350 kB]
Get:17 http://security.ubuntu.com trusty-security/restricted i386 Packages [12.2 kB]
Get:18 http://security.ubuntu.com trusty-security/universe i386 Packages [119 kB]
Get:19 http://security.ubuntu.com trusty-security/main Translation-en [200 kB]
Get:20 http://security.ubuntu.com trusty-security/restricted Translation-en [3076 B]
Get:21 http://security.ubuntu.com trusty-security/universe Translation-en [69.6 kB]
Fetched 2943 kB in 14s (199 kB/s)
Reading package lists... Done
E: No packages found
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc is already the newest version.
gcc set to manually installed.
python is already the newest version.
python-dev is already the newest version.
git is already the newest version.
git set to manually installed.
The following packages were automatically installed and are no longer required:
  libavcodec53 libavdevice53 libavfilter2 libavformat53 libavutil51 libcaca0
  libcdio-cdda0 libcdio-paranoia0 libcdio10 libdc1394-22 libgsm1 libjack0
  libmp3lame0 libopenjpeg2 liborc-0.4-0 libpostproc52 libraw1394-11
  libschroedinger-1.0-0 libsdl1.2debian libspeex1 libswresample0 libswscale2
  libtheora0 libx264-120
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  augeas-lenses libssl1.0.0
Suggested packages:
  augeas-doc augeas-tools
Recommended packages:
  libssl-doc
The following NEW packages will be installed:
  augeas-lenses dialog libaugeas0 libffi-dev python-virtualenv
The following packages will be upgraded:
  ca-certificates libssl-dev libssl1.0.0
3 upgraded, 5 newly installed, 0 to remove and 211 not upgraded.
Need to get 4194 kB of archives.
After this operation, 5113 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/main dialog i386 1.2-20130928-1 [294 kB]
Get:2 http://security.ubuntu.com/ubuntu/ trusty-updates/main libssl-dev i386 1.0.1f-1ubuntu2.15 [989 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ trusty/universe python-virtualenv all 1.11.4-1 [1485 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ trusty/main libffi-dev i386 3.1~rc1+r3.0.13-12 [99.0 kB]
Get:5 http://security.ubuntu.com/ubuntu/ trusty-updates/main libssl1.0.0 i386 1.0.1f-1ubuntu2.15 [780 kB]
Get:6 http://security.ubuntu.com/ubuntu/ trusty-updates/main ca-certificates all 20141019ubuntu0.14.04.1 [189 kB]
Get:7 http://security.ubuntu.com/ubuntu/ trusty-updates/main augeas-lenses all 1.2.0-0ubuntu1.1 [230 kB]
Get:8 http://security.ubuntu.com/ubuntu/ trusty-updates/main libaugeas0 i386 1.2.0-0ubuntu1.1 [129 kB]
Fetched 4194 kB in 21s (194 kB/s)
Preconfiguring packages ...
(Reading database ... 31453 files and directories currently installed.)
Preparing to unpack .../libssl-dev_1.0.1f-1ubuntu2.15_i386.deb ...
Unpacking libssl-dev:i386 (1.0.1f-1ubuntu2.15) over (1.0.1f-1ubuntu2.8) ...
Preparing to unpack .../libssl1.0.0_1.0.1f-1ubuntu2.15_i386.deb ...
Unpacking libssl1.0.0:i386 (1.0.1f-1ubuntu2.15) over (1.0.1f-1ubuntu2.8) ...
Preparing to unpack .../ca-certificates_20141019ubuntu0.14.04.1_all.deb ...
Unpacking ca-certificates (20141019ubuntu0.14.04.1) over (20130906ubuntu2) ...
Selecting previously unselected package augeas-lenses.
Preparing to unpack .../augeas-lenses_1.2.0-0ubuntu1.1_all.deb ...
Unpacking augeas-lenses (1.2.0-0ubuntu1.1) ...
Selecting previously unselected package dialog.
Preparing to unpack .../dialog_1.2-20130928-1_i386.deb ...
Unpacking dialog (1.2-20130928-1) ...
Selecting previously unselected package libaugeas0.
Preparing to unpack .../libaugeas0_1.2.0-0ubuntu1.1_i386.deb ...
Unpacking libaugeas0 (1.2.0-0ubuntu1.1) ...
Selecting previously unselected package python-virtualenv.
Preparing to unpack .../python-virtualenv_1.11.4-1_all.deb ...
Unpacking python-virtualenv (1.11.4-1) ...
Selecting previously unselected package libffi-dev:i386.
Preparing to unpack .../libffi-dev_3.1~rc1+r3.0.13-12_i386.deb ...
Unpacking libffi-dev:i386 (3.1~rc1+r3.0.13-12) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
Setting up libssl1.0.0:i386 (1.0.1f-1ubuntu2.15) ...
Setting up libssl-dev:i386 (1.0.1f-1ubuntu2.15) ...
Setting up ca-certificates (20141019ubuntu0.14.04.1) ...
Setting up augeas-lenses (1.2.0-0ubuntu1.1) ...
Setting up dialog (1.2-20130928-1) ...
Setting up libaugeas0 (1.2.0-0ubuntu1.1) ...
Setting up python-virtualenv (1.11.4-1) ...
Setting up libffi-dev:i386 (3.1~rc1+r3.0.13-12) ...
Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... 17 added, 8 removed; done.
Running hooks in /etc/ca-certificates/update.d....
Adding debian:ACCVRAIZ1.pem
Adding debian:Atos_TrustedRoot_2011.pem
Adding debian:DigiCert_Assured_ID_Root_G2.pem
Adding debian:DigiCert_Assured_ID_Root_G3.pem
Adding debian:DigiCert_Global_Root_G2.pem
Adding debian:DigiCert_Global_Root_G3.pem
Adding debian:DigiCert_Trusted_Root_G4.pem
Adding debian:E-Tugra_Certification_Authority.pem
Adding debian:QuoVadis_Root_CA_1_G3.pem
Adding debian:QuoVadis_Root_CA_2_G3.pem
Adding debian:QuoVadis_Root_CA_3_G3.pem
Adding debian:SG_TRUST_SERVICES_RACINE.pem
Adding debian:T-TeleSec_GlobalRoot_Class_2.pem
Adding debian:TWCA_Global_Root_CA.pem
Adding debian:TeliaSonera_Root_CA_v1.pem
Adding debian:WoSign.pem
Adding debian:WoSign_China.pem
Removing debian:Entrust.net_Secure_Server_CA.pem
Removing debian:Firmaprofesional_Root_CA.pem
Removing debian:RSA_Root_Certificate_1.pem
Removing debian:TDC_Internet_Root_CA.pem
Removing debian:TDC_OCES_Root_CA.pem
Removing debian:ValiCert_Class_1_VA.pem
Removing debian:ValiCert_Class_2_VA.pem
Removing debian:Wells_Fargo_Root_CA.pem
done.
done.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: virtualenv==1.8.4

After this, I "sudo pip install virtualenv==1.8.4" and retried. I also wiped ~/letsencrypt (where I checked out the code) and ~/.local/share/letsencrypt and retried. Getting this failure since:

$ ./letsencrypt-auto --agree-dev-preview --server \
>      https://acme-v01.api.letsencrypt.org/directory auth
Bootstrapping dependencies for Debian-based OSes...
[sudo] password for gunsch:
Hit http://security.ubuntu.com trusty-updates InRelease
Ign http://us.archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://us.archive.ubuntu.com trusty-updates InRelease
Hit http://security.ubuntu.com trusty-updates/main Sources
Hit http://us.archive.ubuntu.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-updates/restricted Sources
Hit http://us.archive.ubuntu.com trusty-updates/universe Sources
Hit http://security.ubuntu.com trusty-updates/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://security.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://security.ubuntu.com trusty-updates/main Translation-en
Hit http://us.archive.ubuntu.com trusty Release
Hit http://security.ubuntu.com trusty-updates/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Reading package lists... Done
E: No packages found
Reading package lists... Done
Building dependency tree
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
ca-certificates is already the newest version.
git is already the newest version.
libaugeas0 is already the newest version.
libssl-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  libavcodec53 libavdevice53 libavfilter2 libavformat53 libavutil51 libcaca0
  libcdio-cdda0 libcdio-paranoia0 libcdio10 libdc1394-22 libgsm1 libjack0
  libmp3lame0 libopenjpeg2 liborc-0.4-0 libpostproc52 libraw1394-11
  libschroedinger-1.0-0 libsdl1.2debian libspeex1 libswresample0 libswscale2
  libtheora0 libx264-120
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 211 not upgraded.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2560, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 964, in main
    never_download=options.never_download)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1074, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 611, in install_setuptools
    search_dirs=search_dirs, never_download=never_download)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 583, in _install_req
    cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1042, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/gunsch/.local/...ncrypt/bin/python2.7 -c "#!python
\"\"\"Bootstra...sys.argv[1:])

" /usr/local/lib/pytho...ols-0.6c11-py2.7.egg failed with error code 1

**Comment by pde** [comment]
It's a bad sign that virtualenv is being run from `/usr/local/lib/python2.7`, rather than an OS-packaged copy from `/usr/lib`.  Did you intentionally install one with `pip` or `python setup.py install` at some point?

**Comment by braytonstafford** [comment]
I'm having a similar issue. I did install virtualenv with pip but am not married to anything python related in case i need to backtrack.  Below is the error i get when running ./letsencrypt-auto

Reading package lists... Done                                                  
E: No packages found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
ca-certificates is already the newest version.
git is already the newest version.
libaugeas0 is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by braytonstafford** [comment]
I initially started with ubuntu 14.04 with python 2.7.6 built in so i followed [this](https://renoirboulanger.com/blog/2015/04/upgrade-python-2-7-9-ubuntu-14-04-lts-making-deb-package/) tutorial on upgrading to 2.7.9, but I forgot to install the tools. My mistake here but I believe your issue may be related in that virtualenv is throwing errors.  Now I'm off to fight a cryptography error i'm getting.
```
wget https://bootstrap.pypa.io/ez_setup.py -O - | /usr/local/lib/python2.7.9/bin/python
  /usr/local/lib/python2.7.9/bin/easy_install pip
  /usr/local/lib/python2.7.9/bin/pip install virtualenv
```

**Comment by WoLpH** [comment]
I just had the same issue, in case anyone has the same problem, it can be solved easily by upgrading your `virtualenv` through `pip` again (if you installed it through `pip` initially):
```
pip install -U virtualenv
```

Imho the bug here is that letsencrypt apparently just assumes that everything is installed through the package manager. The Python package manager does perfectly fine on it's own and is generally much more up to date than the Ubuntu one so it's a better one to use. Imho the code should change to check if virtualenv was installed through pip or through apt-get.

**Comment by gunsch** [comment]
I had to do some experimenting, but worked through it. A couple comments:

* I had a lot of stuff out of date (started with an `apt-get upgrade` to get to a better state)
* I had two virtualenv installations, both one from pip (`virtualenv`) and the system package (`python-virtualenv`).
* Somehow, the system package (`python-virtualenv`) was supposed to have provided `/usr/bin/virtualenv` (according to `dpkg -L)`, but that file wasn't present. `command -v virtualenv` (as used in `_deb_common.sh`) failed.  `apt-get remove python-virtualenv; apt-get install python-virtualenv` resolved this issue.

I'd ask for some better error messaging in each case. At a quick glance, I'm not sure what is causing the first set of error output. However, later, "Failed to install a working \"virtualenv\" command, exiting" could instead explain that a virtualenv binary was not found, which could point users to the solution more quickly.

**Comment by bmw** [comment]
I'm glad you resolve the issue @gunsch. I created #2114 to track adding better error messages to `letsencrypt-auto`.

**Comment by Ardakilic** [comment]
I just had this issue on Debian Jessie after pulling latest changes, @WoLpH 's comment helped me solve it.
