### ISSUE TITLE
Consider renaming ./letsencrypt-auto to be more autocomplete-friendly

### ISSUE THREAD

**Issue by underyx** [letsencrypt/letsencrypt#1557]
Now, this might seem like a really tiny issue, but it's actually incredibly frustrating for me to start the script — I keep expecting that I can type just a few characters to launch it, but the truth is far from that:

`.` `/` `l` `e` `<TAB>` `<TAB>`

…currently at `./lets`…

`e` `<TAB>` `<TAB>`

…got to `./letsencrypt` here, so I always think I must be just two characters away…

`-` `a` `<TAB>` `<ENTER>`

…dammit, I got a `no such file or directory: ./letsencrypt-a` because `letsencrypt-apache` also exists…

`<UP>` `u` `<TAB>` `<ENTER>`

At this point, just typing the entire name of the script would have needed the same amount of keystrokes, and that wouldn't have required me to stop three times to check how I should proceed (reading why it didn't complete yet, and reading why I got a no such file error).

One idea to change this would be: `ln -s letsencrypt-auto auto-letsencrypt`:

`.` `/` `a` `u` `<TAB>` `<ENTER>` :tada:

**Comment by pde** [comment]
While this is a UI rough edge, it's temporary.  The fix comes with native OS packaging, where the executable is called `letsencrypt`, and is in the PATH.
