### ISSUE TITLE
./letsencrypt-auto fails on update because of missing package python2.7-dev

### ISSUE THREAD

**Issue by dune73** [letsencrypt/letsencrypt#1564]
Problem:
```bash
$>cat /etc/issue
Ubuntu 14.04.3 LTS \n \l
$> git show
commit 6ea51360f9fcbd40e1c754bbc63a57224b73fb92
$> ./letsencrypt-auto certonly -a webroot --webroot-path /apache/htdocs/ -d example.com --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
Updating lUpdating letsencrypt and virtual environment dependencies......Command "/home/dune73/.local/share/letsencrypt/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-JtvkAg/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yrfsWF-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dune73/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-JtvkAg/cffietsencrypt and virtual environment dependencies......Command "/home/dune73/.local/share/letsencrypt/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-JtvkAg/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yrfsWF-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dune73/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-JtvkAg/cffi
```
The root-cause:
```bash
$> sudo pip install --upgrade cffi
...
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

The Solution:

```bash
$> sudo apt-get install pythond2.7-dev
```

**Comment by pde** [comment]
What OS was this on?

**Comment by dune73** [comment]
Ubuntu 14.04.3 LTS \n \l

**Comment by bmw** [comment]
So I just tested this on a fresh install of Ubuntu 14.04 and did not encounter the problem.

Digging into the issue a little further, one of the packages `letsencrypt-auto` installs is `python-dev` which installs `python2.7-dev` as a dependency. [source](http://packages.ubuntu.com/trusty/python-dev)

**Comment by pde** [comment]
@dune73 is it possible that you had a non-standard copy of `python-dev` from somewhere other than the main ubuntu 14.04 repos?

**Comment by dune73** [comment]
On Fri, Nov 20, 2015 at 07:20:09PM -0800, Peter Eckersley wrote:
> @dune73 is it possible that you had a non-standard copy of `python-dev` from somewhere other than the main ubuntu 14.04 repos? 

Thanks for digging into this Peter. I do not think there is anything
special about my python-dev, but the machine is not vanilla either.

I'm fine with closing the bug report after your successful test.

**Comment by ohthehugemanatee** [comment]
I'm on Amazon linux 2015.09 , and tried running ```./letsencrypt-auto --debug``` from master branch. It failed on the same step. I resolved it with ```yum install python27-dev```. From there on in everything worked great (with certonly mode of course). Thank you, letsencrypt team!

**Comment by pde** [comment]
I tentatively believe this should have been fixed by our numerous bootstrapping changes, but please reopen if it hasn't been.
