### ISSUE TITLE
Requested domain is not a FQDN

### ISSUE THREAD

**Issue by enjikaka** [letsencrypt/letsencrypt#1565]
Hello.

I'm trying to enable the Lets Encrypt SSL cert on my VPS. 
My domains are ```sverige.science``` && ```www.sverige.science```

When running 
```
./letsencrypt-auto certonly -a standalone \
  -d sverige.science -d www.sverige.science \
  --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
```

I'm getting ```Requested domain is not a FQDN```

**Comment by enjikaka** [comment]
When running ```./letsencrypt-auto certonly --server https://acme-v01.api.letsencrypt.org/directory``` and then following everything in the GUI-CLI-thingy it worked fine. I did not enter the "www." version of the domain though. https://sverige.science/ now up with Let's Encrypt and SSL Labs score of A+. :smiley:

**Comment by apos** [comment]
see #1536
