### ISSUE TITLE
Too many certificates already issued for

### ISSUE THREAD

**Issue by centminmod** [letsencrypt/letsencrypt#1569]
Was doing some more webroot testing and ran into this error where http2ssl.xyz only had one SSL certificate issued back on october 27th around 23 days ago and a total of 10 certificates where issues between october 27th, 2015 and november 15th, 2015 - so which rate limit was hit ?

    /root/.local/share/letsencrypt/bin/letsencrypt --version
    letsencrypt 0.0.0.dev20151114
    
    /root/.local/share/letsencrypt/bin/letsencrypt -c /etc/letsencrypt/webroot.ini --user-agent centminmod-centos6-webroot --webroot-path /home/nginx/domains/le10.http2ssl.xyz/public -d le10.http2ssl.xyz certonly
    An unexpected error occurred.
    Error: rateLimited :: There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: http2ssl.xyz
    Please see the logfiles in /var/log/letsencrypt for more details.
    
from https://crt.sh/?Identity=%25&iCAID=7395
    
    2015-11-15      2016-02-13      CN=le10.http2ssl.xyz
    2015-11-15      2016-02-13      CN=le10.http2ssl.xyz
    2015-11-15      2016-02-13      CN=le10.http2ssl.xyz
    2015-11-15      2016-02-13      CN=le10.http2ssl.xyz
    2015-11-15      2016-02-13      CN=le10.http2ssl.xyz
    2015-11-15      2016-02-13      CN=le10.http2ssl.xyz
    2015-11-04      2016-02-02      CN=le2.http2ssl.xyz
    2015-10-31      2016-01-29      CN=le8.http2ssl.xyz
    2015-10-27      2016-01-25      CN=http2ssl.xyz
    2015-10-27      2016-01-25      CN=le1.http2ssl.xyz

i see rate limits as https://community.letsencrypt.org/t/beta-program-announcements/1631

    Rate limit on registrations per IP is now 10 per 3 hours up from 10 per day.
    Rate limit on certificates per Name is now 10 per 59 days up from 6 per 59 days.

@bmw @jsha @pde so i git 10 per 59 days for all SSL certificates on *.http2ssl.xyz ? that means i can no longer do any testing for my whitelisted domain ?

I see I have 6x `le10.http2ssl.xyz` issued SSL certificates so hit the old rate limit ?
    
contents of /etc/letsencrypt/webroot.ini where validemail@addy.com is valid email address just replaced for example purposes

    rsa-key-size = 2048
    
    # Always use the staging/testing server
    #server = https://acme-staging.api.letsencrypt.org/directory
    
    # for beta invitees
    server = https://acme-v01.api.letsencrypt.org/directory
    
    # Uncomment and update to register with the specified e-mail address
    email = validemail@addy.com
    
    # Uncomment to use a text interface instead of ncurses
    text = True
    agree-tos = True
    agree-dev-preview = True
    renew-by-default = True
    
    authenticator = webroot

**Comment by centminmod** [comment]
Ah looks like i found my problem the auto renewal cronjob I set was running more frequently than every 2 months so ran into the 10 regos per IP per day limit

my boo boo heh

**Comment by marcdraco** [comment]
Ach. Yeah, got the same problem here, trying to get a certificate issued for my staging server. Working with one hand tied behind your back can be a bit trying so a more specific error would be really handy.

I guess I have to sit on my hands for 3 hours now.

**Comment by jsha** [comment]
@marcdraco Sorry you're having trouble! Please feel free to post on https://community.letsencrypt.org/ for further help. I'm going to lock this issue thread because it's very old, so additional comments confuse the issue somewhate.
