### ISSUE TITLE
Update website renewal documentation for Public Beta

### ISSUE THREAD

**Issue by tuxayo** [letsencrypt/letsencrypt#1599]
https://letsencrypt.org/howitworks/

`letsencrypt renew --cert-path example-cert.pem`
gives
`letsencrypt: error: unrecognized arguments: renew`

**Comment by pde** [comment]
The answer for now is "re-run the client to renew".  If you provide the correct CLI flags, that should be scriptable, with the following provisos:
* if you use the standalone plugin, your script will need to stop your webserver before renewal and start it again afterwards
* if you used the "certonly" command, you will need to make sure your [web]server is loading certs, chains and keys from `/etc/letsencrypt/live`, where they will be renewed, and you will need to restart your [web]server after renewal.
* We should document exactly what CLI flags are required for full automation. 

In the near future the renewer will work as specifed at `https://letsencrypt.org/howitworks', so those docs are not so much outdated as predated.  Meanwhile, the client team should provide up-to-date renewal advice for the website at least a few days before Public Beta, which is what this ticket is for.

**Comment by pde** [comment]
@schoen anything I'm missing?

**Comment by pde** [comment]
Things the `letsencrypt renew` will do, which re-running the client currently can't:

* Picking up extra domains that your webserver has started serving them and adding them to your cert, if your default was to ask for all domains.
* Degrading gracefully if you were asking for N domains but you no longer have one of those N domains.
* Avoid running an installer if the cert is already installed, since it isn't doing anything useful and there's a slim chance it would cause problems.

**Comment by MAFLO321** [comment]
if someone wants to `renew` a cert (which was created with `certonly` or `auth`) has to run folowing command:
`./letsencrypt-auto certonly --renew -d <domain> --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview`

**Comment by gileri** [comment]
Thank you @MAFLO321, I figured it out with @tuxayo, but is this present in some kind of documentation as of now ?

**Comment by MAFLO321** [comment]
I don't found nothing on the official documentation. I searched and found this https://gist.github.com/renchap/c093702f06df69ba5cac (thx @renchap)

**Comment by MAFLO321** [comment]
I have a general question to this. Is is willed that you can't renew your cert (which was created with `certonly` or `auth`) with `letsencrypt run` ?
Because if that is not willed, the renew of `certonly` created certs could be added to the `run` function (in my opinion that would be the best solution) .
And if that is willed then it must be more clearly documentated.

**Comment by bmw** [comment]
@MAFLO321, have you figured out the answer to your question? If not, I'm curious what difference between `run` and `certonly` you're referring to.

Assuming you're not using your own CSR, `run` is basically `certonly` followed by the extra behavior of installing the certificates, performing optional security enhancements, etc.

**Comment by gileri** [comment]
@bmw : Could you reference the associated PR which fixes this issue ?

I think it would be useful to direct user to the associated [user guide section](https://letsencrypt.readthedocs.org/en/latest/using.html#renewal) in the renewal section of the [How it works](https://letsencrypt.org/howitworks/) page on letsencrypt.org.

**Comment by bmw** [comment]
@gileri the PR was made against a private repo for the Let's Encrypt website.

**Comment by tuxayo** [comment]
@pde @bmw Considering that it's possible to renew automatically with `--renew`, isn't the doc still outdated?

> To renew a certificate, simply run letsencrypt again providing the same values when prompted. Let’s Encrypt is working hard to fully automate this process and we apologize for the inconvenience until this functionality is ready.

**Comment by bmw** [comment]
@tuxayo, adding `--renew` (or the full version `--renew-by-default`) simply skips the prompt about whether or not to renew the certificate. To really make this process automatic, we have to remove all prompts and help people set up crontabs/systemd timers to automatically run the client.
