### ISSUE TITLE
Support for Plesk

### ISSUE THREAD

**Issue by Mythos** [letsencrypt/letsencrypt#16]
Hello,
I don't know if this is the right place for this kind of question, but will Plesk be supported?
As you say only `lets-encrypt example.com` is needed for generating and activating an SSL certificate for this domain I wonder if this works with Plesk's certificate management.
In Plesk you have to add a ca-certificate and your own certificate to a domain/subdomain to get it activated.

Kind regards,
Stefan

**Comment by tillz** [comment]
I just got the first version of a plesk plugin (and reusable PHP-Class) 'working' (it's still very hacky in many parts but it's a starting point). As soon as it's ok to call it an 'alpha' version, i'll publish it on github.
If you're interested in helping me with the development and/or want to test the first 'version', feel free to contact me.

**Comment by jdkasten** [comment]
@tillz That is awesome!  I am definitely interested in taking a look at it and would like to help out if I can.

**Comment by JHGitty** [comment]
There is an official voting page for Plesk Suggestions.

I found a suggestion for ACME implementation:
https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/6739357-acme-implementation

**Comment by ThomasWaldmann** [comment]
hmm, is this something that should be added to a) plesk or to b) letsencrypt (client)?
if a) then opening an issue there and closing this one here might be better.

**Comment by MatrixCrawler** [comment]
@tillz Any news on this? I would like to help out if i can

**Comment by dakira** [comment]
@tillz any update on your implemenation?

**Comment by kuba** [comment]
@xgin, from the Plesk team, has developed a Plesk plugin (https://github.com/letsencrypt/letsencrypt/pull/936) - it will soon live under https://github.com/plesk/letsencrypt-plesk.

**Comment by JHGitty** [comment]
Official support: https://github.com/plesk/letsencrypt-plesk

This issue can be closed.

**Comment by kuba** [comment]
We still should keep it open in order to track status of whitelisting the plugin here: https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151030/letsencrypt/plugins/disco.py#L19.

**Comment by kuba** [comment]
@xgin has now a Maintainer role on PyPI index entry `letsencrypt-plesk`

**Comment by MazzMazz** [comment]
Could anyone tell me how to use letsencrypt-plesk? I'm still getting only pem files

**Comment by xgin** [comment]
We have released extension for Plesk 12.5: https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt

**Comment by AmaZili** [comment]
Odin has delivered LE on Plesk 12.5 now, and with usages comes new issues....
Currently only plain domain and www subdomain are supported, but with hsts enforced, it is not possible to get access to webmail. subdomain with modern browsers.

Is there a simple (standard) method (enven command line) to add subdomains to the LE certificate managed by the plesk LE addon ?

**Comment by pde** [comment]
@AmaZili what happens if you specify more domains with the `-d` command line flag?

**Comment by pde** [comment]
I'm also going to close this ticket, because I think this is done!

**Comment by AmaZili** [comment]
@pde never tried the command line, that was the resaon to my question...
