### ISSUE TITLE
Race condition between updating PyPI and users running letsencrypt-auto

### ISSUE THREAD

**Issue by a1exus** [letsencrypt/letsencrypt#1601]
I'm trying to follow `Quick Start` and I'm getting some errors:

```
[alexus@j ~/letsencrypt]$ uname -a
FreeBSD X 9.2-RELEASE-p17 FreeBSD 9.2-RELEASE-p17 #0 r282430: Mon May  4 13:59:58 PDT 2015     root@X:/usr/obj/usr/src/sys/R610  amd64
[alexus@j ~/letsencrypt]$ ./letsencrypt-auto --agree-dev-preview --server \
> https://acme-v01.api.letsencrypt.org/directory certonly
Updating letsencrypt and virtual environment dependencies......  Could not find a version that satisfies the requirement acme==0.0.0.dev20151123 (from letsencrypt) (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151107, 0.0.0.dev20151108, 0.0.0.dev20151114)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external acme to allow).
No matching distribution found for acme==0.0.0.dev20151123 (from letsencrypt)
[alexus@j ~/letsencrypt]$ 
```

Please advise.

**Comment by bmw** [comment]
Please try running the command again and see if you get the same problem.

The packages were just updated on PyPI and I wonder if you tried to run the client while they were being updated.

**Comment by a1exus** [comment]
ha! you're right! i re-run same command and everything works now)

```
[alexus@j ~/letsencrypt]$ git pull
Already up-to-date.
[alexus@j ~/letsencrypt]$ ./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory certonly
Updating letsencrypt and virtual environment dependencies......	.
```

I then got promoted for email, ToS, domain and for the last step, I was asked to stop my httpd process.. I'm little bit confused about last step, I thought I'd be given a certificate that I can configure my httpd process myself as I have custom configuration..

**Comment by bmw** [comment]
Wow! Your timing is pretty impeccable. Thanks for reporting the issue. We'll look into seeing what we can do to mitigate the problem in the future.

As for stopping your webserver, I suggest you take a look at our [plugin documentation](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins). Many of our plugins do not require you to do this.

**Comment by pde** [comment]
Preliminary conclusion: if you script the let's encrypt client, you shouldn't assume it will never fail for silly and transient reasons.  That might be true if the CA servers are down, you hit a rate limit, if this happens, or for reasons we haven't yet learned about.  Tasks like renewal should be scheduled early enough that there's time to retry a few times (spaced apart by days, ideally) before the matter requires human attention and/or urgency.

Having said that, if we think we can catch cases like this and suggest the user try again, I'm open to it.

**Comment by a1exus** [comment]
I end up using `--manual`, everything works as expected)

Thanks!
