### ISSUE TITLE
Letsencrypt cert not accepted by all browsers

### ISSUE THREAD

**Issue by gjb** [letsencrypt/letsencrypt#1617]
After installing my new cert, I tested with several browsers. Chrome and Firefox on Ubuntu were happy. Safari and Chrome on OSX were happy. Chrome on iOS was happy.

But Firefox on OSX, Safari on iOS and all three Android browsers (the native client, Chrome and Firefox) all complained about the cert.

Is this to be expected, or have I done something wrong?

**Comment by pde** [comment]
Did you install the cert using only then `cert.pem` file, without `fullchain.pem` or `cert.pem`?  If so, it would have been missing intermediate CA certificates.  Such certificates are "transvalid", and only browsers that had cached the right intermediate CA certs beforhand will trust them.

You can test that with this website:
https://www.ssllabs.com/ssltest/

**Comment by pde** [comment]
https://community.letsencrypt.org/t/solved-why-isnt-my-certificate-trusted/2479

**Comment by gjb** [comment]
It seems odd to close an issue immediately after asking a question without waiting for an answer. I have solved the problem (and some others), which I will explain in the comments to follow for the benefit of others who may be using Letsencrypt certs with lighttpd.

**Comment by gjb** [comment]
To use *Letsencrypt* certs with *lighttpd*, it's necessary to provide two files and to list them in ```lighttpd.conf```. The ```ssl.pemfile``` is a combination of ```privkey.pem``` and ```cert.pem``` and the ```ssl.ca-file``` is ```chain.pem```. To create the first and copy them both into place for *lighttpd*, do:

    cat privkey.pem cert.pem > www.example.com.pem
    cp www.example.com.pem chain.pem /etc/lighttpd

Then edit the config file (described below), restart *Lighttpd* and all will be well, apart from one other problem revealed by the fine people at https://www.ssllabs.com/ssltest/

By default, *Lighttpd* uses a weak Diffie Hellman setting. This can be corrected by running the following command. It warns that it will take a long time, and it does take a long time:

    openssl dhparam -out /etc/lighttpd/dhparams.pem 2048

Assuming you have worked with the file names as described above, you'll need an SSL stanza in ```lighttpd.conf``` that looks like this:

    $SERVER["socket"] == ":443" {
        ssl.engine  = "enable"
        ssl.use-sslv2 = "disable"
        ssl.use-sslv3 = "disable"
        ssl.ca-file = "/etc/lighttpd/chain.pem"
        ssl.pemfile = "/etc/lighttpd/www.example.com.pem"
        ssl.dh-file = "/etc/lighttpd/dhparams.pem"
        ssl.cipher-list = "aRSA+HIGH !3DES +kEDH +kRSA !kSRP !kPSK"
        ssl.honor-cipher-order = "enable"
    }

Obviously, all the commands here need to be run as root or with sudo.

Having done all the above, I can now report that ssltest gives my server an A grade with the only issues being lack of support for IE6/XP, IE8/XP and java6u45, none of which I care about at all. More to the point, all the browsers I tested previously that failed on Android, iOS and OSX are now happy.

**Comment by kjmph** [comment]
Thank you @gjb. I know this is an old post, however, it was very helpful for me. If there are any updates, it is greatly appreciated if you could keep this fresh. This was the most informative information I found so that Firefox would accept the server's cert.

**Comment by kjmph** [comment]
For future people looking into this, I recommend using Mozilla's SSL Configuration Generator:

https://ssl-config.mozilla.org/
