### ISSUE TITLE
Apache --redirect doesn't work in the presence of RewriteRules

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1620]
It was probably written that way in order to be cautious about overlapping regexp semantics.  But it should be safe to add a HTTP -> HTTPS redirect after other redirects have fired, even if that winds up being redundant.

**Comment by pde** [comment]
@sagi is working on this

**Comment by bmw** [comment]
I'm not even going to pretend to understand the details here, but I believe @jdkasten was very careful and worried about causing problems here. We should check with him if we can and if not, tread carefully. I personally haven't heard any complaints about Apache redirect not working properly.

**Comment by pde** [comment]
@bmw: @sagi and I read the code and concluded that what it does is intentionally error out in any situation where `mod_rewrite` has been used.  Our conclusion is that that's overly cautious; most uses of `mod_rewrite` don't conflict with the addition of a final HTTP -> HTTPS redirect.

Having said that, there is a kind of conflict that can occur, which is an infinite loop in the case where other `RewriteRule`s send HTTPS -> HTTP.  There are a few solutions to that:

1. Only succeed on Apache 2.3.9+, where we can add the `[END]` flag to our rewrite, as documented [here](https://stackoverflow.com/questions/7798099/how-to-block-multiple-mod-rewrite-passes-or-infinite-loops-in-a-htaccess-cont).  Downsides: (1) that penalises most Apache 2.2 mod_rewrite users, who have not created infinite loops and don't deserve to be penalised for them; (2) it would break uses of `mod_rewrite` that are currently multi-pass.
2. Variant of 1.: if you're on Apache <2.3.9, do something like [this](https://stackoverflow.com/a/7799831) to prevent loops.
3. Parse and simulate all the mod_rewrite rules, and ensure that at least for some test URLs, there are no infinite loops
4. Rely on the fact that the user *asked* for a rewrite to conclude that it's up to them to debug infinite loops (or unexpected consequences of `[END]`) if those occur.
5. Print a note warning that there are `RewriteRule`s already present, asking the user to check the resulting set of rewrites.

I think I favour 5, probably without `[END]`.  Infinite loops are a pretty easy-to-understand and fix situation; a situation where multiple rewrite passes were occurring and necessary would be harder to catch.

**Comment by pde** [comment]
Actualy... we should test this but I believe it's safe to add `[END]`.  Our HTTP -> HTTPS rewrite is going to send a 302 and cause a whole separate TCP/HTTP connection (what Apache calls an "external redirect").  If the server wants to do some multi-pass mod_rewrite stuff, it can almost certainly do that after the user comes back over HTTPS, and our rewrite with its associated `[END]` will not fire.

The only theoretical exception is if the config has a [RewriteCond](https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond) containing the REQUEST_SCHEME parameter, which performs multi-pass redirects but only if REQEUST_SCHME = "http".  I think we can ignore that theoretical corner case.

**Comment by pde** [comment]
So to summarise a lot of complicated text, my feeling is that we should add the `[END]` modifier to our rewrite on Apache >= 2.3.9, and always be willing to install a rewrite.  But if there are preexisting rewrites, we should send the user a note asking them to double check that the final state is sane.
