### ISSUE TITLE
"The apache plugin is not working"

### ISSUE THREAD

**Issue by singpolyma** [letsencrypt/letsencrypt#1626]
./letsencrypt-auto --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview

I get this error:

     The apache plugin is not working; there may be problems with your existing configuration.
     The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/c-beta.ossguy.com.conf', u'Syntax error'),)

the file in question is: http://pastie.org/private/dparrnehfdtny0uwt4j88g

My apache version is 2.4.10

**Comment by pde** [comment]
Thanks! This is probably an instance of #1531, but we shall see.

**Comment by singpolyma** [comment]
I just pulled the latest and I still get the same error.  Is there something else I need to do in order to update?

**Comment by bmw** [comment]
@singpolyma, how are you running the client? Are you building from `master` or PyPI? For example, `letsencrypt-auto` uses PyPI and the change has not been made there yet. I plan to push it to PyPI today.

**Comment by singpolyma** [comment]
I am pulling master and then using `letsencrypt-auto` -- how should I run master directly?

**Comment by bmw** [comment]
No. Running from `master` is a bit trickier due to our `virtualenv` setup, but it is described [here](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client).

**Comment by singpolyma** [comment]
working, thanks
