### ISSUE TITLE
Creating documentation requires application already installed

### ISSUE THREAD

**Issue by hogarthj** [letsencrypt/letsencrypt#1632]
The makefile to create the man pages requires the application to already be installed.

Unfortunately this creates a fairly circular dependency that is an issue in packaging for Fedora/EPEL 

Due to the way rpmbuild works there is no time letsencrypt, jws or letsencrypt-renew will be on the path to be called to capture the --help output unless it is already actually installed in the mock environment.

Is there a specific reason sphinxcontrib.programoutput was selected to created the man page or is it feasible to generate a man page without the application from being installed in the first place?

Calling make in the %install  section with PATH manipulation to build the man pages is not very clean and it would be far nicer to generate from markdown or similar (or just a plain straight man page) in the %build phase

**Comment by andrewsomething** [comment]
Seems to be more or less the same issue as #1126

**Comment by kuba** [comment]
Yes, this is a duplicate
