### ISSUE TITLE
How far in the certchain should I go with my HPKP?

### ISSUE THREAD

**Issue by intchloe** [letsencrypt/letsencrypt#1636]
Will Let's Encrypt always use 'Let's Encrypt Autohity X1' in its cert chain? So the hash "YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=" can be used on all websites issued by Let's Encrypt?

**Comment by pde** [comment]
I've tried to answer this question in a [post] on community.letsencrypt.org.
