### ISSUE TITLE
Don't ask to temporarily shut down web server to pass challenge, instead make use of proxy_pass

### ISSUE THREAD

**Issue by leonklingele** [letsencrypt/letsencrypt#1643]
I've recently set up letsencrypt on my server and I was not quite happy with how the default setup process works:

letsencrypt uses port 80 to do the challenge/response thing https://github.com/letsencrypt/letsencrypt/blob/236af19a50de18a7cd831157dc53a6d22f79ee10/acme/acme/challenges.py#L223
It asks to temporarily stop an already running web server for it to bind its own web server to port 80 https://github.com/letsencrypt/letsencrypt/blob/d209b5ea20c2f5f35eadc304dbe5cbb85c233f4d/letsencrypt/plugins/standalone.py#L222

This causes downtime of the main http service. Downtime = bad.
Please offer an option to bind to another port and proxy_pass it to port 80. This will not cause any downtime.

**Comment by emansom** [comment]
+1

**Comment by pde** [comment]
If you don't like the `standalone` plugin, you can use the `webroot` or `apache` plugins to get a cert without shutting down your webserver:

https://letsencrypt.readthedocs.org/en/latest/using.html#plugins

**Comment by pde** [comment]
(if after trying those out you still believe we should consider proxypass for some reason, feel free to reopen).

**Comment by emansom** [comment]
I don't like sharing the same root for a VHost with letsencrypt. I'd prefer if I could specify a port on which the standalone plugin runs thru a command line flag. e.g. --port=30323.

**Comment by leonklingele** [comment]
It's simple: Do not use this repo.
Use letsencrypt-nosudo: https://github.com/diafygi/letsencrypt-nosudo/pull/37

**Comment by leonklingele** [comment]
In case anyone is still looking for a letsencrypt tool which properly handles proxy_pass to avoid downtime:
https://github.com/gheift/letsencrypt.sh
