### ISSUE TITLE
On Fedora 23, install fails

### ISSUE THREAD

**Issue by cultavix** [letsencrypt/letsencrypt#1644]
`gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`

This is what I get when running the auto install on Fedora 23. 

It looks like it's missing a dependency, I determined this by running the pip command separately.

It can be solved by simply running `yum install redhat-rpm-config`

**Comment by pde** [comment]
We have two PRs for this, but they're blocked on testing on Amazon Linux and other exotic RPM-based systems.

**Comment by pde** [comment]
#1527 has been merged.
