### ISSUE TITLE
How to debug "could not connect to the client for DV" ?

### ISSUE THREAD

**Issue by singpolyma** [letsencrypt/letsencrypt#1650]
```
FailedChallenges: Failed authorization procedure. roundcube.singpolyma.net (tls-sni-01): urn:acme:error:connection :: The server could not connec
t to the client for DV :: Failed to connect to host for DVSNI challenge
```

My server is accessible to the internet, no proxies in front or anything.  What might be the issue?

**Comment by pde** [comment]
Please take a look at the [past threads mentioning that error](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=%22could+not+connect+to+the+client+for+DV%22+site%3ACommunity.letsencrypt.org&es_th=1).  It can for instance be caused by stale results in DNS caches.

As for debugging strategies if that's not the cause, perhaps you could tweak your client to pause the once it's prepared for DV (the place where it first receives that ACME error would probably do), so that you can try connecting to the test name with tls-sni-01 yourself and see what's going on.

**Comment by pde** [comment]
Are you running against staging or production servers?

**Comment by pde** [comment]
(The staging ones seem to be erroring in general at the moment).

**Comment by singpolyma** [comment]
Should be using production.  Command is:

```
letsencrypt --verbose --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
```

**Comment by pde** [comment]
* make sure you don't have stale DNS entries
* make sure you're not firewalled, and when you connect to roundcube.singpolyma.net:443 from a random part of the Internet, it gets to your machine (currently I get no reply to when I try that)

I would be surprised if more elaborate debugging steps turn out to be necessary.

**Comment by singpolyma** [comment]
No issue connecting to roundcube.singpolyma.net:443 from anywhere I can get to, but if you can't maybe it's a netsplit of some kind.  I'll try again tomorrow :)

**Comment by singpolyma** [comment]
It seems that letsencrypt can't handle an apache config that listens on 443 at specific ips in ports.conf -- changing it to Listen 443 seems to have fixed it

**Comment by singpolyma** [comment]
Hmm.  Instead of installing my cert into apache for me it instead disabled my virtualhost.  But I configured it manually and it's working at least :)

**Comment by pde** [comment]
@singpolyma would you be willing to share your Apache config so that we can add it to our test cases?

**Comment by singpolyma** [comment]
@pde it's a bit bit... I could email you the whole thing and maybe some parts of it are worth including?

**Comment by aoighost** [comment]
@singpolyma could you please post a censored but still useful version of the one that works for you? I'm having the same issue.

**Comment by tazeat** [comment]
Tagging this for updates, appears to be the same issue using virtualhosts listening only on specific IPs...

**Comment by taher435** [comment]
I faced this issue and none of the fixes mentioned above worked for me. At the end, the problem was because I was routing my website through CloudFare. I disabled it and everything worked. Hope this helps someone using CloudFare who faces this same issue.
