### ISSUE TITLE
Don't try to auto-configure local names

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#1682]
In https://community.letsencrypt.org/t/dns-name-does-not-have-enough-labels/5036/2, we have a couple of people who ran into trouble because they had a virtualhost for a local name, i.e. one with no dots. We should omit these from the list of names we try to auto-configure.

More generally, we could try to reproduce some of the validity checks that happen in boulder, so if you have "foo.corp", the client could see that that doesn't end in a public suffix and ignore it.

Alternately, we could be a little friendlier about presenting "these names failed to validate. do you want to issue a cert for the other names anyhow, or keep trying to validate these names?"

**Comment by pde** [comment]
I had  seen this with nginx and filed #1664, but perhaps it makes more sense to handle pruning of local names in the main client.
