### ISSUE TITLE
Apache 2 Config files

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [letsencrypt/letsencrypt#1691]
Maybe Let's Encrypt should ignore files in apache config folder that aren't config extension, like .bak. I had the problem that Let's encrypt was changing my backup config and not the working one.

**Comment by Crazee** [comment]
Well in my case letsencrypt-auto ignored the hostname.conf file in /etc/apache2/sites-enabled/ and made its own 000-default-le-ssl.conf file there.  Apache was still serving up the old default "snakeoil" self-signed cert until I removed my original conf file from sites-enabled and restarted Apache.

**Comment by ZatsuneNoMokou** [comment]
The existing configuration was more complicated for me, there was 2 different certificates in several sub domain and a main domain. In /etc/apache2/sites-available/ there was 2 files, on .conf and one .conf.bak that was supposed to be a backup. And that .bak file wasn't linked to the enabled folder.

**Comment by pde** [comment]
We should mirror Apache's own semantics; if (on Debian) it only reads .conf files from /etc/apache2/sites-enabled we should only read .conf; if reads everything except .bak then we should copy that behaviour.

**Comment by ZatsuneNoMokou** [comment]
@pde Because in my case, the right config file wasn't changed for exemple

**Comment by Crazee** [comment]
Actually the whole --apache mode is too much trouble.  Now that I know the 3 (important) lines it needs to add/alter in your conf file I changed them myself and just run
```
#!/bin/sh

sudo service apache2 stop

/opt/letsencrypt/letsencrypt-auto certonly --standalone --email spiro.agnew@example.com --agree-tos -d `hostname`

sudo service apache2 start
```
once to start and every month from a crontab.

**Comment by ZatsuneNoMokou** [comment]
I'm using the manual mode too, but this one is harder to make cron task, useful when there's only ftp access to a website
