### ISSUE TITLE
Should not select domains which can't be used with letsencrypt

### ISSUE THREAD

**Issue by mithro** [letsencrypt/letsencrypt#1708]
Neither international (names starting with `xn--`) nor wildcard domains are currently supported by letsencrypt. In the "Which names would you like to activate HTTPS for?" dialog these domains should not be selectable.

![image](https://cloud.githubusercontent.com/assets/21212/11580376/fa15c5d2-9a8a-11e5-9be5-379beeeff21d.png)

**Comment by joohoi** [comment]
You are right, we have the check currently in place for command line arguments, but not for apache VirtualHosts, I'll extend the checks to apache module too.

**Comment by mzealey** [comment]
Also wildcards should be excluded as they crash the installer
