### ISSUE TITLE
How to verify using DNS challenge

### ISSUE THREAD

**Issue by richardkazuomiller** [letsencrypt/letsencrypt#1711]
Is it possible now to use the DNS challenge instead of provisioning the `.well-known/acme-challenge/...` HTTP resource? With my current configuration, the DNS challenge would be much easier than the HTTP method but I can't find documentation of how to do that in the docs for the CLI.

If it's not possible now are there plans to implement this in the future?

**Comment by pde** [comment]
https://community.letsencrypt.org/t/on-the-state-of-the-dns-01-challenge/4805
