### ISSUE TITLE
Forcing 443 acme challenge with certonly

### ISSUE THREAD

**Issue by precurse** [letsencrypt/letsencrypt#1715]
My ISP blocks port 80, but allows port 443 inbound. I successfully pulled a cert by using standalone with the  --standalone-supported-challenges tls-sni-01    flag to force 443/https and used the cert. However, if I want to automate it, I can't shut down my nginx instance in order to verify the domain.

I'm using this command to renew the cert.
This is the command I'm using to run: ./letsencrypt-auto certonly -a webroot --renew-by-default --email me@example.com -w /tmp/letsencrypt-auto  -d domain1.com

However, I keep getting the following error:
Could not connect to http://domain..com/.well-known/acme-challenge/DVtvdatt1XYUVJlu2cO9
zZmHnzyisUh6WmqreqoivwM, domain.com (http-01): urn:acme:error:connection :: The server could not connect to the client for DV

There doesn't appear to be a flag for forcing 443/https to be used, so it keeps using 80/http, and failing. Is this a limitation for webroot?  

Thanks!

**Comment by pde** [comment]
Starting with a connection on :80 is a limit to the http-01 challenge type that webroot uses, and it exists for [security reasons](https://www.ietf.org/mail-archive/web/acme/current/msg00524.html).  If you really have inbound 80 blocked, and can't automatically stop and start nginx immediately before and after renewal, your next best bet might be to renew with the nginx plugin.  But please be aware that it is experimental and buggy.

If you want to try that, back up your configuration first, and expect to encounter bugs.  Then follow the [developer instructions](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client) to get a copy of the client with the nginx plugin available.  You can activate the venv or just run `/path/to/letsencrypt/venv/bin/letsencrypt certonly --nginx --renew-by-default -d example.com,www.example.com,www.etc.com`.  You should then be able to reload nginx to pick up the new cert that will be deployed in `/etc/letsencrypt/live`.

Or just get a new ISP :)
