### ISSUE TITLE
Too many certificates already issued for: domain.org while -d sub.domain.org was requested

### ISSUE THREAD

**Issue by mcnesium** [letsencrypt/letsencrypt#1721]
on Ubuntu 14.04 with nginx webserver, I tried to request a standalone certificate using
    ./letsencrypt-auto --standalone -d sub.domain.org --email my@mail.org

As domain.org is a dyndns service, where I registered my sub-domain, it might be true that there have been requested a lot of certificates this morning. But I did request a certificate for just my third-level-domain, so I consider this a bug, because it requests for the second-level domain.

    2015-12-04 09:19:48,192:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
    2015-12-04 09:19:48,553:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-cert HTTP/1.1" 429 142
    2015-12-04 09:19:48,569:DEBUG:root:Received <Response [429]>. Headers: {'Content-Length': '142', 'Expires': 'Fri, 04 Dec 2015 09:19:48 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 04 Dec 2015 09:19:48 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '58geScLC4YqcBRbSjf19ZKyU4h2E_4yauvxS8iWJZOo'}. Content: '{"type":"urn:acme:error:rateLimited","detail":"Error creating new cert :: Too many certificates already issued for: domain.org","status":429}'
    2015-12-04 09:19:48,576:DEBUG:acme.client:Storing nonce: '\xe7\xc8\x1eI\xc2\xc2\xe1\x8a\x9c\x05\x16\xd2\x8d\xfd}d\xac\x94\xe2\x1d\x84\xff\x8c\x9a\xba\xfcR\xf2%\x89d\xea'
    2015-12-04 09:19:48,576:DEBUG:acme.client:Received response <Response [429]> (headers: {'Content-Length': '142', 'Expires': 'Fri, 04 Dec 2015 09:19:48 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 04 Dec 2015 09:19:48 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '58geScLC4YqcBRbSjf19ZKyU4h2E_4yauvxS8iWJZOo'}): '{"type":"urn:acme:error:rateLimited","detail":"Error creating new cert :: Too many certificates already issued for: domain.org","status":429}'
    2015-12-04 09:19:48,589:DEBUG:letsencrypt.cli:Exiting abnormally:

**Comment by fisharebest** [comment]
> Too many certificates already issued for: domain.org

There is a [rate limit](https://community.letsencrypt.org/t/beta-program-announcements/1631) of 5 subdomains in a 7 day period.  So, if you request

* <https://example.com>
* <https://www.example.com>
* <https://blog.example.com>
* <https://api.example.com>
* <https://forum.example.com>
* <https://support.example.com>

then you have made 6 requests for <http://*.example.com> and the last one will fail.  The error message tells you the base domain for which the limit applies - not the sub-domain which you requested.

Try again in 7 days...

It's a real problem if you use subdomains for internationalisation (<https://en.example.com>, <https://fr.example.com>, <https://de.example.com>, ...)  - but it's a free service, and they do say they will reduce the rate limit once things settle down...

**Comment by mcnesium** [comment]
What if people request certificates for lets say domain.co.uk - are there only 5 of them available per week?

**Comment by fisharebest** [comment]
...then it seems that you are out of luck.

I've got 17 subdomains on my server, and it's going to be 3 weeks before I can register them all :-(

**Comment by mcnesium** [comment]
I am not complaining about the beta release of a free service, even though I have been waiting for this desperately since the first announcement. Just arguing that if a third-level-domain certificate is requested, then the tool should just issue one for the third-level-domain and not care about the second-level-domain at all.

**Comment by as-com** [comment]
You can specify multiple domains per certificate with multiple -d domain.tld arguments. Example: `./letsencrypt-auto --standalone -d domain.org -d www.domain.org -d sub.domain.org -d foo.domain.org`

**Comment by fisharebest** [comment]
> You can specify multiple domains per certificate with multiple 

Yes - but the (documentation)[https://community.letsencrypt.org/t/beta-program-announcements/1631] makes it clear that the limit applies to the number of subdomains, not the number of requests or certificates.

**Comment by as-com** [comment]
I just got a certificate with 10 subdomains on a single domain.

> On Dec 5 2015, at 4:21 am, Greg Roach &lt;notifications@github.com&gt;
wrote:  

>

>> You can specify multiple domains per certificate with multiple

>

> Yes - but the (documentation)[<https://community.letsencrypt.org/t/beta-
program-announcements/1631>] makes it clear that the limit applies to the
number of subdomains, not the number of requests or certificates.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/letsenc
rypt/letsencrypt/issues/1721#issuecomment-162163743).![](https://github.com/no
tifications/beacon/ADpIaZpBFJgzfFT5l4jLIkJsYpTXwHerks5pMqQXgaJpZM4GutK5.gif)

**Comment by Fourdee** [comment]
Receiving the same error.
Extremely annoying while trying to implement Lets Encrypt without being able to test it.

> https://github.com/Fourdee/DietPi/issues/128#issuecomment-162335027

I'am also getting the same error when trying different domains on the same network. Is the block based on IP address?

**Comment by mcnesium** [comment]
Everyone is missing my point: why does letsencrypt care about domain.org when I requested sub.domain.org? This is a bug IMHO which I am trying to report here.

**Comment by fisharebest** [comment]
> Everyone is missing my point

The sub-domain limit applies to domain.org.  The limit includes the bare domain.

So, the error message says "limit reached for domain.org".

IMHO, this is not a bug.  They have a published limit, and we are both hitting it.

Not sure how @as-com managed to get 10. Maybe a bug in the rate limiter ;-)

**Comment by mcnesium** [comment]
Thank you for clarifying that. I assumed that because one has to create an account, that the limit will only apply for the account. Makes sense though, too bad.

**Comment by pde** [comment]
Agree this is not a bug.  Hopefully rate limits should be a bit less of a problem with a fix for #1546 shipping next week, but Let's Encrypt will also be creating a process shortly for requesting rate limit exceptions for those that genuinely need them.

**Comment by ssbarnea** [comment]
I am getting this error while trying to generate a certificate for my Synology box, which obviously also have DDNS records on `synology.me` and `quickconnect.to` domains. While I am using my OWN domain for the certificate, I do also need to add the DDNS entries as subject-alternative-names but this fails:

Having a limit for these makes it impossible to use letsencrypt as they clearly have lots and lots of customers.

![screenshot 2016-02-21 17 06 15](https://cloud.githubusercontent.com/assets/102495/13204062/c739f48c-d8bd-11e5-9c11-b8c1a31ba1b4.png)

**Comment by cgcgbcbc** [comment]
Why not documented, I didn't know I can request multiple host in one cert, and I didn't know the limit until I see the error message, while I need to wait another 7 days for requiring a "large" cert

**Comment by danger89** [comment]
The limit part is listed here:
https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769

The stupid part is I knew the limits, but I didn't knew it makes a difference to 'chain' them together in 1 request -,-...
