### ISSUE TITLE
Custom Port for File Validation

### ISSUE THREAD

**Issue by iveoles** [letsencrypt/letsencrypt#1731]
There appear to be several issues relating to automating validation on a cluster. This is typically due to the file replication delay.

If we could use the webserver option with a custom port most of these issues could be avoided as Sysadmins could redirect their custom port to the primary authentication server.

**Comment by bmw** [comment]
Using a custom port is not currently a feature of the ACME spec found [here](https://github.com/ietf-wg-acme/acme) and is therefore outside of the scope of what we can do in the client.
