### ISSUE TITLE
Segmentation fault on first launch - Debian 8 - GrSec

### ISSUE THREAD

**Issue by stylersnico** [letsencrypt/letsencrypt#1737]
Hi,

I have a error at the first launch of let's encrypt client, I got this :

updating letsencrypt and virtual environment dependencies ... 
segmentation fault

I have a custom 4.2.6 GrSec kernel, debian 8 and dedicated server with Xeon, 32Gb of ram and SSD's.

Any idea ?

Thanks

**Comment by pde** [comment]
For grsec systems, I'd suggest trying to build Debian packages from source.  They're in experimental now, should be in unstable soon.

I'm going to close this ticket for now, but please reopen it if you see the crash with grsec + native Debian packages.

**Comment by stylersnico** [comment]
This is what I get with the packages for Debian in unstable

apt-get -t experimental install python-letsencrypt
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-letsencrypt : Depends: python-acme (>= 0.1.0) but it is not going to be installed
                      Depends: python-configargparse but it is not installable
                      Depends: python-cryptography (>= 0.7) but 0.6.1-1 is to be installed
                      Depends: python-dialog but it is not installable
                      Recommends: letsencrypt but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by stylersnico** [comment]
root@webhost:/tmp/letsencrypt/bootstrap# ./venv.sh
Segmentation fault
root@webhost:/tmp/letsencrypt/bootstrap#

The problem seems to be coming from venv.sh script

**Comment by qzio** [comment]
I'm also seeing this error on debian/unstable with grsec kernel.
But only when using `standalone`, `certonly + --webroot` works fine.
