### ISSUE TITLE
Not possible to issue a certificate if Apache does not bind to all IPs

### ISSUE THREAD

**Issue by dwilson390** [letsencrypt/letsencrypt#1739]
Firstly, very pleased with this project, and how far it has some in such a sort space of time!

On saying that, I do have an issue regarding Apache.  My current `ports.conf` is this, obviously replacing `(IP)` with my actual IP;
```
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen (IP):80

<IfModule ssl_module>
        Listen (IP):443
</IfModule>

<IfModule mod_gnutls.c>
        Listen (IP):443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
However, this means certificate issuance fails with the following error;
```
IMPORTANT NOTES:
 - The following 'urn:acme:error:connection' errors were reported by
   the server:

   Domains: minersrealm.net, www.minersrealm.net
   Error: The server could not connect to the client for DV
```
...this means I am forced to use this configuration...;
```
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen 80

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
...which then means Apache is binding to **all** IPs on the server, something which I do not want.  My main problem with this is I wish to automate the SSL renewal once every two months, something which I cannot do if I need to manually update the configuration everytime I wish to renew a certificate.

**Comment by rubin110** [comment]
May be related to #1994.
