### ISSUE TITLE
"If letsencrypt is packaged for your OS..." Which?

### ISSUE THREAD

**Issue by hickford** [letsencrypt/letsencrypt#1740]
> If letsencrypt is packaged for your OS, you can install it from there, and run it by typing letsencrypt. Because not all operating systems have packages yet

Do you have a list? I'm using

> Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 3.13.0-57-generic x86_64)

**Comment by egillespie** [comment]
https://letsencrypt.readthedocs.org/en/latest/using.html#operating-system-packages
