### ISSUE TITLE
Support HTTP Basic Authentication with webroot

### ISSUE THREAD

**Issue by mikehaertl** [letsencrypt/letsencrypt#1744]
When using the webroot method it would be great, if we could supply a username/password combination. I therefore propose a feature like `-u user:password` or similar.

**Comment by chriscroome** [comment]
I came up against this issue, the way I resolved it was to not require HTTP Authentication for `/.well-known/acme-challenge`. For example if you use a `.htaccess` file for enforcing HTTP Authentication:

```apache
AuthUserFile /var/www/example/.htpasswd
AuthType Basic
AuthName "My Private Stuff"
require valid-user
```

And then at a Apache configuration level set `ServerAlias` so that `/.well-known/acme-challenge` is somewhere else, for example:

```apache
Alias "/.well-known/acme-challenge" "/var/www/lets-encrypt/example/.well-known/acme-challenge"
```

Then create directories for each `VirtualHost` and use the `Alias` directory for `-d` on the command line.

**Comment by pde** [comment]
This would require a change to the IETF ACME spec, so flagging it "wontfix" in the client for now.

**Comment by mikehaertl** [comment]
That's what I did now, thanks. For the record here's my config for nginx:

```
# Main SSL Site
server {
    server_name www.example.com
    root /var/www/www.example.com;
    listen *:443 ssl;
    ssl_certificate             /etc/letsencrypt/live/www.example.com/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/www.example.com/privkey.pem;
    # ...
}

# Redirect 80 -> 440 (SSL)
server {
    server_name www.example.com
    root /var/www/www.example.com;
    listen *:80;

    location / {
        rewrite ^(.*)$ https://www.example.com$1 permanent;
    }

    # Exclude let's encrypt
    location /.well-known {
    }
}
```

**Comment by PatrickCronin** [comment]
Another way, if using Apache 2.4, is to add a Require directive above valid-user that allows requests to lets-encrypt's urls:

```ApacheConf
<Location />
	AuthUserFile /var/www/example/.htpasswd
	AuthType Basic
	AuthName "My Private Stuff"
	Require expr %{REQUEST_URI} =~ m#^/.well-known/acme-challenge/#
	Require valid-user
</Location>
```

**Comment by kohkimakimoto** [comment]
I'm using the following configuration at Apache 2.2. It works well.

```apache
<Location />
    Satisfy Any
    AuthType Basic
    AuthName "My Private Stuff"
    AuthUserFile /var/www/example/.htpasswd
    Require valid-user

    SetEnvIf Request_URI "/.well-known/acme-challenge" acme-challenge
    Order Deny,Allow
    Deny from all
    Allow from env=acme-challenge
</Location>
```

**Comment by binarykitchen** [comment]
and how can we do the same for nginx?

**Comment by mikehaertl** [comment]
@binarykitchen Uhm, there's an example above? https://github.com/certbot/certbot/issues/1744#issuecomment-162172711

**Comment by cvbkf** [comment]
@binarykitchen @mikehaertl 

there is a lot easier solution, which disables auth basic for acme-challenge only. 

`    location /.well-known/acme-challenge {
        auth_basic off;
        root /var/www/letsencrypt;
    }
`

**Comment by mikehaertl** [comment]
@cvbkf Hmm, how is it easier? Note that my example above is a full domain configuration, including a redirect from insecure port 80 to secure 443.

**Comment by patricknelson** [comment]
🎉 Great idea, thanks @kohkimakimoto!

**Comment by xshadow** [comment]
You could also add a directory directive for your .well-known directory, instead of using the Location Directive

```
    <Directory /var/www/mywebsite.com/www>
        AllowOverride AuthConfig
        AuthType Basic
        AuthName "Password Required"
        AuthUserFile /var/www/mywebsite.com/.htpasswd
        Require valid-user
    </Directory>

    # Allow access to .well-known directory, to enable LetsEncrypt ACME Challenge
    <Directory /var/www/mywebsite.com/www/.well-known>
        Require all granted
    </Directory>
```

**Comment by praveenayko** [comment]
> @binarykitchen @mikehaertl
> 
> there is a lot easier solution, which disables auth basic for acme-challenge only.
> 
> ```
> location /.well-known/acme-challenge {
>     auth_basic off;
>     root /var/www/letsencrypt;
> }
> ```

@cvbkf Thanks for the suggestion.
This solution is working for me.
I was just needed to move this condition before the basic auth condition.
**Ex.:**
> location /.well-known/acme-challenge {
>     auth_basic off;
>     root /var/www/letsencrypt;
> }
>include /etc/nginx/conf.d/includes/authentication.enable

Thanks again...!!!
