### ISSUE TITLE
IDN are not supported

### ISSUE THREAD

**Issue by wolkenschieber** [letsencrypt/letsencrypt#1746]
It seems that IDNs are not supported:

```
./letsencrypt-auto certonly --standalone -d xn--dmin-moa0i.example
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: sudo /home/keibak/.local/share/letsencrypt/bin/letsencrypt certonly --standalone -d xn--dmin-moa0i.example
Punycode domains are not supported
```

**Comment by rainest** [comment]
In addition, the error for the non-punycode variation of IDNs is incorrect:

```
# letsencrypt -d ёжикв.сайт
Requested domain is not a FQDN
```

**Comment by Envek** [comment]
I think that Let's Encrypt should not care about whether certain registrars have some restrictions or not. If such domain does exist and it's resolving to the address of machine, that runs the letsencrypt client (so checks can be passed), then everything should be fine. Am I missing something?

**Comment by Ascendor** [comment]
I have the feeling that the IDN discussion is now completely ignored by Let's Encrypt? At least give us a statement like: "We'll never do it.", then we can stop wasting time & energy here.

**Comment by bmw** [comment]
This repository is for issues related to the Let's Encrypt client. Since this is an issue with the Let's Encrypt CA, I'm closing this issue.

The relevant issue against `boulder`, the server side of Let's Encrypt is: letsencrypt/boulder#597
