### ISSUE TITLE
add_deprecated_argument needs to accept arguments of any type (letsencrypt: error: agree-dev-preview set to 'True' rather than a value)

### ISSUE THREAD

**Issue by fsantiago07044** [letsencrypt/letsencrypt#1750]
latest version of the official client installed; just ran git pull.
worked fine until several days ago with a pull i had made then.
webroot auth being used.
centos 7 / nginx (but i'm installing the cert(s) manually)

same error appears on renewal attempts as well as new domain cert requests. 

tried using a cli.ini file as well as full command line only.

no change in results. 

what am i missing?

**Comment by pde** [comment]
The --agree-dev-preview flag/config option is now deprecated; you've found a bug in our option deprecation code.

Remove that setting as a workaround.

**Comment by fsantiago07044** [comment]
Some else told me it was deprecated and to remove it which I've since done and I still receive the same error. almost as if it's being cached somewhere (not possible right?). i don't know what's up....

**Comment by fsantiago07044** [comment]
Now I'm really confused; I just tried again with a new domain and this time strictly followed the Beta invite's email instructions (with letsencrypt-auto):

/root/.local/share/letsencrypt/bin/letsencrypt certonly -a webroot --webroot-path /usr/lib/mailman -d lists.garbage-juice.com --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview

and while it did warn me of the deprecation of the agree-dev-preview command, it worked, for the new cert.

Now I just tried renewing the same cert i just received, this time adding --renew-by-default, and it also now worked fine, while still warning me of the deprecated command.

So now I went back to one of my original domains (one cert, 2 domains) I had been trying to renew for days now (as a test), and SOB, it appears to possibly have worked except i got rateLimited (probably due to my testing).

So IDK what's up but it works now seemingly. WTF!? haha........

**Comment by svennd** [comment]
Maybe you have a .ini file somewhere ?

**Comment by fsantiago07044** [comment]
But I was specifying the ini file in my cmd line. It worked now once I went back to simply using the exact example in the beta invite for a new cert. Then modified that by adding renew-by-default for a renewal and should have worked except I hit the rate limit. 

Weird. Not sure why it wasn't working before that. I don't feel I really tried anything different truly. Idk. 

Sincerely,

Fabian Santiago

**Comment by pde** [comment]
probably adding `type=any` to `add_deprecated_argument`'s argparse call will fix this.
