### ISSUE TITLE
Email Validity Checking is Bugged

### ISSUE THREAD

**Issue by hongkongkiwi** [letsencrypt/letsencrypt#1762]
It seems that the email checking is a bit wonky.

My email is something like "me@blah.hk" which is a perfectly valid email and .hk is a valid TLC however, it is rejected and it tells me the only way to register is unsafely without email (obviously not what I want).

If I use an email from work which has "me@blah.com.hk" it is perfectly happy.

Seems like the email is valid checking has issues. Really I think it shouldn't do any kind of validation on email address except something that has an @ symbol and a dot. If I mistype it, or else if I write it incorrectly it's my own fault.

**Comment by ewxrjk** [comment]
I see the same behavior, so I modified the client to display the exception. I got:

Error(typ=u'urn:acme:error:malformed', detail=u'Error creating new registration :: Validation of contact mailto:<my address> failed: Server failure at resolver', title=None)

**Comment by ewxrjk** [comment]
... in fact I think this is the client-side reflection of https://github.com/letsencrypt/boulder/issues/1197. The server attempts to validate mail domains with a DNS A lookup, rather than the correct MX then A/AAAA sequence.

**Comment by ejc3** [comment]
@campbell.name doesn't work too.

**Comment by a4lg** [comment]
As I mentioned in https://github.com/letsencrypt/boulder/issues/1197 , try adding a dummy A record to domain part of the email address (`campbell.name` in this case; setting private addresses may fail). It worked fine for me.

**Comment by ejc3** [comment]
thank you! (and sorry for piling on)

**Comment by iamgroot42** [comment]
I had a look through the repo and can't seem to find the part where email validation is performed.

**Comment by ewxrjk** [comment]
https://github.com/letsencrypt/boulder/issues/1197 has now been fixed and deployed, and the client now works for me. So I suggest anyone else reading here try again.

**Comment by bmw** [comment]
Thanks for point that out @ewxrjk. With that in mind, I'm closing this issue. Please comment if anyone still has the issue and I'll reopen.
