### ISSUE TITLE
Apache config parse failure with SSL_CLIENT_S_DN_CN and an array

### ISSUE THREAD

**Issue by philvdb** [letsencrypt/letsencrypt#1766]
Hello (especially @domcleal , trying out LE and *loving* it so far.

Here's my apache parsing trouble right now (PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/xy-le-ssl.conf', u'Syntax error')), which hinges on the following line in my apache configuration:

SSLRequire %{SSL_CLIENT_S_DN_CN} in {"foo@bar.com", "bar@foo.com"}

If you need the entire config file, let me know. But commenting out this line leads to LE running normally.

**Comment by domcleal** [comment]
Thanks for the bug report.  I've fixed this in Augeas in commit https://github.com/hercules-team/augeas/commit/f86a28d03a5c42a6c58293667a95d7794e30a42f.

There's a conflicting change being made to the LE Augeas module right now, but as soon as that's merged I'll submit the change back to LE.

**Comment by philvdb** [comment]
Awesome. Thank you!
