### ISSUE TITLE
Webroot breaks for non-root due to chown

### ISSUE THREAD

**Issue by SunMar** [letsencrypt/letsencrypt#1795]
Hi,

Today I'm trying out letsencrypt and stumbled upon that using webroot breaks when not using root due to a chown on line 72 of letsencrypt/plugins/webroot.py:

```
 49     def prepare(self):  # pylint: disable=missing-docstring
 50         path_map = self.conf("map")
 51
 52         if not path_map:
 53             raise errors.PluginError("--{0} must be set".format(
 54                 self.option_name("path")))
 55         for name, path in path_map.items():
 56             if not os.path.isdir(path):
 57                 raise errors.PluginError(path + " does not exist or is not a directory")
 58             self.full_roots[name] = os.path.join(path, challenges.HTTP01.URI_ROOT_PATH)
 59
 60             logger.debug("Creating root challenges validation dir at %s",
 61                          self.full_roots[name])
 62             try:
 63                 os.makedirs(self.full_roots[name])
 64                 # Set permissions as parent directory (GH #1389)
 65                 # We don't use the parameters in makedirs because it
 66                 # may not always work
 67                 # https://stackoverflow.com/questions/5231901/permission-problems-when-creating-a-dir-with-os-makedirs-python
 68                 stat_path = os.stat(path)
 69                 filemode = stat.S_IMODE(stat_path.st_mode)
 70                 os.chmod(self.full_roots[name], filemode)
 71                 # Set owner and group, too
 72                 os.chown(self.full_roots[name], stat_path.st_uid,
 73                           stat_path.st_gid)
 74
 75             except OSError as exception:
 76                 if exception.errno != errno.EEXIST:
 77                     raise errors.PluginError(
 78                         "Couldn't create root for {0} http-01 "
 79                         "challenge responses: {1}", name, exception)
```

It tries to set the ownership of the directory to the owner of the parent. So currently to bypass this issue either the webroot must be chown'd to the letsencrypt user, or the script needs to be run as root. Neither of which are satisfactory solutions. Is chown at all neccesary when letsencrypt is not run as root?

**Comment by pde** [comment]
Probably the right answer is that `chown` should be wrapped in a try: except: pass branch.  @lbeltrame, are you interested in taking this?

**Comment by kuba** [comment]
That's really sad news :( In the meantime you can use https://github.com/kuba/simp_le - it's a client for webroot only, without any root requirements.

**Comment by lbeltrame** [comment]
Il 06 dicembre 2015 22:00:18 CET, Peter Eckersley <notifications@github.com> ha scritto:

>Probably the right answer is that `chown` should be wrapped in a try:
>except: pass branch.  @lbeltrame, are you interested in taking this?

I can take a look tomorrow hopefully (yay for public holidays).

-- 
Luca Beltrame
GPG key ID: 6E1A4E79

**Comment by aburch** [comment]
More correct is probably to just create the directories with the right owner (by temporarily changing the uid and gid if root) and permissions (by using os.makedirs' mode option with optionally temporarily changing the umask as well as explained in the linked discussion on stackoverflow).

Otherwise one easily gets race conditions if other users have write permissions to the webroot or a parent directory.  Using `fchown` and `fchmod` instead of `chown` and `chmod` is also a good idea.

Also os.makedirs can create multiple directories, but it looks like the permissions are only changed for the last one?

**Comment by aburch** [comment]
The easier solution for `_perform_single` (which also uses chmod/chown) is probably to

- Create the file writable-by-owner & world-readable (w/o any chmod call; this might require changing the umask temporarily).
- Do not care about the owner: users with write access to the parent directory can remove it anyway and there is not much interesting to do besides that.

**Comment by lbeltrame** [comment]
In my opinion, I would not change the umask, I'm expecting whoever set the directory to have made it with correct permissions: the client should only be concerned with the files and directory it creates itself.

**Comment by lbeltrame** [comment]
```python

with open(path, "w") as validation_file:
            old_umask = os.umask(022)
            validation_file.write(validation.encode())
            os.umask(old_umask)
```

Would something of the sort suffice for `_perform_single`?

**Comment by lbeltrame** [comment]
@aburch How would you define the "right" owner for a directory? The UID of the process?

**Comment by lbeltrame** [comment]
FYI, I am trying to implement the suggestions, but I want to make sure I get things right, hence the questions.

**Comment by aburch** [comment]
Luca Beltrame <notifications@github.com> writes:
> ```python
>
> with open(path, "w") as validation_file:
>             old_umask = os.umask(022)
>             validation_file.write(validation.encode())
>             os.umask(old_umask)
> ```
>
> Would something of the sort suffice for `_perform_single`?

No, you need to change the umask before creating the file. Something
like

```python

old_umask = os.umask(0o022)
try:
    with open(path, "wx") as validation_file:
        validation_file.write(validation.encode())
finally:
    os.umask(old_umask)
```

This also fails if the file already exists ("x" in open, needs
Python3.3+) and reverts the umask even if an exception is raised.

Note: I didn't test the code snippet above.

Ansgar

**Comment by aburch** [comment]
Luca Beltrame <notifications@github.com> writes:
> @aburch How would you define the "right" owner for a directory? The UID of the process?

Hmm, that's not easy to answer.

For myself, I plan to run letsencrypt as a dedicated service user.  So
it can only create files as its own user anyway.  I think that is also
how most distributions expect services to work.

I understand that you also want to provide a fully magic mode.  This is
always hard to get right; the best approximation is probably to use the
owner of the given webroot (if letsencrypt is started as root).  Maybe
provide a command-line option if this is not the case: for example an
admin could have created .../.well-known/acme-challenges manually and
set appropriate permissions which might not match the one for the
webroot itself.  (Though in this case I would expect the admin to not
run letsencrypt as root anyway.)

In any case, I would recommend avoiding chmod/chown.  For root, it
should be possible to to switch user with `os.seteuid` and `os.setegid`
and revert to the original user later.  This avoids calling `chmod` and
`chown` which are potentially unsafe to use.

Ansgar

**Comment by lbeltrame** [comment]
This looks a little more complicated than what I expected (FYI, I'm not hacking on letsencrypt, just fixing this bug which had been preventing myself from using it), I'll try to post a WIP PR and hopefully gather some feedback.

**Comment by lbeltrame** [comment]
Also, I think `seteuid` and `setegid` will only work on Linux and UNIX-like OSes, while I expect the letsencrypt client to work also on WIndows on the long term (Can someone from LE confirm this?).

**Comment by aburch** [comment]
Luca Beltrame <notifications@github.com> writes:
> Also, I think `seteuid` and `setegid` will only work on Linux and
> UNIX-like OSes, while I expect the letsencrypt client to work also on
> WIndows on the long term (Can someone from LE confirm this?).

Well, chown/chmod have the same issue.  The Python documentation says
that `os.chown` is only available on Unix; `os.chmod` is also provided
on Windows, but only the read-only flag is supported (mapped to the
owner-write bit as I understand it).

Ansgar

**Comment by lbeltrame** [comment]
I posted an initial version, feel free to give feedback.

**Comment by ZeusF1** [comment]
```
                try:
                    stat_path = os.stat(path)
                    os.chown(self.full_roots[name], stat_path.st_uid,
stat_path.st_gid)
```
Why LE is setting ownership to directories but not files?
@SunMar @lbeltrame 
@aburch @kuba @pde 

I have live case based on Centos6 nginx, python 2.6 environment where directory permissions are set correctly, but files are owned as root, which is causing 403 error.
Here is thread about it:
https://community.letsencrypt.org/t/webroot-plugin-wrong-permission-on-validation-files-nginx-403-error/21728/1

Should I create separate issue?

**Comment by yaccin** [comment]
this seem to be an issue again with certbot 0.14.0
