### ISSUE TITLE
asn1 error trying to obtain a certificate for self-generated CSR

### ISSUE THREAD

**Issue by oleyka** [letsencrypt/letsencrypt#1796]
* FreeBSD 10.2-RELEASE, letsencrypt installed as a py27-letsencrypt package.

* Have a self-generated CSR (using OpenSSL 1.0.1p-freebsd):
```
/usr/bin/openssl req -newkey rsa:2048 -nodes \
-subj "/C=US/ST=California/L=LosAltosHills/O=Self/CN=tools.redpaw.space/subjectAltName=DNS.1=tools.redpaw.space" \
-keyout /etc/ssl/my.key -out /etc/ssl/my.csr
```

* Attempt to obtain a certificate:
```
sudo /usr/local/bin/letsencrypt certonly --standalone \
--standalone-supported-challenges http-01 \
--csr /etc/ssl/my.csr \
--cert-path /etc/ssl/ -t -v --agree-dev-preview --agree-tos
```

Get an error:
```
2015-12-06 22:21:28,590:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-12-06 22:21:28,719:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2015-12-06 22:21:28,942:ERROR:letsencrypt.crypto_util:[('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 225, in _get_sans_from_cert_or_req
    cert_or_req = load_func(typ, cert_or_req_str)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 2380, in load_certificate_request
    _raise_current_error()
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
An unexpected error occurred.
Error: [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
Please see the logfiles in /var/log/letsencrypt for more details.
```

* CSR attached. OpenSSL seems to be happy with it. 
[my.csr](https://github.com/letsencrypt/letsencrypt/files/53315/my.csr.txt)

PS: tried the letsencrypt client-generated CSR and it worked fine in my setup.

**Comment by aburch** [comment]
The letsencrypt client expects the CSR in DER format which is not the default for OpenSSL.  Use "-outform der" when creating the CSR.

I think the client should also accept PEM format as this is the default used by tools like OpenSSL and is also the output format the client uses for the certificates.

**Comment by oleyka** [comment]
aburch, yup, that was it. Additional issue was the missing subjectAlternativeName in the csr. Thank you for your help.

**Comment by osirisinferi** [comment]
In [client.py:245](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/client.py#L245) it's clear the DER format is hardcoded (`OpenSSL.crypto.FILETYPE_ASN1`). Luckily, [crypto_util.get_sans_from_csr](http://letsencrypt.readthedocs.org/en/latest/api/crypto_util.html#letsencrypt.crypto_util.get_sans_from_csr) has an alternative option: `OpenSSL.crypto.FILETYPE_PEM`

Perhaps it's wise to use the OpenSSL defaults (PEM encoding) and add a CLI/configuration file option (--csrformat or something else) to set the DER format?

**Comment by bmw** [comment]
Closing this since it appears the issue has been resolved.

See #1076 and #1082 for issues about the limitations of `--csr`.
