### ISSUE TITLE
webroot-path can't be defined with -w option

### ISSUE THREAD

**Issue by MeKeyCool** [letsencrypt/letsencrypt#1797]
according documentation [https://letsencrypt.readthedocs.org/en/latest/using.html#webroot](https://letsencrypt.readthedocs.org/en/latest/using.html#webroot), we should be able to define webroot path in two ways, using --webroot-path or -w

if i run with --webroot-path everything ok, if i tried with -w like 

>  letsencrypt certonly --renew-by-default --webroot -w /var/www/html -d my.comain.com

I have this error message
> letsencrypt: error: unrecognized arguments: -w /var/www/html

letsencrypt --version
> letsencrypt 0.0.0.dev20151123

I used letsencrypt under a 8.2 debian server and installed it from experimental repositories

**Comment by pde** [comment]
You're reading the docs for version 0.1.0, but are running 0.0.0.dev20151123.  -w was implemented in between.

**Comment by pde** [comment]
0.1.0 is now in experimental I believe.

**Comment by pde** [comment]
there's also a debian package with docs that match your current packages

**Comment by MeKeyCool** [comment]
Ok, sorry for the trouble.
