### ISSUE TITLE
Add an option to use email instead of port knocking.

### ISSUE THREAD

**Issue by espress0** [letsencrypt/letsencrypt#1798]
cron(taskschd)
letsencrypt.exe --cert-only --update-certs (run it every 7 days) ... 1

(only use when first)
letsencrypt.exe --cert-only --domain="freecert.server www.freecert.server" --auth-method=email --admin-email=email2admin@admin.server ... 2

LE server: send an email. email2admin@admin.server
LE server: Lookup WHOIS for freecert.server
LE server: send an email. whoisguarded@admin.server
Admin: Visit activation link 1 and click "I agree".
Admin: Visit activation link 2 and click "I agree".
LE server: domain verified.

client 1: new cert found OR renew ready.
client 1: updating certs.

I don't want LE to modify my config.
I don't want to open port 80.
I want LE to use email authentication like other CAs offer.

**Comment by pde** [comment]
Please take this up on the IETF ACME mailing list, that's where the available Challenges are being defined:

https://www.ietf.org/mailman/listinfo/acme
