### ISSUE TITLE
Don't modify Apache for testing port knock.

### ISSUE THREAD

**Issue by espress0** [letsencrypt/letsencrypt#1799]
Use something like

service apache2 stop
letsencrypt-dummyserver --run --auto-self-kill=600 ;1
service apache2 start
echo "Ready!"

1
Listen to port 443.
Connect to LE server; please-connect-to-me.cgi?randomcode=2746507464527126
LE server connect to 443.
reply from LEs: ok
Close port 443.
Eliminate process.
Exit.

**Comment by pde** [comment]
This is supported.  Just run the client like this:

```
service apache2 stop
letsencrypt --standalone certonly
service apache2 start
```
(where letsencrypt may be `letsencrypt-auto` if your OS doesn't have packages yet).
