### ISSUE TITLE
Custom port for manual mode for reverse-proxy

### ISSUE THREAD

**Issue by Kami-no** [letsencrypt/letsencrypt#1801]
It would be nice to have an ability to change the port in manual mode.

I'm using nginx with rather complex config and don't want let's encrypt client to modify it. I'm interested in  nginx as a reverse proxy for the client:

location ~ ^/(.well-known/acme-challenge/.*)$ {
	proxy_pass		http://192.168.10.104/$1;
	proxy_set_header	X-Real-IP $remote_addr;
	proxy_set_header	Host $http_host;
	proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
}

Now I use docker container but would like to use it native without interference with nginx running at port 80.
From outside it'll be still at port 80 so server-side does not need any changes for that.

**Comment by kuba** [comment]
`--tls-sni-01-port` is the thing you're looking for. [On wiki](https://github.com/letsencrypt/letsencrypt/wiki/Links) you will also find a link to https://coolaj86.com/articles/lets-encrypt-with-haproxy/ - although a bit old, it still uses the same concept.

**Comment by Kami-no** [comment]
I was looking for an option for http port and not https. It's not in wiki or somewhere else. It's in config for renew but I can't find a parameter for that for the first issue.

**Comment by thomas-mc-work** [comment]
This parameter should help: `--http-01-port HTTP01_PORT`
