### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by pavankumarkatakam** [letsencrypt/letsencrypt#1810]
Hi, im creating a website with rancher_server https://github.com/rancher/rancher/ for maintaingin docker containers and im used lets encrypt generated ssl certificates with nginx , but im getting Error when going to domain i registered
    x509: certificate signed by unknown authority

Can anybody help me out of this?

**Comment by schoen** [comment]
Did you include the chain in your server configuration (from `chain.pem` or `fullchain.pem`, as appropriate for your server)? The `cert.pem` alone is not sufficient to convince clients to accept the certificate, without the addition of the chain.

And are you sure that you got the certificate from the production CA and not from the test CA? If you look at the cert with, for example, `openssl x509 -in cert.pem -text -noout`, can you confirm that it's issued by Let's Encrypt and not by the happy hacker fake CA?

**Comment by pde** [comment]
Closing this here.  If you're still stuck, please ask for help on https://community.letsencrypt.org.

**Comment by pavankumarkatakam** [comment]
Yeah, it about fullchain.pem problem solved. Thanks for awesome opensource "LetsEncrypt"

**Comment by gavargas22** [comment]
@pavankumarkatakam Hey there man, how did you manage to solve this problem? Can you remember what you did? I am having an issue with this as well.

Thank you
