### ISSUE TITLE
CentOS 7 install misses python pieces

### ISSUE THREAD

**Issue by sorvani** [letsencrypt/letsencrypt#1823]
I have a [detailed post here](http://mangolassi.it/topic/7127/setting-up-letsencrypt-on-a-centos-7-nginx-proxy) on the issue.

If you are on a clean CentOS 7 minimal install the setup has problems because it does not include `python-tools` and `python-pip`

**Comment by erikrose** [comment]
We'll need to also update the letsencrypt-auto-source/pieces/bootstrappers/.
