### ISSUE TITLE
Move development-environment into a repository of it's own.

### ISSUE THREAD

**Issue by htgoebel** [letsencrypt/letsencrypt#1830]
The current git-repository (and thus the distribution) contains the *complete* test environment, including testing-tools, docker- and vagrant-files, examples, the complete documentation.

**This is contrary to the security best-practice of installing only the minimal requires software on production systems.**

It may even contradict ISO 27002 which recommends separating test and production environment.

**Comment by pde** [comment]
For production environments, you should definitely wait for proper OS packages.  Those are in Debian unstable and Fedora rawhide now, and work is underway to backport them to distributions such as Jessie, Ubuntu 14.04 and RedHat EPEL.

But even when those are available, you should also understand that letsencrypt as a whole and especially the Python client is beta software, and is therefore not yet appropriate for use on production systems.  By all means commence testing and integration work, but don't expect anything to be mature yet.
