### ISSUE TITLE
letsencrypt is currently unusable with dynamic DNS

### ISSUE THREAD

**Issue by discoHR** [letsencrypt/letsencrypt#1834]
Yesterday I've tried to generate cert for disco.homenet.org and got the following error:
>There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: homenet.org

I thought it's because homenet.org is not in the Public Suffix list so today I tried it with disco.myds.me (myds.me IS in the public suffix list) and got practically the same error:
>There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: myds.me

Now what?

**Comment by patf** [comment]
Please refer to this post:
https://community.letsencrypt.org/t/please-update-the-public-suffix-on-the-acme-server/6021/2?u=pfg

(tl;dr: myds.me was only added recently; public suffix list isn't updated instantly.)

**Comment by discoHR** [comment]
Makes sense, thanks.
