### ISSUE TITLE
Letsencrypt --help asks for root

### ISSUE THREAD

**Issue by d33tah** [letsencrypt/letsencrypt#1838]
```
$ ./letsencrypt-auto --help
Bootstrapping dependencies for RedHat-based OSes...
[sudo] password d33tah@d33tah-pc:
```

**Comment by pde** [comment]
It's going to be tricky to fix this without breaking the design constraints of letsencrypt-auto, which are:
* it's a wrapper script that's a temporary stopgap before native packages are available on your OS
* it should accept the exact same flags as the the true `letsencrypt` and wrap it transparently

For instance, we could have `letsencrypt-auto --help` baked into the script.  But what if the user types `letsencrypt-auto --help certonly`?  They still won't expect installation as a side effect, but it will be necessary.

Perhaps we can adjust the docs to not suggest `letsencrypt-auto --help` as a first command or something, and find some other first-run command that is free of consequences but connotes installation.

**Comment by bmw** [comment]
Closing as a more specific instance of #1829.
