### ISSUE TITLE
Question: How are you getting detailed error messages?

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/letsencrypt#1855]
**Question**:

How is the python client getting such detailed error messages to deliver to the user?

Is it the error that's coming back in the http response, or is it extrapolated from a code number?

I just figured it would be easier to ask some people that know and can answer quickly rather than grep around the code for hours myself.

**Background**:

I had a misconfiguration with my DNS server which was prevented validation.

I first tried using Caddy (an LE client written in go, uses lego) which gave me this:

```
2015/12/06 03:51:44 [blog.coolaj86.com] failed to get certificate: The server could not validate our request.
```

I thought that perhaps the Caddy implementation was simply incomplete, so then I tried letsencrypt's own python client and got this:

```
Failed authorization procedure. blog.coolaj86.com (tls-sni-01): urn:acme:error:unknownHost :: The server could not resolve a domain name :: No IPv4 addresses found for blog.coolaj86.com
```

Over at Caddy Matt I filed an issue "ambiguous error message" (https://github.com/mholt/caddy/issues/393) and he says that all they're seeing is an `invalid` in the response from boulder, so they don't want what error message to give back.

Also following up with lego at https://github.com/xenolf/lego/issues/49

**Comment by bmw** [comment]
The error is coming back in the body of the HTTP response as described [here](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-5.4).

Closing, but feel free to follow up if you have more questions.
