### ISSUE TITLE
How to renew certificate use the config file in /etc/letsencrypt/renewal

### ISSUE THREAD

**Issue by kuoruan** [letsencrypt/letsencrypt#1862]
I want to renew my certificate, and I find a conf file in /etc/letsencrypt/renewal, how to use the conf to renew my certificate? Thinks!

**Comment by pde** [comment]
That file isn't ready for use yet, but in the future, you will be able to run renewer.py to work with it.

**Comment by pde** [comment]
If you want to arrange renewal in the mean time, find a `letsencrypt certonly` command that works for you, script that followed by reloading your webserver.
