### ISSUE TITLE
Won't accept email

### ISSUE THREAD

**Issue by EvanCarroll** [letsencrypt/letsencrypt#1865]
When I run `letsencrypt-auto certonly` it asks for my email, however it won't accept it. My email address is me <at> evancarroll dot com.

**Comment by pde** [comment]
What error did you get?  I can't reproduce your problem.

**Comment by frankf-cgn** [comment]
Might it be that there is no A Record for the domain of the email-address? Test it with `ping  evancarroll dot com`. If this is the case look aorund here in the issues, as far as I understand the lets encrypt team is working on this. Until a proper fix is published, you might simply add an A record for the domain.

**Comment by EvanCarroll** [comment]
This is definitely what happened then. There was a time when my domain had no A Record. What an obtuse error. Do you have a link to the bug report? @frankf-cgn

**Comment by devster31** [comment]
letsencrypt/boulder#1197 I believe it is

**Comment by pde** [comment]
Closing this ticket since this isn't a client bug.
