### ISSUE TITLE
webroot broken on ubuntu 10.04

### ISSUE THREAD

**Issue by ProfMerlin** [letsencrypt/letsencrypt#1866]
Hi

Installed certificates on 2 machines without any issue, but trying to install on ubuntu 10.04 with the command `./letsencrypt-auto certonly --standalone -d <domain> --debug` returns the error:
An unexpected error occurred:
KeyError: 'webroot'

The error log:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/cli.py", line 1237, in main
    args = prepare_and_parse_args(plugins, cli_args)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/cli.py", line 957, in prepare_and_parse_args
    _plugins_parsing(helpful, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/cli.py", line 1080, in _plugins_parsing
    help="public_html / webroot path. This can be specified multiple times to "
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/cli.py", line 754, in add
    if self.visible_topics[topic]:
KeyError: 'webroot'

**Comment by nextgenthemes** [comment]
End of life for version 10.04 has passed. Letsencrypt should not support such outdated software IMO.

https://wiki.ubuntu.com/Releases
May 9, 2013 (Desktop)
April 30, 2015 (Server)

Mind telling me why your server runs on 10.04?

**Comment by pde** [comment]
We don't officially support Ubuntu 10.04, and strongly recommend against using it, but errors are always interesting from a code robustness perspective.

The problem is that (1) something on your system is causing the webroot plugin to be totally unavailable, and (2) the implementation of `-w` / `--webroot-path` in cli.py assumes that the webroot is always available.  Can you add `-vv` to that command line and tell us what errors you hit?

**Comment by ProfMerlin** [comment]
Hi.

Sadly the site that is running on 10.04 cannot be migrated to a newer version of ubuntu due to the dependencies that do not run on 12.04 or above. We only have 1 or 2 of these boxes left. 

I understand that the OS is old, and not supported anymore. If you do not want to support it, I do understand. I was also posting so that you are aware of it

Below output when run with `-vv`:
./letsencrypt-auto certonly --standalone -d m.lifestylesa.co.za --debug -vv
-vv
Updating letsencrypt and virtual environment dependencies...
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
Collecting setuptools
  Downloading setuptools-18.8-py2.py3-none-any.whl (463kB)
    100% |████████████████████████████████| 466kB 1.1MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 18.7.1
    Uninstalling setuptools-18.7.1:
      Successfully uninstalled setuptools-18.7.1
Successfully installed setuptools-18.8
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
Requirement already up-to-date: pip in /root/.local/share/letsencrypt/lib/python2.6/site-packages/pip-7.1.2-py2.6.egg
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
Requirement already up-to-date: letsencrypt in /root/.local/share/letsencrypt/lib/python2.6/site-packages
Requirement already up-to-date: letsencrypt-apache in /root/.local/share/letsencrypt/lib/python2.6/site-packages
Collecting ConfigArgParse from git+https://github.com/kuba/ConfigArgParse.git@python2.6-0.9.3#egg=ConfigArgParse (from -r ./py26reqs.txt (line 1))
  Cloning https://github.com/kuba/ConfigArgParse.git (to python2.6-0.9.3) to /tmp/pip-build-PSApmJ/ConfigArgParse
Requirement already up-to-date: acme==0.1.0 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: setuptools in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: python2-pythondialog>=3.2.2rc1 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: PyOpenSSL in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: requests in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: parsedatetime in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: configobj in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: pytz in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: psutil>=2.1.0 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: six in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: cryptography>=0.7 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: zope.interface in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: zope.component in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: mock in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: pyrfc3339 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt)
Requirement already up-to-date: python-augeas in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from letsencrypt-apache)
Requirement already up-to-date: argparse in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from ConfigArgParse->-r ./py26reqs.txt (line 1))
Requirement already up-to-date: ordereddict in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from ConfigArgParse->-r ./py26reqs.txt (line 1))
Requirement already up-to-date: unittest2 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from ConfigArgParse->-r ./py26reqs.txt (line 1))
Requirement already up-to-date: pyasn1 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from acme==0.1.0->letsencrypt)
Requirement already up-to-date: ndg-httpsclient in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from acme==0.1.0->letsencrypt)
Requirement already up-to-date: werkzeug in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from acme==0.1.0->letsencrypt)
Requirement already up-to-date: idna>=2.0 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: enum34 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: ipaddress in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: cffi>=1.1.0 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: zope.event in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from zope.component->letsencrypt)
Requirement already up-to-date: funcsigs in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pbr>=0.11 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from mock->letsencrypt)
Requirement already up-to-date: traceback2 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from unittest2->ConfigArgParse->-r ./py26reqs.txt (line 1))
Requirement already up-to-date: pycparser in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
Requirement already up-to-date: linecache2 in /root/.local/share/letsencrypt/lib/python2.6/site-packages (from traceback2->unittest2->ConfigArgParse->-r ./py26reqs.txt (line 1))
Installing collected packages: ConfigArgParse
  Found existing installation: ConfigArgParse 0.10.0
    Uninstalling ConfigArgParse-0.10.0:
      Successfully uninstalled ConfigArgParse-0.10.0
  Running setup.py install for ConfigArgParse
Successfully installed ConfigArgParse-0.9.3
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly --standalone -d m.lifestylesa.co.za --debug -vv
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
An unexpected error occurred:
KeyError: 'webroot'
Please see the logfile 'letsencrypt.log' for more details.

**Comment by pde** [comment]
OK, I'm not seeing anything very enlightening there. Maybe more verbosity (-vvvv) or looking in the log would get us the actual Python traceback.

Meanwhile, you might be able to hack your way past the problem by [following the developer instructions](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client) and then commenting out the two [webroot-related command line flags](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L1091) from cli.py.

**Comment by ProfMerlin** [comment]
I am closing this issue since adding more verbosity gives no information. The traceback was posted in the original post, but does also not give any interesting information. 

I understand that this is not supported on 10.04
