### ISSUE TITLE
--help output says --apache-dismod seeks a2enmod

### ISSUE THREAD

**Issue by jaylett** [letsencrypt/letsencrypt#1867]
```
  --apache-dismod APACHE_DISMOD
                        Path to the Apache 'a2enmod' binary. (default:
                        a2dismod)
```

Should be `Path to the Apache 'a2dismod' binary…`?

**Comment by joohoi** [comment]
This is fixed in master since yesterday.

**Comment by jaylett** [comment]
Weird; a fresh clone and -auto run just now displays this problem, even though the code in `letencrypt-apache/letencrypt_apache/configurator.py` looks good at first blush. Looking closer, I'm at 8c6e242b13ac818c0a94e3dceee81ab4b3816a12, which is the commit that claims to fix this. And yet:

```
# ./letsencrypt-auto -h all | grep a2.*mod
                        Path to the Apache 'a2enmod' binary. (default:
                        a2enmod)
                        Path to the Apache 'a2enmod' binary. (default:
                        a2dismod)
```

**Comment by joohoi** [comment]
Ah, letsencrypt-auto must have left its virtualenv behind (with the old version of the apache plugin itself), the virtualenv resides in ~/.local/share/letsencrypt/ and it's safe to remove that directory and let the letsencrypt-auto rebuild it.

**Comment by jaylett** [comment]
That doesn't really make sense; the clone and install happened in the last few hours, considerably after the PR merge to master. In any case, killing the virtualenv and trying again gets the same result.

**Comment by jaylett** [comment]
Oh, is the problem that it's installing from pypi or something and there hasn't been a new release? Rather than doing a direct install-to-venv from source.

**Comment by joohoi** [comment]
Check out: https://letsencrypt.readthedocs.org/en/latest/using.html#from-source

**Comment by jaylett** [comment]
Okay, so the "clone-and-auto" doesn't use most of the source it clones. Fine to close this issue once a new release of `letsencrypt-apache` is made.
