### ISSUE TITLE
Let's Encrypt fails when upgraded, virtual environment is not updated correctly

### ISSUE THREAD

**Issue by TheNavigat** [letsencrypt/letsencrypt#1885]
```
#!/Users/nav/Documents/letsencrypt/venv/bin/python2.7
# EASY-INSTALL-ENTRY-SCRIPT: 'letsencrypt==0.1.0.dev0','console_scripts','letsencrypt'
__requires__ = 'letsencrypt==0.2.0.dev0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('letsencrypt==0.2.0.dev0', 'console_scripts', 'letsencrypt')()
    )
```

That is the content of ```venv/bin/letsencrypt```. Apparently, that fails, because the current version of Let's Encrypt is 0.2.0.dev0 and not 0.1.0.dev0.

The file is generated using ```letsencrypt-auto``` and not included in the repo.

**Comment by KeiroD** [comment]
Try a `git pull` to pull in an updated copy of `letsencrypt-auto`?

**Comment by TheNavigat** [comment]
While ```letsencrypt-auto``` works, running ```letsencrypt``` fails, actually.

**Comment by TheNavigat** [comment]
It looks like ```letsencrypt-auto``` runs a different ```letsencrypt``` file from the one ran while using the virtual environment. The one ```letsencrypt-auto``` runs is in ```/Users/nav/.local/share/letsencrypt/bin/letsencrypt```. The other file that doesn't work is inside ```venv/bin``` inside the repo's directory.

Not sure if that should be expected, but since running ```letsencrypt``` while using the virtual environment fails, I think it shouldn't.

**Comment by pde** [comment]
The one in ~/local/share/letsencrypt/ is the latest release, fetched by letsencrypt-auto.  The one in venv/ is a live copy of whatever is in your git repo.

**Comment by TheNavigat** [comment]
Which is generated by ```./bootstrap/dev/venv.sh```. Shouldn't be something to indicate that the one in ```venv/``` is outdated, or am I (which is the more probably thing) misunderstanding something?
