### ISSUE TITLE
Make dependency on a2enmod & a2dismod optional

### ISSUE THREAD

**Issue by osirisinferi** [letsencrypt/letsencrypt#1896]
At the moment, the client makes use of a2enmod and a2dismod for enabling some mods in [configurator.py](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L140). But these scripts are [Debian (based distro's) only](http://manpages.debian.org/cgi-bin/man.cgi?query=a2dismod). At least: those scripts are unavailable on Gentoo.

Therefore, the Apache plugin is unavailable too.

It's not unlikely the required mods are already enabled on the server. As far as I can tell, Let's Encrypt just enables [mod_ssl](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L544), [mod_headers](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L820) and [mod_rewrite](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L890). But perhaps I'm missing something :neutral_face: 

Those are not very uncommon modules at all if I'm not mistaken. I would very much like to see some kind of check: if the required modules are already properly enabled, then the dependency on a2enmod and a2dismod could be dropped.

**Comment by joohoi** [comment]
This will be fixed by #1811 if it gets merged.

**Comment by osirisinferi** [comment]
Kudo's to you @joohoi, stupid of me to miss that PR! Thanks in advance!

**Comment by osirisinferi** [comment]
By the way, I'm seeing: "(...) still missing gentoo fingerprint though"? Can I be of assistance as I'm running a Gentoo server?

**Comment by joohoi** [comment]
You can! 

What I need is output from:
```
python -c "import platform;print(platform.system_alias(platform.system(), platform.release(), platform.version()))"
```
When ran on Gentoo box.

**Comment by osirisinferi** [comment]
Sure, no problem:

    osiris@server ~ $ python -c "import platform;print(platform.system_alias(platform.system(), platform.release(), platform.version()))"
    ('Linux', '4.0.5-gentoo', '#2 SMP Thu Aug 27 16:33:32 CEST 2015')
    osiris@server ~ $

But I think the `-gentoo` part isn't quite fixed, as it's very well possible to use vanilla kernels on Gentoo instead of the [gentoo patched versions](https://packages.gentoo.org/packages/sys-kernel/gentoo-sources). :neutral_face:

**Comment by joohoi** [comment]
I'd prefer closing the issue and continuing the discussion in the PR #1811 . We may need to look into other ways of OS fingerprinting, but that's completely out of scope of this issue ticket.

**Comment by osirisinferi** [comment]
No problem, I'll paste the output in the PR too, so it doesn't get lost :stuck_out_tongue:
