### ISSUE TITLE
Print no changes message when cert isn't renewed and --keep-until-expiring is used

### ISSUE THREAD

**Issue by kyl191** [letsencrypt/letsencrypt#1918]
If I re-run letsencrypt-auto for an existing cert that isn't up for renewal yet, and I specify --keep-until-expiring, letsencrypt terminates with just the donate message:
```
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly --webroot -w /var/www/test.net/ -d test.net -c /etc/letsencrypt/cli.ini --keep-until-expiring --server https://acme-staging.api.letsencrypt.org/directory
IMPORTANT NOTES:
 - If you like Let's Encrypt, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```
Printing a "No changes made; certificate not renewed" would be helpful from a user interaction perspective

**Comment by ametad** [comment]
Would be helpful indeed!

**Comment by noniq** [comment]
I’d really like to have this, too. Even better: A `--quiet` option that also supresses the “Updating letsencrypt …” and “Running with virtualenv …” messages. So the script would produce output only if a certificate was renewed or something went wrong. This would be very helpful for running the script via cron to automate the renewal process.

**Comment by pde** [comment]
In theory you should be able to suppress stdout, and look only at stderr and return values for signs of trouble.

**Comment by pde** [comment]
We'll probably use --quiet or -q as the trigger, so you can do `letsencrypt -nq` to get non-interactive, quiet operation.

**Comment by pde** [comment]
For the 0.4.0 renewal release, we're going to work around this by using [scripts like this](https://letsencrypt.org/howitworks/#writing-your-own-renewal-script).

**Comment by pde** [comment]
Actually I'm going to open a different ticket for that...
