### ISSUE TITLE
remove python-ndg-httpsclient dependency on modern Python platforms

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1926]
If the available python platform supports secure TLS connections natively, we don't need to depend on `python-ndg-httpsclient`.

**Comment by pde** [comment]
Closed by #1914

**Comment by pde** [comment]
Reopening since we reverted those changes; however #2177 may be a satisfactory PR for this.

**Comment by erikrose** [comment]
I believe we decided to minimize or eliminate conditional dependencies, and #2177 is merged, so we should be able to close this.
