### ISSUE TITLE
Allow specifying an explicit vhost file for Apache

### ISSUE THREAD

**Issue by dantman** [letsencrypt/letsencrypt#1944]
My `/etc/apache2` config is ephemeral. I puppetize anything I need to be there. And my vhosts are located in a `/web/apache.d` folder that is part of an EBS volume I keep when I destroy and recreate the rest of the server.

For anyone that has a similar setup or any other config that keeps their vhost config separate. It would be worthwhile to have options to explicitly specify the path to the vhost file and maybe the le-vhost file as well.

**Comment by joohoi** [comment]
This will be remedied by #1811 which is on roadmap for next release. It will let you define your vhost conf path and also the LE created file extension.

**Comment by pde** [comment]
Fixed by #1811
