### ISSUE TITLE
Test the renewer in integration tests

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1950]
Currently, integration tests run `letsencrypt-renewer` but they currently don't test anything other than making sure the renewer doesn't error out. The comment [here](https://github.com/letsencrypt/letsencrypt/blob/master/tests/boulder-integration.sh#L59) says this is because the renewer fails the test which is at least partially due to #1949.

**Comment by bmw** [comment]
`s/letsencrypt-renewer/letsencrypt renew/`

**Comment by pde** [comment]
Closed by #2404.
