### ISSUE TITLE
-bash: ./letsencrypt: Is a directory

### ISSUE THREAD

**Issue by a1exus** [letsencrypt/letsencrypt#1951]
I'm trying follow [User Guide — Let's Encrypt 0.2.0.dev0 documentation](https://letsencrypt.readthedocs.org/en/latest/using.html#manual) (plugin:manual), yet I'm getting following while trying to run `./letsencrypt`:

```
[alexus@j ~/letsencrypt]$ git pull
Already up-to-date.
[alexus@j ~/letsencrypt]$ ./letsencrypt
-bash: ./letsencrypt: Is a directory
[alexus@j ~/letsencrypt]$ uname -a
FreeBSD X 9.2-RELEASE-p17 FreeBSD 9.2-RELEASE-p17 #0 r282430: Mon May  4 13:59:58 PDT 2015     root@X:/usr/obj/usr/src/sys/R610  amd64
[alexus@j ~/letsencrypt]$ 
```

please advise.

**Comment by donovancade** [comment]
That is correct, letsencrypt is a directory.  I think you want to be using:
./letsencrypt-auto

From the User Guide:
**Throughout the documentation, whenever you see references to letsencrypt script/binary, you can substitute in letsencrypt-auto**

**Comment by a1exus** [comment]
even for manual plugin?

**Comment by bmw** [comment]
Yes. `letsencrypt-auto` automatically installs and runs `letsencrypt`, but allows you to run whatever plugins you want (including `manual`).

Using `letsencrypt-auto` is the recommended installation method, but you can find alternatives [here](https://letsencrypt.readthedocs.org/en/latest/using.html#other-methods-of-installation).
