### ISSUE TITLE
why func in renewal/:hostname.conf?

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/letsencrypt#1955]
I see this line in `renewal.conf`:

```
func = <function obtain_cert at 0x30c9500>
```

I just want to make sure that's leftover debugging junk and not something used by the client.

I'm working on a [node.js letsencrypt client](https://github.com/Daplie/node-letsencrypt-cli) and I'm trying to make sure that my config file is as exactly compatible with the python as possible.

Obviously that's not portable and there's nothing I can do about it, but as long as the python client doesn't actually use it there's not a problem. Otherwise I'd like to file a bug on it and see if it can be represented in some other way.

**Comment by bmw** [comment]
These renewal config files are for `letsencrypt-renewer` which is still under development. These config files will likely change in the near future so please keep this in mind when developing your client.

With that said, we will not use the value of `func` now or in the future.
