### ISSUE TITLE
[Question] Shared VPS hosting security problem

### ISSUE THREAD

**Issue by ThePixelPony** [letsencrypt/letsencrypt#1956]
Suppose that I assign an A record to my VPS and then get rid of the VPS.

The next person to get that IP can get a certificate for my domain, right?

Are there any measures to prevent issues like this?

**Comment by KeiroD** [comment]
No. IP doesn't matter. What matters is when `letsencrypt-auto` verifies you own the domain. It does this by way of using the `challenge` protocol outlined elsewhere.

This is why you're required to use several different plugins, such as `standalone`, `certonly`, `apache2` and so on.

They verify you actually own the domain. Hence, `Domain Validated` certs.
