### ISSUE TITLE
Apache plugin error -- syntax error in configuration file

### ISSUE THREAD

**Issue by jeremiah** [letsencrypt/letsencrypt#1960]
Hi,

I'm getting this error message;

"The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/jeremiahfoster.com.conf', u'Syntax error'),)"

In the file mentioned, there is a second <IfModule> rule. This one contains; 

    <IfModule mod_rewrite.c>
     RewriteEngine On
     RewriteCond %{REQUEST_URI} ^.*(,|;|:|<|>|">|"<|/|\\\.\.\\).* [NC,OR]
     RewriteCond %{REQUEST_URI} ^.*(\=|\@|\[|\]|\^|\`|\{|\}|\~).* [NC,OR]
     RewriteCond %{REQUEST_URI} ^.*(\'|%0A|%0D|%27|%3C|%3E|%00).* [NC]
     RewriteRule ^(.*)$ - [F,L]
    </IfModule>`

When I remove that rule, the parse error disappears and letsencrypt runs to completion.

**Comment by pde** [comment]
@domcleal this looks like an augeas issue.

**Comment by domcleal** [comment]
This is fixed by the same patch as #1934, but I've added a new test for it over in #1990 to make sure it stays fixed.

(I'm assuming the backtick after the closing IfModule section is a Markdown typo.)

**Comment by jeremiah** [comment]
Yes, you're right about the backtick, good catch and my apologies. 

I'll close this and update or use the patch.
