### ISSUE TITLE
the procedure stop but has no error in the centos7 x64

### ISSUE THREAD

**Issue by hiproz** [letsencrypt/letsencrypt#1964]
i clone code today ,use the letsencrypt-auto as the manual. it will stop with nothing error: 

Creating virtual environment...
Updating letsencrypt and virtual environment dependencies...

can anyone tell me how to check the error log? or it is a bug?

**Comment by bmw** [comment]
Add `-v` or `--verbose` to the command line to see more information.

**Comment by hiproz** [comment]
Updating letsencrypt and virtual environment dependencies...
Cannot fetch index base URL https://pypi.python.org/simple/
Could not find any downloads that satisfy the requirement setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Downloading/unpacking setuptools
Cleaning up...
No distributions at all found for setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Storing complete log in /root/.pip/pip.log

**Comment by bmw** [comment]
Are you still having trouble with this? If so, I recommend doing a `git pull` so you have the latest version of `letsencrypt-auto`, deleting the folder `/root/.local/share/letsencrypt`, and running the client again.

If this fails, can you include the output from running `./root/.local/share/letsencrypt/bin/pip freeze`?

**Comment by hiproz** [comment]
yes ,failed still, and:
/root/.local/share/letsencrypt/bin/pip freeze
wsgiref==0.1.2

**Comment by hiproz** [comment]
thank you very much @bmw 
i have resolved the issue ,the reason is : Cannot fetch index base URL https://pypi.python.org/simple/
my server cant get the https pip source. i change another https source .it works.

thanks you!
