### ISSUE TITLE
letsencrypt-0.1.1 but it requires acme=0.2.0.dev0

### ISSUE THREAD

**Issue by willysr** [letsencrypt/letsencrypt#1966]
Hi

It seems in letsencrypt-0.1.1, you missed this file
"letsencrypt/__ init __ .py" (i added space otherwise it will be edited by the editor)

it still point to 0.2.0.dev0
i suggest to make a quick release of 0.1.2 to fix this problem as the problem will not be spotted until the client runs letsencrypt command

**Comment by kuba** [comment]
Tarball from PyPI seems to have correct version string (https://pypi.python.org/packages/source/l/letsencrypt/letsencrypt-0.1.1.tar.gz#md5=ddd393563f3d5835d678b7478148e3d9). However, https://github.com/letsencrypt/letsencrypt/blob/v0.1.1/letsencrypt/__init__.py is wrong, which suggests that wrong commit has been tagged.

**Comment by willysr** [comment]
Yes, i used the one from github since it contains all the code, not just the acme protocol

**Comment by pde** [comment]
Looks like the bug is that the release scripts [set the version correctly](https://github.com/letsencrypt/letsencrypt/blob/master/tools/release.sh#L87) but [fail to stage that file](https://github.com/letsencrypt/letsencrypt/blob/master/tools/release.sh#L89) for committing and tagging.

**Comment by willysr** [comment]
good thing it can be found and hopefully gets fixed for the next round of release
