### ISSUE TITLE
add pypi metadata to setup.py, fix license there

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/letsencrypt#198]
plus some other things, just build a pypi package and look into its metadata. "UNDEFINED".

i suggest to put some of that stuff into `letsencrypt/__init__.py` and read the metadata from there as we'll soon do with `__version__`.

**Comment by ThomasWaldmann** [comment]
author: ?
author_email: ?
summary: ?
license: Apache License 2.0
platform: ?
classifiers:

https://pypi.python.org/pypi?%3Aaction=list_classifiers <--- choose some

**Comment by kuba** [comment]
I'd say...

author: "Let's Encrypt Project" (with #211)

Trove classifiers:
- Environment :: Console
- Environment :: Console :: Curses
- Intended Audience :: System Administrators
- License :: OSI Approved :: Apache Software License
- Operating System :: POSIX :: Linux
- Programming Language :: Python
- Programming Language :: Python :: 2
- Programming Language :: Python :: 2.6
- Programming Language :: Python :: 2.7
- Topic :: Internet :: WWW/HTTP
- Topic :: Security
- Topic :: System :: Installation/Setup
- Topic :: System :: Networking
- Topic :: System :: Systems Administration
- Topic :: Utilities

**Comment by ThomasWaldmann** [comment]
btw, iirc author_email is required for pypi. so think about which email address you want there.
I'ld suggest to give a generic email address (like info@letsencrypt.org or pypi@...).

**Comment by kuba** [comment]
Trove classifiers added in 6166255.

@jdkasten, how about client-dev@letsencrypt.org for email?

**Comment by kuba** [comment]
```
$ python setup.py check
running check
warning: check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too

```
