### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by penn5** [letsencrypt/letsencrypt#1982]
I am using a raspi model a to run a web server and i am getting insecureplatformwarning (docs at https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) I hope the setup will work but it could just be that warnings need disabling as shown in the docs

**Comment by pde** [comment]
The warning is due to the fact that your OS's version of virtualenv cannot install things securely. We're working on a fix for this in 0.2.0.

**Comment by BurakDev** [comment]
Same on Debian 7.

**Comment by jeyemwey** [comment]
Having that too.. Ubuntu 14.04..

**Comment by evilaliv3** [comment]
duplicated of https://github.com/letsencrypt/letsencrypt/issues/1982, this could be closed.

**Comment by jeyemwey** [comment]
@evilaliv3 I feel like being in an infinite loop, it's a glitch in the matrix!

**Comment by shakaran** [comment]
In CentOs 6.7 with cPanel I am getting similar warnings for Python 2.6 using the --debug flag for apache, it shows:

	Creating virtual environment...
	Updating letsencrypt and virtual environment dependencies...../root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
	  InsecurePlatformWarning
	/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
	  InsecurePlatformWarning
	./root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
	  DeprecationWarning
	/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
	  DeprecationWarning

	Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --apache --debug
	/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
	  DeprecationWarning
	Version: 1.1-20080819
	Version: 1.1-20080819
	/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/cli.py:550: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
	  return e.message
	The apache plugin is not working; there may be problems with your existing configuration.
	The error was: NoInstallationError()

**Comment by bmw** [comment]
Closing in favor of #1883.
