### ISSUE TITLE
letsencrypt-auto option --release=v0.1.0

### ISSUE THREAD

**Issue by ajaegers** [letsencrypt/letsencrypt#1983]
Hello,

It seems that letsencrypt-auto update himself to the latest release of source files.

Is there a way to use letsencrypt-auto without automatic update to the latest version? 

If not, it will be great to have an option like `--release` with values release name found on https://github.com/letsencrypt/letsencrypt/releases and default `auto`.

Thanks,

Arnaud

**Comment by pde** [comment]
At least disabling auto-updates will be supported by the next version of letsencrypt-auto (See #1665)

**Comment by ajaegers** [comment]
Ok thanks for the information.
