### ISSUE TITLE
Could not issue certificate for IP address

### ISSUE THREAD

**Issue by pavel-odintsov** [letsencrypt/letsencrypt#1985]
Hello!

We have big amount of customers with our own custom server management toolkit. For security reasons we are not using hostnames and use main server IP as web panel address.

And we want to issues certificates for IP itself.

We tried to do it with Letsencrypt but haven't any success here:
```bash
The request message was malformed :: Error creating new authz :: Issuance for IP addresses not supported
```

Could you add support for certificates issues for IP addresses?

**Comment by BurakDev** [comment]
Hello, is possible ? :scream:

**Comment by pde** [comment]
This is currently not supported by the Let's Encrypt CA, so the client can't support it.  Feel free to continue the conversation here:

https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082

**Comment by xiaohuilam** [comment]
Yes, you can't apply letsencrypt cert for a IP address event it's a public.
You can search on google "SSL for IP Address" , maybe not free.
