### ISSUE TITLE
When installing a cert for a system that only has a *:80 model vhost, add ServerName / ServerAlias to the new vhost

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1991]
The failure to do this is one of the major reasons we hit the "please tell me which vhost to install on" dialog that underlies #1944 and other issues.

**Comment by SwartzCr** [comment]
Fix should be live in #2286 with tests passing, probably still needs some farm testing or personal vm testing.
No new tests were written for it, which I'd be happy to do before a merge

**Comment by bmw** [comment]
Fixed in #2286.
