### ISSUE TITLE
firefox do not trust my ssl certificate

### ISSUE THREAD

**Issue by zhenfdfs** [letsencrypt/letsencrypt#1993]
![qq 20151223110803](https://cloud.githubusercontent.com/assets/6366234/11970429/db5d7bdc-a965-11e5-904b-6486e3a8ec6a.png)

**Comment by zhenfdfs** [comment]
chrome and ie is ok

**Comment by pde** [comment]
Probably you have not configured the chain / intermediate certificates correctly.

Use https://www.ssllabs.com/ssltest/analyze.html to test whether you have this correct.

**Comment by pde** [comment]
(Please reopen if that is not the problem)
