### ISSUE TITLE
the apache plugin adds an unconditional redirect inside the :443 vhost

### ISSUE THREAD

**Issue by timir** [letsencrypt/letsencrypt#1996]
The apache plugin adds an unconditional redirect inside the :443 vhost

I had to comment out these lines or else the webaddress just kept looping

RewriteEngine on
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,QSA,R=permanent]

**Comment by bmw** [comment]
I personally haven't been following this issue closely, but do you have any thoughts @sagi?

**Comment by pde** [comment]
What version of Apache are you running @timir?

**Comment by timir** [comment]
Server version: Apache/2.4.10 (Debian)

**Comment by sagi** [comment]
@timir, did you have a http (:80)  vhost prior to configuring with letsencrypt ?

**Comment by timir** [comment]
Yeah, I did have a http(:80) vhost conf file prior to configuring with letsencrypt.

**Comment by sagi** [comment]
I'm on it.

**Comment by sagi** [comment]
@timir uses 2.4, and for apache versions greater than 2.3.9  we don't use the L flag, but the END flag. 
Id est, @timir probably used an older version of letsencrypt. 

It seems that @timir's client returns a `ssl_vhost` when executing `self._get_http_vhost(ssl_vhost)` (and not a general http vhost). 

Unfortunately, I can't reproduce the scenario. 

@timir, if it is not too demanding, can you please elaborate more on the prior states of both http and https vhosts? (The best thing would be to have the actual vhosts prior to configuring with letsencrypt, but it is probable you don't have them anymore)

**Comment by timir** [comment]
@sagi the original vhost conf file can be seen on this pastie http://pastie.org/10659144

after running letsencrypt it creates another vhost file with a name like somedomain-le-ssl.conf
http://pastie.org/10659148

**Comment by pseudo2** [comment]
thanks @timir! I've been able to reproduce the scenario. It occurs on an edge case - there exists a http vhost for a domain with a redirection rewriterule and a ssl vhost, for the same domain, doesn't exist. Then the client creates a new ssl vhost and mistakenly puts a redirection rewriterule. 

Btw, the reason the `L` flag is there and not the `END` flag is - `letsencrypt-auto` uses `pip install letsencrypt`  which is letsencrypt 0.1.1.

**Comment by sagi** [comment]
thanks @timir! I've been able to reproduce the scenario. It occurs on an edge case - there exists a http vhost for a domain with a redirection rewriterule and a ssl vhost, for the same domain, doesn't exist. Then the client creates a new ssl vhost and mistakenly puts a redirection rewriterule.

Btw, the reason the `L` flag is there and not the `END` flag is - `letsencrypt-auto` uses `pip install letsencrypt` which is letsencrypt 0.1.1.

**Comment by sagi** [comment]
After some debugging I found the problem - it's not the `redirection enhancement` but the `_copy_create_ssl_vhost_skeleton` function. When no ssl vhost present it just copies everything from the `http vhost` to the newly created `ssl vhost`.
