### ISSUE TITLE
letsencrypt.validator.Validator is dead code. Remove it as well as its dependencies.

### ISSUE THREAD

**Issue by Natim** [letsencrypt/letsencrypt#1997]
As per https://github.com/letsencrypt/letsencrypt/pull/1914#discussion_r48341824

**Comment by kuba** [comment]
```
jakub@iks:~/dev/letsencrypt/letsencrypt$ git grep 'from letsencrypt import validator'
letsencrypt-compatibility-test/letsencrypt_compatibility_test/test_driver.py:from letsencrypt import validator
letsencrypt/tests/validator_test.py:from letsencrypt import validator
```

So it seems like `letsencrypt-compatibility-test` is still using that. In turn, I'm not sure if that package is still in use.

**Comment by Natim** [comment]
Yes it is what I was going to ask :)

**Comment by Natim** [comment]
Apparently it is used to test plugins:

> Tests Let's Encrypt plugins against different server configuratons. It is
> assumed that Docker is already installed. If no test types is specified, all
> tests that the plugin supports are performed.

**Comment by Natim** [comment]
Should we move the validator code in here?

**Comment by bmw** [comment]
I think moving the code into `letsencrypt-compatibility-test`, at least for now, makes sense.

**Comment by pde** [comment]
Yes @Natim, we'd love a PR for that.  What dependencies would it free us from?

**Comment by Natim** [comment]
Apparently requests as well as l the one for secure SSL connection with
python < 2.7.9

**Comment by Natim** [comment]
Tentative of fixing this here: https://github.com/letsencrypt/letsencrypt/pull/2007

**Comment by pde** [comment]
Thanks @Natim !
