### ISSUE TITLE
RenewableCert should verify symlinks and targets

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2000]
In `letsencrypt.storage.RenewableCert.__init__`, we should verify that all symlinks and their targets exist after calling `_fix_symlinks`. If they do not, we should raise an exception to prevent problems like the one identified in #1959 from occurring.

**Comment by cowlicks** [comment]
We depend on the symlinks not existing in some places in the tests.

In the `le/le/tests/renewer_tests.py::BaseRenewableCertTest` we create a test `RenewabelCert` ([here](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/tests/renewer_test.py#L70)) where the  `self.cert`, `self.privkey`, etc. symlinks do not exists yet.

Then later, in some tests we manually add the links ([here](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/tests/renewer_test.py#L173)).

So I think this check should still be added, but the tests need to be changed too.

**Comment by cowlicks** [comment]
I have a branch that adds the check [here](https://github.com/cowlicks/letsencrypt/blob/gh-2000/letsencrypt/storage.py#L131-L139) (link to code).

**Comment by pde** [comment]
@cowlicks can you make a PR for that branch?

**Comment by bmw** [comment]
Fixed in #2280
