### ISSUE TITLE
There should be an official web-based LE service

### ISSUE THREAD

**Issue by alexweissman** [letsencrypt/letsencrypt#2001]
Let's Encrypt is awesome!  Free SSL for everyone!

The `letsencrypt-auto` utility is very easy to use if you're able to run it on the same machine that is hosting your website.  Unfortunately, shared hosting is still very popular and often does not allow/provide shell access.  This directly conflicts with ISRG's core mission:

>  ISRG’s mission is to reduce financial, **technological, and education** barriers to secure communication over the Internet.

To address that, I propose a web-based interface, hosted on letsencrypt.org, that allows webmasters to generate SSL certificates that they can copy-paste into cPanel.  There are some third-party solutions out there, but since the security of the private key is essential for SSL to work, it would be best if the issuer (LE) hosted the service themselves.

I propose something like `certs.letsencrypt.org` where:

1. A webmaster can create an account linked with their email address;
2. They can initiate a certificate request;
3. They are then told how to go about verifying their control of the domain(s);
4. Once verified, the certificate and private keys are generated, and they can then copy-paste them into cPanel;
5. They are automatically emailed a series of notices when their cert is about to expire, along with a link or instructions to sign back into the website and renew their cert.

**Comment by Goodnewstown** [comment]
^5 for that!

**Comment by pde** [comment]
1. This is not a Python client bug or feature request, so this repo is the wrong place to discuss this :)

2. Anyone could make the web application you describe, it doesn't need to be on letsencrypt.org.  However here are a number of pretty serious concerns with having a web application generate your keys.  Theoretically it may be possible with the WebCrypto API, but there's currently no way to ensure to verify the integrity of web applications, and ensure that they aren't squirreling away a copy of your private keys.

3. It **might** be possible to make a cPanel [plugin](https://letsencrypt.readthedocs.org/en/latest/contributing.html#plugin-architecture) for the Python client.  But that's a totally separate ticket, and some volunteers would have to step forward and be highly committed to designing, implementing and maintaining that.

**Comment by alexweissman** [comment]
For point 1: Is there a better place where we should discuss this?

For point 2: People [have](https://gethttpsforfree.com/) done [this](https://www.sslforfree.com/) already, but the security concerns you point out are **precisely** why it should be hosted and managed by letsencrypt.org instead.

For point 3: the cPanel plugin is a good step as well, but it will only work if the host installs it.  100% compliance is a difficult thing to achieve ;-)
