### ISSUE TITLE
log changes to Apache conf files right before performing .reload()

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#2002]
This should make it much easier to see what's going wrong in cases like #1994 where the changes we think we should have made to conf files apparently aren't quite what's happened.

**Comment by SwartzCr** [comment]
@pde how does https://github.com/SwartzCr/letsencrypt/commit/c9b9b0edda27c3be3173fdcda0e98bcbd4995b3c look?

**Comment by pde** [comment]
Done.

**Comment by pde** [comment]
Had to revert that PR because of unintended iDisplay.notification() interactivity, so reopening this ticket.

**Comment by SwartzCr** [comment]
can you give more info on the error and how to repro it?

**Comment by SwartzCr** [comment]
Oh I see it's in the PR ( #2009 )
That's garbage, I wonder if there's a way to get the logger from elsewhere so it doesn't hit that code in reverter.
On the other hand, it seems like we're making good progress with the bug that this was meant to help debug, so maybe it's not worth spending too much time working on.
I'm going to focus on #2012 for now
