### ISSUE TITLE
PHP -  OpenSSL ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by lukepolo** [letsencrypt/letsencrypt#2023]
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

Here is some relevant code 

````
  $result = file_get_contents($url, false, stream_context_create(['http' => ['timeout' => (float) $this->options['timeout']]]));
````

Basically im trying to connect to socket.io implementation and its rejecting it because of of the SSL 3 check...which im pretty sure we dont want anyways

**Comment by lukepolo** [comment]
http://stackoverflow.com/questions/34515120/php-verify-failed-with-letsencrypt

**Comment by kuba** [comment]
It's not even clear from the problem description what you're trying to achieve. This is an official client repository, written in Python, not PHP. If you need generic help with the entire project, please go to https://community.letsencrypt.org
