### ISSUE TITLE
Standard certificate allowing fallback to weak DH keys?

### ISSUE THREAD

**Issue by Levino** [letsencrypt/letsencrypt#2028]
I am currently deploying letsencrypt ssl certs for coyno.com. When I check the configuration with ssllabs.com I get this warning:
```
TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x33)   DH 1024 bits   FS   WEAK
```
Please verify here: https://www.ssllabs.com/ssltest/analyze.html?d=coyno.com

I created the certs using the docker image. I suppose I could disable this cipher during the creation of the certs or hopefully during renewal (which would be easier as I would not break the live deployment). Do I have to use a custom ssl-options.conf? How would it look like? I would like to use these ciphers, following https://weakdh.org/sysadmin.html.

```
ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
```

Any objections?

Thanks

Levin

**Comment by schoen** [comment]
This kind of ciphersuite setting is controlled by your webserver (or other
TLS endpoint) configuration, not by the content of the cert.  In almost
all cases, TLS certs don't specify anything about the ciphersuites that
they can (or can't) be used with.  In this case you can disable this
ciphersuite in your httpd.conf (if you're using Apache) -- in any case,
you don't need a new or different cert.

There is a lot that can be said about ciphersuite selection and about
DH groups, but you can find suggestions from Mozilla that LE has decided
to adopt as defaults at

https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by Levino** [comment]
I see. Thank you for clearing this up. I am always confused what the certificate defines and what is a matter of the webserver config. I am using HAProxy in a docker container, but I think I already know where to look. Leaving this somewhat embarrassing issue here for reference :)

**Comment by Levino** [comment]
For reference: I added this to the global settings:
```
tune.ssl.default-dh-param 2048
```
In my case as I was using https://github.com/tutum/haproxy I just needed to set the environment variable
```
EXTRA_GLOBAL_SETTINGS
```
Only downside: we can kiss all clients which don't support 2048 bit keys goodbye (which are very old (software wise) clients anyhow, as far as I can tell).
