### ISSUE TITLE
Add support for XMPP certificates

### ISSUE THREAD

**Issue by languitar** [letsencrypt/letsencrypt#2032]
Certificates for XMPP should have some additional attributes, cf. [this] and [that]. It would be nice if the client supported issuing such certificates. Right now, I need to hand-craft a CSR and use the ACME protocol manually to get a suitable certificate for such a purpose.

[this]: https://blog.hamzahkhan.com/2012/11/09/ssl-certificates-for-xmpp/
[that]: https://tools.ietf.org/html/draft-ietf-xmpp-3920bis-22#section-13.7.1.2

**Comment by schoen** [comment]
Is the Let's Encrypt CA issuing certificates with these attributes now?
(If you hand-craft the CSR, do you get the attributes that you want?)

My recollection was that the Let's Encrypt CA was stripping out
absolutely everything from the CSR before issuance and just using it as
a transport for subject domains names and subject public key, and maybe
a proof of the ability to sign using the subject public key.  I didn't
think you would be able to request any additional attributes.

**Comment by pde** [comment]
Please re-file this bug against [boulder](https://github.com/letsencrypt/boulder)!  Thanks!

**Comment by languitar** [comment]
Thanks for the explanation. You are right. Attributes are stripped.
