### ISSUE TITLE
Bad request while using standalone plugin

### ISSUE THREAD

**Issue by Marty** [letsencrypt/letsencrypt#2033]
Hi there,
I'm running letsencrypt on Ubuntu 14.04.3 behind an installation of haproxy.
I've configured haproxy to forward every request on port 443 containing `acme-challenge` to the letsencrypt standalone server running on port 444 which I changed with `--dvsni-port 444`.

I built a script that automatically refreshes all of my certificates **which worked flawlessly** for my configuration until now.
Obviously the parameter `--dvsni-port` is no longer available, so I changed the call to use `--tls-sni-01-port 444`.

However, this does not seem to work:
`/root/.local/share/letsencrypt/bin/letsencrypt certonly --email admin@***** --domains api.*****.com --standalone --standalone-supported-challenges tls-sni-01 --tls-sni-01-port 444 --debug`

It returns the following:
```
FailedChallenges: Failed authorization procedure. api.*****.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge. Found api.*****.com

The following 'urn:acme:error:unauthorized' errors were reported by the server:

Domains: api.*****.com
Error: The client lacks sufficient authorization
```
In my haproxy log I just get this:
```
Dec 27 17:54:09 localhost haproxy[21317]: *****:35127 [27/Dec/2015:17:54:09.403] https_relay~ https_relay/<NOSRV> -1/-1/-1/-1/298 400 187 - - CR-- 0/0/0/0/0 0/0 "<BADREQ>"
```
The standalone server runs on port 444 (since the log says `DEBUG:letsencrypt.plugins.standalone:Stopping server at 0.0.0.0:444...`) and the request comes in on 443 (otherwise it would not be handled by my haproxy frontend `https_relay`), so everything is as I would expect.

**Does anyone have any idea what could cause this bad request?**

**Comment by pde** [comment]
The standalone port can only be changed for testing purposes at the moment.  The IETF ACME working group will need to standardise an extra port before challenges can be completed on anything other than 80 or 443.

**Comment by Marty** [comment]
Well, ok. 
But this isn't the problem here.
The challenge is using port 443, but it produces the bad request as described above.

**Comment by Marty** [comment]
Please reopen this issue, since the real problem here is the **bad request from the letsencrypt** backend and not the changing of the port.

**Comment by kuba** [comment]
It seems like your load balancer setup is broken. `zName` should match `*.acme.invalid`, but instead it shows your domain, so TLS SNI doesn't seem to work.

**Comment by phylor** [comment]
If using haproxy, make sure that you use `strict-sni` in your https frontend configuration.

Example: `bind *:443 ssl crt domain1.pem crt domain2.pem strict-sni`

This ensures that haproxy uses the correct certificate and doesn't use only the first one it can find. Might not be your specific problem, but it results in the same error.
