### ISSUE TITLE
delay root requirement

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/letsencrypt#204]
currently, the code checks rather early for running as uid 0 and terminates letsencrypt if it is not running as root.

this code should be put in a function "require_root" (or so) and calls to that should be put at all places where it is clear that it can't continue without root.

see also #200 - that does not require root (in fact, it doesn't require much at all, except being able to modify DNS somehow).

**Comment by jdkasten** [comment]
Yes, I was kind of waiting for a reason to implement this and have been thinking about it for quite some time.

**A lot of time*** will need to be spent analyzing the attack surface as it becomes much harder ensure a safe operating environment when you are running as root and the client's previously generated files aren't necessarily protected.... or you are running as a normal user and you don't have permission to edit anything (though this is much easier to detect :))

**Comment by ThomasWaldmann** [comment]
working on that.

**Comment by kuba** [comment]
FYI code in `master` doesn't require root any more.
