### ISSUE TITLE
An unexpected error occurred: KeyError: 'webroot'

### ISSUE THREAD

**Issue by alles32** [letsencrypt/letsencrypt#2043]
hi, 
i get an error with le official client (problem is not DeprecationWarning):

__# letsencrypt --help plugins__
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
An unexpected error occurred:
KeyError: 'webroot'
Please see the logfile 'letsencrypt.log' for more details.

logfile:

__# cat letsencrypt.log__
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 1350, in main
    args = prepare_and_parse_args(plugins, cli_args)
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 1066, in prepare_and_parse_args
    _plugins_parsing(helpful, plugins)
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 1193, in _plugins_parsing
    help="public_html / webroot path. This can be specified multiple times to "
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 849, in add
    if self.visible_topics[topic]:
KeyError: 'webroot'

got same error with another commands, for example:

__# letsencrypt certonly -vvvv  --webroot -w /home/hosting90.be/vaginalnikuze.hosting90.be/ -d vaginalnikuze.hosting90.be__
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
An unexpected error occurred:
KeyError: 'webroot'

logfile:

__# cat letsencrypt.log__
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 1350, in main
    args = prepare_and_parse_args(plugins, cli_args)
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 1066, in prepare_and_parse_args
    _plugins_parsing(helpful, plugins)
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 1193, in _plugins_parsing
    help="public_html / webroot path. This can be specified multiple times to "
  File "/usr/lib/python2.6/site-packages/letsencrypt/cli.py", line 849, in add
    if self.visible_topics[topic]:
KeyError: 'webroot'

interesting thing is, that on another computer with same configuration the client work fine.
OS and installed packages:

OS Centos 6.7
Python 2.6.6
letshelp-letsencrypt, letsencrypt and acme in versions 0.1.1 (installed from pypi)
executed bootstrap/centos.sh from latest letsencrypt git tree
cli.ini:
rsa-key-size  = 2048
email         = mymail.mydomain.tld
server        = https://acme-staging.api.letsencrypt.org/directory
account       = some_number
config-dir    = /mnt/data/letsencrypt
work-dir      = /mnt/data/letsencrypt/lib
logs-dir      = /mnt/data/letsencrypt/log
text          = True
agree-tos     = True

**Comment by sl45sms** [comment]
+1

on ubuntu 10.04 (Lucid Lynx) Python 2.6.5

run standalone with --debug flag

first I fix InsecurePlatformWarning
with
pip install requests[security]

after i get the same error 
An unexpected error occurred:
KeyError: 'webroot'

**Comment by bmw** [comment]
Installing the client from PyPI outside of a virtual environment is not supported. Please see [here](https://letsencrypt.readthedocs.org/en/latest/using.html#from-source) for more info.
