### ISSUE TITLE
Configuration files appear not to work

### ISSUE THREAD

**Issue by jribbens** [letsencrypt/letsencrypt#2045]
If I run `letsencrypt-auto` manually, e.g. `./letsencrypt-auto certonly --webroot -w /var/www/html -d example.com` then it works fine. If however I try to do the same thing but using a configuration file as described in the User Guide, it does not work: 
```
$ ./letsencrypt-auto -c /etc/letsencrypt/cli.ini 
Updating letsencrypt and virtual environment dependencies......
Requesting root privileges to run with virtualenv: sudo /home/jon/.local/share/letsencrypt/bin/letsencrypt -c /etc/letsencrypt/cli.ini
No installers seem to be present and working on your system; fix that or try running letsencrypt with the "certonly" command
```
My `cli.ini` file is as follows:
```
email = webmaster@example.com
domains = example.com
authenticator = webroot
webroot-path = /var/www/html
```

**Comment by KeiroD** [comment]
@jribbens Try adding agree-tos

Basically:

```
email = webmaster@example.com
domains = example.com
authenticator = webroot
webroot-path = /var/www/html
agree-tos
```

**Comment by jribbens** [comment]
No change. I should probably add:
```
$ uname -a
Linux example.com 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```
and I am using `letsencrypt` as pulled from github an hour or two ago.

**Comment by KeiroD** [comment]
Hmm, that's very odd.

Oh. You may want to try adding `text = True`.

My cli.ini is as follows, though note that if you haven't created a `cert` with `letsencrypt-auto` for a particular domain, comment out `renew-by-default = True`:

```
# LE Configuration
rsa-key-size = 4096
email = admin@heimkoma.com
domains = cplexus.heimkoma.com
renew-by-default = True
text = True
agree-tos
```

Then from my bash script which I used to automate the process of renewing SSL certificates:

```
#!/bin/bash
# Get new keys!
/root/letsencrypt/letsencrypt-auto -c /root/cli.ini certonly

# Reload Servoces
service webmin restart
```
This one's mostly because I'm using LE for my Webmin install. I'm not sure why yours isn't working as yours has more or less similar setup to mine.

**Comment by jribbens** [comment]
Ah, I've worked it out, I need to run `./letsencrypt-auto certonly` and then it works.
