### ISSUE TITLE
Should .well-known/acme-challenge be removed?

### ISSUE THREAD

**Issue by phpdan** [letsencrypt/letsencrypt#2049]
After running "./letsencrypt-auto certonly --webroot -w /some/path -d thedomain" successfully, should .well-known/acme-challenge be removed? It was not on my system.

**Comment by bmw** [comment]
Thanks for the report @phpdan. `.well-known/acme-challenge` should be removed, but this is a dupe of #1003.

**Comment by alanhogan** [comment]
Whew. I just saw this in my Dreamhost account and it gave me a bit of a scare.

**Comment by ozh** [comment]
Heh. Same. You guys should ping Dreamhost about this, it's awesomly awesome that they're providing 1-click install for Let's Encrypt certs, but this hidden dir should be removed afterwards...

**Comment by jerrygarciuh** [comment]
Same here.  What a relief that it's not an intrusion.

**Comment by mariomara** [comment]
Phew!
