### ISSUE TITLE
Run configtest before attempting to modify config files

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#2056]
It's possible that the user's config files are in a bad state before we even touch them. We should run `service nginx configtest` or equivalent before even trying to modify configs.

**Comment by tcz001** [comment]
Actually this is already been [included](https://github.com/letsencrypt/letsencrypt/blob/ff7e765611aa1a8fa927988e102ab03fdcb85ce1/letsencrypt-nginx/letsencrypt_nginx/configurator.py#L409) in nginx plugin,
only difference is when we use `service nginx configtest` it's just a service script wrapping `nginx -t`, `service nginx configtest` also won't return exit code, I think we can just enable the `config_test ` in prepare stage.

**Comment by olabini** [comment]
I think this has been fixed, based on the merged pull request from @tcz001

**Comment by pde** [comment]
Great!
