### ISSUE TITLE
Docker container for load balanced setups

### ISSUE THREAD

**Issue by Levino** [letsencrypt/letsencrypt#2058]
Dear all, I have created this repo with a service that can create certificates behind a load balancer without breaking the deployment. I would be interested in feedback.

https://github.com/Levino/letsencrypt-cert-service

It is also available on docker hub: https://hub.docker.com/r/levino/letsencrypt-cert-service/

**Comment by bmw** [comment]
Nice! Thanks for sharing this.

Unfortunately, I don't think this is the best place to do so. Please checkout the [community forum](https://community.letsencrypt.org) or #letsencrypt on freenode which are better places to post things like this.
