### ISSUE TITLE
Doesn't understand `ssl on` directive

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#2059]
In Nginx there are two ways to turn on SSL for a server:

```
server {
  listen 443 ssl;
}
```

```
server {
  listen 443;
  ssl on;
}
```

Our Nginx plugin doesn't understand the latter. In parser.py's `get_vhosts`, the `VirtualHost` object will be created with `ssl = False`, leading later code to attempt to "enable" SSL on that vhost, creating a fatal conflict for the ssl_certificate directive. One possible easy fix: Look for `ssl_certificate` to determine whether a vhost has ssl enabled, instead of looking at the `listen` or `ssl` directives.

**Comment by SwartzCr** [comment]
so here's the code that's likely at fault 
...
446 def _parse_server(server):                                                       
 ---
453     parsed_server = {'addrs': set(),                                             
454                      'ssl': False,                                               
455                      'names': set()}                                             
456                                                                                  
457     for directive in server:                                                     
458         if directive[0] == 'listen':                                             
459             addr = obj.Addr.fromstring(directive[1])                             
460             parsed_server['addrs'].add(addr)                                     
461             if not parsed_server['ssl'] and addr.ssl:                            
462                 parsed_server['ssl'] = True                                      
463         elif directive[0] == 'server_name':                                      
464             parsed_server['names'].update(                                       
465                 _get_servernames(directive[1]))                                  
466                                                                                  
467     return parsed_server                     
...

It seems that we're just looking at one line of the directive - we could easily make this part of the code more robust, to check multiple lines for ssl and also check for ssl_certificate

**Comment by SwartzCr** [comment]
can you share some conf files with me?
I'm curious to see what these lines in parser.py spit out
```
109             for i, server in enumerate(servers[filename]):                       
110                 new_server = self._get_included_directives(server)               
111                 servers[filename][i] = new_server                                
```

**Comment by jsha** [comment]
crud.net:
```
server {
    listen 80;
    listen [::]:80;
    server_name crud.net;

    location / {
        return 301 https://$host$request_uri;
    }
}
```

crud.net-ssl:
```
server {
    listen 443;
    listen [::]:443;
    server_name crud.net;
    ssl on;
    ssl_certificate /etc/apache2/certs/2015/crud.net.crt;
    ssl_certificate_key /etc/apache2/certs/2015/crud.net.key;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_stapling on;
    ssl_stapling_verify off;

    root /var/www/crud;

    location / {
        try_files $uri $uri/ /index.html /index.php;
    }
}
```
