### ISSUE TITLE
Update _get_ranked_matches comment to describe ordering by SSL too

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#2060]
(Slightly related to #2059)

One technique for managing Nginx vhosts is to have two config files per server name, one for HTTP and one for HTTPS. Both files would contain the same server_name, and the Nginx configurator would pick one arbitrarily to install the certificate in.

Instead, configurator.py's `_get_ranked_matches` should use the SSL status of a vhost as part of its ranking, and preferentially install certificates in a vhost which already has SSL enabled.

**Comment by SwartzCr** [comment]
isn't this what the vhost.ssl statements in the elif block are for?
They seem to come from parser.py's _parse_server() function which checks the addr directive for ssl

Maybe it's just not working because it's looking in the wrong place?

**Comment by jsha** [comment]
Yep, you're right. I was reading the comment, which doesn't mention ordering by SSL. Let's make this ticket about updating the comment, which should be easy. :-)
