### ISSUE TITLE
STFU mode?

### ISSUE THREAD

**Issue by Levino** [letsencrypt/letsencrypt#2063]
I do not want any prompts.

```letsencrypt certonly --webroot -w /var/www/html -d example.com -m mail@example.com --agree-tos```

brings me pretty far but if I have certificates in place and want to add more domains:

```letsencrypt certonly --webroot -w /var/www/html -d example.com,app.example.com -m mail@example.com --agree-tos```

I get an annoying prompt. Is there something like a ```-y``` flag?

**Comment by dusek** [comment]
Perhaps you can use one of `--keep-until-expiring`, `--expand` and `--renew-by-default` (which implies `--expand`) to provide your answer on command line? (Look at `letsencrypt-auto --help all` for more information on these options).

(Also the `--text` option might be useful for your purposes.)

**Comment by Levino** [comment]
Thanks, will try.
