### ISSUE TITLE
Error with site configurations not ending with newline

### ISSUE THREAD

**Issue by Eeemil** [letsencrypt/letsencrypt#2066]
System: Ubuntu 14.10 x86_64 with a fresh install of apache2.

Running `./letsencrypt-auto -v --apache` with the following configuration file:

```
<VirtualHost *:80>

	     ServerName server-name-not-important
	     ServerAdmin mail@not.important
	     DocumentRoot /var/www/wiki

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

Gives the following error if the file does not end with newline (`\n`):

`apache2: Syntax error on line 219 of /etc/apache2/apache2.conf: Syntax error on line 15 of /etc/apache2/sites-enabled/wiki-le-ssl.conf: Expected </VirtualHost> but saw </VirtualHost></IfModule>`

Adding the newline character fixes the problem.

**Comment by pde** [comment]
This has already been fixed in git master.  You can wait for 0.2.0 or [run from git directly](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client).
