### ISSUE TITLE
Let's Encrypt & Tor Hidden Service Protocol

### ISSUE THREAD

**Issue by a1exus** [letsencrypt/letsencrypt#2067]
How would one use [Let's Encrypt](https://letsencrypt.org/) with [Tor: Hidden Service Protocol](https://www.torproject.org/docs/hidden-services.html.en)?

**Comment by schoen** [comment]
Hi,

This is not possible right now.  There's a detailed discussion at

https://community.letsencrypt.org/t/if-when-will-le-support-onion-addresses/341/32

**Comment by bmw** [comment]
Closing as a dupe of #91.
