### ISSUE TITLE
Need information on error while installation

### ISSUE THREAD

**Issue by adithyakhamithkar** [letsencrypt/letsencrypt#2068]
Hi,

Can someone please help me identify what this error means?
```
IMPORTANT NOTES:
 - The following 'urn:acme:error:unauthorized' errors were reported by
   the server:

   Domains: mydomain.com
   Error: The client lacks sufficient authorization
```

**Comment by adithyakhamithkar** [comment]
This directory is getting created .well-known/acme-challenge
But i am not seeing any file like over there
OHkkJRoVER9hDFZBEHqNrijoDz5eFugLmWLPQDNUY3o

**Comment by bmw** [comment]
This means that `boulder`, the server side of Let's Encrypt, is unable to verify that you control `mydomain.com`. As for not seeing the file, the client deletes the file before it exits.

While tedious, one thing you could try is the manual authenticator by including `--manual` on the command line. This allows you to set up the file yourself and you can verify that you can access the file in your web browser.

**Comment by adithyakhamithkar** [comment]
I was actually trying that on my local, It worked when tired it on the actual domain it work.

Thanks for your reply.

Also I had one more question on the recent news on malware coming along with let's encrypt. Is there any official statement on this?

**Comment by bmw** [comment]
I'm glad you got it to work.

The reports you are talking about are not about malware coming with the Let's Encrypt software, but websites taking advantage of the cert given to them by Let's Encrypt to make a site containing malware look more legitimate (they have a green lock next to the URL).

The ISRG executive director commented on the issue in this [thread](https://community.letsencrypt.org/t/misused-certificates/8423) and wrote a [blog post](https://letsencrypt.org/2015/10/29/phishing-and-malware.html) about the issue back in October.

**Comment by adithyakhamithkar** [comment]
Thanks I just hand one last question. I was told to use these certificates only in a test environment and not in production.
When I setup the certificate they still say that the certificate is not issued by a trusted authority. I understand this project is still in beta. When can we utilize the certificate with out any error.

**Comment by bmw** [comment]
Who told you that you shouldn't use our certificates in a production environment? While the project is still in beta, we are issuing certificates that are trusted in all major web browsers and can certainly deployed on production systems.

**Comment by adithyakhamithkar** [comment]
I am sorry I read an article about it.
I tired it on one of my production servers and I am excited that I have got a valid certificate.
Thanks!

**Comment by adithyakhamithkar** [comment]
But sometimes I get this error.
<img width="577" alt="screen shot 2016-01-09 at 9 06 10 am" src="https://cloud.githubusercontent.com/assets/3615342/12214191/9bb1942a-b6b0-11e5-901f-297b1eacacfb.png">

**Comment by bmw** [comment]
If you're getting that error, there could be a couple different things going on:

1. Your webserver is misconfigured. See the [user guide](https://letsencrypt.readthedocs.org/en/latest/using.html#where-are-my-certificates) for some help with this.
2. [Windows XP problems](https://community.letsencrypt.org/t/lets-encrypt-certificates-do-not-work-on-xp-in-ie8-or-chrome/2654).

Either of those seem possible?

**Comment by adithyakhamithkar** [comment]
I am using nginx as my web server and I did check the configuration again i am using the certificates from `/etc/letsencrypt/live/domain_name/*`
Only firefox gave me that error when I checked in chrome it did not prompt me for the error. In chrome it says it's a valid certificate.
<img width="482" alt="screen shot 2016-01-12 at 7 21 40 am" src="https://cloud.githubusercontent.com/assets/3615342/12252482/b79516ea-b8fd-11e5-9fac-10c55bb513fd.png">

**Comment by bmw** [comment]
From which OS are you getting this error?

**Comment by adithyakhamithkar** [comment]
I am using OS X El Captain

**Comment by bmw** [comment]
I updated the comment that leaked it, but one of your previous screenshots included your domain name. Because of this though, I was able to take a look at your website myself.

It appears to me that your website is set up properly. Firefox will behave like your most recent screenshot if you access your website over HTTP. Add `https://` to the front of the URL to access the secure version. If you'd always like users to access your website over HTTPS, looking into setting up a HTTP to HTTPS redirect in nginx. You can find plenty of manuals on how to do this online.

Are you still able to reproduce your first screenshot that says "Could not verify this certificate because the issuer is unknown"? If so, what OS/browser?

**Comment by adithyakhamithkar** [comment]
Thanks for updating the comment.

I do have a provision to redirect to HTTPS 
[This is my sample config](https://github.com/adithyakhamithkar/ansible/blob/master/roles/deployment-nginx/templates/virtualhost.j2)
Once I am confident of running it only in HTTPS I will make the necessary changes.

This is the screenshot I took after clearing the cache from my Firefox 43.0.4 Running on OS X El Captain
<img width="641" alt="screen shot 2016-01-12 at 10 26 58 am" src="https://cloud.githubusercontent.com/assets/3615342/12255219/55b92a5a-b917-11e5-9ca0-830f56a735e9.png">

**Comment by bmw** [comment]
Looking at this a little closer, it appears it was what I suggested earlier about your server being misconfigured and not sending the full certificate chain. I'll include the link to that section our user guide again [here](https://letsencrypt.readthedocs.org/en/latest/using.html#where-are-my-certificates) (look at `fullchain.pem`).

With that said, this is not the proper medium for help setting up your webserver and is instead focused on further development of the Let's Encrypt client. If you need further help, I recommend you check out https://community.letsencrypt.org or #letsencrypt on Freenode.

**Comment by adithyakhamithkar** [comment]
OK I understood my mistake.

I had to use `fullchain.pem` value for the `ssl_certificate` I got it working.

Thanks a lot for directing me to the solution.
Is there any way that I can contribute back to Let's Encrypt?

**Comment by bmw** [comment]
I'm glad you were able to fix the problem. There are a number of ways to give back to `letsencrypt`:

1. Donate to [ISRG/Let's Encrypt](https://letsencrypt.org/donate) or the [EFF](https://eff.org/donate-le).
2. If you're a programmer, send us a pull request. Here's links to the [client](https://github.com/letsencrypt/letsencrypt) and [server](https://github.com/letsencrypt/boulder) repositories. If you need help getting started, come see us in #letsencrypt-dev on Freenode.
3. Help other users use `letsencrypt` by answering questions on the [community forum](https://community.letsencrypt.org) or #letesncrypt on Freenode.

Thanks for your interest in giving back and increasing the security of the web by setting up HTTPS on your site!

**Comment by adithyakhamithkar** [comment]
Thanks a lot I'll do my best to help out on the community forum I have signed up on it.
