### ISSUE TITLE
webroot auth file isn't created on Gentoo

### ISSUE THREAD

**Issue by Shadok** [letsencrypt/letsencrypt#2077]
I'm trying to use "./letsencrypt-auto certonly" on Gentoo using webroot authenticator.
webroot-path is set to /tmp/letsencrypt-auto and i have a global alias in Apache.

    Alias /.well-known/acme-challenge "/tmp/letsencrypt-auto"
    <Directory "/tmp/letsencrypt-auto">
            Allow from all
            DefaultType text/plain
    </Directory>

The problem is no file is created in /tmp/letsencrypt-auto
I'm using the same method on Ubuntu and it's working fine.

    # ./letsencrypt-auto certonly -d www.domain.tld
    Updating letsencrypt and virtual environment dependencies......
    Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly -d www.domain.tld
    Failed authorization procedure. www.domain.tld (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.domain.tld/.well-known/acme-challenge/s4i7TepN2IAI6st-uBaN_F4AehoB93KemNzGQNBpHGg 404

Access to http://www.domain.tld/.well-known/acme-challenge works fine but since there wasn't any s4i7TepN2IAI6st-uBaN_F4AehoB93KemNzGQNBpHGg created, it fails.

**Comment by bmw** [comment]
The file is deleted before the client exits. While tedious, one thing you could try is to use the manual authenticator by including `--manual` on the command line. This allows you to set up the file yourself and you can verify that you can access it in a web browser before completing the challenge.

**Comment by Shadok** [comment]
It was a typo issue on my part, sorry.
Thanks for the tip, the --manual flag helped noticing it :)
