### ISSUE TITLE
Perl code in Apache config causes letsencrypt-auto to fail

### ISSUE THREAD

**Issue by mgollo** [letsencrypt/letsencrypt#2079]
The widely used request-tracker4 package on Debian Jessie ships the file /etc/request-tracker4/apache2-modperl2.conf which contains the following at the very end:

> \<Perl\>
>   use Plack::Handler::Apache2;
>   Plack::Handler::Apache2->preload("/usr/share/request-tracker4/libexec/rt-server");
> \</Perl\>

The second line within the <Perl> tag causes the following error when running letsencrypt-auto with the apache plugin:
> The apache plugin is not working; there may be problems with your existing configuration.
> The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/request-tracker4/apache2-modperl2.conf', u'Syntax error'),)

Commenting out the line gets the letsencrypt client to work, but in my Opinion, it shouldn't fail because the config file is perfectly valid.

If you need further information, please let me know.

Thanks,
Martin

**Comment by mjrider** [comment]
this is also reported in augeas hercules-team/augeas#327
and is fixed in hercules-team/augeas@3a901a4ba1166703bb0fc87d8dd9b7357a06d427
