### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by durian808** [letsencrypt/letsencrypt#2087]
According to https://github.com/letsencrypt/letsencrypt, System Requirements:

"The Let's Encrypt Client presently only runs on Unix-ish OSes that include Python 2.6 or 2.7..."

However, when I run ./letsencrypt-auto --help, I get:

"WARNING: Python 2.6 support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!"

My question is, when will Python 2.6 be fully supported?

thanks

**Comment by bfallik** [comment]
I just encountered this issue as well while trying to experiment with Let's Encrypt on CentOS 6.

**Comment by alex** [comment]
You should be able to obtain a Python 2.7 on CentOS by using SCL: https://www.softwarecollections.org/en/scls/rhscl/python27/

**Comment by bfallik** [comment]
@alex thanks!

**Comment by bmw** [comment]
@durian808 soon! We're testing against py26 in a number of our test suites and py26 support should no longer be considered experimental.

I hope to write a pull request to fix this issue sometime next week.

**Comment by durian808** [comment]
@bmw awesome!  keep up the good work.

~~~
"Buttons aren't toys."

**Comment by bfallik** [comment]
@bmw great!

**Comment by rbu** [comment]
@pde, have you investigated why LE's dependency "parsedatetime" claims to require Python 2.7 or later? Tests fail on Python 2.6, but the errors might be cosmetic.
I haven't been able to get a green test run on 2.6 with the project though (after installing PyICU).
