### ISSUE TITLE
docs issues

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/letsencrypt#210]
put documentation issues here.

also, if stuff from wiki is ready to get moved to sphinx docs (provide URLs).

note: likely this will be a permanent issue.

**Comment by ThomasWaldmann** [comment]
how to deal with configuration of letsencrypt (currently in CONFIG.py) is missing.
note that client/CONFIG.py might be installed to a read-only system location.

**Comment by kuba** [comment]
in regards to `CONFIG`: #220

**Comment by ThomasWaldmann** [comment]
https://github.com/letsencrypt/lets-encrypt-preview/wiki/How-to-Contribute move generic stuff to docs (check what's already there). move issues (contribution/project suggestions) to issue tracker.

**Comment by pde** [comment]
This is a very non-specific issue, so closing it; we should just tag specific documentation issues with the "documentation" label.
