### ISSUE TITLE
letsencrypt-auto certonly (Obtain cert, but do not install it (aka "auth"))

### ISSUE THREAD

**Issue by a1exus** [letsencrypt/letsencrypt#2101]
Hello,

Please correct me if I'm wrong, I ran `./letsencrypt-auto certonly`, enter my FQDNs, then I'm got following message:
```
│ The program httpd (process ID 98230) is already listening on TCP     │  
│ port 80. This will prevent us from binding to that port. Please stop │  
│ the httpd program temporarily and then try again.                    │  
```
Isn't `certonly` suppose to do only certificate for me and I'd need to apply it myself?

**Comment by alles32** [comment]
hi,
you need to use 'webroot' authenticator plugin for obtain cert (which do 'certonly' argument), if you want to use running web server for it.

**Comment by a1exus** [comment]
I actually do _NOT_ want to use running web server, what I'd like to get is certificate only...

**Comment by bmw** [comment]
Per the [ACME protocol](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7.3), `letsencrypt` needs to bind to either port 80 or 443 to perform domain validation so we can issue a certificate. Please see our [plugin documentation](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins) for different methods of doing this.

**Comment by pde** [comment]
Note that "use the running webserver" means "put some files in the webroot directory that will be temporarily served by the running webserver".

I do think adding a new IANA ACME port to the spec will help with some of these confusion cases.
