### ISSUE TITLE
Apache: another parsing error related to double quotes

### ISSUE THREAD

**Issue by NelsonMinar** [letsencrypt/letsencrypt#2103]
The following line in an Apache config causes `letsencrypt-auto --apache` to fail with "There has been an error in parsing the file"

`RewriteRule ^test" http://example.com/`

Apache configtest is OK with it though and I use a similar rule on a real server because some search engine years ago decided one of my URLs ended with an unbalanced "

I suspect this parsing problem is similar to issue #1960 or #1531.

**Comment by pde** [comment]
@NelsonMinar I believe this is fixed in git master.  Can you [run the latest git code](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client) and check?

**Comment by NelsonMinar** [comment]
Can confirm it's fixed; both my test example and my real config line too. Sorry for the duplicate + slow response. I'm impressed with your professionalism answering filed issues!
