### ISSUE TITLE
letsencrypt-auto does not support utf-8 characters in webroot-path

### ISSUE THREAD

**Issue by destruktomatik** [letsencrypt/letsencrypt#2123]
I ran into this problem when putting a german umlaut in the --webroot-path option
```
letsencrypt-auto certonly --test-cert --text --rsa-key-size 4096 --webroot --webroot-path /path/to/umlaut-ü-dir/subdir --email mail@domain.tld -d domain.tld -d www.domain.tld
```
gives result
```
The webroot plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('/path/to/umlaut-\xc3\xbc-dir/subdir does not exist or is not a directory',)
```
solved it via a symlink rather than renaming the folder for compatibility reasons.
Maybe a problem for just a small group of users but in general UTF-8 suppport would be great in there.

**Comment by msoedov** [comment]
I could not reproduce it with a401384

**Comment by pde** [comment]
Yup, this should be done in 0.4.0.
