### ISSUE TITLE
letsencrypt-auto pip permission issue

### ISSUE THREAD

**Issue by bastienvinh** [letsencrypt/letsencrypt#2124]
Hello,

I have a problem when i try to use sudo permission. But When I use user permission, it's doing something but he don't create my domains certificates. 

This is the message that it give me :

```
The directory '/home/[user]/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/[user]/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

Maybe I am doing it wrong.

**Comment by pde** [comment]
I suggest (1) deleting that .cache/pip directory, and then not running letsencrypt-auto with sudo.  It will use sudo itself internally for the specific tasks that require root.

**Comment by pde** [comment]
If that doesn't fix the problem, please reopen.

**Comment by bastienvinh** [comment]
Ok I resolve it. Thank you.
