### ISSUE TITLE
Intallation problem (openssl) ?

### ISSUE THREAD

**Issue by jonathanpmartins** [letsencrypt/letsencrypt#2125]
Python 2.7.11
pip 7.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
Ubuntu 14.04

When I try ``sudo pip install letsencrypt`` I get this problem:

	gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
	    build/temp.linux-x86_64-2.7/_openssl.c:2:20: fatal error: Python.h: No such file or directory
	     #include <Python.h>
	                        ^
	    compilation terminated.
	    error: command 'gcc' failed with exit status 1
	    
	    ----------------------------------------
	Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-iTjozu/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vk2d8q-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iTjozu/cryptography

I think is something relation with openssl, but I cannot figure it out. How can I get around this problem?

``sudo pip install cryptography``
``sudo pip install pyOpenSSL``

generate the same problem!

**Comment by jonathanpmartins** [comment]
@xavfernandez Do you know something about that? I came across this problems just before I do this stupit thing: https://github.com/pypa/pip/issues/1892#issuecomment-170155636

**Comment by jonathanpmartins** [comment]
Found the problem. In ubuntu run ```sudo apt-get install python-dev```

**Comment by DavidBruchmann** [comment]
Looks like the header files are missing.
python2.7-dev has to be installed if I don't mistake.

But I'm stumbling about "#include <Pythonh>", usually it should be "#include
<Python.h>"

**Comment by xavfernandez** [comment]
Yup, most of the time when you get an error about missing `.h` files, it means you are missing some `-dev` package.
Glad you've found it.
