### ISSUE TITLE
better way to confirm domain ownership, standalone custom port, letsencrypt IP range redirection?

### ISSUE THREAD

**Issue by lope** [letsencrypt/letsencrypt#2127]
Currently the only viable options for me are using

1. Webroot mode
Requires me to make superflous webroots on my webserver such as mail.foo.com, imap.foo.com smtp.foo.com and many other things which have nothing to do with my web-server.

2. Standalone mode
[*] Requires me to shut down my webserver for a few seconds, interrupting customers. Not good at all.

Neither of these options are very appealing.
What if we can use a non-standard port for standalone mode, such as port 79 or something?

Alternatively can we get a list of letsencrypt IP addresses, so that I can redirect letsencrypt connections seeking port 80 to port 79?

There's gotta be some clean solution?

[*] This can be very dangerous because currently letsencrypt-auto often wants to go into interactive mode unexpectedly. If this were part of a script then the webserver would stay down permanently while letsencrypt waits for user response.

**Comment by pde** [comment]
Version 0.3.0 will support [a guaranteed non-interactive mode](https://github.com/letsencrypt/letsencrypt/pull/2078).  Supporting one extra port is a good idea, but it's going to take more work at the IETF ACME working group to pick and standardise one.

**Comment by pde** [comment]
IP range detection isn't going to work in the long run; making the IP addresses unpredictable is an important security feature.

**Comment by pde** [comment]
Closing this as a dupe since each of these requests has other tickets elsewhere.
