### ISSUE TITLE
DNS query timed out

### ISSUE THREAD

**Issue by od3n** [letsencrypt/letsencrypt#2153]
Failed authorization procedure. eduhub.my (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS query timed out during A-record lookup of eduhub.my

IMPORTANT NOTES:
 - The following 'urn:acme:error:connection' errors were reported by
   the server:

   Domains: eduhub.my
   Error: The server could not connect to the client to verify the
   domain

**Comment by levinus** [comment]
Same here with an .tk Domain. Before (~ 1 week ago) signing worked with even this domain easily... Whats going on there?

**Comment by bmw** [comment]
This is likely caused by [this](https://github.com/letsencrypt/boulder/issues/1008#issuecomment-149457432).

**Comment by jsha** [comment]
Sometimes name servers are slow, and we have a maximum timeout. Have you tried multiple times?

Also, FWIW, this isn't actually a client bug, so the best place is at https://community.letsencrypt.org. If you still have trouble after retrying, could you post at https://community.letsencrypt.org? Thanks!
