### ISSUE TITLE
Tries to open /var/log/letsencrypt/letsencrypt.log with --logs-dir set to something else

### ISSUE THREAD

**Issue by nagisa** [letsencrypt/letsencrypt#2154]
--logs-dir option is ignored and letsencrypt still attempts writing to files in /var/log.

**Comment by nagisa** [comment]
Easily rerpdocible running `letsencrypt` as a regular user with all/most path options specified to to point at `/tmp/`

**Comment by pde** [comment]
I can't reproduce this; with `--logs-dir /tmp/ --config-dir /tmp --work-dir /tmp/ -t certonly --webroot -w $WEBROOT -d $DOMAIN` I get a cert as non-root.

**Comment by pde** [comment]
Can you provide a specific example of the command you tried and the error message?

**Comment by nagisa** [comment]
@pde I was renewing the cert with configuration copied over from the `/etc` of another server. Renewal config contains `logs_dir = /var/log/letsencrypt` so might that be a reason (even though letsencrypt ended up writing logs to the location I specified on the command line anyway)?

The command I was running was similar to

```
letsencrypt --work-dir ~/Desktop/letsencrypt/ certonly --manual --logs-dir=/tmp/ --config-dir ~/Desktop/letsencrypt/
```

Where `~/Desktop/letsencrypt` contained configuration copied over from a remote machine’s `/etc`. The error would occur right after I’ve entered domains to get certificate for.

**Comment by bmw** [comment]
I also cannot reproduce the problem. @nagisa, can you provide a log where the problem occurred?

**Comment by nagisa** [comment]
@bmw I’m pretty sure the log files were empty – letsencrypt failed before it did anything.

Either way, I don’t think this will go anywhere, so closing.
