### ISSUE TITLE
owncloud server with webmin manangement

### ISSUE THREAD

**Issue by MaxTorque1** [letsencrypt/letsencrypt#2170]
Hi,
I have successfully installed a Letsencrypt certificate for an owncloud server using the --apache automated method. I am running a Debian 8 system.
However, I am now not able to gain access to my webmin web interface. Firefox throws up a warning of an untrusted cert (the default webmin one) and does not give the option to add an exemption.
Any ideas on how to resolve the issue would be greatly received.

**Comment by MaxTorque1** [comment]
Ok, I have resolved the issue.
For anyone with a similar problem you can do the following:
SSH into your server and edit the /etc/webmin/miniserv.conf file. Change the line ssl=1 to a 0 and save out the file.
Then type /etc/init.d/webmin restart to restart the webmin service and you should then be able to access the webmin UI using http. 
Next, from the webmin UI go to webmin configuration / ssl encryption / upload certificate tab where you can then copy and paste the three elements of your letsencrypt certificate into the fields. Click save and you are done. Log out or close the web page and log back in with HTTPS enabled
Hope that helps anyone with the same problem

**Comment by bmw** [comment]
Great! Thanks for taking the time to write up the solution to the problem.
