### ISSUE TITLE
Configure removal during renewal

### ISSUE THREAD

**Issue by kroeckx** [letsencrypt/letsencrypt#2204]
Hi,

I seem to be running into #1354 again.  That is, the site was working properly, I started letsencrypt-auto and pressed control-C and the next time it says it's misconfigured.  It seems the -le-ssl config file is still enabled, but it's been removed from the available sites.

**Comment by pde** [comment]
@kroeckx so what you're saying is that if you control-c the apache plugin, there's a file in `sites-enabled` that's not in `sites-available`, and that causes a misconfiguration error?

Is this in `certonly` mode, or `run` mode?  Do you know what step you were on when you pressed control-c?

**Comment by pde** [comment]
Perhaps send us a tarball of your entire `/etc/apache2`?

**Comment by kroeckx** [comment]
On Mon, Jan 18, 2016 at 04:58:26PM -0800, Peter Eckersley wrote:
> @kroeckx so what you're saying is that if you control-c the apache plugin, there's a file in `sites-enabled` that's not in `sites-available`, and that causes a misconfiguration error?

Yes.

> Is this in `certonly` mode, or `run` mode?  Do you know what step you were on when you pressed control-c?

I don't know, I first ran in run mode and then in certonly mode
and pressed ^C in both cases.  But then I can't reproduce it
anymore.


Kurt

**Comment by SwartzCr** [comment]
@kroeckx it'd be really useful to know what OS you're doing this on and what version of Apache you have (2.2 or 2.4?) Have you updated your version of Let's Encrypt between first having the issue and your current inability to reproduce?

**Comment by kroeckx** [comment]
This is an Debian wheezy system, so apache2 2.4.10-10+deb8u4.

As far as I know it was always with the current git snapshot when I reported the issue.

**Comment by SwartzCr** [comment]
and you were running via the local virtualenvironment (./venv/bin/letsencrypt {options}) or via the letsencrypt command (which fetches from the last release)

And you haven't been able to reproduce this, correct?

**Comment by kroeckx** [comment]
I use the letsencrypt-auto script inside the git repository.

I did try to reproduce it at that time, but I haven't tried since.

**Comment by bmw** [comment]
@kroeckx, do you have a log of this issue? By default, logs are stored in `/var/log/letsencrypt`.

**Comment by hlieberman** [comment]
Spoke with @kroeckx about this problem.  He believes that the upcoming resolution of #1143 will solve this issue; closing in anticipation thereof.
