### ISSUE TITLE
certs in etc/letsencrypt/live/* are softlinked to the archives dir, not helpful

### ISSUE THREAD

**Issue by geekscrapy** [letsencrypt/letsencrypt#2207]
I appreciate this may have been done on purpose, but it's not really helpful when trying to 'dockerise' letsencrypt. This is my usecase:

I have a LE container which exposes the etc/letsencrypt/live/<domain>/ directory to an nginx proxy (a reverse proxy for a few domains). However because the cert files in the live directory are softlinked the nginx container does not have access to the softlink targets (in the etc/letsencrypt/archive directory).

I don't want to expose the whole etc/letsencrypt/ directory to the nginx proxy because that's a bit of a security risk (and the reason why I chose to deploy Docker! plus I don't want to expose additional cert files). Anyone got any suggestions as to deal with this? Short of copying the certs somewhere that's accessible?

TIA

**Comment by kuba** [comment]
You probably mean `/etc/letsencrypt/live` and `/etc/letsencrypt` directories respectively. Why don't you expose both `/etc/letsencrypt/live` and `/etc/letsencrypt/archive`?

**Comment by geekscrapy** [comment]
Yes I did @kuba! Thanks!

Well the softlinks are relational which makes it a bit more of a pain! It just seems counter intuitive when the docs say to softlink to the certs in the live dir... Softlinks to softlinks never end well...

**Comment by kuba** [comment]
I find documentation quite clear on that matter. [Docker section](https://letsencrypt.readthedocs.org/en/latest/using.html#running-with-docker) doesn't give any misguiding instructions - it explicitly tells you to expose entire `/etc/letsencrypt` to the host, while you decided to do something else. https://letsencrypt.readthedocs.org/en/latest/using.html#where-are-my-certificates explicitly tells you what is the relation between `/etc/letsencrypt/live` and `/etc/letsencrypt/archive` (the blue box). Since you're running one of the setups that are not supported out of the box, you're responsible of making sure to read the docs carefully and implement it correctly.

**Comment by geekscrapy** [comment]
I agree, the doco is clear and I'm not suggesting it's wrong. However when trying to implement a secure setup this will potentially expose unwanted data to docker containers that could be compromised. It exposes private keys for all domains that the letsencrypt daemon controls.

I'm suggesting that the current files are held in the live directory and are not symlinked.

Also the docker example in the docs suggests that the setup is running the web server on the host, not in another docker container. This probably wouldn't be the case, as if you are running one docker container to run letsencrypt, chances are you're also probably running the web server in another docker container. And therefore you'll hit this inconvenience.

**Comment by pde** [comment]
Symlinks allow several other possibilities:

* obtaining a new cert in a lineage without deploying it immediately
* having the underlying storage for private keys be containerised in some way that is different/more secure than the storage of certificates

For those reasons, we are disinclined to switch to non-symlinks in `/etc/letsencrypt/live`.

**Comment by pde** [comment]
Also, I'm confused.  How can nginx use the certs in question without also having access to the private keys?  The more serious containerisation proposals I've heard seem to focus on keeping the key material and webservers for various sites separate from each other.

**Comment by geekscrapy** [comment]
Thanks for the clarification. nginx has access to its private key yes, but in the suggested application for a docker app it would have access to all the keys, but I guess this could be limited to volume exposure using the individual domain paths in etc/letsencrypt/live/*.
