### ISSUE TITLE
Letsencrypt-auto: line 106: [: too many arguments / CentOS 5.5

### ISSUE THREAD

**Issue by tkimnguyen** [letsencrypt/letsencrypt#2215]
Running "./letsencrypt-auto --help" on CentOS 5.5 I got the error
``
letsencrypt-auto: line 106: [: too many arguments
``
which is caused by Python 2.4 (the distro-supplied version) not recognizing "--version" but "-V"

**Comment by alex** [comment]
This looks like a dupe of #2039.

(On a personal note, please upgrade to a newer os)

**Comment by tkimnguyen** [comment]
Thanks, it is - sorry, had searched for "too many arguments" only in the issues.
