### ISSUE TITLE
Apache plugin fails with "cannot find a cert or key directive"

### ISSUE THREAD

**Issue by osirisinferi** [letsencrypt/letsencrypt#2216]
Hi,

For some reason, my Apache plugin broke since I updated everything to the latest Git versions (ACME, letsencrypt and letsencrypt-apache), commit 10214e2.

I already had a certificate for the domain, but when I say  "Attempt to reinstall" when asked, I get the following error:

    Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 1
    2016-01-18 01:17:25,897:INFO:letsencrypt_apache.configurator:Created an SSL vhost at /etc/apache2/vhosts.d/vhosts/le-test-05.example.com-le-ssl.conf
    2016-01-18 01:17:25,979:DEBUG:letsencrypt.reverter:Creating backup of /etc/apache2/vhosts.d/vhosts/le-test-05.example.com-le-ssl.conf
    2016-01-18 01:17:26,135:WARNING:letsencrypt_apache.configurator:Cannot find a cert or key directive in /files/etc/apache2/vhosts.d/vhosts/le-test-05.example.com-le-ssl.conf/IfModule/VirtualHost. VirtualHost was not modified
    2016-01-18 01:17:26,136:DEBUG:letsencrypt.error_handler:Encountered exception:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/letsencrypt/client.py", line 375, in deploy_certificate
        fullchain_path=fullchain_path)
      File "/usr/lib64/python2.7/site-packages/letsencrypt_apache/configurator.py", line 236, in deploy_cert
        "Unable to find cert and/or key directives")
    PluginError: Unable to find cert and/or key directives

    2016-01-18 01:17:26,137:DEBUG:letsencrypt.error_handler:Calling registered functions
    2016-01-18 01:17:26,139:DEBUG:letsencrypt.cli:Exiting abnormally:
    Traceback (most recent call last):
      File "/usr/lib/python-exec/python2.7/letsencrypt", line 9, in <module>
        load_entry_point('letsencrypt==0.2.0.dev0', 'console_scripts', 'letsencrypt')()
      File "/usr/lib64/python2.7/site-packages/letsencrypt/cli.py", line 1398, in main
        return args.func(args, config, plugins)
      File "/usr/lib64/python2.7/site-packages/letsencrypt/cli.py", line 563, in run
        lineage.chain, lineage.fullchain)
      File "/usr/lib64/python2.7/site-packages/letsencrypt/client.py", line 375, in deploy_certificate
        fullchain_path=fullchain_path)
      File "/usr/lib64/python2.7/site-packages/letsencrypt_apache/configurator.py", line 236, in deploy_cert
        "Unable to find cert and/or key directives")
    PluginError: Unable to find cert and/or key directives

    Unable to find cert and/or key directives

I find this very strange, as the content of the original `.conf` is just this:

    <VirtualHost *:80>
    Servername le-test-05.example.com
    DocumentRoot /var/www/vhosts/le-test-05.example.com/htdocs/
    </VirtualHost>

I've put *many* debug messages extra in `letsencrypt_apache/configurator.py`, `letsencrypt_apache/parser.py` and I think even in the Augeas python files, but to no succes.

The client successfully transforms the `.conf` file to the `-le-ssl.conf` file, i.e., add an `<IfModule>`, transform `*:80` into `*:443` and add the `SSLCertificateFile`, `SSLCertificateKey` (set to the temporary `insert_cert_file_path` and `insert_key_file_path` values resp.) and the `Include` to the basic LE option file.

Unfortunately, even with the mock directives added by `_add_dummy_ssl_directives()`, for some reason the `self.parser.find_dir("SSLCertificateFile", None, vhost.path)` command in `deploy_cert()` fails.. And I have no clue why. It is there.. It should be found by `find_dir()`. Augeas just added them!

Any clue/hints how I could debug this any further?

**Comment by pde** [comment]
@joohoi, any chance you have time to investigate this?

**Comment by joohoi** [comment]
Interesting, there doesn't seem to be any recent changes to functionality touching those parts. This sounds like an augeas problem to me, but let's not jump into too hasty conclusions.

Have you been debugging with just print messages? If so, the best way forward would be installing ipdb from pip to your venv and using it (ipdb drops you in an interactive debugger, makes debugging a lot easier). 

Also: does the test suite pass on your configuration?

**Comment by osirisinferi** [comment]
My Let's Encrypt doesn't run in a virtual environment. It's installed from Gentoos repository. I'll install `ipdb` and see what I can do with that :stuck_out_tongue: 

Also, I have no clue how to check the test suite, but I'll try to figure that out too :stuck_out_tongue_closed_eyes:

**Comment by joohoi** [comment]
@osirisinferi ah, right. sorry. See https://letsencrypt.readthedocs.org/en/latest/contributing.html#testing for the test suite stuff.

You could also clone the git repository, checkout the referred commit and do the venv dance; https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client

**Comment by osirisinferi** [comment]
Well, that's going to be a hassle I think:

    server letsencrypt # ./letsencrypt-auto-source/letsencrypt-auto --os-packages-only
    WARNING: Gentoo support is very experimental at present...
    if you would like to work on improving it, please ensure you have backups
    and then run this script again with the --debug flag!
    server letsencrypt # ./letsencrypt-auto-source/letsencrypt-auto --os-packages-only --debug
    Bootstrapping dependencies via Gentoo...
    ./letsencrypt-auto-source/letsencrypt-auto: line 330: : command not found
    server letsencrypt # 

I'll see what I can do..

BTW, `ipdb` doesn't "follow" envoked functions? At this point:

    ipdb> n
    > /usr/lib64/python2.7/site-packages/letsencrypt_apache/configurator.py(226)deploy_cert()
        225                 "cert_key": self.parser.find_dir("SSLCertificateKeyFile",
    --> 226                                                  None, vhost.path)}
        227 

I would *think* a debugger would follow the (two) `self.parser.find_dir()` functions, so I could debug the specific call from lines 223 and 225.. Otherwise, if you put `ipdb.set_trace()` *inside* `find_dir()`, it would execute every single time some function calls `find_dir()`.. And that's not very handy IMHO..

**Comment by osirisinferi** [comment]
I think I've found it (very nice piece of software, `ipdb`!):

In [`configurator.py`](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L219), `find_dir()` is called as followed:

    self.parser.find_dir("SSLCertificateFile", None, vhost.path)

And its definition is: `def find_dir(self, directive, arg=None, start=None, exclude=True)`

So what I didn't notice with my previous debug attempts was that `exclude` was `true`. For some reason I assumed it was `false` and ignored the `matches = self._exclude_dirs(matches)` part from `find_dir()`.

No with `ipdb` I've learned checks all loaded Apache modules and checks if the directive in question isn't "encased" in an `<IfModule>` which *isn't* loaded..

Now, to the Gentoo-part: as I've made clear many times, Gentoo doesn't have the Debian style `enmod` and `dismod`. It uses `<IfDefine>` sections in the `loadmodule` part of `httpd.conf` and the `-D` switches for those `<IfDefine>`s are added to the command in the configuration file `/etc/conf.d/apache2` of the init script.
The Let's Encrypt client doesn't consider those `-D` switches from the `conf.d` file, so `mod_ssl` is never loaded, as far as Let's Encrypt is concerned. Therefore, `_exclude_dirs()` will return `false` and everything fails..

**Comment by joohoi** [comment]
Nice that you found the source!

But to the subject itself: the configuration differences in Gentoo are wild and many. enmod / dismod functionality is actually disabled in Gentoo, and pretty much every other distro than Debian / Ubuntu. 

While pretty much every distribution have their own way of enabling Apache modules (symlinks in various directories, command line parameters etc) I think the only reasonable way forward is to document the requirements rather than building complex methods per OS basis to parse configuration files. It gets scarier when we need to write into those configurations based on a vague OS fingerprinting.

So my suggestion: let's add more documentation.

**Comment by joohoi** [comment]
To inspect the case with Gentoo a bit further:

If we would completely automate this on Gentoo, we'd have to make sure that user has built Apache with ssl USE-flag, adding the flag if not + rebuilding Apache & all the deps, making sure that the conf.d/apache (or was it httpd, have forgotten) has the -D SSL parameter defined. Most (if not all) of this belongs to the realm of OS based packaging in my view, and we can point the users to the right direction with documentation.

**Comment by osirisinferi** [comment]
Well, that's not so bad a solution I guess. If you're running Gentoo, you'll probably figure things out with a few pointers here and there.. :smile: 

From the code I see `init_modules()` uses Augeas to search for `LoadModule` directives.. So it'll probably ignore the `<IfDefine>`s anyway, even if you'd set those `-D` switches in `constants.py` or something.. :disappointed:

**Comment by joohoi** [comment]
Do you want to write down the documentation parts? The relevant place would be: https://github.com/letsencrypt/letsencrypt/blob/master/docs/using.rst#operating-system-packages

or should I?

**Comment by osirisinferi** [comment]
In https://github.com/letsencrypt/letsencrypt/pull/2117 I also added some documentation to `using.rst`. I could elaborate on the proper usage of the client on Gentoo, i.e., not out of the box, but needs some tweaking.. 

Probably some time tomorrow or this weekend.

**Comment by joohoi** [comment]
Ok, great!

**Comment by pde** [comment]
I'm going to close this ticket now; it sounds like we've mitigated it as much as we can from upstream, and further work needs to be done by gentoo packagers.
