### ISSUE TITLE
Feature Request: Allow certs for bare IP address

### ISSUE THREAD

**Issue by snakecharmer1024** [letsencrypt/letsencrypt#2217]
Basically, I'm trying to integrate letsencrypt with streisand, an anti-censorship project https://github.com/jlund/streisand

The code sets up a lot of things for the user, but users still have to download a cert and install it in their browser to use it, so I thought maybe letsencrypt could help. Problem is streisand is designed to work without a domain.

I'm not an expert in this area, so maybe this is not a good proposal, but I know it's possible to associate a cert with an IP address. It seems like it might not be a good idea, since you might be able to mitm traffic sent to an ip after you no longer control it...altho if that's true, it would also be true of domains...

Any help understanding this?

**Comment by pde** [comment]
This is not a client feature request.  Please discuss on https://community.letsencrypt.org.

**Comment by laukstein** [comment]
I agree that Web would be safer if LE would accept IPs too, has decided to accept only DNS.

> https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082/6
> Let's Encrypt has decided not to issue certificates for bare IP addresses even if this would be permitted by the Baseline Requirements.
