### ISSUE TITLE
Please, make Let's Encrypt client less intrusive

### ISSUE THREAD

**Issue by bviktor** [letsencrypt/letsencrypt#2229]
I think we can agree on that reducing the attack surface should be a principle everyone should follow. That means install the least amount of packages that still lets you get things done. Now if I do a mere

    # letsencrypt-auto --help

It installs the following packages:

    python-devel python-virtualenv gcc libffi-devel openssl-devel redhat-rpm-config cpp dwz glibc-devel glibc-headers kernel-headers keyutils-libs-devel krb5-devel libcom_err-devel libmpc libselinux-devel libsepol-devel libverto-devel mpfr pcre-devel perl-srpm-macros zip zlib-devel

**without even asking**. `yum -y` all the way. If I do this as a sudoer _user_, it still becomes root in the blink of an eye, everything's run with `sudo`.

If you think it's acceptable to install compilers and a lot of libs and headers on each and every web server for... running a Python script, that's totally up to you. But please, at least ask us if we really want that.

Now, this wouldn't bother me this much if there was a way to set up a single, isolated VM which I could use to request certificates for all our servers. Except I, of course, can't do that. The script needs to be run on the server that'll serve those domains.

I personnaly erased all these packages and reverted to our Comodo certs for now and by the look of things, it'll stay that way. I want to make it clear that I'm not _complaing_ - it wouldn't even make any sense since you're giving away certs for free, which is awesome. This is merely a suggestion that you may or may not consider.

I do believe that most admins would greatly appreciate if letsencrypt came in the way of

a) a single binary - IIRC there are tools for doing that in Python but FIXME
b) a self-contained Python script - e.g. does serving HTTP requests, amongst other, mostly simple things really require kernel headers and a C compiler in Python? I doubt it.

iinstead of a script that

a) installs a lot of bloat on web servers
b) sets up a Python virtual environment... somewhere, that may be trivial for you python guys but not for the average nginx admin and honestly, I really don't have the interest or desire to deal with it
c) installs packages via pip

Thanks in advance.

**Comment by kuba** [comment]
FYI #334 and https://github.com/kuba/letsencrypt/tree/pyinstaller.

**Comment by bviktor** [comment]
Hm, so if it's that simple, why can't I download a binary from the letsencrypt project? Could this be on the TODO list?

**Comment by pde** [comment]
`letsencrypt-auto` isn't the letsencrypt client, it's an auto-updating shim for the client that stands in for packaging if your OS doesn't provide it yet.  We've been working hard to support OS packaging in the hope of making it obsolete on as many platforms as we can, as quickly as we can.

**Comment by pde** [comment]
Probably in retrospect we should have supported some kind of "setup" or "install" command for `letsencrypt-auto`, or we should change the docs around it a little, but we can't change its behaviour now because a lot of people now expect it to work in that way.

**Comment by kuba** [comment]
OS packaging? PPA's (#1706) haven't been looked at even, it seems. :(

**Comment by pde** [comment]
Harlan said on last week's call that they were on the way shortly, and that the "only thing" blocking a jessie backport was the need for a sphinx backport :(

**Comment by pde** [comment]
In any case, this duplicates #1903 and #1286.

**Comment by pde** [comment]
@bviktor if you're on CentOS 7 / RHEL 7 / Fedora 23, packages for your OS should be on the way fairly soon; that's the real solution for your request: 
https://bugzilla.redhat.com/show_bug.cgi?id=1288743

**Comment by bviktor** [comment]
Oh, thanks for the info. If those packages won't install the same headers/compilers/whatever I guess we plants are happy plants.

**Comment by bviktor** [comment]
Guys, I just wanted to say thank you for this happening so quick. The EPEL package works great.

[Let’s Encrypt now available via EPEL](http://vault-tec.info/post/138010816051/lets-encrypt-now-available-via-epel)
