### ISSUE TITLE
Infinite loop generating manual cert

### ISSUE THREAD

**Issue by ffxsam** [letsencrypt/letsencrypt#2234]
I get stuck in an infinite loop where it asks me the question about if I'm ok with my IP being logged, to which i say yes. Then I set up the proper .well-known/acme-challenge file as it requests. It says Press ENTER, which I do, and then the "are you ok with being logged" comes up again, and it generates a new acme challenge. Repeat, ad infinitum. What's going on??

**Comment by bmw** [comment]
It shouldn't be an infinite loop and is instead bad UI. I believe this is a dupe of #1032. Please correct me if I'm wrong.

**Comment by ffxsam** [comment]
Ah, nope.. user error! My mistake.
