### ISSUE TITLE
关于openssl版本

### ISSUE THREAD

**Issue by etuan-ck** [letsencrypt/letsencrypt#2242]
你好，我在执行./letsencrypt-auto 的时候，会报错
ImportError: /root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GROUP_new_curve_GF2m
不知道是不是和openssl的版本有关，因为我发现脚本自动安装了openssl-devel1.0.1e，而我的服务器上面的openssl是源码编译安装的openssl1.0.2d版本，如果是这个问题，请问该如何解决呢？
谢谢~

**Comment by etuan-ck** [comment]
centos7 +openssl 1.0.2d(Source Package)
error:
ImportError: /root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GROUP_new_curve_GF2m

**Comment by tcz001** [comment]
可以尝试修改PATH等环境变量，另外建议用英文提问，以便团队答复

**Comment by tcz001** [comment]
Maybe also related with https://github.com/letsencrypt/letsencrypt/issues/2122

**Comment by etuan-ck** [comment]
英文不好，怕描述不清。问题未解决，我换了另一种工具申请完成了！
