### ISSUE TITLE
VersionConflict: ConfigArgParse 0.9.3

### ISSUE THREAD

**Issue by bogdanb** [letsencrypt/letsencrypt#2243]
Hello,

I tried renewing our certificates today, and I got an error from letsencrypt-auto. The error message was:

VersionConflict: (ConfigArgParse 0.9.3 (/home/bogdanb/.local/share/letsencrypt/lib/python2.7/site-packages), Requirement.parse('ConfigArgParse>=0.10.0'))

Please see the two attached files for the logs:
[execution.log.txt](https://github.com/letsencrypt/letsencrypt/files/97381/execution.log.txt)
[letencrypt.log.txt](https://github.com/letsencrypt/letsencrypt/files/97383/letencrypt.log.txt)

This is after I had deleted the ~/.local folder where letsencrypt stores its downloads. (I had the same exception before.) This is on an Ubuntu 15.04 machine:

$ uname -a
Linux qotilabs-dime 2.6.32-042stab112.15 #1 SMP Tue Oct 20 17:22:56 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bmw** [comment]
I believe this is due to the limitations of the current `letsencrypt-auto` script. The script does not update itself and it appears that `letsencrypt-auto` scripts downloaded before [December 22nd](https://github.com/letsencrypt/letsencrypt/pull/1908) don't play nicely with the new 0.2.0 release.

You should be able to fix this by deleting `~/.local/share/letsencrypt`, doing a `git pull` to get a new version of `letsencrypt-auto`, and then running the script again.

**Comment by pde** [comment]
If there's nothing we can put into `setup.py` to leave both py26 and old copies of leauto unbroken, we should consider vendorising ConfigArgParse.  But I'm still a bit confused about how this error wasn't caught by [test_leauto_upgrades.sh](https://github.com/letsencrypt/letsencrypt/blob/master/tests/letstest/scripts/test_leauto_upgrades.sh)

**Comment by pde** [comment]
Oh, no, I do see the bug there.  That script uses the old pip release, but the newer version of `letsencrypt-auto` :( :( :(

**Comment by pde** [comment]
A few possible strategies:
 * vendorize ConfigArgParse (but a lot of folks want us not to do this, especially for easier packaging)
 * relax the versioned dependency to `>= 0.9.3`.  If that would break anything, try to work around it in Python?

**Comment by pde** [comment]
Conclusion: we're going to tweak @kuba's custom release of ConfigArgParse to version 0.10.0, meaning that the problem (and solution) are only visible to old installs of letsencrypt-auto.

**Comment by pde** [comment]
Further diagnostics.  This affects users who installed `letsencrypt-auto` before December 22nd, but only when they supply the `-v` or `--verbose` flags, because pip is invoked slightly differently if they do.

**Comment by duckduckquack** [comment]
So... is there a way to fix this? I'm on Jessie 8.7

**Comment by erikrose** [comment]
@duckduckquack Looks like a different issue to me. Go ahead and open a new issue, and please include what you ran to trigger the crash. Thanks!

**Comment by jeffmcneill** [comment]
Run this and it should fix things:
    rm -rf /opt/eff.org
