### ISSUE TITLE
letsencrypt.log should not be truncated with each run

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#2245]
Right now, each run of letsencrypt truncates the existing letsencrypt.log. Instead we should always append to letsencrypt.log. That way on systems that run letsencrypt repeatedly in an automated way, errors from earlier invocations are not obliterated by later invocations.

**Comment by kuba** [comment]
`letsencrypt.log` is being rotated every time `letsencrypt` binary is run, and hence you can still find them in `letsencrypt.log.X`

**Comment by jsha** [comment]
Excellent, thanks. That makes a lot of sense, and is a better solution than what I proposed.

**Comment by bmw** [comment]
When I read this, I actually thought it was about the `letsencrypt.log` file created in your working directory if an error occurred before the client set up logfiles (almost certainly due to invalid permissions). This file is overwritten but perhaps we should append to the file?
