### ISSUE TITLE
.keepdir mistaken for renewer config

### ISSUE THREAD

**Issue by hlieberman** [letsencrypt/letsencrypt#2254]
When running letsencrypt for a renewal, it seems that the client confuses the .keepdir file installed to prevent the directory for being deleted for a configuration file.

The command: `letsencrypt certonly --webroot --webroot-path /var/www/html -d ...` ends up erroring with:

```

┌──────────────────────────────────────────────────────────────────────┐
│ Renewal configuration file /etc/letsencrypt/renewal/.keepdir is      │
│ broken. Skipping.                                                    │
│                                                                      │
└──────────────────────────────────────────────────────────────────────┘
```

Why is the .keepdir file distributed?

**Comment by xtaran** [comment]
It actually also happened to me (the [original reporter over at Debian](https://bugs.debian.org/812223)) with e.g. `letsencrypt certonly --standalone -d …`

**Comment by pde** [comment]
The solution for this is to have `storage.py` only pick up files specifically ending in `.conf`.

**Comment by schoen** [comment]
I think this will fix it, let's just see if the new `continue` is missing test coverage.
