### ISSUE TITLE
Apache plugin should check that the challenge-location is parsed by Apache

### ISSUE THREAD

**Issue by joohoi** [letsencrypt/letsencrypt#2259]
We should be able to find out if the location that the challenge configuration file is written isn't parsed by apache by inspecting the Apache include paths from augeas tree. 

If the challenge location isn't parsed by apache, print out meaningful error message to the user (suggesting to use --apache-challenge-location /path/parsed/by/apache).

**Comment by joohoi** [comment]
Currently the error the user runs into if the path isn't parsed isn't very informative, example from a system where there already is another active SSL enabled vhost:

```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.attempted.domain.example.com
   Type:   urn:acme:error:unauthorized
   Detail: Correct zName not found for TLS SNI challenge. Found
   'already.existing.ssl.host.tld'

   Domain: attempted.domain.example.com
   Type:   urn:acme:error:unauthorized
   Detail: Correct zName not found for TLS SNI challenge. Found
   'already.existing.ssl.host.tld'
```

**Comment by pde** [comment]
Oh, this is the likely cause of the CentOS 6 error in #2256...

**Comment by pde** [comment]
@bmw tells me that he's kind of confused by the presence of this bug, because we should be adding an explicit `Include` to the main apache conf pointing straight at the synthetic vhost's file.  Is the problem that we sometimes don't have a reference to the main conf file at all?

**Comment by SwartzCr** [comment]
This bug happens when we try to run the challenge but the explicit `Include` line hasn't been added to/or has been removed from the apache conf file. This was happening earlier due to an augeas bug.
That has since been fixed, but it's possible that we want a better error message - for example we can add a check to see the include is there after the reload

**Comment by joohoi** [comment]
Yeah, that seems like a good way forward. This problem was fixed in my environment by #2256 . 
It was an augeas bug, so I think we can just trust that the Include will be added in the future. LE could error out (if it's not already doing that) with more precise error message if the Include statement can't be added. 

This issue can be closed when @bmw confirms the issue that he reported for Ubuntu 12.04 in #2256 solved.

**Comment by bmw** [comment]
Yes. The issue I reported in #2256 for Ubuntu 12.04 is fixed in master so I'm closing. Thanks for the input @joohoi.

**Comment by SwartzCr** [comment]
I started a branch to make a better error message but conf values are being fiddly, so I'm going to shelve it for now and work on something more pressing
