### ISSUE TITLE
Manual Certificate Renewal

### ISSUE THREAD

**Issue by WinPack** [letsencrypt/letsencrypt#2260]
Hi. I used the following command to issue my certificate:

./letsencrypt-auto certonly --email (mail-here) --webroot -w /var/www/ --webroot-map (map-here) --csr (DER-CSR-here)

How can I renew that certificate? Because I have seen that renewals are possible when --apache is set, but I don't want LE client to affect my apache configuration at all.

**Comment by bmw** [comment]
@WinPack, our [renewal documentation](https://letsencrypt.org/howitworks/#renewing-a-certificate) should answer your question. In short, just run the same command again!

Additionally, questions like this are better suited for our [community forum](https://community.letsencrypt.org) and issues on this repo should be saved for reporting problems with the client.

Hope this helps!

**Comment by WinPack** [comment]
@bmw I haven't noticed there is such documentation, but thanks a lot for helping me out!! :)

**Comment by andreymal** [comment]
@bmw but why? How about something like `certbot-auto renew --non-interactive`?

"just run the same command again" is very uncomfortable!

**Comment by bmw** [comment]
Mainly because my response was written before we had a `renew` subcommand. With that said, `renew` still wouldn't work in this scenario. See #3690.
