### ISSUE TITLE
[LE.org/howitworks] Unavailable switch mentioned in documentation

### ISSUE THREAD

**Issue by osirisinferi** [letsencrypt/letsencrypt#2269]
In the [How It Works: Renewing a Certificate](https://letsencrypt.org/howitworks/#renewing-a-certificate) on the LE homepage, the switch `--keep-until-renewal` is mentioned. However, this switch isn't available in the LE client, it's called `--keep-until-expiring`. This unfortunately apparently [confuses people](https://community.letsencrypt.org/t/renew-not-working/9383).

I can't find the content of that page anywhere on GitHub; otherwise I would have made a PR.. :stuck_out_tongue:

**Comment by bmw** [comment]
Thanks a lot for pointing this out @osirisinferi. The repo for https://letsencrypt.org is private, but I just created a PR to fix the problem.

**Comment by bmw** [comment]
Fixed. Thanks again!
