### ISSUE TITLE
Cert file location for domains with multiple SANs

### ISSUE THREAD

**Issue by silverwind** [letsencrypt/letsencrypt#2270]
Very minor issue, but when I ran `letsencrypt certonly` with domains like

```ini
domains = example.com, www.example.com, a.example.com, b.example.com, c.example.com
```

I expected that the cert files would go into `/etc/letsencrypt/live/example.com`, but to my surprise they actually went into `/etc/letsencrypt/live/a.example.com`.

For a better location, I'd suggest either using the first domain name specified, or the root domain if all domains are subdomains.

**Comment by bmw** [comment]
Had you either:
a) Obtained a certificate for these exact domains before?
b) Obtained a certificate for a subset of these domains containing `a.example.com` and either included `--expand` on the command line or chosen expand at a prompt like this:
```
-------------------------------------------------------------------------------
You have an existing certificate that contains a portion of the domains you
requested (ref: /etc/letsencrypt/renewal/a.example.com)

It contains these names: a.example.com

You requested these names for the new certificate: example.com, www.example.com, a.example.com, b.example.com, c.example.com

Do you want to expand and replace this existing certificate with the new
certificate?
-------------------------------------------------------------------------------
(E)xpand/(C)ancel: 
```
Otherwise, you should get the behavior that you suggested of using the first specified domain name.

**Comment by silverwind** [comment]
Indeed, I did obtain a Non-SAN certificate for `a.example.com` before and I think I even got that notice.

Thanks for your help, I'll delete my existing certs before next renewal and see how that goes.
