### ISSUE TITLE
renewal instructions need help

### ISSUE THREAD

**Issue by JohnDenker** [letsencrypt/letsencrypt#2271]
#### Observed text:
At https://letsencrypt.org/howitworks/#renewing-a-certificate it says:
> To renew a certificate, simply run letsencrypt again providing the same values when prompted. In almost all circumstances, renewal should be performed with the certonly subcommand

**BUG:** In that passage, the second sentence contradicts the first.

Also it is not nearly as detailed as it should be.

#### Suggested improved text:

Except as noted below, the process of renewing a certificate is closely parallel to the process you used for generating the certificate initially.  Some exceptions and related observations are:
* The main exception is that if you initially used letsencrypt in **run** mode (which is the default), you should use **certonly** mode for the renewal.  This will add the new certificate into the /etc/letsencrypt/archive/$NAME/ directory, and update the symlinks in /etc/letsencrypt/live/$NAME/.
  * The web server (and anything else that references only the symlinks) should work without further effort.
  * On the other hand, any postprocessing or customization you performed initially may have to be repeated. 
    *  For example, if you added custom DH parameters to the end of the cert.pem file, you will have to repeat this.
    * Similarly, if you copied the *.pem files somewhere else so they could be used by your SMTP server (not just your web server), you will have to repeat this.
* If you initially used the **certonly** mode, you should use **certonly** mode for the renewal.
  * Any postprocessing or customization may have to be repeated, as discussed above.
* If your certificate covers multiple domain names, bear in mind that the certificate files are named after the first domain mentioned on the command line, as discussed in item #1376.  Therefore you should make sure the renewal mentions the same domain first;  otherwise letsencrypt will think you are asking for a new, unrelated certificate.
* It is possible to renew the certificate using different parameters on the command line.  If the differences are not too extreme, the new certificate will function as a replacement for the old.
  * For example, if your server has multiple domain names, you can mention more or fewer aliases in the renewal.  Letsencrypt will warn about this (unless you specify the --expand option).
  * If you don't remember what domain names you specified initially, you can figure it out by examining the old certificate.
    *  One way to do this is by using a browser.  Visit your site, then click on the :lock: padlock icon next to the URL.
    * Another way is to use a command like this:
```
:;  :| openssl s_client -CApath /etc/ssl/certs -connect $NAME:443 \
        | openssl x509 -text -noout  |& egrep -C1 'Subject:|Name:|After.:'
# or you can read the certificate file directly:
:;  cat /etc/letsencrypt/live/$NAME/cert.pem \
        | openssl x509 -text -noout  |& egrep -C1 'Subject:|Name:|After.:'
```
* If you have multiple certificates with the same first name, the renewal process is ambiguous.  The best way to deal with this is ???????????? (FIXME).

**Comment by pde** [comment]
> If your certificate covers multiple domain names, bear in mind that the certificate files are named after the first domain mentioned on the command line, as discussed in item #1376. Therefore you should make sure the renewal mentions the same domain first; otherwise letsencrypt will think you are asking for a new, unrelated certificate.

That is a very alarming claim. `storage.py` should compare sets of domains, not ordered lists of them.  But it cares about ordering, that's a serious and urgent bug.

**Comment by schoen** [comment]
@pde, the code in `cli.py` that should guarantee that renewal behavior is triggered independent of the order in which the names are specified to the client is at

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L208

In particular, the use of `set()` is meant to guarantee that order doesn't matter here. @JohnDenker, do you have a reproducible way to trigger some other behavior in the client?

**Comment by pde** [comment]
> Similarly, if you copied the *.pem files somewhere else so they could be used by your SMTP server (not just your web server), you will have to repeat this.

I guess that is due to incompatible permissions demands between some SMTP and some webservers? :(

**Comment by JohnDenker** [comment]
The guess about conflicting permissions is correct.

BTW the fact that letsencrypt certificates work for SMTPS and for STARTTLS is a Nice Thing. 
It's a bit odd that the only way to get a mail-server certificate is to ask for a web-server certificate ... but that's a small price to pay for a perfectly good mail-server certificate.

Maybe this ought to be documented somewhere.

**Comment by JohnDenker** [comment]
As for the ordering and naming issue:  I have not experimented with how the client behaves.  I previously asked a question about this, and assumed the previous answer was correct;  see item #1376.

In any case, somebody who knows what's really going on should document it explicitly, both as part of the renewal instructions and as part of the description of the -d option.  This includes discussing the case of overlapping but inequivalent sets of names.  This includes discussing the case where the intent is an expansion, and the case where the intent is to create an independent co-existing certificate.

A stated goal of the project is to make it user-friendly, even for non-experts.   A lot of users don't like to experiment with security-related stuff.  They prefer to know in advance what it's going to do.

**Comment by schoen** [comment]
@JohnDenker, I agree about the clarity of the documentation, and thank you for pointing that out.

With regard to #1376, the behavior @bmw describes applies when a totally new cert is created (that doesn't overlap with existing names), but not when a cert is renewed (by overlapping with the names in an existing cert). There is logic in `client.py` related to the lineage naming of new certs

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/client.py#L301

-- here the `domains[0]` selects the first name in the list as the base name for the certificate lineage -- and in `cli.py` for treating identical cert requests as renewals regardless of the order in which the domains are mentioned

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L208

-- here `set()` ignores the order in which the certs were specified to the client when comparing them against each previously-obtained cert.

And yes, I'm not at all sure that a user would anticipate this behavior on the basis of our current documentation.

**Comment by JohnDenker** [comment]
Let me ask a couple of questions about specific use-cases.

*  By way of background, suppose I start from a clean slate and create a certificate where the CN is ``www.example.com``, while ``mail.example.com`` is mentioned as a SubjectAltName.  I assume this is easy and routine.  Call this certificate A.

*  Similarly, restarting from a blank slate, I create a certificate where the roles are reversed.  That is, the CN is ``mail.example.com``, while ``www.example.com`` is mentioned as a SubjectAltName.  I assume this is easy and routine.  Call this certificate B.

1.  Suppose that rather than restarting from a clean slate, I want to create certificate A **and** certificate B, so that both exist and are usable at the same time.  There are plenty of plausible motivations for doing this;  for example, I might want to use one on port 443 and the other on port 25 via STARTTLS.  **QUESTION**:  Is this possible?  How does the letsencrypt command know that I intend to create certificate B, rather than renewing certificate A?

2.  Assume both certificates have been created and some time has passed.  It is now necessary to renew one of them.  **QUESTION**: How does the letsencrypt command know which one I intend to renew?


I understand that a major goal of the project is to make it easy to use in the typical case ... which does not mean that atypical cases will be equally easy.  The cases considered here are only slightly atypical, not implausible, not crazy.  Is there a systematic way of handling them?

**Comment by pde** [comment]
Numerous docs are now in the tree, a few more will be landing after release.
