### ISSUE TITLE
 renewal notice : email should sequence the domain names correctly

### ISSUE THREAD

**Issue by JohnDenker** [letsencrypt/letsencrypt#2273]
#### Background

Suppose a certificate was created using a command of the form
> letsencrypt-auto run -d www.example.com -d example.com ....

Note the order in which the domain names appear.

#### Observed behavior

The renewal email mentions the relevant domain names in some wacky order:
> example.com, www.example.com

#### Desired behavior

* It should mention them in the correct order ... at least with the correct name first.  This is important, because the certificate files are named after the **first** domain name mentioned on the command line, as discussed in item #1376.

* The email should be even more explicit:  It should say like:
> To renew the same set of domain names, pass the following options on the command line:
> -d www.example.com -d example.com

**Comment by bmw** [comment]
@jsha, how is the order of domain names in the expiration e-mail chosen?

**Comment by jsha** [comment]
It's the same order in which the DNSNames section of the certificate is listed. However, that order is random.

**Comment by bmw** [comment]
Since this is a boulder issue, I opened an issue at letsencrypt/boulder#1454 and am closing this issue.
