### ISSUE TITLE
Do not save default values to renewal configuration files

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2277]
If a client configuration parameter is set to its default value and wasn't specified by the user in some way, it shouldn't be saved into the renewal configuration at all. If it was derived from another configuration file, we can allow it to be derived from that file again rather than saved in a duplicative way.

**Comment by schoen** [comment]
Related to #2503.

**Comment by pde** [comment]
It's probably a good idea to do something like this:

if you have a default value for a config entry, and the RCF is new or does not contain the string for that entry anywhere, add a comment to the RCF showing that that setting is available.  Eg:

# DEFAULT VALUES
# rsa-key-size = 2048

**Comment by bmw** [comment]
Also see #421 for more context.

**Comment by bmw** [comment]
Closed in #2663.
