### ISSUE TITLE
Download to the CA Certificate File

### ISSUE THREAD

**Issue by ghost** [letsencrypt/letsencrypt#2283]
I'd like to add LetsEncrypt to my Java program for HttpsUrlConnections to work properly.

Where can I download the file to generate the X509Certificate with?

**Comment by schoen** [comment]
Hi,

This issue tracker is for issues with our Python client, so I don't think this question belongs here. You could try again on the Let's Encrypt Community Forum, which is for all Let's Encrypt related questions.

https://community.letsencrypt.org/

If you're just looking for the Let's Encrypt CA intermediate certificate, you can find it at

https://letsencrypt.org/certificates/

We are currently issuing under Let's Encrypt Authority X1.
