### ISSUE TITLE
Support for QNAP servers?

### ISSUE THREAD

**Issue by xorcus** [letsencrypt/letsencrypt#2287]
I have a QNAP NAS server at home and would like to issue a cert for the apache web server running on it. Unfortunately, the prerequisites seem to be unavailable and must be manually installed.

Is it posible to issue the cert in a VM running e.g. Ubuntu on a laptop and then copy the cert to QNAP NAS?

**Comment by schoen** [comment]
Hi @xorcus,

Probably! Please try asking in the Let's Encrypt Community Forum at https://community.letsencrypt.org/
