### ISSUE TITLE
Who signs the letsencrypt packages listet on PyPi

### ISSUE THREAD

**Issue by weberhofer** [letsencrypt/letsencrypt#2297]
I'd like to verify the signatures. Can you provide the key?

**Comment by bmw** [comment]
Signatures are made by key specifically for this purpose. Fingerprint is: A2CFB51FA275A7286234E7B24D17C995CD9775F2

**Comment by weberhofer** [comment]
Can you also provide the public key?

**Comment by bmw** [comment]
It should be on all major keyservers, but I've also attached it to this comment.

[release-key.txt](https://github.com/letsencrypt/letsencrypt/files/107836/release-key.txt)
