### ISSUE TITLE
Renewer test farm tests

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2302]
We need these.

**Comment by SwartzCr** [comment]
made a simple test: https://github.com/letsencrypt/letsencrypt/commit/1c52e1982ccb580e5bc4a3e0d28902c4865fe7e0
got:
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 pass
9 amazonlinux-2015.03.1 pass
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
13 centos6 pass

**Comment by pde** [comment]
Nice!  Make a PR for it?

**Comment by bmw** [comment]
fixed in #2338
