### ISSUE TITLE
Renewer.py not working since update (object has no attribute 'webroot_map')

### ISSUE THREAD

**Issue by driskell** [letsencrypt/letsencrypt#2311]
I've attempted to run `renewer.py` (am I meant to?)

It used to run through perfectly and just not renew anything. I never actually got to test it renewing automatically. However, recently I updated the letsencrypt repository and it no longer works now that a renewal is due. It fails with a stack trace:

```
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt-renewer", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/renewer.py", line 203, in main
    renew(cert, old_version)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/renewer.py", line 90, in renew
    authenticator.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/plugins/webroot.py", line 49, in prepare
    path_map = self.conf("map")
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/plugins/common.py", line 66, in conf
    return getattr(self.config, self.dest(var))
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/configuration.py", line 47, in __getattr__
    return getattr(self.namespace, name)
AttributeError: '_AttrDict' object has no attribute 'webroot_map'
```

Seems a new config entry was added but my conf files don't contain it. Any thoughts on updating the conf file?

**Comment by bmw** [comment]
`renewer.py` has been abandoned for the time being and it should not be run. Perhaps we should look into removing it from our tree or having it exit early with a nice error message.

A new method of renewing your certificates with the client should be announced in the next week or so.

**Comment by pde** [comment]
Meanwhile, https://letsencrypt.org/howitworks/#renewing-a-certificate

**Comment by driskell** [comment]
I did actually manage to fix the renewer.py. Just needed to generate webroot map where it was missing, and then fix an issue in the reading of domain from existing certificate returned unicode and the CSR generator didn't like it. Then it worked seamlessly.

I liked the concept of it because I didn't need to know what certificates were setup on the server, and simply run the script once, and it would automatically pick up the certificates from the configurations in place and renew any requiring renew. At the time keep-until-expiry didn't exist but now that's there it shouldn't be too much to update configuration management to setup separate scripts for renewals.

@bmw Are there any issues I can track to see an overview of the new method?

**Comment by bmw** [comment]
Yes. Keep an eye on #2304. It's functionality will be very similar to `renewer.py`.

**Comment by driskell** [comment]
Thanks. I'll close this.

I also had a problem with urllib3 doing unverified SSL requests which doesn't seem to be a problem with the main client so maybe it's worth you guys removing renewer.py completely for now as it's potentially a security issue if used.
