### ISSUE TITLE
OpenNIC TLD support

### ISSUE THREAD

**Issue by meZee** [letsencrypt/letsencrypt#2321]
Similar to #91 except for https://opennicproject.org and their alternative DNS root

**Comment by flyingrub** [comment]
+1

**Comment by schoen** [comment]
Hi,

I don't believe the CA/B Forum rules allow us to issue for names that could have a conflicting meaning from their meaning in the ICANN root. I would like to see other mechanisms for naming on the Internet that aren't the existing hierarchical DNS -- I think that's very valuable! -- but if we're going to issue certs from a CA that browsers trust, the browsers are going to want to see evidence that that won't lead to any ambiguity with the mainstream DNS (which is part of the reason for RFC 7686).

**Comment by berrythesoftwarecodeprogrammar** [comment]
why would there be any conflicting meaning?
