### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by SunboX** [letsencrypt/letsencrypt#2329]
Got this email today:

> Hello,
> 
> Your certificate (or certificates) for the names listed below will expire in **1 days** (on 2016-02-02 15:56:00 +0000 UTC). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.
> 
> xxx
> 
> For any questions or support, please visit https://community.letsencrypt.org/. Unfortunately, we can't provide support by email.
> 
> If you are receiving this email in error, unsubscribe at http://mandrillapp.com/track/unsub.php?u=xxx. (HTTP link, we know. We're working on it!)
> 
> Regards,
> The Let's Encrypt Team

I logged in to my server and run

```bash
xxx@xxx /opt/letsencrypt $ sudo git pull
```

And than

```bash
xxx@xxx /opt/letsencrypt $ sudo ./letsencrypt-auto --apache
Updating letsencrypt and virtual environment dependencies...Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/usr/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: No module named _io
```

So now what? Wait until tomorrow?

**Comment by SunboX** [comment]
re-installed python with ...

```bash
xxx@xxx /opt/letsencrypt $ sudo apt-get purge python2.7*
xxx@xxx /opt/letsencrypt $ sudo apt-get install python python-dev
```

... didn't fix it.

**Comment by schoen** [comment]
> ```
>     import _io
> ImportError: No module named _io
> ```
> 
> So now what? Wait until tomorrow?

Hi André, it looks like other people had this problem before:

https://community.letsencrypt.org/t/cant-use-letsencrypt-auto-importerror-no-module-named--io/2345/3

**Comment by schoen** [comment]
The solution that worked in the forum thread was about deleting the
pre-existing Let's Encrypt virtualenv (in ~/.local/share/letsencrypt),
and then re-running letsencrypt-auto, rather than re-installing Python.
(Re-installing Python was my first suggestion in that thread but turned
out not to be relevant.)

**Comment by SunboX** [comment]
Hey @schoen, thanks a lot! This seems to work:

```bash
xxx@xxx /opt/letsencrypt $ sudo rm /root/.local/share/letsencrypt -R
```

But why? It worked some time ago and I didn't change anything? If I have only one day to re-new my certificate and come across such an error ... that's not good.

**Comment by SunboX** [comment]
I will close this, it's working now. But someone should look into it. If necessary, plz re-open this issue.

**Comment by schoen** [comment]
I agree that this is a problem and that this behavior shouldn't happen,
and I'll file a separate bug about it.  I'm sorry for the inconvenience
to you.

**Comment by SunboX** [comment]
Thanks for your fast response, now my ownCloud runs tomorrow :smirk: the reminder e-mail should have come as copy two days earlier. Than it would not have been such a big problem.
