### ISSUE TITLE
Make a default renewal script in /etc/letsencrypt/

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#2331]
Perhaps it should be `/etc/letsencrypt/renew-certs`?  It can call the new `letsencrypt-renew` command, but is also a good place for pre and post renewal homework.

**Comment by bmw** [comment]
> 14:12:04       +bmw | So after thinking about the renewal script during lunch, I'm not sure how much it buys us.
14:12:22       +bmw | As we know from user data, in the most common case, people are using the Apache plugin.
14:12:40       +bmw | In this case, all they have to do is call `letsencrypt renew` and everything will work.
14:13:33       +bmw | The only time it benefits the user is when using they used webroot/standalone.
14:14:08       +bmw | Both need to restart the server afterwards and you may need to stop your server before running standalone.
14:14:44       +bmw | How much better is it to have all of this variation in comments in this renewal script vs mentioning `letsencrypt renew` and pointing them to the documentation for more help.
14:15:13       +bmw | Anyone who actually needs the extra script will have to edit by hand anyway.
14:15:51       +bmw | The benefits to pointing them to documentation are:
14:15:57       +bmw | 1) No added complexity of a second script
14:16:37       +bmw | 2) We can change documentation without another release
14:16:51       +bmw | 3) How would we update this proposed renewal script?

**Comment by pde** [comment]
Still debating to what extent this is a good idea, or the best option we have.  Meanwhile, this is where I got to when drafting a script earlier:

https://paste.debian.net/378057/

**Comment by pde** [comment]
Since we're doing hooks instead, this may be a wontfix for now...
