### ISSUE TITLE
pkg_resources.DistributionNotFound: unittest2

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2334]
When running `letsencrypt-auto-source/letsencrypt-auto --debug` on Debian Squeeze, I get the following:
```
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: unittest2
```
Using the old le-auto, the script runs successfully.

cc @erikrose

**Comment by erikrose** [comment]
Interesting. Manually running the several `pip install` commands from the old le-auto under Python 2.6 on my Mac results in no unittest2 installed. Running `letsencrypt --version` then crashes with a missing module:
```
Traceback (most recent call last):
  File "/Users/erose/ve/snom/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/Users/erose/ve/snom/lib/python2.6/site-packages/letsencrypt/cli.py", line 18, in <module>
    import configargparse
  File "/Users/erose/ve/snom/lib/python2.6/site-packages/configargparse.py", line 13, in <module>
    from ordereddict import OrderedDict
ImportError: No module named ordereddict
```
So I guess I match your ancient-OS bug with one that makes the new le-auto look good. ;-)

The only unittest2 I see in letsencrypt or any of its dependencies is in mock, and it's pulled in only when using the `[test]` extra, which we don't. So it's not at all obvious what's going on; some time in the debugger is probably needed.

**Comment by erikrose** [comment]
Repro'd on a docker Squeeze box:
```
# For running tests, build a docker image with a passwordless sudo and a trust
# store we can manipulate.

FROM debian:squeeze

# Install pip and nose:
RUN apt-get update && \
    apt-get -q -y install python-pip sudo && \
    apt-get clean
RUN pip install nose

# Add an unprivileged user:
RUN useradd --create-home --home-dir /home/lea --shell /bin/bash --groups sudo --uid 1000 lea

# Let that user sudo:
RUN sed -i.bkp -e \
      's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' \
      /etc/sudoers

RUN mkdir -p /home/lea/letsencrypt/letsencrypt

# Install fake testing CA:
COPY ./tests/certs/ca/my-root-ca.crt.pem /usr/local/share/ca-certificates/
#RUN update-ca-certificates

# Copy code:
COPY . /home/lea/letsencrypt/letsencrypt-auto-source

USER lea
WORKDIR /home/lea

CMD ["nosetests", "-v", "-s", "letsencrypt/letsencrypt-auto-source/tests"]
``

**Comment by erikrose** [comment]
It's ConfigArgParse: it has a conditional dependency that brings in unittest2 iff Python < 2.7. Now the question is why I didn't catch that when I did my requirement-gathering installs under 2.6...

**Comment by erikrose** [comment]
It's because ConfigArgParse is packaged wrong. I have a cached wheel of it, built under 2.7, so the wheel states none of its conditional <2.7 deps: none of argparse, ordereddict, or unittest2. Conditional deps are the superdevil:

![superdevil](https://4.bp.blogspot.com/_0Wr0UXG14ok/TUtNCAEbHZI/AAAAAAAAA28/Y-Sd1OtbZhs/s1600/Screen+shot+2011-02-03+at+6.48.14+PM.png)

Adding `--no-cache` to the pip install command gives us a more truthful list of reqs, including unittest2.

**Comment by erikrose** [comment]
This also reveals the additional requirements linecache2 and traceback2.

**Comment by erikrose** [comment]
2.7 run with `--no-cache` didn't reveal any further missed ones.

**Comment by bmw** [comment]
Thanks for looking into this. It would have taken me exponentially longer to figure out the problem. After this is fixed, I'll remove the need to use `--debug` when using py26!
