### ISSUE TITLE
Complete Fail on RHEL 5.11 + cPanel

### ISSUE THREAD

**Issue by Owlz** [letsencrypt/letsencrypt#2337]
Hello,

I just tried using letsencrypt via the git repo for REHL 5.11 with cPanel. Sadly, it was a complete failure. It spit out the following errors:

No package python-virtualenv available.
No package python-pip available.
No package augeas-libs available.
No package libffi-devel available.
No package ca-certificates available.
./letsencrypt-auto: line 104: [: too many arguments
./letsencrypt-auto: line 106: [: too many arguments

Looks like this was never intended for my environment. I'm in a VPS hosted server and I'm guessing a significant number of others will be in the same boat. Would love an easy way to do the webroot method as that's the one I'm planning to use.

**Comment by pde** [comment]
Hi.  We don't support or test on RHEL 5, whose core operating system components date from 2006.  In particular, we only support Python 2.6+, and RHEL 5 systems ship with Python 2.4.  Virtualenv can be avoided if you know what you're doing, but other aspects of our pip packaging may not be natively supported in RHEL 5; we haven't looked closely.

Out main recommendation would be to upgrade to RHEL 7; the client is now included as part of EPEL 7 and works well there!  But if you really can't upgrade, you may have better luck with one of the minimalist clients for the Let's Encrypt service:

https://community.letsencrypt.org/t/list-of-client-implementations/2103

In particular, I'd look at clients with very few dependencies, like [letsacme](https://github.com/neurobin/letsacme) or [letsencryptshell](https://mojzis.com/software/letsencryptshell/).  They aren't as featureful as the main python client, but they are much easier to run on very old systems.
