### ISSUE TITLE
Functions in cli.py should use config, not args or args+config

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#2341]
The profusion of `args` and `config` together is silly.  Since we've made these config objects, we should use them exclusively.

**Comment by kuba** [comment]
I didn't follow what you were doing here and in #2342, but treating parsed arguments and config as the same thing doesn't sound good... You've probably broken the entire Confiugration interface / concept.

**Comment by bmw** [comment]
I could be mistaken, but I don't think that is correct. `args` and `config` are basically identical except for the few extra properties `accounts_dir`, `backup_dir`, etc. I believe passing both around was a just a relic of how things used to work.
