### ISSUE TITLE
Donate prompt gets printed for each renewed cert

### ISSUE THREAD

**Issue by SwartzCr** [letsencrypt/letsencrypt#2346]
the donate prompt needs to check for the renew verb and not print if it's been specified

**Comment by SwartzCr** [comment]
fixed in https://github.com/letsencrypt/letsencrypt/commit/b97ddb92f06f5a8c1dc4fa321466ff38862ca138

**Comment by bmw** [comment]
Currently we don't print a donation message at all when running `renew`. I'm told this is the desired behavior so closing. Fixed in #2338.
