### ISSUE TITLE
letsencrypt renew should imply non-interactive

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2350]
I think this behavior is somewhat confusing, but multiple other contributors want this change and we're moving forward with it. It simplifies running `letsencrypt renew` in cron.

**Comment by SwartzCr** [comment]
fixed in https://github.com/letsencrypt/letsencrypt/commit/06b6dcc9c8c483071615c40ef1bed742b3f988cf

**Comment by SwartzCr** [comment]
https://github.com/letsencrypt/letsencrypt/commit/e14feb2919ecdda071e743137f2d6c0fb3a6cd6b should fix it

**Comment by SwartzCr** [comment]
or that that didn't fix it but it should be fixed now

**Comment by bmw** [comment]
fixed in #2338
