### ISSUE TITLE
renew() stops for any unhandled exception

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2353]
If we get an unhandled exception during the renewal attempt, it doesn't crash the client but it does make `renew()` stop at that point. For example, try setting `standalone_supported_challenges` to an invalid value in a lineage's renewal configuration file, then running `renew()`. When it tries to renew that lineage, it will crash with an exception, and no subsequent lineages will be renewed. This is presumably the case with respect to every kind of unhandled exception that might occur for any reason.

**Comment by pde** [comment]
Yup, so each call to `obtain_cert`, or perhaps each entire entry in your `for file in *.conf` loop should be wrapped in a `try:` `except:` block.

**Comment by schoen** [comment]
But which exceptions should we catch? I understand it's kind of bad
practice to catch unspecified exceptions.

**Comment by bmw** [comment]
fixed in #2338
