### ISSUE TITLE
Multiple renewals with standalone don't work

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2362]
If you create two separate lineages with the standalone configurator, and then try to renew both with the new `letsencrypt renew`, the second one will fail because the port is already in use.

The standalone plugin does try to stop the listening server when the challenge has been satisfied, but it seems that this fails to release the port. We may need to find a way to explicitly set `SO_REUSEADDR` on the listening socket (before it's bound!) in order to allow a listening socket to be immediately rebound.

**Comment by bmw** [comment]
I believe this is fixed in a659b07b4cd0cebec53cf294e7d3b531e18caca8

**Comment by bmw** [comment]
fixed in #2338
