### ISSUE TITLE
Renewer can give up when a single renewal fails

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2363]
I'm not sure where this is happening in the renewer logic, but the renewer can give up and not attempt any subsequent lineage renewals if a single lineage renewal fails.

When fixing this we should also check that the renewer exits with nonzero status if any renewal failed (but that it still attempts the other ones).

**Comment by SwartzCr** [comment]
is this the same as #318 ?

**Comment by bmw** [comment]
fixed in #2338
