### ISSUE TITLE
webroot failure gives a not-very-useful error

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2365]
If webroot renewal (or probably initial auth) fails due to the lack of a running web server that's pointed at that webroot, the error message returned to the user is very generic and doesn't really mention the possibility that a suitable web server was unavailable. Users might find it hard to diagnose this problem on this basis.

**Comment by bmw** [comment]
Moving this into the milestone for now as it is an easy fix and might be useful for people running `renew` off of `0.4.0`.
