### ISSUE TITLE
Rate limits and letsencrypt-renewer

### ISSUE THREAD

**Issue by Kami-no** [letsencrypt/letsencrypt#2376]
I'm unable to test letsencrypt-renewer because I have 8 certificates for different domains. Need a method to fit it the rate limit.

Also if there is a problem with at least 1 cert renewal than the tool will fail and will not even try other certs.

**Comment by schoen** [comment]
The rate-limit is a server-side policy issue; many threads on the LE community support forum have made clear that there is no way to lift the limit, sorry.

The renewer problem is genuine, but we are about to replace `letsencrypt-renewer` entirely with the new `letsencrypt renew` command -- today! -- and we have issue #2363 to ensure that what you're seeing doesn't happen for the new command. So I hope you'll give the new `letsencrypt renew` a try soon and hopefully it will work better for you. Thanks!
