### ISSUE TITLE
Problem getting cert: CSR generated automatically without SAN

### ISSUE THREAD

**Issue by franckr** [letsencrypt/letsencrypt#2379]
I would like to request a certificate using a CSR for which I have minimal control over the generation. This CSR is generated without Subject Alternative Name and there is no way to force it. I don't have access to the private key to create a CSR myself either.

It would be great to have a way to specify SANs along with the CSR so that they are integrated in the certificate during the signing process.

**Comment by schoen** [comment]
I'm not confident that this use case is acceptable according to industry
standards. If the CSR doesn't contain a request for those names, then you
need to use the key in another way to prove a binding between control of
the key and desire to associate the key with the names. I don't believe
it's considered a valid request to the CA without some kind of proof of
that connection.

The current ACME protocol implemented by the Let's Encrypt CA does not
support this case, so there's nothing we could do here in the Let's
Encrypt client to add support for it. If you think it's allowable
according to CA industry rules and issuance policies, you could ask
about it in the letsencrypt/acme (protocol development) repository or
the IETF ACME working group.

Sorry!

**Comment by franckr** [comment]
You're right. Actually, I was focussed on the requirement for a SAN, but the CN might suffice in this case, also I have to look more deeply in the current draft, section 6.6 states:

>   The CSR encodes the client's requests with regard to the content of
>    the certificate to be issued.  The CSR MUST indicate the requested
>    identifiers, either in the commonName portion of the requested
>    subject name, or in an extensionRequest attribute [RFC2985]
>    requesting a subjectAltName extension.
