### ISSUE TITLE
Certificate expiration notice: send it only for the more recent certificate for a given domain

### ISSUE THREAD

**Issue by tuxayo** [letsencrypt/letsencrypt#2382]
To avoid sending many emails that users might consider as "false positive" (and will end up ignoring the important ones).

For example, when setting up automated renewal, it can be easy to request several certificates for a same domain. And few month later getting "spammed" by certificate expiration notices.

**Comment by tuxayo** [comment]
Also, when setting up an automated renewal for example 25 day before expiring, that would prevent sending all certificate expiration notices **except if something went wrong during the renewal**, allowing such a strategy could be nice (to only have an email when something goes wrong).

**Comment by schoen** [comment]
This is a server-side issue so it belongs in

https://github.com/letsencrypt/boulder/issues

It may duplicate https://github.com/letsencrypt/boulder/issues/1346 and https://github.com/letsencrypt/boulder/issues/1358 or some other stuff over there.

Thanks.

**Comment by tuxayo** [comment]
Thanks! I haven't found the server repo
