### ISSUE TITLE
Calling sudo from inside a script = bad

### ISSUE THREAD

**Issue by x0x7** [letsencrypt/letsencrypt#2399]
So typically people should be aware root actions are about to be performed when they type in a command.

$ letsencrypt --help would not instictually be thought of as a command needing root access.  It's fine that it does but not ideal.  What is troubling is the use of sudo inside the script.

This means that if they had just run a few commands as root (someone working on their https would be in server configuration mode) and then decided to read the most available cli documentation on your command.  BOOM.  Let's install all the things.

A better solution would be to reject running without root and give a prompt stating that root access is need, then allow the user to explicitly grant it for your program.

The golden rule should be never include sudo in anything.  I can't think of any tool on debian that does.  I know on arch systemctl prompts for raised privilage but it doesn't use sudo because each issue requires granted privaliges.  Let the user manage root access.  Don't seripticiously gain root access through the back door without permission.

I'm sure you figured they would be prompted so it's all the same but sudo does have a grace period.  It is equal level of convinience for the user to sign for it on the outside of the program and is just polite.

Anyways hopefully this was just a mistake ;)

**Comment by pde** [comment]
The converse argument is that of least privilege: only use `sudo` and root access for the specific sub-tasks that require it, and not for everything.

In any case, `letsencrypt-auto` is something of a hack.  There are now packages for debian unstable (jessie comming RSN), and also a ticket against those to ensure that we can run as GID `ssl-cert` where that's possible / appropriate.

**Comment by pde** [comment]
(And aren't going to change the way `letsencrypt-auto` works; we're going to aim to retire it instead).
