### ISSUE TITLE
letsencrypt-auto --help should not run "apt-get install -y ..." automatically

### ISSUE THREAD

**Issue by pmorch** [letsencrypt/letsencrypt#2406]
I just had a machine trashed.

Running `./letsencrypt-auto --help` ran `apt-get install -y ...` automatically, which, among other things updated `libc`, trashing the entire machine to a point where re-installation was the easiest path. Sure the cause was a misconfiguration of `/etc/apt/sources` performed by us months ago, but still, `./letsencrypt-auto --help` shouldn't trash the machine because of that.

I suggest removing the `-y` switch so that the user is prompted for confirmation before apt-get does its thing, and/or a `letsencrypt-auto --yes-to-apt` switch or something. If one were to argue that the '-auto' in `letsencrypt-auto` implies automatic behaviour, then please provide a `letsencrypt-non-auto` or something *and use __that__ as the default in the documentation*.

Please don't perform an operation that can trash my entire machine by running `./letsencrypt-auto --help`. Nobody expects that. 

Or at the very least check that this doesn't install any packages you didn't anticipate. Perhaps running `apt-get install -s $packages` and testing the output. If only packages from an expected white-list show up, then run `apt-get install -y $packages` otherwise omit the -y and do `apt-get install $packages`, so the user is prompted for confirmation.

**Comment by bmw** [comment]
I'm very sorry that you just had a machine trashed. `letsencrypt-auto` is supposed to be a temporary solution while we work on distro packing. With that said, the script can certainly be improved.

I feel that this is largely a duplicate of #1903, focusing more on the issue of using `apt-get install -y` in the script. If, however, you feel that this is a different issue, I'm happy to keep both open until the issue is resolved.

**Comment by pmorch** [comment]
I agree, this issue is a subset of #1903. I'll move some comments to #1903 instead.

**Comment by pmorch** [comment]
> I'm very sorry that you just had a machine trashed.

Thanks. I understand that nobody did this on purpose and that this is new software. It's fine.
