### ISSUE TITLE
Yum install fails with RHEL v7.2

### ISSUE THREAD

**Issue by jwieder** [letsencrypt/letsencrypt#2409]
yum installation of letsencrypt.noarch and python2-letsencrypt.noarch fails when using RHEL's EPEL repository. The issue is the result of python-werkzeug - which is a dependency of both letsencrypt packages, but is not provided by EPEL. Manually installing the `python-werkzeug-0.9.1-2.el7.noarch.rpm` from the CentOS 7 Extras repository fixes the issue; installing Werkzeug by compiling from source or using pip does not resolve the issue, as yum will still list it as a failed dependency unless it sees the rpm has been installed.

Here is a list of all installed repos on the server where this fails:

Repo-id      : epel/x86_64
Repo-name    : Extra Packages for Enterprise Linux 7 - x86_64
Repo-revision: 1454890725
Repo-tags    : binary-x86_64
Repo-updated : Sun Feb  7 20:49:57 2016
Repo-pkgs    : 9,397
Repo-size    : 7.4 G
Repo-metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64
  Updated    : Sun Feb  7 20:49:57 2016
Repo-baseurl : http://s3-mirror-us-east-1.fedoraproject.org/pub/epel/7/x86_64/ (34 more)
Repo-expire  : 21,600 second(s) (last: Tue Feb  9 04:06:34 2016)
Repo-filename: /etc/yum.repos.d/epel.repo

Repo-id      : rhui-REGION-client-config-server-7/x86_64
Repo-name    : Red Hat Update Infrastructure 2.0 Client Configuration Server 7
Repo-revision: 1439271503
Repo-updated : Tue Aug 11 01:38:23 2015
Repo-pkgs    : 6
Repo-size    : 299 k
Repo-mirrors : https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/mirror/rhui-client-config/rhel/server/7/x86_64/os
Repo-baseurl : https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/repos//rhui-client-config/rhel/server/7/x86_64/os/ (1 more)
Repo-expire  : 21,600 second(s) (last: Tue Feb  9 04:06:34 2016)
Repo-filename: /etc/yum.repos.d/redhat-rhui-client-config.repo

Repo-id      : rhui-REGION-rhel-server-optional/7Server/x86_64
Repo-name    : Red Hat Enterprise Linux Server 7 Optional (RPMs)
Repo-revision: 1454007492
Repo-updated : Thu Jan 28 13:59:28 2016
Repo-pkgs    : 8,213
Repo-size    : 9.6 G
Repo-mirrors : https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/7Server/x86_64/optional/os
Repo-baseurl : https://rhui2-cds02.us-east-1.aws.ce.redhat.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/optional/os/ (1 more)
Repo-expire  : 21,600 second(s) (last: Tue Feb  9 04:06:34 2016)
Repo-filename: /etc/yum.repos.d/redhat-rhui.repo

Repo-id      : rhui-REGION-rhel-server-releases/7Server/x86_64
Repo-name    : Red Hat Enterprise Linux Server 7 (RPMs)
Repo-revision: 1454005863
Repo-updated : Thu Jan 28 13:33:14 2016
Repo-pkgs    : 10,152
Repo-size    : 12 G
Repo-mirrors : https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/7Server/x86_64/os
Repo-baseurl : https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/os/ (1 more)
Repo-expire  : 21,600 second(s) (last: Tue Feb  9 04:06:34 2016)
Repo-filename: /etc/yum.repos.d/redhat-rhui.repo

Repo-id      : rhui-REGION-rhel-server-rh-common/7Server/x86_64
Repo-name    : Red Hat Enterprise Linux Server 7 RH Common (RPMs)
Repo-revision: 1447968073
Repo-updated : Thu Nov 19 16:21:13 2015
Repo-pkgs    : 168
Repo-size    : 3.2 G
Repo-mirrors : https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/7Server/x86_64/rh-common/os
Repo-baseurl : https://rhui2-cds02.us-east-1.aws.ce.redhat.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/rh-common/os/ (1 more)
Repo-expire  : 21,600 second(s) (last: Tue Feb  9 04:06:34 2016)
Repo-filename: /etc/yum.repos.d/redhat-rhui.repo

**Comment by domcleal** [comment]
I don't know how the AWS package repo stuff works, but there is a RHEL repository called Extras that should mirror what's in CentOS Extras.  It isn't enabled by default, so check yum.repos.d or with `yum-config-manager` to see if you can enable it. The python-werkzeug package is in rhel-7-server-extras-rpms.

**Comment by rbu** [comment]
From: https://fedoraproject.org/wiki/EPEL

> NOTE for RHN users
> You need to also enable the 'optional' repository to use EPEL packages as they depend on packages in that repository. This can be done by enabling the RHEL optional subchannel for RHN-Classic. For certificate-based subscriptions see Red Hat Subscription Management Guide. For EPEL 7, in addition to the 'optional' repository (rhel-7-server-optional-rpms), you also need to enable the 'extras' repository (rhel-7-server-extras-rpms).
> Idea.png
> NOTE for CentOS users
> You can install EPEL by running yum install epel-release. The package is included in the CentOS Extras repository, enabled by default.

**Comment by jwieder** [comment]
Thanks for the replies. @domcleal I should have been more clear that the list is not just installed repos but that these repos are also enabled on the system this occurred. The repos I provided are copied and pasted from the output of "yum repolist enabled". It is my understanding that EPEL is the 'Extras' repository (EPEL stands for Extra Package for Enterprise Linux) - its at the very top of my list of enabled repos. I haven't tried this with a non-AWS version of RHEL7, but I don't think that this is an AWS-specific issue. From what I can tell, python-werkzeug is _not_ included in EPEL7 for x86_64 machines. It is not listed: https://dl.fedoraproject.org/pub/epel/7/x86_64/repoview/letter_p.group.html

@rbu  I'm not an RHN user (and as mentioned above and in my copy+paste from OP, I have EPEL enabled):

    subscription-manager repos --enable rhel-7-server-extras-rpms
    Error: rhel-7-server-extras-rpms is not a valid repository ID. Use --list option to see valid repositories.

    # subscription-manager repos --list
    This system has no repositories available through subscriptions.

From what I can tell the change instituted by @pde completely resolved this issue for future users. I'd be happy to open a ticket at https://bugzilla.redhat.com/ but I am not clear what they could have done to address this issue. CentOS and RHEL repos are not identical and this appeared to be one of those weird edge cases.

@pde - Cool commit which should entirely resolve the issue. Thanks! If you like I can attempt to test the latest patch for you.

**Comment by domcleal** [comment]
> The repos I provided are copied and pasted from the output of "yum repolist enabled". It is my understanding that EPEL is the 'Extras' repository (EPEL stands for Extra Package for Enterprise Linux) - its at the very top of my list of enabled repos.

Unfortunately not, they're similarly named but are different.  EPEL is a Fedora community project of extra packages, while the "Extras" repo is part of RHEL/EL itself (but often disabled).

> I haven't tried this with a non-AWS version of RHEL7, but I don't think that this is an AWS-specific issue.

Indeed it isn't, though the repo mechanism in AWS-installed hosts is a bit different to regular RHN, so it might limit which repos you can get.

**Comment by jwieder** [comment]
@domcleal Thanks you are correct the python-wurkzeug package is there (rhui-rhel-server-extras or in AWS rhui-REGION-rhel-server-extras). 

If it helps anyone in the future AWS users who pay for a RH license but dont have their own RHN subscription (who arent able to use the subscription manager plugin) can still enable additional RHN repos by manually updating /etc/yum.repos.d/redhat-rhui.repo and updating the Enabled variable from 0 to 1 - there maybe another way to do it as well somewhere in the documentation. (I think cloud-init replaces REGION with your VM location, like us-east-1, etc - anyway it should really look like that)

[rhui-REGION-rhel-server-extras]
name=Red Hat Enterprise Linux Server 7 Extra(RPMs)
mirrorlist=https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/$releasever/$basearch/extras/os
enabled=1
[...]

anyway, its fixed. Thanks for everyones input.

**Comment by rbu** [comment]
@jwieder, EPEL != Extras, see also https://wiki.centos.org/AdditionalResources/Repositories for a distinction. But EPEL requires the Extras repository be enabled.

The reference to RedHat's bugzilla was intended for bugs within the letsencrypt package, which you said you were using. It's the bug tracker where EPEL issues are managed, even though that is a Fedora project.

**Comment by udaireddy007** [comment]
@ jwieder - How you fixed this error ? 
subscription-manager repos --enable rhel-7-server-extras-rpms
Error: rhel-7-server-extras-rpms is not a valid repository ID. Use --list option to see valid repositories.

# subscription-manager repos --list
This system has no repositories available through subscriptions.
