### ISSUE TITLE
Test #2388 in integration tests

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2411]
If #2388 lands, we should probably test it in integration tests to make sure it works and prevent regressions.

**Comment by pde** [comment]
There was some stuff in #2398 to do that; we could fish it out...

**Comment by bmw** [comment]
It looked like [these lines](https://github.com/letsencrypt/letsencrypt/pull/2398/files#diff-c74d3ad4d86d0804f64e9354fa460b94R84) started to test that, but since a different key size was never set anywhere, I figured it was never finished.

If I'm missing something, feel free to reopen #2398 if you feel that's appropriate.

**Comment by pde** [comment]
The test [was there](https://github.com/letsencrypt/letsencrypt/commit/f37908eadc61d6ab90a25174119cbb4a31fa290a) but was pulled out while trying to identify the source of the -oldest breakage.
