### ISSUE TITLE
how to implement letsencrypts acme challenge on AWS API Gateway?

### ISSUE THREAD

**Issue by whatsdis** [letsencrypt/letsencrypt#2439]
I'm trying to setup an endpoint

`example.com/.well-known/acme-challenge`

but I can't find any node.js code that will return the appropriate response

I'm trying to setup an API Gateway that will automatically renew my certificate. I managed to generate a certificate using letsencrypt by spinning up an instance, like suggested by this user here:

https://community.letsencrypt.org/t/aws-api-gateway-lets-encrypt/7060/7

but it's not clear what this endpoint should return ... would be lovely if somebody had a node.js endpoint that I could just plug into lambda and point the AWS api gateway to that....

**Comment by schoen** [comment]
Hi @whatsdis,

The ACME specification draft is at

https://tools.ietf.org/html/draft-ietf-acme-acme-01

which describes what should be returned in response to each kind of challenge. There's also the list of alternative implementations

https://community.letsencrypt.org/t/list-of-client-implementations/2103

which can give you sample code and libraries that may be relevant.

This particular issue tracker is meant for tracking issues with our Python client implementation, so I think a community forum thread would be a more appropriate place to ask about this kind of issue (if you encounter a bug where the CA side appears not to be following the spec, you can file it at https://github.com/letsencrypt/boulder/issues). Thanks, and good luck!

**Comment by rcknr** [comment]
Here's a description of one way to do it with API Gateway: https://gist.github.com/rcknr/f7cb503f270e89c29dc70d1c8ef29461
