### ISSUE TITLE
webroot only verifies through port 80

### ISSUE THREAD

**Issue by greyltc** [letsencrypt/letsencrypt#2440]
It seems that the webroot option of verification only works when my server is visited through port 80. I'd rather keep port 80 firewalled.
It would be great if I could somehow tell let's encrypt to validate me through 443 or some other port.

**Comment by schoen** [comment]
Hi @greyltc, the goal of webroot is to allow validation for people who have a legacy HTTP web site.

The ACME spec says that this validation "challenge must be completed over HTTP, not HTTPS".

https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7.2

There was a prior discussion in the ACME working group about using other ports; the main concerns, I think, are protocol-in-protocol attacks (where someone can make a different server output something that will be interpreted as HTTP even though it wasn't meant to be) and shared server environments where non-root users are allowed to run server software on ports of their choice. So far I don't think people have been comfortable with allowing challenges to arbitrary ports, but you're welcome to join the IETF ACME working group if you're interested in advocating further for this.

For people who can't use port 80, we've provided two other validation methods -- the SNI challenge (which can be completely using a TLS listener on port 443) and the DNS challenge (which just requires being able to add records to your DNS zone). Both of these are live today, and the SNI challenge is supported in this Python client if your TLS listener is Apache, while the DNS challenge is supported in some alternative clients.

**Comment by greyltc** [comment]
Hm. Thanks for the info.

Not allowing arbitrary ports makes sense to me, but I don't really get why the spec wouldn't allow the challenge to be completed through 443 (with the validator ignoring whatever (self signed) certificate I present).

**Comment by schoen** [comment]
> Hm. Thanks for the info.
> 
> Not allowing arbitrary ports makes sense to me, but I don't really get why the spec wouldn't allow the challenge to be completed through 443 (with the validator ignoring whatever (self signed) certificate I present).

The ACME draft claims this is "[b]ecause many webservers allocate a default HTTPS virtual host to a particular low-privilege tenant user in a subtle and non-intuitive manner". (I'm not sure what that manner is.)

**Comment by greyltc** [comment]
Wow! I guess it might be marginally more difficult to hijack port 80 than port 443. I would think that the negatives associated with asking me to open my web server on port 80 to unencrypted traffic (even momentarily, to get a certificate so that I can properly encrypt my traffic!) would outweigh that concern though.

Thanks for doing my homework for me with the spec draft document! ;-)
