### ISSUE TITLE
Is it possible to issue a certificate for an IP (not an FQDN)?

### ISSUE THREAD

**Issue by NiklasRosenstein** [letsencrypt/letsencrypt#2441]
As the title says, I would like to issue a certificate for an IP address rather than a domain name. As far as I know, that is generally possible. Not with Letsencrypt it seems. I use `./letsencrypt-auto certonly --standalone` and enter the IP address. It tells me that it is not an FQDN and if I want to re-enter it or not. If  I press "no", it will exit immediately with the message "Please specify --domains, or --installer that will help in domain names autodiscovery".

**Comment by schoen** [comment]
The Let's Encrypt CA doesn't issue certificates for IP addresses.

https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082

https://community.letsencrypt.org/t/certificate-for-static-ip/84

We can try to make this clearer in the client by having it explicitly detect IP addresses and explain this.
