### ISSUE TITLE
Support MacPorts on OS X

### ISSUE THREAD

**Issue by nneonneo** [letsencrypt/letsencrypt#2447]
Some people (like myself) are using MacPorts rather than Homebrew and would prefer not to have Homebrew automatically installed. Instead, the `letsencrypt-auto` script should support Macports.

(Patch forthcoming)

**Comment by kunthar** [comment]
same here. brew is screwing macports environment. experienced macports users don't like brew automatic package breaking mechanism. @nneonneo let me know a working branch  then i can give a hand.

**Comment by nneonneo** [comment]
@kunthar: See #2448.
