### ISSUE TITLE
Enable http-01 over TLS for the Manual Plugin (Was: Add Support for TLS-SNI-01 in Manual Plugin)

### ISSUE THREAD

**Issue by Miserlou** [letsencrypt/letsencrypt#2459]
Looks like this is a [known TODO](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/plugins/manual.py#L34), but I have a pressing need for it!

This is necessary for using Let's Encrypt with "serverless" (AWS Lambda) applications on Amazon's API Gateway (for instance with [Zappa](https://github.com/Miserlou/Zappa) or the [Serverless.org/JAWS Framework](https://github.com/serverless/serverless)), as there is no way to serve plaintext HTTP through the API Gateway.

As such, with Zappa we have a bootstrapping problem where we must first generate a self-signed cert for the initial domain deployment, then use the LE manual client in TLS-SNI-01 mode to generate our first LE certificate. Currently, this is impossible because this feature isn't implemented yet in the LE manual plugin.

I imagine the interface would be quite simple, simply add a "--challenge-mode" argument that defaults to http-01 but accepts tls-sni-01. The other change would be to the SimpleHTTPServer CMD_TEMPLATE to use ssl.wrap_socket on port 443.

I'd be happy to implement it if you'd accept that, but if somebody owns this part of the code already would like to step up and add this feature, that'd be much appreciated as well.

Thanks!

**Comment by Miserlou** [comment]
Ah. Upon further investigation, it seems like I misunderstood how how tls-sni-01 works, and that it wouldn't be applicable for this use case.

Instead, what we _need_ is http-01 in TLS mode for the manual plugin.

However, this capability was [removed from the client](https://github.com/ietf-wg-acme/acme/pull/7) and then again [rejected as a request](https://github.com/letsencrypt/letsencrypt/issues/1343) for reasons mentioned in this [mailing list post](https://mailarchive.ietf.org/arch/msg/acme/B9vhPSMm9tcNoPrTE_LNhnt0d8U). However, the security concern raised on the mailing list does not apply to serverless architectures, because there are no vhosts - because there is no server!

This presents a real problem for Zappa/Serverless, and it means, quite unfortunately, that architectures of the future won't be able to use Let's Encrypt in order to support the implementations of the past. (It also introduces the strange irony of requiring me to lobby Amazon to _remove_ the SSL requirement in order to support plaintext HTTP.)

So, this is a request for http-01 support over TLS in Manual mode in order to support Let's Encrypt in serverless architectures.

(Pinging @pde because this seems to be your area of concern.)

**Comment by pde** [comment]
Hi @Miserlou,

Why don't you or Amazon Lambda serve a redirect from port 80 to 443?  Then HTTP-01 will work for your use case.  That will also prevent people who naively type "your.example.com" into the address bars of older browsers will from getting a broken result (new browsers support HSTS preloading, but you need to make sure you've done that).

Turning of port 80 does not improve security, because it doesn't prevent network attackers from spoofing a port 80 for your service while they impersonate you.

We'd be open to an appropriate revision to ACME that adds an HTTP-02 that supports TLS but is safe from default vhost attacks.  It'll just take much longer for something like that to be specified and deployed.

**Comment by Miserlou** [comment]
Ah, okay, I think that may work (in theory) - but in practice it seems like that doesn't work with self-signed certificates?

    ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
    Self-verify of challenge failed.
    Failed authorization procedure. spheres.gun.io (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://spheres.gun.io/.well-known/acme-challenge/aF53qhA0y6LTi8yhoU5v384fasxkdztE9cNlja6hSfs [54.240.170.69]: 400

To be clear, the issue is not "turning off" port 80 - in a "serverless" architecture, we have no control over the server other than the HTTPS response content (fortunately, Amazon provides a free 301 redirect to the HTTPS subdomain.)

In IRC, we discussed a solution that would allow bootstrapping via DNS and then auto renewing via previous-configuration, but it seems like we are very close to be able to bootstrap with the official client in manual mode here. Is there a way to disable the rejection of self-signed certs? It doesn't seem like they're any less secure than plaintext HTTP in this case.

**Comment by pde** [comment]
Disabling cert checking after the redirect would be a ticket to file against https//github.com/letsencrypt/boulder.  Theoretically it could be okay to disable cert checking after an HTTP-01 redirect, though it's the kind of change that always makes people nervous.

**Comment by schoen** [comment]
Closing this because it was refiled as a boulder issue, where it's more appropriate.
