### ISSUE TITLE
Failed Authorization procedure   

### ISSUE THREAD

**Issue by vyjhala** [letsencrypt/letsencrypt#246]
i getting error while verification process i attach screenshot of error tell me how to fix this problem. 

Error(error=u'unauthorized', message=u'Could not validate', more_info=None)    unauthorized        Failed Authorization procedure - cleaning up challenges            

![error](https://cloud.githubusercontent.com/assets/6338740/6217094/542b0094-b636-11e4-8f72-c719b40568fd.jpg)

**Comment by jdkasten** [comment]
First off, the code isn't meant to be run on production systems yet and we are currently using a dummy server (Let's Encrypt is not operational yet) that doesn't give great error messages. (as you have discovered).  This code is only meant to be run by developers right now.

If you are still interested...
I know of several TODOs in the Apache Configurator that I have not addressed yet that could lead to it, but here are a few questions.

1.  I assume that you do own the domain mycloudsite.ga and it is running Apache.
2.  What OS are you running?  I have only tested this on various versions of Ubuntu.
3.  Are you running an atypical configuration?
4.  Is port 443 free and available to be used?

Things you can do to test...
Hit control-C right after it says "Ready for verification".  You should see that the configuration (apache2.conf or httpd.conf) now includes a new file from /etc/letsencrypt which is a Vhost that is designed to solve the DVSNI challenge from the ACME spec.  When you restart Apache everything should be fine.  The challenge vhost should have the same addresses as the le-ssl-conf file and be a name-based vhost based on the NONCE in the DVSNI challenge.  

Running letsencrypt again will automatically remove all of the changes to configuration that were left when you hit control-C.  So it should be easy to get back to a clean state.

**Comment by jdkasten** [comment]
Everything has changed since this was reported.  (Protocol, errors, ect...) If anyone is still having an issue, a separate issue should be started.
