### ISSUE TITLE
Fatal certlint error in recently signed certificate

### ISSUE THREAD

**Issue by martinsuchan** [letsencrypt/letsencrypt#2463]
See this certlint result in certificate transparency log:
**FATAL: ASN.1 Error in X520CommonName**
https://crt.sh/?id=12791738&opt=cablint
https://crt.sh/?caid=7395&opt=cablint

If it's not false positive, then it should be fixed on the backend and the issued certificate should be revoked.

**Comment by schoen** [comment]
Thanks for pointing this out. I filed an issue at https://github.com/letsencrypt/boulder/issues/1488 and https://github.com/awslabs/certlint/issues/24 (definitely not a client issue).
