### ISSUE TITLE
Expected a numeric value for http01_port

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2468]
Forum user Randall describes this problem when using `letsencrypt renew`:

> ...The error was `Expected a numeric value for http01_port. ...` 
> Editing the file /etc/letsencrypt/renewal/[my.domain].conf file solved this problem. I changed `http01_port = None`  to  `http01_port = 80`

https://community.letsencrypt.org/t/help-us-test-renewal-with-letsencrypt-renew/10562/5

@bmw said that this would have been fixed (in terms of renewal config files correctly specifying `http01_port`) back in November, but people who have older lineages than that may have this problem when renewing with `standalone`. That could conceivably be a pretty large number of users!

**Comment by bmw** [comment]
For reference, this was the commit that changed the behavior: bb6736f36cfe68fc31595954965635d337df1d24

**Comment by bmw** [comment]
Looks like we had a similar problem before when `renewer.py` tried to cast the value to an int.

**Comment by schoen** [comment]
A number of people are still having trouble with this (we just had another report on the forum).

**Comment by schoen** [comment]
Hopefully nobody will be troubled by this bug anymore thanks to @bmw's PR. I'll try to let some people know on the forums and confirm that it works for them.

**Comment by bmw** [comment]
Note: No one (including `letsencrypt-auto` users) will get these changes before the next release unless they're installing directly from this repo.
