### ISSUE TITLE
automatic upgrading in letsencrypt-auto downgrades to incompatible version

### ISSUE THREAD

**Issue by tsuriga** [letsencrypt/letsencrypt#2490]
Tested in latest master, https://github.com/letsencrypt/letsencrypt/commit/1a77c7385768e73851b2e4e685073fa39d4a2298

**Steps:**

1. git clone https://github.com/letsencrypt/letsencrypt.git
2. cd letsencrypt
3. ./letsencrypt-auto

`letsencrypt: error: unrecognized arguments: --le-auto-phase2`

Cause: **letsencrypt-auto-source/letsencrypt-auto**
```bash
REMOTE_VERSION=`"$LE_PYTHON" "$TEMP_DIR/fetch.py" --latest-version`
if [ "$LE_AUTO_VERSION" != "$REMOTE_VERSION" ]; then
    echo "Upgrading letsencrypt-auto $LE_AUTO_VERSION to $REMOTE_VERSION..."
    ...
fi
"$0" --le-auto-phase2 "$@"
```
will fetch the version from https://pypi.python.org/pypi/letsencrypt/json. Right now that version is "0.4.0". Since the check above only checks if the versions are different, the auto script will "upgrade" version "0.5.0.dev0" to "0.4.0", which does not know about the new argument, and attempt to run with that.

The changes were introduced in https://github.com/letsencrypt/letsencrypt/commit/e8f6d4ff39e0d7cd4331a99a8941fc3771c5f07c

**Comment by bmw** [comment]
Fixed in #2492
