### ISSUE TITLE
Renewer should report failures via exit status

### ISSUE THREAD

**Issue by marcan** [letsencrypt/letsencrypt#2508]
The `renew` subcommand should cause the process to exit with a nonzero exit status if renewal failed for any certificate. This makes it easier for an automated renewal script to determine if something went wrong or not. Right now, it seems to exit with status 0 anyway (at least in dry run mode).

Relatedly, I would also suggest adding a "quiet" option that skips the "Processing" lines and does not print the final summary if the status of all certs is "skipped". This makes it easier to just run as a cronjob, since it will avoid producing any output if nothing was done, and therefore won't send an email.

**Comment by pde** [comment]
Eeep, I actually think this is a bug because we've given examples of scripts that assume this return code is available.

**Comment by bmw** [comment]
Created #2512 so the `--quiet` issue isn't lost with the issue about the `letsencrypt renew` exit code.
