### ISSUE TITLE
Implement --quiet / -q

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2512]
As suggested in #2508, we should add `--quiet` so the client can more easily be used with cron.

**Comment by bmw** [comment]
Perhaps this should provide output if an error occurs. On the other hand, all relevant output will be in the log files (with the exception of the renewal summary which was recently added).

**Comment by osirisinferi** [comment]
But a "no output if all is OK, do give output when something is wrong" setting would be very helpfull in a `cron` situation.

**Comment by nitmir** [comment]
Or put OK output to stdout and error output to stderr (I do not know, it can already be the case).
So in a `cron` one can do `> /dev/null` and still receive errors.

**Comment by osirisinferi** [comment]
That's even better IMHO.

**Comment by pde** [comment]
This will be a necessary item if we do #2676 instead of #2331
