### ISSUE TITLE
no response "Installing Python packages"

### ISSUE THREAD

**Issue by joviqiao** [letsencrypt/letsencrypt#2516]
![20160220203209](https://cloud.githubusercontent.com/assets/13116366/13196841/65098e24-d815-11e5-9d67-8e34bf8e9d6c.png)
stop here, no response.
What's wrong?

**Comment by bmw** [comment]
One thing to try is running `letsencrypt-auto` with `--verbose` which will provide you with more output to help identify the problem.

**Comment by LzIManD** [comment]
long long long long time,then
```
Had a problem while downloading and verifying Python packages:
Downloading argparse==1.4.0 (23K)...
Downloading cffi==1.4.2 (365K)...
Downloading ConfigArgParse==0.10.0 (36K)...
Downloading configobj==5.0.6 (33K)...
Downloading cryptography==1.1.2 (349K)...
Downloading enum34==1.1.2 (46K)...
Downloading funcsigs==0.4 (14K)...
Downloading idna==2.0 (61K)...
Downloading ipaddress==1.0.16 (17K)...
Downloading linecache2==1.0.0 (12K)...
Downloading ndg-httpsclient==0.4.0 (24K)...
Downloading ordereddict==1.1 (2K)...
Downloading parsedatetime==1.5 (50K)...
Downloading pbr==1.8.1 (89K)...
Downloading psutil==3.3.0 (261K)...
Downloading pyasn1==0.1.9 (36K)...
Downloading pycparser==2.14 (223K)...
Downloading pyOpenSSL==0.15.1 (102K)...
Downloading pyRFC3339==1.0 (8K)...
Downloading python-augeas==0.5.0 (90K)...
Downloading python2-pythondialog==3.3.0 (1831K)...
Downloading pytz==2015.7 (476K)...
Downloading requests==2.9.1 (501K)...
Downloading six==1.10.0 (10K)...
Downloading traceback2==1.4.0 (16K)...
Downloading unittest2==1.1.0 (96K)...
Downloading Werkzeug==0.11.3 (305K)...
Downloading zope.component==4.2.2 (546K)...
Downloading zope.event==4.1.0 (476K)...
Downloading zope.interface==4.1.3 (141K)...
Downloading acme==0.4.0 (95K)...
Downloading letsencrypt==0.4.0 (197K)...
Downloading letsencrypt-apache==0.4.0 (93K)...
Downloading mock==1.0.1 (818K)...

THE FOLLOWING PACKAGES DIDN'T MATCH THE HASHES SPECIFIED IN THE REQUIREMENTS
FILE. If you have updated the package versions, update the hashes. If not,
freak out, because someone has tampered with the packages.

    pbr: expected one of Rsjbda51oFa9HMB_ohc0_i5gPRGgeDPswe63TDXHLgw
                         4hJ2JqkebIhduJZol22zECDwry2nKJJLVkgPx8zwlkk
                     got JqA3WPcoq9yYrWfg287d-goLq0Q_Z172mEuKRV4O7rY
-------------------------------
Not proceeding to installation.
```
Thk.

**Comment by LzIManD** [comment]
I new/rewrite ```.pip/pip.conf```, all good now. ~~FckGFW.~~

**Comment by joviqiao** [comment]
Thanks, but how to rewrite? @LzIManD

**Comment by LzIManD** [comment]
vim ```.pip/pip.conf```
```
[global]
index-url = http://mirrors.aliyun.com/pypi/simple/

[install]
trusted-host=mirrors.aliyun.com
```
Because of my aliyun ECS , so aliyun mirrors.

**Comment by joviqiao** [comment]
~~FckGFW!! 
Thx, it works. @LzIManD

**Comment by benweizhu** [comment]
@LzIManD 
Thanks a lot,

**Comment by smoothdvd** [comment]
FGFW! Thanks @LzIManD

**Comment by hatakawas** [comment]
FK GFW! Thanks @LzIManD

**Comment by MoonShining** [comment]
FK GFW! Thanks @LzIManD

**Comment by ice6** [comment]
GFW! Thanks @LzIManD

**Comment by michaelwschultz** [comment]
Mine gets stuck at `Running setup.py install for cryptography ... `

**Comment by DeveloperPans** [comment]
~~Fxxk GFW!~~ Thanks @LzIManD

**Comment by xushengs** [comment]
~~Fck GFW!~~ Thanks @LzIManD

**Comment by itbdw** [comment]
FK GFW! Thanks @LzIManD

**Comment by HanSon** [comment]
~~Fck GFW!~~ Thanks @LzIManD

**Comment by liyikun** [comment]
FK GFW! Thanks @LzIManD

**Comment by joviqiao** [comment]
其实吧，你既然都用阿里云了，直接用阿里云的免费证书岂不更好。

**Comment by godblesshugh** [comment]
Could not find a version that satisfies the requirement acme==0.12.0
Change to:
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by aaroncohen** [comment]
Working on this in the Pycon 2017 sprints. I've made a change to `pipstrap.py` that checks whether or not it can resolve pypi.python.org, and exits with an error if it can't, giving guidance to change your config as discussed above. We'd like to avoid having automatic behavior to fall back to servers inside of China, as that might spur a negative reaction from users from outside of China.

It would be more user friendly to provide an argument for users to add additional pip index urls, but I'd need some guidance in how to persist that option so that subsequent runs of the letsencrypt-auto script would continue to use the alternate pip index.

My PR: #4711

Any tips?

**Comment by bmw** [comment]
Thanks for working on this! I haven't looked at the PR yet, but if @erikrose is open to it, I think it'd be better to land this change on the [pipstrap repo](https://github.com/erikrose/pipstrap) first.

**Comment by godblesshugh** [comment]
Maybe put that 'index' in here at GitHub [has been accessible for few years]

**Comment by shofukamachi** [comment]
I had the same problem this work for me:
https://community.letsencrypt.org/t/the-ndg-httpsclient-distribution-was-not-found-error/33084
Hope it will help

**Comment by yeweishuai** [comment]
Thanks, the following works.

> vim ~/.pip/pip.conf

[global]
index-url = http://mirrors.aliyun.com/pypi/simple/

[install]
trusted-host=mirrors.aliyun.com
Because of my aliyun ECS , so aliyun mirrors.

**Comment by 5452** [comment]
didn't work for me. I use centos 6 and python is native with it, the version is 2.6, I cannot find the ~/.pip/pip.conf, and I created one with the given content, but when I executed certbot-auto, still got hung there... could anyone help me with it? Thanks.

**Comment by addedjacky** [comment]
@LzIManD It's does not work now.

**Comment by addedjacky** [comment]
vim ~/.pip/pip.conf
```
[global]:q
index-url=http://mirrors.aliyun.com/pypi/simple/

[install]
trusted-host=mirrors.aliyun.com
```

now:

```
# sudo ./certbot-auto --nginx
Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
yum 是 /bin/yum
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
软件包 gcc-4.8.5-11.el7.x86_64 已安装并且是最新版本
软件包 augeas-libs-1.4.0-2.el7.x86_64 已安装并且是最新版本
软件包 1:openssl-1.0.1e-60.el7_3.1.x86_64 已安装并且是最新版本
软件包 1:openssl-devel-1.0.1e-60.el7_3.1.x86_64 已安装并且是最新版本
软件包 libffi-devel-3.0.13-18.el7.x86_64 已安装并且是最新版本
软件包 redhat-rpm-config-9.1.0-72.el7.centos.noarch 已安装并且是最新版本
软件包 ca-certificates-2017.2.14-70.1.el7_3.noarch 已安装并且是最新版本
软件包 python-2.7.5-48.el7.x86_64 已安装并且是最新版本
软件包 python-devel-2.7.5-48.el7.x86_64 已安装并且是最新版本
软件包 python-virtualenv-1.10.1-3.el7.noarch 已安装并且是最新版本
软件包 python-tools-2.7.5-48.el7.x86_64 已安装并且是最新版本
软件包 python2-pip-8.1.2-5.el7.noarch 已安装并且是最新版本
无须任何处理
Creating virtual environment...
Installing Python packages...
```

**Comment by erfan2333** [comment]
@addedjacky 使用清华大学的镜像
`[global]
index-url=https://pypi.tuna.tsinghua.edu.cn/simple/

[install]
trusted-host=pypi.tuna.tsinghua.edu.cn`

**Comment by addedjacky** [comment]
@erfan2333 可以了，速度有点慢，等老长一段时间。

**Comment by xuxujiang0** [comment]
@addedjacky 你用哪个镜像？等了大概多长时间？我也遇到这个问题，好烦呢。

**Comment by Shasharoman** [comment]
`~/.config/pip/pip.conf` work for me.

**Comment by addedjacky** [comment]
@xuxujiang0 阿里的，不行的话，就试试清大的镜像

**Comment by bmw** [comment]
Can someone dealing with GFW issues test something for me? We're trying to help with some of the problems here.

Please:

1. Install `git`.
2. Run:
```
git clone -b pypi-mirrors --depth 1 https://github.com/erikrose/letsencrypt
letsencrypt/letsencrypt-auto-source/letsencrypt-auto --no-self-upgrade --pypi-mirror --version
```

This command should finish by printing "certbot 0.18.2". If it does not, can you please tell me the output?

Thanks for any help! Afterwards, you can delete the `letsencrypt` directory that was created.

**Comment by BirkhoffLee** [comment]
@bmw Hang. Tencent Cloud at Shanghai

```
[root@VM_0_3_centos ~]# letsencrypt/letsencrypt-auto-source/letsencrypt-auto --no-self-upgrade --pypi-mirror --version
Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Package gcc-4.8.5-16.el7.x86_64 already installed and latest version
Package augeas-libs-1.4.0-2.el7_4.1.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-8.el7.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-8.el7.x86_64 already installed and latest version
Package libffi-devel-3.0.13-18.el7.x86_64 already installed and latest version
Package redhat-rpm-config-9.1.0-76.el7.centos.noarch already installed and latest version
Package ca-certificates-2017.2.14-71.el7.noarch already installed and latest version
Package python-2.7.5-58.el7.x86_64 already installed and latest version
Package python-devel-2.7.5-58.el7.x86_64 already installed and latest version
Package python-virtualenv-1.10.1-4.el7.noarch already installed and latest version
Package python-tools-2.7.5-58.el7.x86_64 already installed and latest version
Package python2-pip-8.1.2-5.el7.noarch already installed and latest version
Nothing to do
Creating virtual environment...
Installing Python packages...
```

**Comment by BirkhoffLee** [comment]
For anyone encounters the same situation and still can't fix using the solutions above, I solved by following this article:

https://my.oschina.net/xiongliding/blog/825231

**Comment by bmw** [comment]
Thanks so much @BirkhoffLee.

We'll see if we can come up with another approach that will help here.

cc @erikrose

**Comment by erikrose** [comment]
@BirkhoffLee Can you download https://mirrors.ustc.edu.cn/pypi/web/packages/69/65/4c544cde88d4d876cdf5cbc5f3f15d02646477756d89547e9a7ecd6afa76/setuptools-20.2.2.tar.gz using a web browser, or does that hang also?

**Comment by BirkhoffLee** [comment]
@erikrose On the same server, it could be downloaded

```
[root@VM_0_3_centos ~]# wget https://mirrors.ustc.edu.cn/pypi/web/packages/69/65/4c544cde88d4d876cdf5cbc5f3f15d02646477756d89547e9a7ecd6afa76/setuptools-20.2.2.tar.gz
--2017-10-20 08:12:47--  https://mirrors.ustc.edu.cn/pypi/web/packages/69/65/4c544cde88d4d876cdf5cbc5f3f15d02646477756d89547e9a7ecd6afa76/setuptools-20.2.2.tar.gz
Resolving mirrors.ustc.edu.cn (mirrors.ustc.edu.cn)... 202.141.176.110, 2001:da8:d800:95::110
Connecting to mirrors.ustc.edu.cn (mirrors.ustc.edu.cn)|202.141.176.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 676284 (660K) [application/gzip]
Saving to: ‘setuptools-20.2.2.tar.gz’

100%[========================================================================================================================================>] 676,284     2.88MB/s   in 0.2s

2017-10-20 08:12:48 (2.88 MB/s) - ‘setuptools-20.2.2.tar.gz’ saved [676284/676284]
```

**Comment by lublues** [comment]
marked. see later.

**Comment by pCyril** [comment]
To fix this issue i desable IPV6 `sysctl -w net.ipv6.conf.all.disable_ipv6=1` and `sysctl -w net.ipv6.conf.default.disable_ipv6=1`
