### ISSUE TITLE
Bundle dependencies along with the software

### ISSUE THREAD

**Issue by pradeepchhetri** [letsencrypt/letsencrypt#2519]
I am new to letsencrypt but i was reading through the documentation and found that the wrapper script `letsencrypt-auto` is actually determining the OS distribution and installing dependencies based on that. I would recommend to use something like `Omnibus` to package dependencies (https://github.com/chef/omnibus) or `Hashdist` (https://github.com/hashdist/hashdist) along with letsencrypt. 

There are some disadvantages to packaging dependencies (because you need to keep track of updates to all bundled dependencies) but maybe worth to consider.

**Comment by pde** [comment]
Our main objective is to move to native OS packaging (including backports); `letsencrypt-auto` is a temporary hack in the mean time...

**Comment by pde** [comment]
BTW we now have packages for RHEL/CentOS 7, and backports for Debian jessie and Ubuntu 14 should be around in the next week or so...
