### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: ..

### ISSUE THREAD

**Issue by hilbertknl** [letsencrypt/letsencrypt#2522]
Hi guys,

I retrieve this error while adding an SSL to my domain.

Error:
`Exception while solving challenge for mydomain.science: Connection to tcp://mydomain.science:80 failed: [Error #0] php_network_getaddresses: getaddrinfo failed: Name or service not known`

What to do?

**Comment by joohoi** [comment]
This does not appear to be an error message generated by the official Let's Encrypt client. You should direct the question towards the maintainer of the client you are using in order to get it resolved.

**Comment by hilbertknl** [comment]
Why do I get this message only in your plugin?

**Comment by joohoi** [comment]
I don't know what plugin you are talking about, or in what system, but it is not made by us. You will have to ask its maintainer.
