### ISSUE TITLE
 ComparableX509 breaks _pyopenssl_cert_or_req_san()

### ISSUE THREAD

**Issue by FrancisRussell** [letsencrypt/letsencrypt#2526]
It seems that acme defines wrappers for various OpenSSL classes in order to get correct comparable behaviour. However, _pyopenssl_cert_or_req_san() uses isinstance to determine whether or not the passed object is a certificate or a request. Due to the wrapping this check gets the incorrect answer and will eventually cause OpenSSL to throw an error.

**Comment by bmw** [comment]
You are correct that the `acme` module wraps some OpenSSL classes, however, the documentation for that function says it takes the unwrapped version and all code in the official client uses the function properly.

**Comment by bmw** [comment]
To clarify my comment, the docstrings in the `acme` library properly differentiate between when a wrapped object should be used ([example](https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py#L293)) and when the OpenSSL object should be used directly ([example](https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/crypto_util.py#L157)).
