### ISSUE TITLE
GCE Error Creating Virual Environment - Cannot locate wrapped file

### ISSUE THREAD

**Issue by jknopp** [letsencrypt/letsencrypt#2554]
I am running into an issue with executing 'letsencrypt-auto' on the GCE Bitnami Ghost image. 
The issue can be reproduced using the base installer below:
https://cloud.google.com/launcher/solution/bitnami-launchpad/ghost

Here is the command I use, and it's output:
```
sudo wget https://github.com/letsencrypt/letsencrypt/archive/master.zip
sudo unzip master.zip
cd letsencrypt
sudo /opt/bitnami/ctlscript.sh stop
sudo ./letsencrypt-auto --debug
```

..install dependencies...

```
**Reading package lists... Done **
Reading package lists... Done
**Building dependency tree **
Reading state information... Done
ca-certificates is already the newest version.
dialog is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
libssl-dev is already the newest version.
augeas-lenses is already the newest version.
libaugeas0 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Checking for new version...
Creating virtual environment...
Cannot locate wrapped file
```

Dependencies were all installed without issue. I have tried from both the 'home' directory and the root of the drive.

I have also tried:
```
./letsencrypt-auto --apache -d {domain}
./letsencrypt-auto certonly -w /home/bitnami/htdocs -d {domain}
```

Any ideas what could be causing the wrapped file issue?

**Comment by pde** [comment]
Run with `-v` for more debugging output?

**Comment by pde** [comment]
Also what is the underlying host operating system? We might have packages for it...

**Comment by pde** [comment]
BTW you now get the latest letsencrypt auto by just doing:

`wget https://raw.githubusercontent.com/letsencrypt/letsencrypt/master/letsencrypt-auto` or
`https://raw.githubusercontent.com/letsencrypt/letsencrypt/v0.4.0/letsencrypt-auto`

**Comment by jknopp** [comment]
Problem solved. Thanks for the suggestions @pde

The key with on Bitnami seems to be to run the command on the "bitnami console"
More info about this here: https://wiki.bitnami.com/Components/BitNami_console

**Comment by lapswr** [comment]
@jknopp how did you do the install can you describe the steps?

**Comment by kreig303** [comment]
@jknopp Yes I'd love to know what you executed at the command line to drop out of the Bitnami console, their instructions are not clear.

**Comment by jknopp** [comment]
@kreig303 @lapswr

Here are the steps I took:

```
wget https://github.com/letsencrypt/letsencrypt/archive/master.zip
unzip master.zip
rm master.zip
mv letsencrypt-master letsencrypt
cd /opt/bitnami
sudo /opt/bitnami/ctlscript.sh stop
sudo ./use_ghost
bash-4.2# cd /home/<USERNAME>/letsencrypt/
bash-4.2# ./letsencrypt-auto certonly
sudo nano /home/bitnami/apps/ghost/conf/httpd-vhosts.conf
```

<VirtualHost *:443>
    ServerName ghost.example.com
    ServerAlias www.ghost.example.com
    DocumentRoot "/opt/bitnami/apps/ghost/htdocs"
    SSLEngine on
    SSLCertificateFile "/etc/letsencrypt/live/<CERTNAME>/cert.pem"
    SSLCertificateKeyFile "/etc/letsencrypt/live/<CERTNAME>/privkey.pem"
    SSLCertificateChainFile "/etc/letsencrypt/live/<CERTNAME>/fullchain.pem"
    Include "/opt/bitnami/apps/ghost/conf/httpd-app.conf"
</VirtualHost>
 
`sudo nano /home/bitnami/stack/apache2/conf/bitnami/bitnami.conf`

<VirtualHost _default_:443>
  DocumentRoot "/opt/bitnami/apache2/htdocs"
  SSLEngine on
  SSLCertificateFile "/etc/letsencrypt/live/<CERTNAME>/cert.pem"
  SSLCertificateKeyFile "/etc/letsencrypt/live/<CERTNAME>/privkey.pem"
  SSLCertificateChainFile "/etc/letsencrypt/live/<CERTNAME>/fullchain.pem"
  [...]
</VirtualHost>

`sudo /opt/bitnami/ctlscript.sh start`

**Comment by minhchu** [comment]
@jknopp thanks. your solution works for me.
a small note: I used `standalone` option.

**Comment by imiRemy** [comment]
@jknopp thank you! Your solution also worked for me using the `standalone` option that @minhchu used.  I have a bitnami image running apache on AWS and the out-of-the-box certbot setup did not work.

**Comment by itdansharpe** [comment]
@jknopp Help! Followed your example, and ended up with this:

```
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.DJk8tZXSnw/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.DJk8tZXSnw/pipstrap.py", line 133, in main
    shell=True)
  File "/opt/bitnami/python/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-jxsE8o/pip-8.0.3.tar.gz /tmp/pipstrap-jxsE8o/setuptools-20.2.2.tar.gz /tmp/pipstrap-jxsE8o/wheel-0.29.0.tar.gz' returned non-zero exit status 1
```

**Comment by rickitan** [comment]
Hi @itdansharpe, I'm getting the same error. But I run the command with as sudo, I get the same error that @jknopp was getting ("Cannot locate wrapped file"). By any chance did you find a solution?

**Comment by fabLouis** [comment]
Same error :(

**Comment by itdansharpe** [comment]
And that worked for you?

> Stop all the services: sudo /opt/bitnami/ctlscript.sh stop
Load the Mean console: sudo /opt/bitnami/use_gitlab
Download pip from: sudo wget https://bootstrap.pypa.io/get-pip.py
Install it executing: sudo python get-pip.py
Open the installation script (letsencrypt-auto)with your favourite CLI editor and edit the following line:
- PIP_OUT=`"$VENV_BIN/pip" install --no-cache-dir --require-hashes -r "$TEMP_DIR/letsencrypt-auto-requirements.txt" 2>&1`
+ PIP_OUT=`pip install --no-cache-dir --require-hashes -r "$TEMP_DIR/letsencrypt-auto-requirements.txt" `
Install Let's Encrypt: sudo ./letsencrypt-auto
Start all services: sudo /opt/bitnami/ctlscript.sh start

**Comment by fabLouis** [comment]
No sorry, just one step more, now I have got this [one](https://community.bitnami.com/t/cant-install-lets-encrypt-on-bitnami-gitlab-8-6-5-0/41334/3)
