### ISSUE TITLE
Expiration notification sent even after renewal of cert

### ISSUE THREAD

**Issue by mikehaertl** [letsencrypt/letsencrypt#2557]
I have received an expriation notification email for a domain that I had already renewed about a week ago:

> Your certificate (or certificates) for the names listed below will expire in 6 days (on 04 Mar 16 09:50 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

I have verified the expiration date in the browser. The renewed cert was issued on 2016-02-17 12:27:00 CET and is valid through 2016-05-17 13:27:00 CEST.

**Comment by webcraft** [comment]
Same here

**Comment by nitmir** [comment]
Duplicate of https://github.com/letsencrypt/boulder/issues/1346

**Comment by mikehaertl** [comment]
Thanks, closing this then.
