### ISSUE TITLE
Planned Path Forward?

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#256]
***Major steps***:
**Finish Apache Configurator** (test extremely thoroughly)  - *This is next on my personal list.*
Read configuration with knowledge of loaded modules and other more complex logic.
Review policies regarding vhost selection especially those based on _default_ vhost.
Rewrite redirect, implement HSTS (includes more advanced logic because it really messes with mixed-content in modern browsers), OCSP stapling, SPDY?

**Finish Nginx Configurator**

This will probably also require finishing the integration testing framework, incorporating the Validator branch, and finding a way to get a large sample of configurations.

**Renewal** - create renewal cron job
This probably takes an installer (get_all_certs_keys())

**Testing** - Integrate with other OSs/Testing under different different versions

***Minor steps***:
Implement RecoveryContact
Integrate DNSAuthenticator - I think I see the proper way to move forward on this one...

***Would be nice***:
PoP challenge (might change)
SimpleHTTPs (at least the document placement, don't worry about the self-signed certificate yet)

***Major future steps***
Write Installers for Postfix, Exim, other web servers...

I am surely missing something here so feel free to suggest or add things as needed.  My number one goal is to make sure all of the features work.  If you would like to be assigned to any given task.  Just make a comment or open a separate issue about it.

**Comment by kuba** [comment]
When #250 gets pulled in, I will submit a rebased PR for `acme.challenges`. I will then start working on the "**restification**" of  the`acme` module and the **network code**. Please keep in mind, though, that next 3 weeks are extremely busy for me and I might actually not be able to make any progress. But then, we're all busy and I estimate that `acme.challenges` might not even be pulled in by that time (it's ~2.5k LOC, necessary to be reviewed, etc.). Feel free to assign.

**Comment by ThomasWaldmann** [comment]
creating separate issues and milestones is useful for planning. never mix lots of issues/tasks into one issue, you will not be able to close it in the foreseeable future nor be able to have a useful discussion.

**Comment by kuba** [comment]
#267 has now been submitted and I've also started working on "restify" branch

**Comment by rolandshoemaker** [comment]
Is the plan to use [`dnspython`](http://www.dnspython.org/) for the DNSAuthenticator?

**Comment by schoen** [comment]
@rolandshoemaker, we were originally looking at using `nsupdate`. However, the dynamic DNS implementation in `dnspython` might be a simpler and cleaner alternative.

**Comment by rolandshoemaker** [comment]
I would definitely recommend using dnspython over shelling out to nsupdate.
I'd definitely be interested at taking a crack at this if nobody minds...

**Comment by jdkasten** [comment]
Great!  Here is what is written thus far... (by @ThomasWaldmann)
https://github.com/letsencrypt/lets-encrypt-preview/blob/ddns_auth/letsencrypt/client/ddns/ddns.py

I haven't personally tested it out yet and was waiting to fix some permissions issues before attempting to integrate it.

**Comment by rolandshoemaker** [comment]
Cool, I'll see if I can churn something out tomorrow morning.

**Comment by n1trux** [comment]
>Write Installers for Postfix, Exim, other web servers...

Maybe have a configuration option that it only pulls certificates and puts it in a certain directory? Then we could at least manually integrate it into nginx & co...

**Comment by kuba** [comment]
@n1trux, StandaloneAuthenticator (found in `master`) should do the job...

**Comment by pde** [comment]
Closing this as obsolete.
