### ISSUE TITLE
PyInstaller and sklearn

### ISSUE THREAD

**Issue by OliverKramer02** [letsencrypt/letsencrypt#2562]
Hello all, I currently have a problem with the pyinstaller and sklearn random forest. Does anyone know how I can use the module RandomForestRegressor pyinstaller with?

**Comment by cowlicks** [comment]
Did you mean to ask this on scikit-learn's [github](https://github.com/scikit-learn/scikit-learn) page?

**Comment by bmw** [comment]
I'm not sure what this issue is for, but it is not for the official Let's Encrypt client.
