### ISSUE TITLE
renew --force-renew attempts to install test certs

### ISSUE THREAD

**Issue by duncanwerner** [letsencrypt/letsencrypt#2576]
using `letsencrypt-auto renew --force-renew` gave me the following error:

```
2016-03-01 07:34:57,850:WARNING:letsencrypt.cli:Attempting to renew cert from 
/etc/letsencrypt/renewal/[...].conf produced an unexpected error: You've asked to renew/replace a
seemingly valid certificate with a test certificate (domains: [...]). We will not do that unless you use
the --break-my-certs flag!. Skipping.
```

renewing the "old way", 

```
/letsencrypt/letsencrypt-auto certonly --webroot -w [...] -d [...] --force-renewal --non-interactive
```

worked fine.  [edit: formatting]

**Comment by bmw** [comment]
I'm unable to reproduce this. Do you have a [configuration file](https://letsencrypt.readthedocs.org/en/latest/using.html#configuration-file) somewhere that's being picked up?

**Comment by duncanwerner** [comment]
It's working for me now.  Only thing I can think of is my old configuration would have been pre-4.0, maybe that contributed to the problem.  Unfortunately I didn't save state, so the old conf is gone.  I'll close it.
