### ISSUE TITLE
apache error: Error in checking parameter list

### ISSUE THREAD

**Issue by evert** [letsencrypt/letsencrypt#2584]
I couldn't get letsencrypt-auto to configure apache automatically, so I first did a `certonly` via a standalone http server.

After that, if I run letsencrypt-auto and choose:
    
    Attempt to reinstall existing certificate

I get the following error:

                             │ Error in checking parameter list: AH00526: Syntax error on line 24   │
                              │ of /etc/apache2/sites-enabled/api-apachevhost-le-ssl.conf:           │
                              │ SSLCertificateFile: file '/etc/apache2/insert_cert_file_path' does   │
                              │ not exist or is empty                                                │
    
And:

    Apache is unable to check whether or not the module is loaded because Apache is misconfigured.

**Comment by giuscri** [comment]
Can't reproduce the issue.

Using the Let's Encrypt client at commit `6e041eb` and `Apache/2.4.10`, via

```
$ ./letsencrypt-auto certonly --standalone
$ ./letsencrypt-auto
```
I succedeed in having a valid signed certificate for a domain I own.
Could you provide more details?

**Comment by evert** [comment]
Closing this for now. Don't have all the details right this moment. I can reopen later if  I run into it again.

**Comment by gaddmsk** [comment]
Having the same problem. Ubuntu 15.04 2.6.32
Apache 2.4.10
![lea](https://cloud.githubusercontent.com/assets/8012556/15558719/e9e09380-22e4-11e6-852b-8caccd8b712f.png)

**Comment by gaddmsk** [comment]
Okay, the solution is use _only symlinks_ in `sites-enabled`. If you have `.conf` files in folder `sites-enabled` - you will have that problem.

**Comment by christophbuehler** [comment]
@gaddmsk Should I create a folder "sites-enabled-conf" and then create symlinks for each config file? Seems weird to me..

**Comment by grgustaf** [comment]
FWIW, I ran into this same problem, but my sites-enabled contained only symlinks. Then I looked in sites-available, and I happen to have symlinks in *there* too... just a configuration management trick I use so that I store all changes outside /etc and won't forget what I've changed. It doesn't like that either. When I replaced those with real files everything worked.
