### ISSUE TITLE
Upgrading letsencrypt-auto 0.4.1 to 0.4.2 failes with Text file busy

### ISSUE THREAD

**Issue by marcofranssen** [letsencrypt/letsencrypt#2609]
Vagrant box: `ubuntu/trusty64 (virtualbox, 20160303.0.0)`
HOST OS: `Windows 10`
Commit hash: `6e041eb`

```
Upgrading letsencrypt-auto 0.4.1 to 0.4.2...                                                                                                                  
Replacing letsencrypt-auto...                                                                                                                                 
   sudo cp -p /vagrant/letsencrypt-auto /tmp/tmp.qD8lnMuQl6/letsencrypt-auto.permission-clone                                                                 
   sudo cp /tmp/tmp.qD8lnMuQl6/letsencrypt-auto /tmp/tmp.qD8lnMuQl6/letsencrypt-auto.permission-clone                                                         
   sudo mv -f /tmp/tmp.qD8lnMuQl6/letsencrypt-auto.permission-clone /vagrant/letsencrypt-auto                                                                 
mv: inter-device move failed: ‘/tmp/tmp.qD8lnMuQl6/letsencrypt-auto.permission-clone’ to ‘/vagrant/letsencrypt-auto’; unable to remove target: Text file busy 
Stopping as of bad exit code (0)...                                                                                                                           
```

**Comment by bmw** [comment]
This has to do with the way #2456 is resolved. I might take this issue myself and fix the problem the way I suggested [here](https://github.com/letsencrypt/letsencrypt/issues/2456#issuecomment-186364711).

@marcofranssen, in the meantime, you can download the latest version of the script [here](https://raw.githubusercontent.com/letsencrypt/letsencrypt/v0.4.2/letsencrypt-auto). By doing this, there will be no updates available and you will avoid this problem.

**Comment by erikrose** [comment]
It looks like you're running le-auto in a vagrant box, and vagrant (IIRC) shares the vagrant home dir with the host—in your case, Windows. le-auto tries to remove the old version of itself to move the new one overtop, but the underlying file is a Windows file, and Windows hates that sort of thing. To avoid this, park the le-auto file outside `~vagrant`.

**Comment by marcofranssen** [comment]
It always has been working like this. So how do you clarify it stopped working all of a sudden? I use many vagrant boxes where I also have Linux, nodejs and other tools make operations on files.
