### ISSUE TITLE
can't renewal site. append "-1000" issue

### ISSUE THREAD

**Issue by SSaMKJ** [letsencrypt/letsencrypt#2617]
when I run renewal script it seems to be success.
but -1000 appended on domain.
example.
expect) www.mydomain.com
actual) www.mydomain.com-1000

**Comment by bmw** [comment]
`letsencrypt renew` should not create a new lineage by appending `-0001` to the domain name. I suspect the `www.mydomain.com-0001` version was created earlier when running `letsencrypt` or `letsencrypt certonly` with `--duplicate` or a subset of the domains contained in the certificate for `www.mydomain.com`.

**Comment by cybernet** [comment]
can you provide a fix ?
how can i fix it ?

**Comment by pde** [comment]
@cybernet:

1. Decide which directories in `/etc/letsencrypt/live` contain lineages that you want to keep
2. If there are any that you don't want to keep, delete the corresponding renewal configuration file in `/etc/letsencrypt/renewal`.

**Comment by pde** [comment]
(A lineage is a series of certificates that replace each other as they expire)
