### ISSUE TITLE
Not working with BlackBerry 10 browsers?

### ISSUE THREAD

**Issue by nntoan** [letsencrypt/letsencrypt#2630]
Hello there,
As the title said, SSL currently not working with BlackBerry OS 10.X browsers.

**Comment by nitmir** [comment]
This is a known issue https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394

### Known not to work

 * Blackberry OS 10, 7, & 6
 * […]

**Comment by x29a** [comment]
For everybody else landing here, the certs are supported (see e.g. http://blog.chris007.de/?p=628) just not bundled by default. So installing them manually works just fine for now.
