### ISSUE TITLE
Make sure git pull on git cloned clients still updates after rename

### ISSUE THREAD

**Issue by SwartzCr** [letsencrypt/letsencrypt#2641]
Some people will have initially installed the LE client by cloning the LE/LE repo, we need to make sure that renaming the project won't prevent them from using git pull to update their clients (in the case that we update something like LE auto)

This is related to #2638

**Comment by SwartzCr** [comment]
https://webcache.googleusercontent.com/search?q=cache:fGtUzPWzn34J:https://help.github.com/articles/renaming-a-repository/+&cd=3&hl=en&ct=clnk&gl=us says:
In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line

**Comment by SwartzCr** [comment]
so we should be fine, but maybe we want to find a way to alert users who are doing git pull to update their remote origin:
`git remote set-url origin new_url`

**Comment by pde** [comment]
Okay, I think this is probably enough to close this ticket (though an actual command line test of plausible workflows wouldn't hurt)
