### ISSUE TITLE
Make sure issues and PRs don't break with rename

### ISSUE THREAD

**Issue by SwartzCr** [letsencrypt/letsencrypt#2642]
Certain sources will refer to specific github issues or PRs with urls, if we change the directory name these links may break, we should identify and mitigate this breakage

related to #2638

**Comment by strugee** [comment]
@SwartzCr these days, GitHub does redirects when you rename repos.

**Comment by SwartzCr** [comment]
@strugee can you find any documentation for this? It'd be great if I could reference it in this ticket :)

**Comment by strugee** [comment]
https://help.github.com/articles/renaming-a-repository/

**Comment by SwartzCr** [comment]
tested and issues re-direct using index #
