### ISSUE TITLE
Make sure the LE pip package in doesn't break with rename

### ISSUE THREAD

**Issue by SwartzCr** [letsencrypt/letsencrypt#2643]
We need to rename the client, which may mean renaming the packaged version(s) in PyPI. We should make sure this doesn't break things.

**Comment by SwartzCr** [comment]
I'm gonna tag @hlieberman and @erikrose and hope that one of them feels like they can assign this to themselves

**Comment by bmw** [comment]
I believe this is resolved with #2849, however, we should still do additional testing.
