### ISSUE TITLE
Ensure that people who have pip installed Let's Encrypt aren't broken with rename

### ISSUE THREAD

**Issue by SwartzCr** [letsencrypt/letsencrypt#2644]
Some people may have used pip to install let's encrypt. When we change the name these packages might not get updated - or instructions in pip might fail

related to #2643

**Comment by SwartzCr** [comment]
it's been suggested that we might make an empty letsencrypt package that would depend on whatever the new package is, making so that it would pull in the new client when it's fetched

**Comment by SwartzCr** [comment]
From meeting notes:
"Tentative plan: upload dummy packages that depend on our new ones, until we stop seeing substantial traffic to those dummy packages"

**Comment by SwartzCr** [comment]
@erikrose does this sound feasible?

**Comment by erikrose** [comment]
Seems reasonable. I might even have come up with it in the first place.

**Comment by SwartzCr** [comment]
I'm assigning this to @erikrose, feel free to flail your arms and yell at me if you think someone else should be in charge of this

**Comment by bmw** [comment]
I believe this is resolved with #2849, however, we should still do additional testing.
