### ISSUE TITLE
Python modules - possible/needed to rename?

### ISSUE THREAD

**Issue by SwartzCr** [letsencrypt/letsencrypt#2647]
from meeting notes:
- Python module names: do we keep letsencrypt.*, or change it?
- Renaming will be fine except where plugins import from us?
- Can we shim so that letsencrypt.* temporarily mirrors newname.*?

**Comment by SwartzCr** [comment]
pinging @hlieberman and @erikrose for input

**Comment by erikrose** [comment]
It's more pragmatic to keep the old name. Then old plugins continue to work, and there are no surprises born of clever tricks. We can rename the "distribution" (that is the PyPI name) without changing the package name; it's not at all unusual to have a difference there (though usually it's just one of capitalization).

However, if you very much want to rename the package, we can probably get away with a clever trick. Put this in the `letsencrypt` package's `__init.py__`:
```python
import sys
import certbot

sys.modules['letsencrypt'] = certbot
```
Python's import system is full of special cases, so I don't doubt that will fail in some dark corner, but all of these common uses seem to work:
```
import certbot
```
```
from certbot import whatever
```
```
from certbot.whatever import whatever_else
```

**Comment by bmw** [comment]
So my understanding is that we want to keep the `letsencrypt` packages as a wrapper of the new packages. Doing this will allow updates for people who do `pip install letsencrypt`, 3rd party plugins, and users of the ancient `letsencrypt-auto`.

I think this is a fairly small gain and causes us to double our packages but it does smooth the transition for some of our users. If we decide to do this, a couple of thoughts on the issue.

I assume we're going to keep `letsencrypt` as an entry point in the venv. To do this, I believe doing the following is sufficient:
```
    entry_points={
        'console_scripts': [
            'letsencrypt = super_secret_new_name.main:main',
        ],  
```

Additionally, as implied above, `letsencrypt` will depend on `super_secret_new_name`, `letsencrypt-auto` will depend on `super_secret_new_name-apache`, etc. Do we want to pin the packages to specific versions of `super_secret_new_name*` or do we want to upload the `letsencrypt` shim packages once and forget about it?

I think doing what ErikRose said in `__init__.py`, adding the `super_secret_new_name*` packages as a dependency, and fixing up the entry point is all we need in order for this to work. We just need to answer the question if we have/need to modify the `letsencrypt` packages with every release.
