### ISSUE TITLE
When reissuing a revoked cert, the client prompts you to keep the old one

### ISSUE THREAD

**Issue by strugee** [letsencrypt/letsencrypt#2655]
I generated a couple Let's Encrypt certs with the default settings. Then I realized that the default RSA key size is 2048, whereas I prefer to be paranoid and use 4096-bit keys. No problem! I just revoked the old certs and went to reissue new ones, passing `--rsa-key-size`.

It was at this point that I got a prompt telling me that I had a certificate with exactly the same domain name on it, and did I want to keep the existing cert? This is obviously wrong as the certificate is revoked and thus no longer useful.

```
% letsencrypt --version                                                                                                  
letsencrypt 0.4.1

% apt-cache policy letsencrypt
letsencrypt:
  Installed: 0.4.1-1~bpo8+1
  Candidate: 0.4.1-1~bpo8+1
  Version table:
 *** 0.4.1-1~bpo8+1 0
        100 http://ftp.us.debian.org/debian/ jessie-backports/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by bmw** [comment]
This is actually a symptom of #688/#1028. The client has no notion of revoked certificates, causing the problem you described. #1028 is flagged for the 0.6.0 release.
