### ISSUE TITLE
none ascii domains, error catching failed

### ISSUE THREAD

**Issue by puggan** [letsencrypt/letsencrypt#2661]
This code should catch UnicodeDecodeError?
```
    # Unicode
    try:
        domain = domain.encode('ascii').lower()
    except UnicodeDecodeError:
        raise errors.ConfigurationError(
            "Internationalized domain names are not presently supported: {0}"
            .format(domain))
```
So why is my log saying:

> 
> 2016-03-13 18:57:09,064:DEBUG:letsencrypt.cli:Exiting abnormally:
> Traceback (most recent call last):
>   File "./letsencrypt", line 11, in <module>
>     sys.exit(main())
>   File "/root/.local/share/letsencrypt/lib64/python2.7/site-packages/letsencrypt/cli.py", line 1993, in main
>     return config.func(config, plugins)
>   File "/root/.local/share/letsencrypt/lib64/python2.7/site-packages/letsencrypt/cli.py", line 658, in run
>     domains = _find_domains(config, installer)
>   File "/root/.local/share/letsencrypt/lib64/python2.7/site-packages/letsencrypt/cli.py", line 133, in _find_domains
>     domains = display_ops.choose_names(installer)
>   File "/root/.local/share/letsencrypt/lib64/python2.7/site-packages/letsencrypt/display/ops.py", line 208, in choose_names
>     names = get_valid_domains(domains)
>   File "/root/.local/share/letsencrypt/lib64/python2.7/site-packages/letsencrypt/display/ops.py", line 242, in get_valid_domains
>     valid_domains.append(le_util.enforce_domain_sanity(domain))
>   File "/root/.local/share/letsencrypt/lib64/python2.7/site-packages/letsencrypt/le_util.py", line 312, in enforce_domain_sanity
>     domain = domain.encode('ascii').lower()
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 1: ordinal not in range(128)
> 

row 312 is the `domain = domain.encode('ascii').lower()` row, LE version 0.4.2

**Comment by nitmir** [comment]
UnicodeDecodeError != UnicodeEncodeError
u"unicode string".encode() --> UnicodeEncodeError
b"byte string".decode() --> UnicodeDecodeError

**Comment by puggan** [comment]
oh, missed that one, so guess it should be pathced to "except UnicodeEncodeError:",
tried to replace it with just "except:", but then it just moved the errormessage to  the ".format(domain))" row.

>   File "/root/.local/share/letsencrypt/lib64/python2.7/site-packages/letsencrypt/le_util.py", line 318, in enforce_domain_sanity
>     .format(domain))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 1: ordinal not in range(128)

changed it to `.format(":".join("{:02x}".format(ord(c)) for c in domain)))` and it seams to work,
not a good solution, so hope someone with python knowledge can patch it.

**Comment by nitmir** [comment]
As said the docstring on `enforce_domain_sanity`, `domain` can be either a `unicode` or a `str` so we should both catch `UnicodeDecodeError` and `UnicodeEncodeError`, cf my comment on #2662.

**Comment by puggan** [comment]
The test result of my pull-request shows some UnicodeDecodeError, the tests maybe should be extended with domains that generate a UnicodeEncodeError too.

**Comment by pde** [comment]
@puggan can you describe how to reproduce your original error?

**Comment by puggan** [comment]
how to reproduce, hmm, can start  with list stuff about my system.
`uname -r -m`: 3.17.7-gentoo x86_64
`python2 --version`: Python 2.7.10
`python --version`: Python 3.4.3
www-servers/apache-2.2.31
LE version 0.4.2, commit 09a649f41749333017fa2363b1ab93d9ed3cc0e2

the vhost with the non ascii chars
[klas.vhos.txt](https://github.com/letsencrypt/letsencrypt/files/172974/klas.vhos.txt)

**Comment by schoen** [comment]
I confirmed this (somewhat) - I think the trouble is that if you get the IDN on the command line, it's a `str`/`bytes` object (decoded Unicode), while if you get the IDN from a vhost, it's a `unicode` object (encoded Unicode). When attempting to detect non-ASCII characters, we can then get *either* `UnicodeDecodeError` *or* `UnicodeEncodeError`, depending on what the original type passed to us was.

I don't immediately see the full path to fixing this because when I tried just adding the `UnicodeEncodeError`, I then got an additional error trying to `.format()` the offending domain into the error message string (!). This is a slight subtlety about having a function that can either accept `str` or `unicode` and then try to `.format()` either of them into the same string.

**Comment by schoen** [comment]
Yes, so it's definitely a matter of whether the name being validated was passed with `-d` (→ `str`, I think) or parsed out of a vhost (→ `unicode`, I think).

**Comment by schoen** [comment]
Another question is whether, if we did manage to convert this to a `ConfigurationError` in this case as intended, it would apply only to the individual vhost and cause it to be skipped, or if it will currently cause the entire client to give up on any operation if it found a single Unicode vhost anywhere.

**Comment by puggan** [comment]
looking good, works for me.

tested it bu running:
```
cd /usr/src/letsencrypt/
git pull
cp /usr/src/letsencrypt/letsencrypt/le_util.py /root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/le_util.py
```
