### ISSUE TITLE
server to server communication not working

### ISSUE THREAD

**Issue by pavankumarkatakam** [letsencrypt/letsencrypt#2679]
Hi im using the letsencrypt for one of the sites, actually the site is based on the integration that receive the notification and show as  a message, im integrating my site with Amazon SNS where it will send some notification and my site will receive it and show as a message. Here problem is Amazon SNS is sending notification but no message shown in the site, i checked it ans ssl handshake is going wrong.

**Comment by pde** [comment]
What's the error message?  The most common cause of a handshake error would be failure to include intermediate certificates in (ie make sure you use either `fullchain.pem` or `cert.pem + chain.pem` in your configuration).
