### ISSUE TITLE
--help should never, ever install things. especially without approval.

### ISSUE THREAD

**Issue by jkister** [letsencrypt/letsencrypt#2680]
Debian 7.9
s4> git clone https://github.com/letsencrypt/letsencrypt
Cloning into 'letsencrypt'...
remote: Counting objects: 32913, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 32913 (delta 0), reused 0 (delta 0), pack-reused 32908
Receiving objects: 100% (32913/32913), 8.60 MiB | 4.04 MiB/s, done.
Resolving deltas: 100% (23352/23352), done.
s4> cd letsencrypt/
s4> ./letsencrypt-auto --help
Bootstrapping dependencies for Debian-based OSes...
Hit http://ftp.us.debian.org wheezy Release.gpg
Hit http://ftp.us.debian.org wheezy-updates Release.gpg     
Hit http://ftp.us.debian.org wheezy-backports Release.gpg   
Hit http://ftp.us.debian.org wheezy Release              
[...]
Reading package lists... Done              
./letsencrypt-auto: 182: ./letsencrypt-auto: lsb_release: not found
./letsencrypt-auto: 184: ./letsencrypt-auto: lsb_release: not found
No libaugeas0 version is available that's new enough to run the
Let's Encrypt apache plugin...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version.
ca-certificates set to manually installed.
gcc is already the newest version.
python is already the newest version.
libssl-dev is already the newest version.
The following extra packages will be installed:
  libexpat1-dev libpython2.7 python-pkg-resources python-setuptools python2.7-dev
Suggested packages:
  augeas-doc augeas-tools python-distribute python-distribute-doc
Recommended packages:
  python-pip
The following NEW packages will be installed:
  augeas-lenses dialog libaugeas0 libexpat1-dev libffi-dev libpython2.7 python-dev python-pkg-resources python-setuptools
  python-virtualenv python2.7-dev
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.3 MB of archives.
After this operation, 39.0 MB of additional disk space will be used.
Get:1 http://ftp.us.debian.org/debian/ wheezy/main augeas-lenses all 0.10.0-1 [195 kB]
Get:2 http://ftp.us.debian.org/debian/ wheezy/main dialog i386 1.1-201
[...]
Setting up python-setuptools (0.6.24-1) ...
Setting up python-virtualenv (1.7.1.2-2) ...
Checking for new version...
Creating virtual environment...
Installing Python packages...
Installation succeeded.

**Comment by nitmir** [comment]
duplicate of #1903

**Comment by jkister** [comment]
mea cupla.  i actually did search but guess it got past me.
