### ISSUE TITLE
Add MariaDB debugging to Travis build

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#2681]
In Boulder, we just landed this change to our Travis config: https://github.com/letsencrypt/boulder/pull/1625. It sends mysql.err to stdout in the event of failure. Hopefully this will give us more insight into the spurious i/o timeout failures.

Unfortunately to be able to do this, I had to set sudo:true (temporarily), which puts us on the slower, non-container infrastructure. I don't yet have an idea of how much slower.

Note that since the client gets more pull requests than Boulder, it tends to trigger the bug more often. You may want to consider making the same change in the client .travis.yml.

**Comment by bmw** [comment]
@jsha, how much slower have you found Travis on the non-container infrastructure?

**Comment by jsha** [comment]
It's been pretty anecdotal. It "felt like" it was taking longer for our jobs to even start. But perhaps Travis has just been slow in general recently?

I think also the client team has been landing a high volume of pull requests recently, and since both client and boulder share Travis' max of 5 simultaneous tasks per organization, and Boulder has 4 tasks per build, and client has ~9 tasks per build, this may have been a matter of waiting on client builds. So, like I said... anecdotal. :-)

**Comment by bmw** [comment]
The client team has certainly has a had a lot of PRs recently as we were approaching the 0.5.0 release. We'll give it a shot and see how it goes.
