### ISSUE TITLE
LE manual client and account private keys

### ISSUE THREAD

**Issue by raphaelokon** [letsencrypt/letsencrypt#2689]
Hi! 
Does the LE client /w manual authenticator + csr needs access to the account private keys?

**Comment by bmw** [comment]
Hello there!

Assuming you're referring to the ACME account key pair as described in the [ACME spec](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-3), then yes, the manual authenticator needs access to your account private key. The reason for this is the ACME protocol requires that all requests are signed by the account private key ([source](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-5.1)).

If on the off chance you're referring to they private key that was used to sign the CSR that was provided with `--csr`, the LE client (regardless of authenticator) does not need access to that private key.

**Comment by raphaelokon** [comment]
Hi @bmw. Thanks, this is really helpful! I was referring to the former – as it is obvious that I can sign the CSR with my own private key and provide it via `--csr`.

Regarding the ACME account key pair: So theoretically it should be possible to sign those API requests myself (similar to like gethttpsforfree.com)?

**Comment by bmw** [comment]
Yes, that is certainly theoretically possible and https://gethttpsforfree.com is a great example of that.

From a practical perspective of doing this using this LE client, a fair amount of work would have to be done as signed requests can occur outside of the `manual` authenticator and in the core of the `letsencrypt` client as well, such as when updating your [registration](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-6.3).

**Comment by raphaelokon** [comment]
@bmw Yes. Is there a way to delete the ACME account btw? I saw it mentioned in the ACME editor's draft but couldn't find anything API endpoint or command option.

**Comment by bmw** [comment]
I believe the only way to delete an existing account is to perform [account recovery](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-6.4) which creates an new ACME account in the process and is not currently implemented by the server or the client.

**Comment by raphaelokon** [comment]
Cheers. I found this here: https://ietf-wg-acme.github.io/acme/#rfc.section.6.3.2

**Comment by bmw** [comment]
Nice catch! This was added to ACME spec 4 days ago in this PR: ietf-wg-acme/acme#98

Being in the spec, it will almost certainly be implemented at some point, but it'll probably be a while.

One thing I forgot to mention in my previous post is the Let's Encrypt server does allow you to update the e-mail address associated with your registration, however, this is not supported by the client yet (see #1215).

**Comment by raphaelokon** [comment]
Nice one! Also great news on updating the registration – quite handy. This issue went a bit off-topic :-) My initial questions has been answered, closing it. Thanks a lot for your time and effort @bmw
