### ISSUE TITLE
Advising the user about important facts

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#271]
It seems like there's an ever-growing number of important things that the user ought to be told about (contractual obligations; locations of key material; existing backups of key material; need to protect and back up key material; existence of auto-renewal; how to revoke a cert).

We need to think through which things the user needs to be told about, under what circumstances, and how they'll be phrased, and perhaps also do some experiments to see whether the information is clear and memorable to the user (and also whether it causes annoyance or makes the cert deployment process appear to take longer than it reasonably should).

**Comment by pde** [comment]
I think a good way to do this would be to print, right before exiting successfully, a set of relevant notes for the sys admin.  Something like:

> IMPORTANT NOTES:

>  - automatic renewals have been configured for your certs; they are controlled from /etc/lets-encrypt/renewal.cfg
>  - your account credentials, keys, certs, chains etc live in directories below /etc/lets-encrypt/.  Please make a secure backup.
>  - [if in secure mode] secure mode is enabled for your site. Run lets-encrypt-nginx --security-status for more info.
>  - if you lose your account credentials, your recovery method will be emails sent to username@you.just.gave.us.com | the following token "FOGGY IMPROBABILITY QUIZZICAL HIPPOPOTAMUS"; you must write that down and put it in a safe place

**Comment by pde** [comment]
By default this buffer of notes should be printed at exit; one day people may want other ways of delivering it, such as email, but that's not a priority.

**Comment by pde** [comment]
@schoen @jdkasten The function that's called here should have some minimal priority component (priority={1,3}?) which helps us to organise the display of these messages after the client has finished.

**Comment by schoen** [comment]
The reporter mechanism (#453) can now take care of displaying them to the user, but we still need the code to actually generate the messages. :-)

**Comment by schoen** [comment]
#480, which I'm about to merge, fixes this at a basic level, but we should still review the selection of notifications as a part of the overall UI review.

**Comment by pde** [comment]
I think this ticket is done; we can open another one for final UI review if we like.
