### ISSUE TITLE
Mac OS X Server "/.well-known/acme-challenge/***KEY***" 

### ISSUE THREAD

**Issue by mooretechman** [letsencrypt/letsencrypt#2710]
I know that this is how letsencrypt verifies that I own the server, however when I make the required file for this URL and navigate to it this is what OS X Server produces:

> Websites are turned off.
> An administrator can turn them on using the Server application.

Does anybody know how I can fix this issue?

**Comment by nitmir** [comment]
duplicate of #1782

**Comment by pde** [comment]
Closing as a duplicate.
