### ISSUE TITLE
Provide a command without any updates

### ISSUE THREAD

**Issue by Levino** [letsencrypt/letsencrypt#2730]
The "apt-get" calls in letsencrypt auto are error prone. Is there a way to call commands without updating and so on? The currenct letsencrypt-auto command does too much and produces too many errors to be used in standalone servers and production environments.

**Comment by pde** [comment]
Yes, absolutely.  If you run it with `--no-self-upgrade`, it won't do any upgrading of anything after the first run.  So you can run it once to install a virtual env, and then supply the flag thereafter.

Note that there are also packages now available for Debian jessie backports, EPEL 7 and Ubuntu xenial. Those are recommended over `letsencrypt-auto`, too.

**Comment by Levino** [comment]
Any refrence for the packages for jessie?

**Comment by nitmir** [comment]
@Levino see http://backports.debian.org/Instructions/
In short:
 * Add `deb http://ftp.debian.org/debian jessie-backports main` to your `/etc/apt/sources.list`
 * Do `sudo apt-get update`
 * Do `sudo apt-get -t jessie-backports install letsencrypt`

**Comment by Levino** [comment]
Thanks @nitmir !
