### ISSUE TITLE
Some people's renewal spuriously appends digits to the directory URI

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2744]
Described in

https://community.letsencrypt.org/t/renewal-failure-404-error/13193

Two different people are seeing 404 errors on renewal because their client is somehow appending a number (different for each of them) to the directory URI (despite these numbers seemingly *not* being present in the `server` variables in the renewal configs!).

I thought we saw something like this before, but the number was then actually present in the renewal config then, where in this case it appears not to be. I don't know why the client would modify the directory location in this way.

**Comment by bmw** [comment]
Both people who reported the issue followed up saying that they had a bad `cli.ini` file that had random numbers appended to the `server` value. Because of this, I believe this issue can be closed.
