### ISSUE TITLE
Can't generate certificate for new TLD (registered in 2014)

### ISSUE THREAD

**Issue by mishu-** [letsencrypt/letsencrypt#2753]
I am trying to register the `preview.builders` domain, but I am getting `"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Name does not end in a public suffix","status":400` on the `Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz` call.
The domain has been in the public domains list for a while:
https://github.com/publicsuffix/list/blame/master/public_suffix_list.dat#L7392
 
![image](https://cloud.githubusercontent.com/assets/611429/14232142/3a281082-f9a7-11e5-8bdf-35afae202a25.png)

Am I missing something?

**Comment by schoen** [comment]
> I am trying to register the `preview.builders` domain, but I am getting `"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Name does not end in a public suffix","status":400` on the `Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz` call.
> The domain has been in the public domains list for a while:
> https://github.com/publicsuffix/list/blame/master/public_suffix_list.dat#L7392

Thanks for the report!  The repository that you filed it in is meant for
tracking client problems rather than server problems.  Could you please
re-file this issue in letsencrypt/boulder?

**Comment by mishu-** [comment]
https://github.com/letsencrypt/boulder/issues/1707
