### ISSUE TITLE
Renew with Ubtuntu

### ISSUE THREAD

**Issue by dotMastaz** [letsencrypt/letsencrypt#2756]
Hello,

On ubuntu : 

After an letsencrypt-auto, i want to renew...
I go to /home/user/.local/share/letsencrypt/bin/letsencrypt , but none here.
I test : letsencrypt-auto renew, but none ?

Any ideas ?
Thank you !!

**Comment by dotMastaz** [comment]
I try :
./letsencrypt-auto --renew --config /etc/letsencrypt/renewal/www.xxxxx.fr.conf certonly
But i many errors... ?

**Comment by bmw** [comment]
> I go to /home/user/.local/share/letsencrypt/bin/letsencrypt , but none here.

Were you looking for the certificates here? By default, they are stored in `/etc/letsencrypt`. More specifically, the symlinks in `/etc/letsencrypt/live/<domain>/` point to the most recently issued certificate/chain/fullchain and the most recently used private key.

> I test : letsencrypt-auto renew, but none ?

If you're certificates aren't due for renewal, this command has no effect. You can change this behavior by providing `--force-renewal` on the command line.

**Comment by dotMastaz** [comment]
There was the common python error 1 with ./letsencrypt-auto renew.
https://community.letsencrypt.org/t/cant-get-letsencrypt-to-install-error-code-1/7955
I restart my droplet and it's done now.
But even with the --force-renewal, if the cert is not due for renewal, you can't force it...
