### ISSUE TITLE
How to install the package globally?

### ISSUE THREAD

**Issue by clytemnestra** [letsencrypt/letsencrypt#2779]
My steps are from the getting started guide

```
 git clone https://github.com/letsencrypt/letsencrypt
 cd letsencrypt
 ./letsencrypt-auto --help
```
This installs it locally, so if I try to run 

```
 ./letsencrypt-auto --apache
```
After selecting the domain for which to install the certif., I'm getting 

```
failed to connect to host for dvsni challenge
```

By accident I discovered I could run from here, too
```
/root/.local/share/letsencrypt/bin/letsencrypt
```

And this worked just fine. What's the difference between the two?

Running 
```letsencrypt --apache```
like the guide says doesn't work because it is not installed globally by default.

Aside from that, :+1: for this, made my life a bit easier.

**Comment by pde** [comment]
`letsencrypt-auto` is a self-updating wrapper script, which creates the virtual environment in `~/.local/share/letsencrypt/` and calls into it.  If you call the copy in the virtual environment, you will not get the autoupdating behaviour if a new release has been made.

(You can also get the same effect with `--no-self-upgrade`)
