### ISSUE TITLE
Dialog display sometimes flickers

### ISSUE THREAD

**Issue by pavgup** [letsencrypt/letsencrypt#279]
**Ubuntu 14.04.1 LTS x64** seems to be having trouble pulling the display together correctly.  But the application certainly hums along smoothly.
![screenshot 2015-03-09 07 26 01](https://cloud.githubusercontent.com/assets/1335171/6554054/8f5d4c9c-c62d-11e4-96d0-64ba75e35d0d.png)

**Ubuntu 14.10 x64** has no problems with displaying the dialog.  This is mostly to prove I don't have a broken terminal somehow.  (which could still be true, frankly.)
![screenshot 2015-03-09 05 39 34](https://cloud.githubusercontent.com/assets/1335171/6554027/5b192e92-c62d-11e4-97d0-64ae24876d52.png)

**Comment by jdkasten** [comment]
I have seen this problem occur a few times throughout development on my 14.04 Ubuntu testing server, but I believe it resolves itself during the next SSH session.  It hasn't occurred recently for me and I haven't investigated.

**Comment by pavgup** [comment]
If this is still open, I'll report back in 48 hours.

**Comment by pde** [comment]
I've seen these while ssh-ing into a remote debian box.

**Comment by jdkasten** [comment]
I don't think that there is anything that we can do about this.  This seems to be a rare occurrence with the python dialog library.

**Comment by pde** [comment]
Perhaps we should file this as an upstream bug with dialog?
