### ISSUE TITLE
ln: /usr/bin/letsencrypt: Operation not permitted

### ISSUE THREAD

**Issue by patelvishal1401** [letsencrypt/letsencrypt#2796]
Just following this Command. 

and getting error on last line.

cd /usr/local
sudo git clone https://github.com/letsencrypt/letsencrypt

sudo ln -sf /usr/local/letsencrypt/letsencrypt-auto /usr/bin/letsencrypt

Error is like : ln: /usr/bin/letsencrypt: Operation not permitted

**Comment by patelvishal1401** [comment]
I solved it via , 

<img width="664" alt="screen shot 2016-04-09 at 1 28 58 pm" src="https://cloud.githubusercontent.com/assets/6769381/14402552/11602da6-fe57-11e5-8ed0-ef0fa93ce27b.png">

**Comment by garrethmcdaid-zd** [comment]
Or just create the link in `/usr/local/bin`
