### ISSUE TITLE
Webroot plugin should support challenges over https/443

### ISSUE THREAD

**Issue by andornaut** [letsencrypt/letsencrypt#2801]
I have a webserver that only accepts connections on port 443. This prevents me from using the webroot plugin, because the challenge fails when attempting to connect to port 80.

It'd be great if the webroot plugin could perform challenges over port 443. Additionally, it be convenient if it ignored certificate errors while performing challenges on port 443, which is probably no less secure than the current default of performing the challenge over plain http.

**Comment by kuba** [comment]
This is by design: spec is available at https://ietf-wg-acme.github.io/acme/. Using https/443 has security problems in practice (this is due to how default vhosts work in major HTTP servers - an issue especially important on shared hosting platforms).
