### ISSUE TITLE
Installing packages when running ./letsencrypt-auto -help is NOT OK

### ISSUE THREAD

**Issue by ThomasHabets** [letsencrypt/letsencrypt#2806]
Give error message, or tell me to run a command. But don't just install things without asking.

**Comment by dave8128** [comment]
I was very surprised when running this "help" command as per the getting started page to find packages installing without prompting me to confirm.

**Comment by bmw** [comment]
This is largely a dupe of #1903, however, the installation instructions at https://letsencrypt.org/getting-started/ probably shouldn't use `--help` as the example.

**Comment by ThomasHabets** [comment]
Using --help as an example is fine.
1) Installing when using --help is NOT fine
2) Installing without asking for permission is NOT fine

But yeah this looks like a dup.
