### ISSUE TITLE
Letsencrypt validation with HTTPS requests

### ISSUE THREAD

**Issue by huegelc** [letsencrypt/letsencrypt#2807]
According to the documentation (https://letsencrypt.readthedocs.org/en/latest/using.html#id9) it is not possible to validate a domain through https requests.
I have multiple domains which I redirect with `return 301 https://$server_name$request_uri;`  thus they are only accessible through https. 
I have to run a script to comment out the redirection and reload nginx before running the automated letsencrypt script.
Is there another way to get around this situation? Thank you

**Comment by patf** [comment]
Redirecting to `https://` is fine as long as your service is initially available on port 80 and the URL to which you're redirecting is serving the challenge token. The `webroot` section of the documentation has a small description of how the validation request works.

Please use the [Community Forum](https://community.letsencrypt.org/) for questions of this nature.

**Comment by huegelc** [comment]
Thank you
