### ISSUE TITLE
Automate email and accept terms

### ISSUE THREAD

**Issue by jbwyatt4** [letsencrypt/letsencrypt#2820]
Hello,

Is there a way to automate passing an email and accepting the terms by the command line. I am trying to integrate let's encrypt into my Chef scripts. Something like --contact contact@example.com --accept_terms

**Comment by bmw** [comment]
Yes. `--email contact@example.com --agree-tos`.

There are many more commands that can be used for automation that can be found by running `letsencrypt --help all`.
