### ISSUE TITLE
System-wide changes

### ISSUE THREAD

**Issue by szepeviktor** [letsencrypt/letsencrypt#2828]
`./letsencrypt-auto certonly --standalone ...`
Could you please make it clear what changes are expected (which files) in the OS?

**Comment by szepeviktor** [comment]
I was able to debug this much:
`apt-get install -y --no-install-recommends python python-dev virtualenv python-virtualenv gcc dialog libaugeas0 augeas-lenses libssl-dev libffi-dev ca-certificates`

**Comment by szepeviktor** [comment]
These are my secret weapons:
```bash
sudo apt-get install -y dialog wget unzip
wget https://github.com/letsencrypt/letsencrypt/archive/master.zip && unzip master.zip
cd letsencrypt-master/
bash -x -- letsencrypt-auto -h
# Phase 2
bash -x -- letsencrypt-auto --le-auto-phase2 -h
```

**Comment by bmw** [comment]
Perhaps a duplicate of #2821? We should make it clearer what `letsencrypt-auto` does and how it will modify your system.

**Comment by szepeviktor** [comment]
Yes, it is.
