### ISSUE TITLE
Easy Mode not working correctly

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [letsencrypt/letsencrypt#2833]
When I enabled Easy Mode when I installed Lets Encrypt after reinstalling, it all keeps being redirected to HTTPS when I use for example http://windmillgaming.net

**Comment by bmw** [comment]
There's certainly a redirect enabled. A couple possibilities:

1. Is it possible you already had an HTTP -> HTTPS redirect enabled on that site? If you search your Apache configuration for `RewriteRule`, you do you see anything relevant that may have been there previously.

2. If you search the `letsencrypt` logfiles (in `/var/log/letsencrypt`) for `redirect`, do you find any references to `redirect`, possibly from a previous run of `letsencrypt`?

**Comment by xH3LLRAIZ3Rx** [comment]
I somehow fixed it, don't really remember how, but I did
