### ISSUE TITLE
Update readthedocs references

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2845]
There are still a number of references to https://letsencrypt.readthedocs.org in our code. These should be cleaned up to point to the new doc location.

**Comment by SwartzCr** [comment]
This will have to wait until after we've started hosting the docs on an EFF site
relatedly, is it possible to get the readthedocs page to redirect once that's done?

**Comment by SwartzCr** [comment]
I've done this in my rename pr
