### ISSUE TITLE
setuptools pip wheel failed with error code 1

### ISSUE THREAD

**Issue by theobarnhart** [letsencrypt/letsencrypt#2850]
I'm working on installing setuptools on OS X 10.11.4, I have an Anaconda python install and pip installed virtualenv, but I keep getting this error when I try and install letsencrypt. I also tried updating setuptools using pip but that didn't help either. Any thoughts on how to fix this would be appreciated. Thanks!

```
ullr:letsencrypt barnhatb$ ./letsencrypt-auto certonly --debug
Bootstrapping dependencies via Mac OS X...
Using Homebrew to install dependencies...
Warning: augeas-1.4.0 already installed
Warning: dialog-1.3-20160209 already installed
Checking for new version...
Creating virtual environment...
Traceback (most recent call last):
  File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Users/barnhatb/anaconda/lib/python2.7/site-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/barnhatb/.loc...ncrypt/bin/python2.7 - setuptools pip wheel failed with error code 1
```

**Comment by bmw** [comment]
Looks like this might be an instance of pypa/virtualenv#741.

**Comment by theobarnhart** [comment]
That worked! Thank you.

Theodore Barnhart
PhD Candidate
INSTAAR / Geography
University of Colorado
theodore.barnhart@colorado.edu
http://theobarnhart.host-ed.me/

**Comment by sw-yx** [comment]
sept 2016 checking in, still have to downgrade to 2.7.9 per @bmw 's link above

**Comment by mahinthjoe** [comment]
Oct 2016 checking in, [downgrade to 2.7.9](http://chris35wills.github.io/conda_python_version/)

**Comment by kabrink** [comment]
Feb 2017 checking in, [http://chris35wills.github.io/conda_python_version/](url) (same link as above).

**Comment by Tejaf** [comment]
Feb 2017, downgrade still works...wow!

**Comment by sitaramanp** [comment]
Mar 2017. We still have to downgrade to 2.7.9

**Comment by Tejaf** [comment]
Lol ikr... I still downgraded yesterday after I mistakenly upgraded my
heroku

**Comment by shintojoseph1234** [comment]
This will work for virtualenv pip wheel errorcode1 problems and also E unable to locate package problems

    apt-get update

    apt-get install python-software-properties

    apt-get install apt-file

    apt-file update

    apt-get install software-properties-common

    apt-get install <your filename>

**Comment by nilooravaei** [comment]
Apr 2017. We still have to downgrade to 2.7.9

**Comment by raydai** [comment]
May 2017, We still have to downgrade to 2.7.9

**Comment by bmw** [comment]
We don't recommend you use Certbot on macOS. Support on that platform has always been experimental. If you don't include the `--debug` flag on the command line when you try to install Certbot on that system, you get a message like:
```
FATAL: macOS support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!
Alternatively, you can install OS dependencies yourself and run this script
again with --no-bootstrap.
```
Instead, we recommend you follow our macOS instructions found at https://certbot.eff.org/#osx-other. Our instructions recommend you use Homebrew, but if you prefer MacPorts, there is a [port](https://www.macports.org/ports.php?by=name&substr=certbot) available.

**Comment by jwilber** [comment]
Running ```conda install -c anaconda virtualenv=15.1.0``` worked for me.

**Comment by fzhcary** [comment]
struggled for hours and finally find solution:
pip uninstall virtualenv
conda install virtualenv

virtualenv in pip doesn't work with conda.

**Comment by tatianafrank** [comment]
@fzhcary solution above does not work for me, produces same error on osx

**Comment by abdulwahid24** [comment]
same here @tatianafrank , Let me know if you got any solution?

**Comment by abdulwahid24** [comment]
I got it resolve by `python3 -m venv myenv`

**Comment by whoget** [comment]
i got it resolve using:
pip install --upgrade virtualenv

**Comment by davidespinozao** [comment]
These two commands are the final solution for me:
pip install --upgrade virtualenv
sudo virtualenv .env

Thanks to all

**Comment by gowthambalusamy** [comment]
pip uninstall virtualenv
conda install virtualenv

**Comment by amorrissette** [comment]
Did not need to downgrade from python 2.7.11

pip uninstall virtualenv
conda install virtualenv 

above worked for me as well

**Comment by sblcook** [comment]
Like @amorrissette and others, 

pip uninstall virtualenv
conda install virtualenv

fixed everything for me

**Comment by abdulwahid24** [comment]
Hey guys,

Check out this super cool and awesome tool [pipenv](https://docs.pipenv.org/). I guarantee you would fall in love with it.

Thanks

**Comment by abinjoabraham** [comment]
I was searching for a fix for hours finally below ones worked for me and I was using minconda versions of python.
pip uninstall virtualenv
conda install virtualenv

**Comment by personaaleatoria** [comment]
this worked
pip install --upgrade virtualenv
