### ISSUE TITLE
What stops Let's Encrypt from becoming corrupt?

### ISSUE THREAD

**Issue by grepwood** [letsencrypt/letsencrypt#2876]
The obvious way a CA can become corrupt is if they disclose the signing key to 3rd parties, in any way, shape or form.

So what exactly stops Let's Encrypt from such scenarios like:
- disclosing the key to the feds
- selling the key on darknet/.onion

The reason I ask is because this is a very tempting opportunity to get SSL certificates for gratis, but how can I be sure that if I don't pay for a product, am I and my traffic not the product itself?

**Comment by lukas2511** [comment]
What stops other CAs from becoming corrupt? It's a system of trust, if you don't trust a CA it doesn't work.

**Comment by lukas2511** [comment]
Also just the CA keys wouldn't give access to your traffic. There will still be the need for an active MITM attack.

**Comment by schoen** [comment]
Hi @grepwood,

Thanks for the question.

This kind of question is more appropriate for the Let's Encrypt Community Forum at https://community.letsencrypt.org/ (where organizational and policy questions about ISRG services are on-topic). This particular issue tracker is only intended for technical problems with the Python client software.

There have been some previous discussions on the community forum that are somewhat related to your question, although I don't think anyone phrased it in exactly the same terms.

https://community.letsencrypt.org/t/lets-encrypt-and-u-s-laws/3251/1

https://community.letsencrypt.org/t/what-is-the-business-model/310

https://community.letsencrypt.org/t/ssl-is-broken-the-backdoor-is-built-in/878

I've tried to address some of these concerns in forum posts. The short answer is that every CA has policy and technical controls that are meant to discourage it from misissuing certs (or inappropriately disclosing its own keys), but auditors can't watch day-to-day to ensure that CAs don't subvert their own control mechanisms. So, right now we're reliant on auditors' determination that a CA's controls and intentions are credible, and on browser vendors and the information security community to monitor what CAs really do in practice and detect and investigate instances of misissuance. Initiatives like Certificate Transparency (which Let's Encrypt has supported from the outset) aim to increase the transparency of CA operations and reduce CAs' ability to undetectably do the wrong thing.

@lukas2511 is right to point out that, given the design of TLS, the CA (even if malicious) never has direct access to user's encrypted communications. The worst thing that the CA could do is allow other parties (who control or tamper with network infrastructure) to perform an active attack against some communications at a particular time, which may not be automatically detected or prevented by the browser, but which does run some risk of leaving behind publicly-visible evidence.

Please feel free to continue this discussion on the community forum if you'd like.
