### ISSUE TITLE
Inconsistent behavior on --webroot-path invocation (OS X)

### ISSUE THREAD

**Issue by gotnate** [letsencrypt/letsencrypt#2891]
When I pass in the --webroot-path flag, the wizard only intermittently offers the option to use the webroot authenticator. 

In this example, it cooperated on my 2nd invocation, and I changed *nothing* on my config.

![broken](http://i.imgur.com/0Qv0e6X.png)
![works](http://i.imgur.com/VthctPo.png)

**Comment by bmw** [comment]
I'm unable to repo this but I don't have access to an OS X machine.

Do you have the log of a run where this problem occurred? Logs are stored in `/var/log/letsencrypt` by default.

Alternatively, if you can still reproduce the problem, can you run the client adding the flags `-vvt` and post the corresponding output?

**Comment by gotnate** [comment]
Thank you bmw for the clue. The log file told me exactly what the issue was (though why it changed between 2 attempted runs, i have no clue). It would be nice if these kind of errors were printed to my shell rather than leave me scratching my head as to why I can't use the webroot authenticator. Of course now that I know that this stuff is logged, I know where to look next time.

2016-04-24 21:18:43,538:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /Volumes/[redacted]/.well-known/acme-challenge
2016-04-24 21:18:43,827:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): ("Couldn't create root for {0} http-01 challenge responses: {1}", '[redacted].com', OSError(1, 'Operation not permitted'))
