### ISSUE TITLE
Cannot revoke and create new SSL certificate

### ISSUE THREAD

**Issue by shaneonabike** [letsencrypt/letsencrypt#2893]
So I stumbled upon an interesting scenario and need some help quite quickly because I can no longer access my encrypted site :/

Basically, I created the following SSL certificate for 
* cloud.mysite.org

All was workng well and then I decided I wanted to provide that for the actual main site so I did..

./letsencrypt-auto apache -d cloud.mysite.org -d www.mysite.org

But this in fact caused the certificate and browsers to get confused. I realize now (perhaps it's a bug) but the second item should have been at the start no vic versa. I no longer was receiving a 'safe' certificate on the subdomain.

So then I revoked the certificate locally and attempted to create a new one. Ironically, no matter what I do the certificate is ALWAYS regenerated with the www.mysite.org even though I have another certificate specifically just for that.

Any help would be super awesome!!

**Comment by schoen** [comment]
Hi @shaneonabike, a couple of things you said don't make sense to me, especially

> I realize now (perhaps it's a bug) but the second item should have been at the start no vic versa. I no longer was receiving a 'safe' certificate on the subdomain.

I'm not familiar with any reason why this should make a difference to clients at all; we have lots of users who use an arbitrary order and get successful cert coverage for many names (even dozens of names, not just two). Would you like to show us the certificate in question? Are your clients very old mobile clients or unpatched Windows XP or something?

> So then I revoked the certificate locally and attempted to create a new one. Ironically, no matter what I do the certificate is ALWAYS regenerated with the www.mysite.org even though I have another certificate specifically just for that.

How did you revoke the certificate and what change in behavior did you expect? What command are you now using to reissue the certificate, and how are you confirming what the coverage of the new certificate is?

Thanks.

**Comment by shaneonabike** [comment]
Hey!

Two things. One of the certificates is generated by apache but for the main domain it cannot be done through apache (since the actual site conf is located in a seperate folder I believe Lets Encrypt doesn't parse). Translation: The main domain was created with the certonly statement.

The weird thing that happened is that after having done that my configuration never used hte proper certificates. Even though in the live directory there were two seperate certificates I ended up with the main www.site.org using the subdomain certificate.

Honestly, I also found this weird because on my own system it's working perfectly. But perhaps the real issue is attempting to create one certificate with teh certonly and the other using apache? Could that be possible...

**Comment by shaneonabike** [comment]
BTW they aren't using old systems it happens on my Ubuntu 15.10 as well

**Comment by schoen** [comment]
If you use `certonly`, the client doesn't attempt to install the certificate for you; you would need to edit your Apache configuration yourself in order to make it refer to that certificate.

**Comment by shaneonabike** [comment]
I am aware of that and had done that as well

On 2016-04-28 05:21 PM, schoen wrote:
>
> If you use |certonly|, the client doesn't attempt to install the
> certificate for you; you would need to edit your Apache configuration
> yourself in order to make it refer to that certificate.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/letsencrypt/letsencrypt/issues/2893#issuecomment-215550083>
>

-- 

Shane Bill

Web Developer & Consultant

Bees on a Bike

E-mail 	shane@beesonabike.com <mailto:shane@beesonabike.com>
Mobile 	(514) 608-8068
Phone 	(418) 969-2334
More information @ Bees on a Bike 	https://beesonabike.com

**Comment by shaneonabike** [comment]
It turns out that in my port.conf I did not have NameVirtualHost *:443 defined. Therefore, it was moving all the directs to the main domain.

It's fair to say that this isn't the fault of the tool or letsencrypt but more the user :/

THanks for everyone contributing
