### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by igroykt** [letsencrypt/letsencrypt#2900]
Hi all!
Strange problem with ssl:

> CONNECTED(00000003)
> depth=0 C = --, ST = SomeState, L = SomeCity, O = SomeOrganization, OU = SomeOrganizationalUnit, CN = share, emailAddress = root@share
> verify error:num=18:self signed certificate
> verify return:1
> depth=0 C = --, ST = SomeState, L = SomeCity, O = SomeOrganization, OU = SomeOrganizationalUnit, CN = share, emailAddress = root@share
> verify error:num=10:certificate has expired
> notAfter=Aug 14 02:50:25 2015 GMT
> verify return:1
> depth=0 C = --, ST = SomeState, L = SomeCity, O = SomeOrganization, OU = SomeOrganizationalUnit, CN = share, emailAddress = root@share
> notAfter=Aug 14 02:50:25 2015 GMT
> verify return:1

Date is wrong. How it could be?

> Server certificate
> subject=/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=share/emailAddress=root@share
> issuer=/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=share/emailAddress=root@share

> No client certificate CA names sent
> Server Temp Key: ECDH, prime256v1, 256 bits

> SSL handshake has read 1334 bytes and written 373 bytes

> New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
> Server public key is 1024 bit
> Secure Renegotiation IS supported
> Compression: NONE
> Expansion: NONE
> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : ECDHE-RSA-AES256-GCM-SHA384
>     Session-ID: 0BF579F4BC254066CCCC990705BA8678F7D0097C5C5783A367ADC87BC8A07283
>     Session-ID-ctx:
>     Master-Key: E95E18A72CA7FB1D533CE83B8E7DC39D623AE151E324AF9BB51646B464843315EE86AA46026ED7DBC99C90B9AA5E6674
>     Key-Arg   : None
>     Krb5 Principal: None
>     PSK identity: None
>     PSK identity hint: None
>     TLS session ticket lifetime hint: 300 (seconds)
> 
>     Start Time: 1461819653
>     Timeout   : 300 (sec)
>     Verify return code: 10 (certificate has expired)

Problem with openssl or with certificates or apache missconfiguration? Any ideas?

**Comment by igroykt** [comment]
Found error:

> [Thu Apr 28 21:58:28 2016] [warn] RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
> [Thu Apr 28 21:58:28 2016] [warn] RSA server certificate CommonName (CN) `share' does NOT match server name!?

I think cn should be share.mydomain.com? This certificate was generated manually:
1.letsencrypt-auto --agree-dev-preview --server \https://acme-v01.api.letsencrypt.org/directory -a manual auth
2.entered share.myadomain.com
3.started standalone webserver
4.on reverse proxy set this directives:
default_type text/plain;
charset off;
but this didn't help and the content type was still plain/text utf8 so added to location
proxy_hide_header Content-Type;
add_header Content-Type text/plain;
then checked header and it show "content-type: text/plain".
5.the i get this error "Self-verify of challenge failed."
6. next message is "Use of --agree-dev-preview is deprecated. IMPORTANT NOTES: - Congratulations! Your certificate and chain have been saved".
but problem is still the same.
I wonder why CN is not complete (just hostname instead of fqdn)?

**Comment by schoen** [comment]
The certificate you're looking at is not a Let's Encrypt certificate. Let's Encrypt doesn't put any of the X.509 contact information such as `S`, `T`, `L`, and `OU` into our certificates, we weren't issuing certificates to the public early enough for one to expire in August 2015, we wouldn't issue a certificate for a non-FQDN like "share", and we have never permitted issuance of certificates for 1024-bit subject public keys. You must be looking at a certificate or a server that's somehow configured to use some other certificate, not one of ours.

**Comment by igroykt** [comment]
@schoen Thank for reply! You answer brought me to right path. Problem was in apache. Somehow he gaved certificate from _default_ vhost only and ignored others. Found disabled directive "use canonical names" and i think thats the problem. Anyway now it give right answer:

> issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
> Verify return code: 0 (ok)

Thank for help. Now i had to do some tests to make sure that everything work fine.
