### ISSUE TITLE
CommonName is not first domain provided

### ISSUE THREAD

**Issue by FlorentCoppint** [letsencrypt/letsencrypt#2904]
Hi,

Today I made a new certificate for a few domains.

I ran : 
letsencrypt-auto certonly --non-interactive --rsa-key-size 4096 --webroot -w /webdata/webdata1/default -d web01.company.ch -w /webdata/webdata1/webmail -d webmail.company.ch -d webmail.customer1.net -d webmail.customer2.net -d webmail.company.com -d webmail.company.net -d webmail.customer3.fr --agree-tos --email serveradmin@company.ch

A few weeks ago, same certificate was issued with CommonName "web01.company.ch", but today CommonName is "webmail.company.net".

BUT Let's Encrypt client still stores it in /etc/letsencrypt/live/web01.company.ch ! (I moved old ones before, to revoke them after new certificate is issued).

Is there a new option to specify which domain to use as CommonName ?

Thank you.
Florent

**Comment by wdzr** [comment]
It's a bug in release v0.5.0, should be fixed in next release, or you can downgrade to v0.4.2. https://github.com/letsencrypt/letsencrypt/releases

**Comment by FlorentCoppint** [comment]
Ok sorry I didn't find existing issue for this ;-)
