### ISSUE TITLE
False "Requested domain  is not a FQDN" 

### ISSUE THREAD

**Issue by LouWii** [letsencrypt/letsencrypt#2916]
Hi,

It's never the right time to have issues...
I got a certificate expiring tomorrow, and I can't renew it.

    letsencrypt certonly --apache --renew-by-default --domains 
    Requested domain  is not a FQDN

This is what I got for the domain https://canada.with.susie.and.louwii.fr/

What file should I modify in order to make that work ? I'd like to renew my cert quite quickly.

Thanks !

**Comment by bmw** [comment]
The FQDN is:
```
canada.with.susie.and.louwii.fr
```

If you prepend `https://` like you would in your web browser, this is no longer a domain name and you'll see the error you encountered.

Alternatively, if you're running an up to date version of the client (if you run `letsencrypt --version` you should see version 0.5.0), you can simply run `letsencrypt renew`. This will renew your cert for you with the names you originally requested.

One caveat to this approach is `letsencrypt renew` will renew any certificates you have that are within 30 days of expiration. This may or may not be the behavior you want.

**Comment by LouWii** [comment]
Hum, interesting.

I have a script to renew certificates. That script was giving me the issue.
But I ran `/opt/letsencrypt/letsencrypt-auto certonly --apache --renew-by-default --domains canada.with.susie.and.louwii.fr` manually and it went through.

I'm gonna need to fix my renewal script.

Thanks bmw, you made me think and test the direct command line.

**Comment by jackrvaughan** [comment]
Posting this as it popped up on google. 

If anyone has getting the `Requested domain  is not a FQDN because it contains an empty label.` issue for multiple domain names (when using --expand for example), ensure there are no spaces between the domain names - only separate them with a comma. 

I was writing: 

```
./certbot-auto certonly --expand -d first.domain.com, second.domain.com
```
It should be:
```
./certbot-auto certonly --expand -d first.domain.com,second.domain.com
``` 

I don't _believe_ that used to be a requirement but certainly is now.

**Comment by adrianbj** [comment]
Thanks @jackrvaughan - that solved the issue for me!

**Comment by countingpine** [comment]
I had the same issue renewing with a CSR generated in Windows where some of the SANs had been added with a comma at the end of the domain name (e.g. '`example.com,`').  So in general that seems to be what causes the error.

I wonder if there's a point where certbot is converting the SANs to a comma-separated list (e.g. `example.com,,www.example.com`, and then the trailing comma gets treated as a delimiter, causing a blank requested domain to appear?

Perhaps before that conversion, it should check for commas at the end of domains (or in the middle of them) and give a warning.

Commas will perhaps only appear at the end of a SAN if passed via the command line, as Jack shows, but they (and presumably other invalid characters) could appear anywhere in a SAN if it's passed via CSR.
