### ISSUE TITLE
Didn't support a domain name "xn--q3cblu9dn4n.com"

### ISSUE THREAD

**Issue by iiitum** [letsencrypt/letsencrypt#2928]
Dear Letsencrypt Team.

I need to install an SSL to "[xn--q3cblu9dn4n.com](http://xn--q3cblu9dn4n.com)" but didn't support.
I run a command line with `/opt/letsencrypt/letsencrypt-auto --apache -d xn--q3cblu9dn4n.com -d www.xn--q3cblu9dn4n.com` after the terminal display a message "Punycode domains are not presently supported: xn--q3cblu9dn4n.com"

PS. A domain "[xn--q3cblu9dn4n.com](http://xn--q3cblu9dn4n.com)" is same "[พระบ้าน.com](http://พระบ้าน.com)". I'm registered in Thailand.

Thanks.

**Comment by schoen** [comment]
Hi @iiitum,

It is correct that the Let's Encrypt CA currently does not support internationalized domains at all. This is a matter of policy and not a software bug.

This policy is discussed on the Community Forum at

https://community.letsencrypt.org/t/internationalized-domain-names/94/74

According to https://letsencrypt.org/upcoming-features/, support for internationalized domain names should become available by August 1, 2016.

**Comment by iiitum** [comment]
Dear @schoen

I thing didn't support forever. I will wait at August 1, 2016.

Thanks.

**Comment by justrp** [comment]
Still unsupported :(

**Comment by dereckson** [comment]
> Still unsupported at least on FreeBSD (current version of certbot is 0.9.3)
FreeBSD port is maintained by @koobs 

You indeed need a version of the client with 605a3cc931ff815e908282d77d0edeebd9ec94f6.

At worst, you can also apply this patch manually on your certbot installation.
