### ISSUE TITLE
Unclear error message when using private IPs

### ISSUE THREAD

**Issue by mitar** [letsencrypt/letsencrypt#2929]
```
The following errors were reported by the server:

Domain: radio.cloyne.net
Type:   unknownHost
Detail: No IPv4 addresses found for radio.cloyne.net

To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address.
```

It is not true that there are not IPv4 addresses for radio.cloyne.net, but it is not a public IP, that is true.

**Comment by schoen** [comment]
Hi @mitar,

This detail message is coming from the boulder server, not the client, so your bug report would be more appropriate in https://github.com/letsencrypt/boulder/issues (the server issue tracker).

https://github.com/letsencrypt/boulder/blob/35b6e83e8119fcc9d93afbb9a3bcb44e5525b6f3/va/validation-authority.go#L107
