### ISSUE TITLE
Patch providing instructions to set up letsencrypt on FreeBSD 10.1

### ISSUE THREAD

**Issue by slicer69** [letsencrypt/letsencrypt#293]
The following instructions can be used to prepare a FreeBSD 10.1 installation to work with Let's Encrypt.

pkg install python27 swig30 pcre libffi augeas
portsnap fetch
portsnap extract
cd /usr/ports/devel/py-setuptools
make install && make clean
ln -s /usr/local/bin/swig3.0 /usr/local/bin/swig
ln -s /usr/local/include/ffi.h /usr/include/ffi.h
ln -s /usr/local/include/ffitarget.h /usr/include/ffitarget.h
cd /path/to/letsencrypt
python setup.py build
python setup.py install

A patch for the documentation file docs/using.rst is provided below.

```
diff --git a/docs/using.rst b/docs/using.rst
index 9b09833..254e641 100644
--- a/docs/using.rst
+++ b/docs/using.rst
@@ -37,6 +37,21 @@ Mac OSX
     sudo brew install augeas swig
 
 
+FreeBSD
+-------
+
+::
+
+   pkg install python27 swig30 pcre libffi augeas
+   portsnap fetch
+   portsnap extract
+   cd /usr/ports/devel/py-setuptools
+   make install && make clean
+   ln -s /usr/local/bin/swig3.0 /usr/local/bin/swig
+   ln -s /usr/local/include/ffi.h /usr/include/ffi.h
+   ln -s /usr/local/include/ffitarget.h /usr/include/ffitarget.h
+
+
 Installation
 ============
 
```

**Comment by kuba** [comment]
Thanks for the patch. However, I'd suggest not to merge it until #294 is resolved.

**Comment by thorerik** [comment]
Instead of sumlinking /usr/local/include to /usr/include (which is a bad hack), probably better to use the pre-packaged (or ports variant) py27-cffi
also worth a note is that M2Crypto got a updated issue [here][1] where M2Crypto fails to load on OS X, workaround is to use swig 3.0.4, on freebsd I fixed that by using ports-mgmt/portdowngrade and checked out r377100

**Comment by MafiaInc** [comment]
It seems like currently there is a py27-setuptools27-17.0 binary package via pkgng so why not just:
pkg install python27 swig30 pcre libffi augeas py27-setuptools27 ?

**Comment by alexska** [comment]
Hi All.  Can`t install letsencrypt on FreeBSD ......
The setup.py install returns an error......

/usr/local/bin/python2 setup.py install
.........
Installed /usr/local/lib/python2.7/site-packages/pyparsing-2.0.3-py2.7.egg
Searching for letsencrypt
Reading https://pypi.python.org/simple/letsencrypt/
Couldn't find index page for 'letsencrypt' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for letsencrypt
error: Could not find suitable distribution for Requirement.parse('letsencrypt')      
-------------------------------------------------------------------------------------------
Someone overcomed letsencrypt installation on FreeBSD ? 


My environment:
FreeBSD 9.3-RELEASE-p8
python2-2_3                    
python27-2.7.9_1    

Were all remaining actions  in accordance with instructions above.

**Comment by kuba** [comment]
@alexska: please follow the installation instructions found at http://letsencrypt.readthedocs.org/en/latest/using.html. You will have to figure out system dependencies yourself as I didn't have yet time to test the project on FreeBSD. Have a look what's necessary on Debian https://github.com/letsencrypt/letsencrypt/blob/master/bootstrap/_deb_common.sh for inspiration. :)

**Comment by kuba** [comment]
Please check out #748.

**Comment by kuba** [comment]
This can be closed now.
