### ISSUE TITLE
Move the debian packaging into a separate repo

### ISSUE THREAD

**Issue by fmarier** [letsencrypt/letsencrypt#307]
I'd like to suggest that we move the `debian` directory to its own repository and that we only keep the contents of that directory in there.

This will remove the need to merge from master and allow us to keep more than one version of the packaging (e.g. one for jessie, one for sid, one for a particular ubuntu release, etc.) as needed. Also, it will keep all of the packaging-specific PRs and issues (which I mostly avoid filing to reduce the noise on the client issue tracker) into a separate place.

How about <https://github.com/letsencrypt/debian>?

**Comment by kuba** [comment]
Would generic letsencrypt/debian be used for both our client and Boulder?

**Comment by fmarier** [comment]
Good point, maybe it should be `letsencrypt-debian` (or `client-debian`?) so that we can add a `boulder-debian` in the future if/when we need to.

**Comment by kuba** [comment]
After thinking about it for a while..

Please note, that it is technically possible to have two totally separate (disjoint) git branches in a single repository, so we could arrange one just for `debian/` and it will not need to be synced with `master` at all.   We could also have separate `debian-jessie`, `debian-wheezy`, etc. in the currrent repo; as far as I understand, your idea assumes separate branches for each Debian version anyway. Therefore, the **argument can be reduced to "have packaging-specific PRs and issues into separate place"**.

Is it worth it? I personally wouldn't worry about the noise that much, and simply use GitHub tag "debian" for all related PRs/issues. However, you're in the end doing all Debian packaging work at the moment and @jdkasten is the decisive person here, so I leave it up to you both. Just please consider what has been written above :)

**Comment by fmarier** [comment]
@kuba Good point.

If you don't mind the extra noise and you don't mind giving me team access to that repo, then I think I could simply re-do the current branch as a disjoint one that only contains a single directory.

What do you think @jdkasten?

**Comment by jdkasten** [comment]
That sounds fine to me, whichever way is the easiest for you to work.  I am
thankful for your help.  Unfortunately, I don't believe I have permission
to add group members to the organization.
Perhaps @bdaehlie <https://github.com/bdaehlie> @pde have further opinions
and can help out.

**Comment by kuba** [comment]
We now have https://github.com/letsencrypt/letsencrypt-debian. :)

@fmarier, can you close the issue?
