### ISSUE TITLE
Add a flag to support "best effort" M-of-N success when requesting N names

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#318]
This will be required for renewal.

**Comment by jdkasten** [comment]
Related to #300

**Comment by pde** [comment]
Possible names for this option: <tt>--best-effort</tt>, <tt>--allow-partial-success</tt>, <tt>--allow-subsets-of-names</tt>.

**Comment by jdkasten** [comment]
This should be taken on after full compatibility with Boulder is achieved.  Authorization handling changes in v02 of the spec and the current dummy server doesn't support multiple names in a certificate.

**Comment by jdkasten** [comment]
This is mostly implemented... but I realized that obtain_certificate should take into account this information before requesting a certificate.

**Comment by SwartzCr** [comment]
closing now that #2327 is merged
