### ISSUE TITLE
Mechanism for remembering installer configurations

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#340]
@jdkasten and I were talking about the case where the user has provided parameters to an installer (for example, indicating a path to an Apache configuration directory).

In theory, the same parameters should be used again if that installer needs to be invoked in the future to perform tasks related to the certs that it installed (for example, by the renewer). That means that we need a way to save and restore those parameters, and presumably to associate particular installers and installer parameters with particular deployed certificates.

**Comment by bmw** [comment]
While the configuration is not remembered for the main `letsencrypt` client, the `installer` and `authenticator` used is stored by the `renewer`.
