### ISSUE TITLE
Revoker for Boulder

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#379]
`revoker.py` still uses old protocol `network.py` code.

Until we get something Boulder-compatible, I'd suggest removing it from `master` to avoid confusion (this is also a blocker for removing `network.py` and renaming `network2.py` to `network.py`), or rather moving it to a different branch for reference.

**Comment by kuba** [comment]
FYI old protocol is removed and updated as of #528

**Comment by jdkasten** [comment]
We should create a certificate management interface that can handle both revocation and renewal.

This is related to #338.

Potential relevant code.
display/revocation.py

**Comment by kuba** [comment]
Fixed in #760
