### ISSUE TITLE
Allow rollback of enabling of mod_ssl

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#394]
I found that when I used the client to get a cert for a site that previously had no HTTPS enabled at all, and then rolled back the configuration change with `-b 1`, the site continued listening on port 443 (but speaking HTTP rather than HTTPS on that port).

@jdkasten has explained this as an inability for the rollback code to disable mod_ssl if it was enabled for the first time by the client. (Apache's ports.conf apparently makes listening on 443 default behavior if mod_ssl is loaded, even if there are no actual HTTPS virtual hosts enabled. So the client enables mod_ssl and then can't disable it afterward, and then Apache continues listening on 443.)

**Comment by jdkasten** [comment]
Fixed in #631
