### ISSUE TITLE
recovery_routine should always be called when letsencrypt fails

### ISSUE THREAD

**Issue by diracdeltas** [letsencrypt/letsencrypt#395]
`recovery_routine` is not consistently called when letsencrypt exits with an error, ex: when the DVSNI challenge fails. Maybe this is intentional, but users may not expect their server config files to be left in a weird state. Also, if the user then manually edits config files, those changes are lost when letsencrypt is run again.

**Comment by jdkasten** [comment]
Cleanup used to be wrapped around all of the errors so this wasn't that big of a problem.  Error handling needs to be improved in auth_handler.py

**Comment by jdkasten** [comment]
I think the base case in auth_handler has been handled, but crash recovery still needs to be improved in general.

@bmw is working on it
Progress: https://github.com/letsencrypt/letsencrypt/tree/crash_recovery
