### ISSUE TITLE
Sensible default handling of lineages when the client is re-run.

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#411]
Suppose the following events occur:

1. On Tuesday the user runs <tt>letsencyrpt</tt> on all her domains (perhaps she has 5)
2. On Wednesday she adds a new vhost
3. On Thursday she runs <tt>letsencrypt</tt> on all her names again (now she has 6)

Step 3 above shouldn't create a second certificate lineage which is renewed along with the first; by default it should create a successor to the first.  There can be a command line flag (perhaps <tt>--duplicate</tt>) to actually create a second, if that's what you really want.

Now suppose this case:

1. On Tuesday the user runs <tt>letsencrypt --vhost sni</tt> to make 5 certs
2. On Wednesday she adds a new vhost
3. On Thursday she runs <tt>letsencrypt --vhost sni</tt> again to make 6 certs

The second command should either not make new certs for the 5 existing ones, or should make successors in their lineages, unless <tt>--duplicate</tt> is present.

**Comment by schoen** [comment]
We'll probably need to have a new attribute for lineages, something like "ambitious", "greedy", "automerge_additional_domains", or whatever name would be clearest to a user, making the lineage attempt to merge with new domains when the requested domains in a new invocation are a superset of the ambitious lineage's existing subject names.

**Comment by schoen** [comment]
@pde: are you OK with a special case where a cert is obtained for all currently-available names (marking that cert as "ambitious"), or do you want to parse all existing certs to create a notion of "expansion request"?  ("this request is a strict superset of the names in some existing cert") ... or are you thinking of some other heuristic?

**Comment by pde** [comment]
I think marking certs as "ambitious" or "all names served" if they were obtained for all the available names is a reasonable default.

In the future I can imagine trying to do something fancy with the ncurses UI to make this an actual natural choice:

**[request cert for all names served]**  <---- this is the default
**[ ]** example.com
**[ ]** webmail.example.com
   ~~**[ ]** 1.2.3.4~~
   ~~**[ ]** ec2-1.2.3.4.amazonaws.com~~
<tt>[ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</tt> add new domain
   **[request cert for selected names]**

in the best of all worlds, "all names" would be the thing you peck, we'd avoid accidentally listing the crossed out names, and the "selected names" option would only become available if you've unselected anything.

But feel free to kick all of that to another ticket.

**Comment by schoen** [comment]
I'm also not sure how to detect the second case. :-)  Is it specific to the `--vhost sni` flag or do you expect this behavior whenever a new cert overlaps precisely with an existing cert?  (Regardless of the number of subject names, or only for existing certs that have exactly 1 subject name?)

**Comment by schoen** [comment]
@pde and I discussed this. We might have two attributes that renewal lineages can have:

```
expandme [allnamesserved/allavailablenames]
steparoundme
```

The `expandme` attribute relates to a cert with multiple names that wants to grow to encompass other subject names if a superset of its names is requested later. A way for a cert to get this attribute automatically is to be a cert for all of the available names that existed at a particular point in time.

The `steparoundme` attribute relates to a cert with a single name that wants to continue to exist and not be replaced or renewed when a cert for an identical single name is requested later.

These attributes could be called something different.

**Comment by schoen** [comment]
Pseudocode.

```
if len(requested_names) > 1:
    for cert in existing_certs():
        if is_expandme(cert) and set(requested_names).issubset(set(names(cert))):
            replace_with_new_cert(cert, requested_names)
            break
    else:
        obtain_totally_new_cert(requested_names)
elif len(requested_names) == 1:
    for cert in existing_certs():
        if is_steparoundme(cert) and names(cert) == [requested_names]:
            # This whole bunch of pseudocode is meant to be called from still another loop (with the
            # SNI vhost mechanism), so that we can individually consider the existence of certs for
            # each and every individual name in the larger list.
            break
    else:
        obtain_totally_new_cert(requested_names)
```

**Comment by schoen** [comment]
We're now discussing the idea of certs all being `steparoundme` by default, and requiring `--replace` or `--rekey` to get a new cert with identical coverage to an existing unexpired and unrevoked cert (in the regular client, outside of the renewer).

**Comment by schoen** [comment]
@jdkasten, can you opine on this radical change? I think I'm convinced that it's actually a desirable default!  Summary: all certs by default in the regular client (not renewer) will not to supplemented/replaced by a new cert if you ask for exactly the same names over again, unless you explicitly give `--replace` or `--rekey`.  (Maybe `--replace` is misleadingly named in this case?)

Then if the client is run several times with a request for the same individual cert, you don't get several different certs if you already have one, unless you give the client some specific reason why an additional cert is what you wanted.

**Comment by schoen** [comment]
One note is that we don't currently have any such thing as `sni_mode` or `--vhost sni`.  It's just not implemented at all.

**Comment by pde** [comment]
Want to take #369 ?

**Comment by schoen** [comment]
Heh! I didn't realize there was an issue for it.

**Comment by schoen** [comment]
That's described as a 2.0 feature, where this is a 1.0, so I should at least do this one first.

**Comment by schoen** [comment]
I implemented a dialog and a lineage search that handle this issue (#411) pretty well according to our latest agreed plan. (Still have to finish tests and PR, and the related issues #627, #369, and the `www.` names aren't included in this PR.)

One UI question is how to describe individual existing certs to the user. What do we say about them and what do we call them within the dialog?

Another question is what to do when there are *multiple* existing cert lineages that have name overlap with the new request. Do we mention all of them (forcing the user to select from a menu!?), or the most recent one, or the oldest one, or an arbitrarily-chosen one?

Cc @pde, @jdkasten
