### ISSUE TITLE
A less verbose cipher list?

### ISSUE THREAD

**Issue by aprescott** [letsencrypt/letsencrypt#412]
(I am not a cryptographer!)

As of d6e554b1fd7eafccd6defba392676e5536a077f1, [the nginx SSL config specifies](https://github.com/letsencrypt/lets-encrypt-preview/blob/d6e554b1fd7eafccd6defba392676e5536a077f1/letsencrypt_nginx/options-ssl.conf) the following `ssl_ciphers` value:

> ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA ECDHE-ECDSA-AES128-SHA256 ECDHE-ECDSA-AES256-SHA384 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES128-SHA DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA256 DHE-RSA-AES256-SHA256 EDH-RSA-DES-CBC3-SHA"

I'm wondering if this is actually necessary or if we can do it in a much less verbose way.

I've had decent luck with a configuration like this:

> ssl_ciphers DEFAULT:!aNULL:!eNULL:!ADH:!RC4:!RC2:!DES:+HIGH:+MEDIUM:!LOW:!SSLv2:!EXP:!MD5:!DSS:!PSK;

[Qualys SSL Labs' SSL test](https://www.ssllabs.com/ssltest/) gives a 90/100 rating for the cipher suite that this shorter configuration allows.

I can see another potential benefit over it simply being shorter: it allows future ciphers that aren't blacklisted to automatically work. I think a lot of the frontend web server configuration people put together comes from copy-pasting samples from various blog posts, and this `ssl_ciphers` list is basically just one long magic string.

Given that a lot of people will no doubt use Let's Encrypt as a point of reference for how to do something right, this sort of configuration would potentially give people an `ssl_ciphers` configuration that doesn't have to be revisited to determine what the latest magic string is.

Is this possible? Is there a giant problem with this approach?

**Comment by schoen** [comment]
I'd say we should seek expert advice on the ciphersuite settings to use, not just to get the A+ on the SSL Labs page, but to make sure that our recommendations are well-informed.

The newest recommendation from the "Imperfect Forward Secrecy" authors is

```ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA```

but I don't doubt that this can be improved upon too.

**Comment by schoen** [comment]
Also compare issue #5, which references https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by pde** [comment]
@aprescott Although your form is more concise, there's also something to be said for being able to see exactly what ciphers are enabled.

**Comment by aprescott** [comment]
@schoen definitely. I wasn't suggesting that the SSL Labs test should be the authority on the cipher suite. I mentioned it only to try to show that it's maybe not an awful idea for a practical reason.

**Comment by schoen** [comment]
At @pde's suggestion, I asked some TLS administrators for recommendations and guidance about ciphersuite selection.  I'm going to try to collect what they and others have said at

https://github.com/letsencrypt/lets-encrypt-preview/wiki/Ciphersuite-guidance

**Comment by schoen** [comment]
Superseded by #555. I hope we can get some good, focused expert attention on this topic.
