### ISSUE TITLE
Mac OS X bootstrap

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#413]
```
17:36 < > Hey guys im having trouble installing the demo client from source
17:36 < > I got it to compile finally, but running it I am getting this error
17:36 < > "can't find the executable for the dialog-like "
17:36 < > dialog.ExecutableNotFound
```

http://brewformulas.org/Dialog suggests that `brew install dialog` should install the dependency. Any Mac OS X users volunteering to test it?

**Comment by hathcox** [comment]
Using http://invisible-island.net/dialog/#download and compiling from source allowed me to get past my errors. 

There were some weird things going on with my local Zope, I was forced to do a pip uninstall and rerun the setup.py

**Comment by fuerst** [comment]
Using the Homebrew packet manager I think it would be good to bootstrap like that on OS X:

```
#!/bin/sh

if ! type brew; then
  echo "Abort: You have to install Homebrew first. See http://brew.sh"
  exit
fi

brew update
brew install augeas swig python
pip install virtualenv
```

By installing _python_ you get _pip_ which otherwise is not available at OS X. 

But: Swig 3.0.5 is incompatible with M2Crypt, see https://github.com/swig/swig/issues/344 and https://github.com/swig/swig/issues/344. Using Swig 3.0.4 (`brew install swig304`) doesn't help though. Any hints how to debug this?

**Comment by kuba** [comment]
@fuerst, M2Crypto and swig problems should be fixed in #495. Would you be so kind to test it and send PR with proposed Mac OS X bootstrap changes? Can we please install `virtualenv` instead of `pip` using Brew?

**Comment by iggyvolz** [comment]
Ran into this problem as well, brew install dialog did the trick.

**Comment by kuba** [comment]
Fixed in #797

**Comment by jmhodges** [comment]
Yo, it's really uncool installing as massive a dependency as homebrew just to run letsencrypt. We can just use pkg-config like everybody else does to determine if dialog is installed (or just try to build).

**Comment by jmhodges** [comment]
Sigh, I'm an idiot. Sorry for misunderstanding.
