### ISSUE TITLE
Only save renewal parameters that differ from the defaults

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#421]
Right now every config attribute at the time a cert was obtained gets saved in the renewal parameters section of the renewal config file. This will contain extraneous information that may confuse users and discourage them from editing other parts of the renewal config.

**Comment by kuba** [comment]
One of a bigger reductions would be to simply filter out all config parameters for all plugins `p` s.t. `p != authenticator and p != installer` (e.g. when you `letsencrypt -c apache run`, there is no need to store config values for `nginx` plugin). Note that it is guaranteed that all plugin config values are prefixed by the unique plugin name and that the prefix will not be used in any of the core config options.

**Comment by schoen** [comment]
We should also decide whether to store the differences from default values, as opposed to storing all of the parameters (which is possibly independent of filtering the saved parameters by name).

**Comment by pde** [comment]
Diffing all the options against the defaults, so that most of them go away, seems like the right answer to this.

**Comment by kuba** [comment]
I think it'd be much better to save those parameters that were supplied directly by the user, so that  explicitly requested defaults are persisted and not amendable by updates to `constants.py`. However, there might not be an obvious `argparse`/`ConfigArgParse` API for that.

**Comment by bmw** [comment]
Closing in favor of #2277
