### ISSUE TITLE
Client persistently broken by a single invocation with invalid --work-dir

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#443]
Using the Apache configurator, running the client with

`sudo ~/venv/bin/letsencrypt --work-dir yowl run`

persistently breaks the client, even when subsequently run with an ordinary

`sudo ~/venv/bin/letsencrypt run`

For reasons I haven't been able to deduce, on all subsequent client invocations Apache complains about not being able to find `/etc/letsencrypt/le_dvsni_cert_challenge.conf`.

**Comment by kuba** [comment]
Is it fixed with #440?

**Comment by jdkasten** [comment]
This is either fixed or is actually another issue.  I was able to successfully run the client in different work-dirs as long as I provided the full path.  

Renewal did bark at me trying to create a new lineage for the cert when it already existed?
This is a separate issue though...
```archive directory exists for domain.com```

https://github.com/letsencrypt/letsencrypt/issues/836
