### ISSUE TITLE
Are jws and letsencrypt-renewer meant to be used by end-users?

### ISSUE THREAD

**Issue by fmarier** [letsencrypt/letsencrypt#458]
There are currently three binaries installed system-wide in `/usr/bin`:

- `letsencrypt`
- `jws`
- `letsencrypt-renewer`

The first one is obviously what end-users will be using, but what about the other two? Are they internal binaries used by other tools / cron jobs?

If so, then in Debian, they will need to live somewhere like `/usr/lib/letsencrypt/` or `/usr/share/letsencrypt`. Do we need extra config somewhere to let the tools find these binaries or should I run the right files through `sed` to fix the paths?

**Comment by kuba** [comment]
`jws` from `acme.jose` is only for debugging purposes and can be safely removed in Debian package. 

`letsencrypt-renewer`, however, should be invoked from crontab (installed at package install, possibly through wrapper script, c.f. #424) and manually by a user (should be in `$PATH`). It is not called directly from the code, though.

**Comment by schoen** [comment]
@fmarier, you can help decide how the renewer should be named and invoked, if you have an opinion about it.  We do want to have both automated (from cron) and manual invocations of `letsencrypt-renewer` possible.

**Comment by fmarier** [comment]
Could `jws` be useful to admins trying to debug problems? I don't mind including it in the Debian package if you think it's useful. On the other hand, if it's just for people developing the client, then I may leave it out.

Regarding, `letsencrypt-renewer`, that sounds fine. I'll just need to write a manpage for it if it's going to be shipped with the package. /me adds to TODO list

**Comment by kuba** [comment]
`jws` is even unlikely to be used by devs themselves

**Comment by pde** [comment]
Closing as answered?
