### ISSUE TITLE
Apache and nginx do not respect --dvsni-port

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#479]
Custom `--dvsni-port` works with the standalone authenticator only. Integration testing should also involve Apache and nginx plugins, but [they don't respect this option](https://github.com/letsencrypt/lets-encrypt-preview/blob/73e9956a481cf6504439ce437db1de978c00b046/letsencrypt/cli.py#L263).

**Comment by diracdeltas** [comment]
I don't think this should be closed; doesn't look like apache supports this option yet.

**Comment by kuba** [comment]
That's correct. Apparently GitHub doesn't recognize "partially fixes #479"... Sorry! :) @jdkasten, reopen please

**Comment by bmw** [comment]
Closed in #631.
