### ISSUE TITLE
Remove "-preview" from client and repository name

### ISSUE THREAD

**Issue by bdaehlie** [letsencrypt/letsencrypt#505]
We should remove the "-preview" suffix. This will be the production client provided by Let's Encrypt, and as we approach release the suffix no longer serves a purpose.

Note to any casual readers of this bug - Let's Encrypt will provide a client, but subscribers are not obligated to use the client provided by Let's Encrypt in order to use Let's Encrypt services. Alternative clients are welcome.

**Comment by kuba** [comment]
Checklist:
- [ ] GitHub repository name
- [ ] coveralls.io
- [ ] Travis
- [ ] Quay (cc @jcjones)
- [ ] rgrep source code (references/URLs to above services)

Please consider renaming `lets-encrypt-preview` to just `letsencrypt`. `lets-encrypt` is in fact only used in the repository name... current binary, Python packages (also plugins: `letsencrypt_nginx`, `letsencrypt_apache`, etc.), PyPI packages, Debian packages, all use the form without hyphen.

**Comment by thao343** [comment]
Ok

**Comment by kuba** [comment]
Quay renamed to https://quay.io/repository/letsencrypt/letsencrypt.

@jdkasten, could you rename coveralls.io?

**Comment by kuba** [comment]
This can be closed now, @bdaehlie.
