### ISSUE TITLE
PHP Client

### ISSUE THREAD

**Issue by albancrommer** [letsencrypt/letsencrypt#511]
Hi,

As noted in #16 there is no issue at the moment regarding a general purpose PHP client for the API, so this one is made to fill the void, collect feedback and more.  

We will need a PHP client for the AlternC web panel [1] and if nothing is under work -as it seems now- we might produce one. 

Open to suggestions and comments, along with general insights from people who are building / built clients with other languages.

Here are a few guidelines we'd follow : 

* Composer compatible 
* A namespaced library ie \ACME\ApiClient  
* PDO storage 

[1] https://github.com/AlternC/AlternC

**Comment by splitice** [comment]
+1

**Comment by raeesiqbal** [comment]
+1

**Comment by bmw** [comment]
A PHP client for the ACME protocol is another project. Closing.
