### ISSUE TITLE
nginx plugin destroys config

### ISSUE THREAD

**Issue by PatrickHeppler** [letsencrypt/letsencrypt#518]
I have a config file called webp.conf in /etc/nginx/conf.d/ which works great.
After running letsencrypt -d example.org run the webp.conf is broken because it's missing a closing }
https://pastebin.mozilla.org/8837365
Line 18 gets removed.

**Comment by PatrickHeppler** [comment]
Seems the parse has an issue with the indentation.

**Comment by quinox** [comment]
Minimum testcase:
```
if ($http_accept ~* "webp") { set $webp "true"; }
```

A non-extensive test shows it can be fixed by a small change:
```patch
diff --git a/letsencrypt-nginx/letsencrypt_nginx/nginxparser.py b/letsencrypt-nginx/letsencrypt_nginx/nginxparser.py
index 749c009..2df26fe 100644
--- a/letsencrypt-nginx/letsencrypt_nginx/nginxparser.py
+++ b/letsencrypt-nginx/letsencrypt_nginx/nginxparser.py
@@ -37,7 +37,7 @@ class RawNginxParser(object):
         + Group(ZeroOrMore(Group(assignment) | block))
         + right_bracket)
 
-    script = OneOrMore(Group(assignment) | block) + stringEnd
+    script = OneOrMore(Group(assignment) ^ block) + stringEnd
```

Reversing the order of `block` and `Group(assignment)` while preserving `|` also fixes it.

After https://github.com/letsencrypt/letsencrypt/pull/602 lands I'll do a full test
