### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/letsencrypt#537]
needs some instructions for common OSes

i.e. OSX and Debian

```
brew install letsencrypt
```

```
sudo apt-get install letsencrypt
# or
sudo easy_install letsencrypt
```

I don't know what these instructions are, but I'll try to figure them out real quick and post back

**Comment by quantumpacket** [comment]
Is letsencrypt currently or will be available through these package managers?

I thought the instructions were here for each OS https://letsencrypt.readthedocs.org/en/latest/using.html#ubuntu

**Comment by coolaj86** [comment]
Here's what I got so far

```bash
git clone git@github.com:letsencrypt/lets-encrypt-preview.git
pushd ./lets-encrypt-preview/
python setup.py build

# OSX and Debian (Ubuntu)
brew install swig || sudo apt-get install swig
sudo python setup.py install
```

Now I need to repeat on a server so I can test...

**Comment by coolaj86** [comment]
Haha! It's got a tiny little link right at the top, which I totally missed.... I know how to fix that.

**Comment by coolaj86** [comment]
https://github.com/letsencrypt/lets-encrypt-preview/issues/537
