### ISSUE TITLE
need option for serving from alternate port

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/letsencrypt#542]
Scenario:

I've got my webserver up and running already and I've got it sending anything matching `.well-known/acme-challenge` upstream to `localhost:4443`.

I want to run the python tool and have it update the certs it `/etc/letsencrypt` (for which my web server is already configured to read from) and then send `SIGHUP` to my webserver. This way there is no downtime and I can renew my certificates.

Currently there's no option to change from port 443 and so it would require taking down my webserver in order to run `letsencrypt`.

**Comment by kuba** [comment]
Note that currently such option makes sense only for `ManualAuthenticator`, which is the only authenticator that supports `simpleHttp`. Manual mode requires you to copy and paste the command, so for the time being you can just change the port manually, before executing. I can prepare a PR for `--simple-http-port`, but it will have to wait until #485 unblocks CLI.

`StandaloneAuthenticator` doesn't do `simpleHttp`, so the option would not affect it at this stage... For the record, it does support different port for `dvsni` challenge:
```
$ letsencrypt --help | grep dvsni -A 2
                   [--dvsni-port DVSNI_PORT] [--configurator CONFIGURATOR]
                   [-a AUTHENTICATOR] [-i INSTALLER] [-d DOMAIN] [-s SERVER]
                   [-k AUTHKEY] [-m EMAIL] [-B N] [-r]
--
  --dvsni-port DVSNI_PORT
                        Port number to perform DVSNI challenge. Boulder in
                        testing mode defaults to 5001. (default: 443)
```

**Comment by coolaj86** [comment]
I think StandAlone mode is what I'm most concerned with because I want to be able to have this registration happen automatically (meaning programmatically via a system exec from node and go).

Will an alternate `--dvsni-port` work in production mode? I just looked at the spec and it sounds like `443` is required, which I can workaround as long as I can tell the process to listen locally on something like `localhost:8443` and have the load balancer listen on 443 with 8443 as an upstream.

Ultimately I'd like a node or a go client. I believe the node client isn't too far from good working order, but since this I know the python client works today it allows me to start prototyping today. :-) Then I can always move to a node or go client later.

**Comment by kuba** [comment]
`--dvsni-port 8443` will work as long as CA can download (SNI) "dvsni challenge certificate" [1] at `:443`. If you can redirect all `*.acme.invalid` domains to `localhost:8443` AND "forward" the SSL certificate, then you should be fine... I just don't think any typical server software will allow you to do that. Please let me know if I'm wrong.

[1] See the end of https://github.com/letsencrypt/acme-spec/blob/master/draft-barnes-acme.md#domain-validation-with-server-name-indication section

**Comment by coolaj86** [comment]
Ah, forwarding the SSL... I keep forgetting that. I was trying to figure that out with `haproxy`, but I don't have an adequate solution yet.

Will a production server only allow port 443? It would be really useful to allow other ports for the sake of not having to take down a live site to fetch a new cert.

**Comment by schoen** [comment]
This is a longstanding debate -- see #341,  letsencrypt/acme-spec#33. I don't think it's clearly resolved yet.

**Comment by narcisgarcia** [comment]
This FOSS utility can help you to automate direct and indirect installs of ACME certificates to hosts that have TCP/443 port busy, or haven't TCP/443 port forwarded to them:

https://www.actiu.net/sesele/
