### ISSUE TITLE
Hide tracebacks in the client [by default?]

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#544]
Currently the client tends to error out with raw Python tracebacks.  We should definitely hide / provide human explanations instead of those.  Possibly we should have a way for developers to get the traceback, either via a logfile or a <tt>--debug</tt> flag or both.

@bradmw is going to work on this, I believe.

**Comment by kuba** [comment]
FYI I have a branch with logfile support ready to be submitted, but I'm waiting until #485 unblocks involved `cli.py`.

**Comment by bradmw** [comment]
That's great, @kuba! If you already implemented logfile support, this should be a pretty simple issue to resolve.

**Comment by kuba** [comment]
FYI logging branch with logfile support sent as #553

**Comment by schoen** [comment]
Addressed by #562 (and thanks for #553).
