### ISSUE TITLE
Get rid of --dvsni-port option?

### ISSUE THREAD

**Issue by diracdeltas** [letsencrypt/letsencrypt#578]
The current revision of the ACME spec only allows dvsni on 443; however, Nginx and Standalone (https://github.com/letsencrypt/letsencrypt/issues/479) allow user-specified ports for dvsni validation.

Apparently this is a contentious issue (https://github.com/letsencrypt/acme-spec/issues/33). I would prefer to restrict dvsni to port 443 for launch unless there is a compelling reason not to.

**Comment by kuba** [comment]
That's necessary for testing, and is listed under `letsencrypt --help testing` with appropriate notice: `The following flags are meant for testing purposes only! Do NOT change them, unless you really know what you're doing!` It is might also be helpful for setups with reverse proxy (c.f. #542)

**Comment by diracdeltas** [comment]
Thanks for clarifying. I guess this is not an issue as long as Boulder in production doesn't accept DVSNI requests on non-443.

**Comment by coolaj86** [comment]
Also, I can setup haproxy to listen on 443 and tcp-forward SNI requests for '*.acme.invalid' to a temporary server so that I don't have to take my main webserver down to add, renew, update certs.

**Comment by kuba** [comment]
@coolaj86: were you actually able to do that? mind sharing setup instructions? :) (btw you can reach me at #letsencrypt@Freenode, nick Kuba)

**Comment by coolaj86** [comment]
One day I'll set up irssi again and pretend like I can use IRC.... but here are some links in the meantime:

* https://coolaj86.com/articles/lets-encrypt-with-haproxy/
* https://coolaj86.com/articles/lets-encrypt-on-raspberry-pi/
* https://coolaj86.com/articles/adventures-in-haproxy-tcp-tls-https-ssh-openvpn/

:-)

**Comment by kuba** [comment]
That's cool, @coolaj86 ! Allowed myself to add it to https://github.com/letsencrypt/letsencrypt/wiki/Links.
