### ISSUE TITLE
Unattended upgrades of client software

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#580]
Research whether we can use an unattended upgrades mechanism to improve the up-to-dateness of the client software.

Cc @jsha.

**Comment by PatrickHeppler** [comment]
I have installed letsencrypt on centos 7 to /opt/letsencrypt
I'm using a little bash script to update:
    cd /opt/letsencrypt
    git pull
    SWIG_FEATURES="-includeall -D__`uname -m`__-I/usr/include/openssl" ./venv/bin/pip install --upgrade -r requirements.txt .

**Comment by jsha** [comment]
What we're thinking with this is to figure out if third-party repos (PPAs in Ubuntu parlance) can mark their packages as eligible for the unattended-upgrades package to auto-update them.

**Comment by jdkasten** [comment]
Note: we just got rid of M2Crypto and swig with @kuba's refactoring:  #591

**Comment by pde** [comment]
This was implemented with #980.
