### ISSUE TITLE
Recommendation for install path?

### ISSUE THREAD

**Issue by PatrickHeppler** [letsencrypt/letsencrypt#584]
Maybe you should recommend a default installation path.
docs/using.rst only says
``` Bash    
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt
```
But where should this be run? 
IMHO the git repo should be placed in /usr/local/src/letsencrypt
``` Bash
cd /usr/local/src/   
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt
```
and then install to /usr/local/bin
```Bash
virtualenv --no-site-packages -p python2 /usr/local/
cd /usr/local/bin/
./pip install -r /usr/local/src/letsencrypt/requirements.txt .
```
Using a default path would it make easier to provide an unattended upgrade tool
[#580](https://github.com/letsencrypt/letsencrypt/issues/580)

As said, that's just my 2 cents :stuck_out_tongue_winking_eye:

**Comment by kuba** [comment]
Under no condition should `virtualenv` setup be mixed with operating system binaries, paths, or Python modules (http://letsencrypt.readthedocs.org/en/latest/using.html#installation, yellow warning box). For the time being `/opt/letsencrypt/` sounds reasonable if you want to install `letsencrypt` for all users. This, however, requires root. And requires you to adjust your `PATH`.

Nonetheless, `virtualenv` was meant to be the developer preview setup, and we are currently looking into alternatives for the launch. For example #334, as well as proper OS packages.

**Comment by PatrickHeppler** [comment]
Proper packages for yum resp. apt-get would be fantastic!

**Comment by jsha** [comment]
Yep, the production release will not require checking out the source repo. Our recommend install will probably be via yum or apt, with a .tar.gz you can install if you don't use either of those. Thanks for the input!
