### ISSUE TITLE
May I use letsencrypt now? why I can't use it in nginx ....

### ISSUE THREAD

**Issue by XMap** [letsencrypt/letsencrypt#590]
Are this config is OK ?
```
 ssl_certificate            0000_csr-letsencrypt.pem;
 ssl_certificate_key    0000_key-letsencrypt.pem;


It show me that 

```
Jul 08 11:50:32 iZ23ncu98fyZ nginx[2138]: nginx: [emerg] PEM_read_bio_X509_AUX("0000_csr-letsencrypt.pem") failed (SSL: error:0906D066:PEM routines:PEM_read_bio:bad end line)

**Comment by PatrickHeppler** [comment]
Path should be
```
ssl_certificate /etc/letsencrypt/live/example.com/cert.pem;
ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
```
This are Symlinks to the current Cert and Private Key and get updated on renewal, so you don't have to change it yourself.

**Comment by jsha** [comment]
I'm afraid Let's Encrypt is not yet ready for production use. Please check in again after September 14.

Thanks,
Jacob
