### ISSUE TITLE
Update DVSNI challenge to match new spec

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#597]
This is the client side of https://github.com/letsencrypt/boulder/issues/434. New spec is at https://github.com/letsencrypt/acme-spec/blob/master/draft-barnes-acme.md#domain-validation-with-server-name-indication-dvsni

Assigned to @kuba.

**Comment by kuba** [comment]
This is pretty much done in https://github.com/kuba/letsencrypt/tree/dvsni-v03. I will need some help to fix `letsencrypt-nginx` (@diracdeltas?) and `letsencrypt-apache` (@jdkasten?), but I don't think it's worth to mess with this given very likely conflicts (especially @jdkasten's work) and the fact that Boulder hasn't had much progress as far as I can see...
