### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'apache_init'

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#603]
https://github.com/letsencrypt/letsencrypt/blob/2f2137ef6beca2e2f5bfd3ab1d44cc55510f7b9f/letsencrypt-apache/letsencrypt_apache/configurator.py#L938, it should use: `conf("init-script")`

@jdkasten

**Comment by kuba** [comment]
Forgot to credit @bynarie for reporting

**Comment by jdkasten** [comment]
Thank you! I am rewrit ing enable mod to be not use Debian specific scripts. I will fix this along the way.

**Comment by jdkasten** [comment]
This was fixed in #631
