### ISSUE TITLE
nginx plugin should insert fullchain.pem instead of cert.pem

### ISSUE THREAD

**Issue by PatrickHeppler** [letsencrypt/letsencrypt#610]
letsencrypt nginx plugin should insert fullchain.pem into vhost conf instead of cert.pem.
I'll bet cert.pem will raise an chain issue on ssllabs.com server test

**Comment by schoen** [comment]
Indeed, fullchain.pem is present in the hope that it will be useful for nginx.

**Comment by schoen** [comment]
Cc @diracdeltas
