### ISSUE TITLE
Challenge Support

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#62]
Right now the only challenges being handled are DVSNI and RecoveryToken challenges.

All of the challenges are listed here.  https://letsencrypt.github.io/acme-spec/#identifier-validation-challenges

If anyone is interested in implementing one of these challenges, you should extend or create an Authenticator.  Right now there are only two Authenticators... Apache.  (apache.configurator.py) and the Client Authenticator (client_authenticator.py)

https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/interfaces.py#L7

See https://github.com/letsencrypt/lets-encrypt-preview/wiki/Documentation#authenticatorsinstallers for more info.

DV Authenticators, like Apache, perform challenges like SimpleHttps and DVSNI. Client Authenticator's perform challenges like RecoveryToken, RecoveryContact, PoP...ect.  (All of this is listed in CONFIG.py)  The reason for the separation is that the Client Challenges should not have to be reimplemented by modules like nginx... stand-alone (null configurator) ect.

Currently, the demo server is only giving one challenge per domain.  However, I will help out and modify the server accordingly if anyone is interested.

**Comment by ThomasWaldmann** [comment]
see #200.

**Comment by bmw** [comment]
Closing this as the info here is outdated.
