### ISSUE TITLE
bootstrap/debian.sh should create files in /var, /etc

### ISSUE THREAD

**Issue by GitHubGeek** [letsencrypt/letsencrypt#625]
Tried out letsencrypt the first time. Unless I missed something obvious in the [install doc](https://letsencrypt.readthedocs.org/en/latest/using.html#quick-start), the following essential dirs and files were not there at first-run (`./venv/bin/letsencrypt auth`)

```
/etc/letsencrypt/
/etc/letsencrypt/cli.ini
/var/log/letsencrypt/
/var/lib/letsencrypt/
```

Bootstrap script should've created them with the specific permissions.

Also, the documentation should specify when `./venv/bin/letsencrypt` should be run with `sudo`, and when not.

**Comment by kuba** [comment]
Thanks for the feedback!

Those directories are created automatically in the first run of the client, but `sudo` has to be used. `/etc/letsencrypt/cli.ini` is optional, and it's mainly for distro package maintainers to change default directories to match distro requirements.  It will also be up to distro package maintainers to mark those directories with particular `confdir`-like flags. We are considering to change client default to be current working directory: `./run/conf`, `./run/work`, `./run/logs`, which would remove initial `sudo` requirement, but this entails some file permission issues (`sudo le` would create those dirs with root privileges, and thus it would be inaccessible by the normal user account).

Indeed, documentation has to be updated. Please bear with us for a bit or send appropriate PR if you can! :)

**Comment by GitHubGeek** [comment]
Thanks for the detailed reply! Totally agreed that the distro specific stuff should be done by the package maintainers. Wish I know more about .deb packaging to be able to help :)

On the matter of file permissions, I believe that there should be a clear distinction of command(s) that require superuser, and commands that don't. Ideally there'd be only a single command, with sub-commands, that handle of all privileged operations. I think it's the right direction to go, to have the logs and temp. files written in non-system locations. Perhaps a centalised location such as `~/.config/letsencrypt/(logs|work)/` is more user friendly?

Thank you for the great work. _Let's Encrypt_ is a game changer.

**Comment by Crazee** [comment]
Ran into the same permission problems.  But running  (./venv/bin/letsencrypt auth) as root created /etc/letsencrypt but left it empty.  The script died with

IOError: [Errno 2] No such file or directory: '/opt/letsencrypt/venv/local/lib/python2.7/site-packages/letsencrypt_apache/options-ssl-apache.conf'

though that .conf file could be found at 

./letsencrypt-apache/letsencrypt_apache/options-ssl-apache.conf

**Comment by frennkie** [comment]
same here

**Comment by kuba** [comment]
Thanks for the report, but this is off topic - please open new issue next time. Fixed in https://github.com/letsencrypt/letsencrypt/pull/634.

**Comment by bmw** [comment]
I believe these issued have been resolved. If not, please yell at me and I'll reopen.
