### ISSUE TITLE
Challenge Updates to v04 of spec and Boulder Reintegration

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#641]
Since Boulder challenge spec changes landed all at once.  This issue will also track when the client is Boulder compliant again.

This issue incorporates #597 and #576?

PR is being worked on at https://github.com/kuba/letsencrypt/tree/update-challenges

**Comment by jcjones** [comment]
Please let me know when you're ready for me to update the staging environment.
