### ISSUE TITLE
Attack on domain verification with BGP hijacking

### ISSUE THREAD

**Issue by rugk** [letsencrypt/letsencrypt#655]
As far as I know you validate the domain only by accessing the site via HTTP. [As explained in a talk on  BlackHat] (https://www.blackhat.com/us-15/briefings.html#breaking-https-with-bgp-hijacking) it's theoretically possible to get certificate for a domain you don't control with bad BGP routing.

Can Let's Encrypt somehow mitigate this attack?
I mean as of what [I've read] (https://letsencrypt.org/howitworks/technology/) on the website the nonce is at first signed, so this is secure as I think.
But what's the verification with a DNS record, which is - according to the site - also offered as a verification possibility? As far as DNSSEC is not used this is not secure.

CC: @ximaera

**Comment by rugk** [comment]
Asked in Let's Encrypt Community: https://community.letsencrypt.org/t/attack-on-domain-verification-with-bgp-hijacking/169

**Comment by jsha** [comment]
Closing in preference for the community discussion.

**Comment by jsha** [comment]
Closing in preference for the community discussion.
