### ISSUE TITLE
Adding a folder to store certificate signing requests

### ISSUE THREAD

**Issue by sfahl** [letsencrypt/letsencrypt#658]
In addition to /etc/letsencrypt/certs and /etc/letsencrypt/keys have a third folder /etc/letsencrypt/csrs to store certificate signing requests instead of putting them into /etc/letsencrypt/certs.

**Comment by bmw** [comment]
CSRs are now stored in `/etc/letsencrypt/csr` while certs are stored in `/etc/letsencrypt/archive/example.com`.
