### ISSUE TITLE
email address issues

### ISSUE THREAD

**Issue by yaseminacar** [letsencrypt/letsencrypt#659]
1.) There is no explanation what the email is for. You should say something like "Please enter a valid email address for recovery purposes and notifications. We will not add it to your certificate nor will we share it. You can also leave this field empty, but that makes recovery harder."

2. ) Right now when an invalid email address is given, the error message says 'an unexpected error occured, please check the logfile'. This should be changed to something along the lines of "You gave an invalid email address. Please enter a valid email address for recovery purposes and notifications, or leave the field empty to give no email address".

**Comment by bmw** [comment]
Related to #414.
