### ISSUE TITLE
"Standalone" needs to be default authenticator in place of "manual" and both options need explanations

### ISSUE THREAD

**Issue by yaseminacar** [letsencrypt/letsencrypt#664]
1.)  To enable users to just press enter for the easiest option, 'standard' needs to be default (pre-selected) instead of manual.
2.) The options right now are "Standard(standard)" and "Manual(manual)". Either the brackets need to go or a meaningful explanation needs to be added (the latter would be better).

**Comment by jdkasten** [comment]
*typo standard -> Standalone

**Comment by bmw** [comment]
I agree we need to a better job of differentiating `manual` from `standalone`.

**Comment by pde** [comment]
Giving this to @swartzcr.

**Comment by bmw** [comment]
Closed in #1079.
