### ISSUE TITLE
letsencrypt --apache doesn't work

### ISSUE THREAD

**Issue by sfahl** [letsencrypt/letsencrypt#666]
If users want to use letsencrypt with Apache, letsencrypt --apache doesn't although the help command output proposes that procedure. Instead an error like 'letsencrypt: error: ambiguous option: --apache could match --apache-server-root, --apache-enmod, --apache-le-vhost-ext, --apache-ctl, --apache-init-script' is presented. To fix this, make the --apache options prefix free.

**Comment by jdkasten** [comment]
The default help commands are not currently linked to any functionality.
