### ISSUE TITLE
Feature request: automatically add the secured domain to HTTPS Everywhere

### ISSUE THREAD

**Issue by ximaera** [letsencrypt/letsencrypt#670]
Let's Encrypt has an option to set all the pages on a Web server to redirect to HTTPS from HTTP. When this option is used, it makes sense to automatically add corresponding rules to HTTPS Everywhere in order to help securing the site from an attempt to drop HTTPS at the first redirect.

Integration of that sort between two important and valuable EFF concepts tends to help in promoting both products and securing the Internet communications, doesn't it? :-)

**Comment by jdkasten** [comment]
Maybe as part of an enhancement?

**Comment by jmhodges** [comment]
Nah. The deal with HTTPS Everywhere is that it's for when users want to be able to access a site of HTTPS but don't control the domain. For site owners, the equivalent is adding the HSTS header to their responses. They can also go into the [HSTS preload list](https://hstspreload.appspot.com/) if the owners decide their site should match the criteria required to be in it. 

I'm not sure if letsencrypt client already sets the HSTS header, but maybe it would be nice to do so. I'm sure that's been discussed previously.

The HTTPS Everywhere folks have had to turn down plenty requests from site owners to be added and say the same thing to those site owners as I've said above, btw.

**Comment by jdkasten** [comment]
Yeah, I agree.  The only usecase I saw was the "wikipedia argument" (their old policy).

They wanted to allow users who cared about https to use it. (mostly through HTTPSEverywhere?), but they didn't want to make it the default.

**Comment by jdkasten** [comment]
It would needlessly clutter up HTTPS Everywhere regexes though.
