### ISSUE TITLE
Command line arguments for plugins are broken

### ISSUE THREAD

**Issue by e00E** [letsencrypt/letsencrypt#689]
It seems the command line arguments for plugins created in ```add_parser_arguments(cls, add):``` cant be extracted with ```self.conf("argument_name")```. I suspect something with the plugin namespace prefix is going wrong.

My code is here https://github.com/e00E/lets-encrypt-icecast/blob/master/icecast.py .
In line 129 I add an argument via ```add("configuration_file")```
and I try to use it in line 150 like so
```
self.config_file = self.conf("configuration_file")
if self.config_file is not None and not os.path.isfile(self.config_file):
    raise PluginError('User supplied icecast configuration file does not exist.')
```

When running ```letsencrypt install``` it crashes with the last log message
```
Traceback (most recent call last):
  File "./letsencrypt/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/home/e/icecast/letsencrypt/letsencrypt/cli.py", line 778, in main
    return args.func(args, config, plugins)
  File "/home/e/icecast/letsencrypt/letsencrypt/cli.py", line 232, in install
    installer = display_ops.pick_installer(config, args.installer, plugins)
  File "/home/e/icecast/letsencrypt/letsencrypt/display/ops.py", line 105, in pick_installer
    config, default, plugins, question, (interfaces.IInstaller,))
  File "/home/e/icecast/letsencrypt/letsencrypt/display/ops.py", line 72, in pick_plugin
    verified.prepare()
  File "/home/e/icecast/letsencrypt/letsencrypt/plugins/disco.py", line 197, in prepare
    return [plugin_ep.prepare() for plugin_ep in self._plugins.itervalues()]
  File "/home/e/icecast/letsencrypt/letsencrypt/plugins/disco.py", line 98, in prepare
    self._initialized.prepare()
  File "/home/e/icecast/letsencrypt/icecast.py", line 151, in prepare
    self.config_file = self.conf("configuration_file")
  File "/home/e/icecast/letsencrypt/letsencrypt/plugins/common.py", line 60, in conf
    return getattr(self.config, self.dest(var))
  File "/home/e/icecast/letsencrypt/letsencrypt/configuration.py", line 39, in __getattr__
    return getattr(self.namespace, name)
AttributeError: 'Namespace' object has no attribute 'letsencrypt-icecast:icecast_installer_configuration_file'
```
I think if an argument is not specified on the command line, the argument should default to None and not throw an AttributeError. But even if I manually have default=None or set default to anything I still get this error. Curiously the attribute error is about ```letsencrypt-icecast:icecast_installer_configuration_file``` while when running ```letsencrypt --help all``` the corresponding command line argument is listed as ``` --letsencrypt-icecast:icecast_installer-configuration_file``` (note the the dash instead of underscore near the end) which leads me to believe the conversion of the argument name in the plugin to the global name is going wrong.

**Comment by jdkasten** [comment]
Hmm... I am looking into this now.  It has been awhile since I have looked at this code.

My guess is that the problem is here.
https://github.com/letsencrypt/letsencrypt/blob/74b677248d082c35489ed96a806e50bd648627e1/letsencrypt/plugins/common.py#L56

**Comment by kuba** [comment]
Problem is in https://github.com/letsencrypt/letsencrypt/blob/74b677248d082c35489ed96a806e50bd648627e1/letsencrypt/plugins/common.py#L23. It should read: `return name.replace("-", "_") + "_"`.

**Comment by jdkasten** [comment]
Did #696 fix your problem @e00E?

**Comment by e00E** [comment]
The arguments correctly use their defaults in the plugin now, however I cannot specify them over the command line, always getting told "unrecognized argument".
Not sure if you want an extra issue for this.

```letsencrypt --help all``` tells me  ```--letsencrypt-icecast:icecast_installer-configuration_file``` is a command line argument but when I try to specify it like ```--letsencrypt-icecast:icecast_installer_configuration_file my_config_file``` I always get ```letsencrypt: error: unrecognized arguments: --letsencrypt-icecast:icecast_installer_configuration_file```.
Something strange again which might indicate that some part of the argument parsing in general is broken is that other arguments need to be in a strange order not specified in the help text to work.
For example
```letsencrypt -t -i letsencrypt-icecast:icecast_installer install --cert-path /etc/letsencrypt/certs/ --key-path /etc/letsencrypt/keys/``` is the only order of arguments that work. Putting the "install" at the start gives ```letsencrypt: error: unrecognized arguments: -t -i letsencrypt-icecast:icecast_installer```
and putting it at the end gives ```letsencrypt: error: argument SUBCOMMAND: invalid choice: '/etc/letsencrypt/certs/' (choose from 'run', 'auth', 'install', 'revoke', 'rollback', 'config_changes', 'plugins')```
The help text just says ```letsencrypt [SUBCOMMAND] [options] [domains]``` which is not what happens.

**Comment by kuba** [comment]
Actually it's more like `letsencrypt [global options, including plugins] SUBCOMMAND [subcommand options]`. Yes, `--help` is broken, c.f. #692.

**Comment by e00E** [comment]
I got it to work with your help just now. The only issue is that the help text still says there would be a dash `-` after the letsencrypt-icecast:icecast_installer when in reality an underscore `_` is expected.

**Comment by e00E** [comment]
With that help it is working as expected now, thanks.
