### ISSUE TITLE
"Unable to rollback 1 checkpoints, only 0 exist"

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#690]
If this means, "let's encrypt hasn't changed your configs so there's nothing to roll back", then that's what it should say :)

**Comment by jdkasten** [comment]
This is produced as a generic warning when the reverter can't rollback as far as the user has requested.

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/reverter.py#L78

Fixing with a special if statement when there are not any configuration checkpoints in #693

As a general statement about the state of the project... UI/UX is in a pretty deplorable state.  There are many many rough edges that need to be fixed that are in the queue.
