### ISSUE TITLE
Apache plugin doesn't auto-enable modssl?

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#691]
If it isn't enabled to begin with

**Comment by jdkasten** [comment]
Thanks, this is an integration bug that was introduced in #682.

It solves the challenges correctly (by enabling mod_ssl) upon rollback it disables mod_ssl, but the parser doesn't recognize that mod_ssl is no longer disabled.  (module info wasn't being updated after rollback)

I am addressing this now.
1.  Appropriately enabling mod_ssl so it won't be "cleaned up" with challenges if "run" is called.  (This just creates extra work.)
2.  Re initializing parsed modules on after cleanup

**Comment by jdkasten** [comment]
Fixed in #693
