### ISSUE TITLE
letsencrypt-compatibility-test: missing travis/tox setup and docs

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#695]
Similar to #692, but wider in scope. Missing:
-  `pip install ... -e letsencrypt-compatibility-test` in `docs/contributing.rst`
- `tox.cover.sh` entry
- `[testenv]` entry in `tox.ini`

**Comment by kuba** [comment]
Ups, there are no unittests for `letsencrypt-compatibility-test`. Is that intended, @bmw?

**Comment by bmw** [comment]
Yes @kuba, I purposefully didn't take the time to write unittests for `letsencrypt-compatibility-test` as it should really only be used internally for testing.

**Comment by kuba** [comment]
Thanks. I guess we also don't want to upload it to PyPI or do any distro packaging.

**Comment by bmw** [comment]
Right. I think doing so would be unnecessary.
