### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#70]
We need unit tests for just about everything in this project.  I know this isn't quite as exciting of a task... and that is why I listed it last, but it would be a major help.

It is imperative that we thoroughly test modules so that we can identify fine-grained errors.  As @kuba pointed out, it will also help you become familiar with the codebase and how it works.  It can enable you to contribute meaningfully without having to read the code in its entirety.

(I am currently working on writing an integration testing suite that I hope can test 100s of example servers quickly, but this only detect end problems and won't provide information about the minor errors that may occur during the course of execution)

**Comment by ThomasWaldmann** [comment]
See pull request #158 (maybe just try it if you don't know pytest yet).

I switched to it a long time ago in one of my projects and suddenly writing tests was not a pain any more and that led to more and better tests getting writting. : )

**Comment by ThomasWaldmann** [comment]
BTW, there is also pytest-pep8 which could be easily added later to improve pep8 compatibility of your src.

It could be adjusted so it doesn't trigger failures at the beginning (by excluding some unwanted warnings) and could get stricter after the issues have been fixed, so they don't get re-introduced again.

Tell me what you think about this (after looking at pytest in general).

**Comment by jdkasten** [comment]
The scope of unittesting has changed substantially since the introduction of this issue.  We can always use more unittests to cover existing code, but we are now at >= 97% code coverage for all of letsencrypt packages.
