### ISSUE TITLE
Make manpages for installed binaries

### ISSUE THREAD

**Issue by hlieberman** [letsencrypt/letsencrypt#700]
Currently, the client produces three binaries - /usr/bin/letsencrypt, /usr/bin/letsencrypt-renewer, and /usr/bin/jws.  However, the sphinx build of documentation only includes a single manpage - letsencrypt.1.

Please create manpages for the other installed binaries, if they are needed.  If they're not needed, let me know, and I will prune them from the Debian packaging.

**Comment by kuba** [comment]
Thanks. Working on patch...
