### ISSUE TITLE
Allow for enrolling certs for renewal without installer integration?

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#716]
Right now my understanding is that we never create a RenewableCert lineage with a renewal config and associated files within `/etc/letsencrypt` unless we installed the cert into a server with configuration changes via an installer plugin.

Some discussions on the forum seem to suggest that this may be too restrictive because people might want renewable lineages to exist and be available for use with their own server configurations (like servers that we don't officially support via installers). This makes sense and I think @jdkasten and I had considered this possibility before.

Is this right? How should it work? How should users choose this behavior as opposed to just saving the PEM files in their working directory?

**Comment by schoen** [comment]
OK, we're talking about putting it in the renewal config file in a separate section, like this:

```
[certstatusdata]
revoked_versions = 3 4 8 11
```

Then any part of the renewer or cert manager that found out that a version was revoked could mention that fact by adding to this list. We would probably want to try to have a comment at the beginning like

```
# Automatically generated; do not edit
[certstatusdata]
revoked_versions = 3 4 8 11
```

**Comment by jdkasten** [comment]
Auth certificates are automatically enrolled for renewal as it currently stands.  Unless there is some other trickery happening underneath the covers in renewal?

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L331

Results of running letsencrypt auth (standalone)
IMPORTANT NOTES:
 - Automatic renewal and deployment has been enabled for your
   certificate. These settings can be configured in the directories
   under /etc/letsencrypt/configs.

**Comment by bmw** [comment]
Yes, you can have a renewal configuration file without an installer, but there is no cron job or anything to actually perform that renewal. If this situation changes in the future, it should be explained to the user.
