### ISSUE TITLE
Quality control on Mac OS X

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#724]
We have a number of issues open about various aspects of OS X support, which are probably symptomatic of the fact that none of the core team have prioritised it at the moment.  Opening this ticket to in search of a volunteer to take responsibility for quality control, dependency management and testing on OS X.

**Comment by BKreisel** [comment]
I would be interested in helping on this front. Does anyone from the core contribution team have any insight or direction as to what needs to be done on this front?

**Comment by jmhodges** [comment]
There are a few OS X tickets you can search for but, specifically, if you can get the integration tests to run on OS X, that would be wonderful. I'm a boulder dev and currently cannot get them to work. (And requiring root to run the tests means having a bunch of root-only binaries end up in my PATH.)

**Comment by bmw** [comment]
Thanks to the great work by @BKreisel, I believe this can be closed. All other OS X tickets have been resolved.
