### ISSUE TITLE
When the staging server has wiped accounts, tell the user what to do

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#727]
Currently, if a developer is testing the client, and the staging server has wiped old test accounts, the user's client will error out with a mysterious <tt>Error: malformed :: The request message was malformed :: Unable to read/verify body</tt> message.

Once boulder has started [sending a more sensible error](https://github.com/letsencrypt/boulder/issues/595), the client should respond by telling the user (1) you'd better be in dev mode; (2) please <tt>rm -rf /etc/letsencrypt/accounts</tt>

**Comment by pde** [comment]
Assigning this to Jacob until the boulder issue is fixed, can be handed to someone else after that.

**Comment by jdkasten** [comment]
Adding that the importance of this decreases once Let's Encrypt goes live.

(It should never happen from Let's Encrypt servers)

**Comment by kuba** [comment]
https://github.com/letsencrypt/letsencrypt/issues/589

**Comment by bmw** [comment]
Closing this in favor of the more general #589.
