### ISSUE TITLE
Manual mode instructions fail in Nginx default configs that forbid serving dotfiles

### ISSUE THREAD

**Issue by centminmod** [letsencrypt/letsencrypt#730]
In the client's Manual Authenticator mode the the directory the client is looking for the ACME challenge is prefixed with a dot

i.e. `.well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys`

    Make sure your web server displays the following content at
    https://newdomain2.com/.well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys before continuing:
    
However, certain Nginx configurations best practices are to block file and directory access to dot prefixed folders and files

    location ~ /\.          { access_log off; log_not_found off; deny all; }

So Manual mode instructions for `./venv/bin/letsencrypt -d newdomain2.com auth`

    Make sure your web server displays the following content at
    https://newdomain2.com/.well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys before continuing:
    
    ?*>|l0t6u$
    
               Content-Type header MUST be set to application/jose+json.
    
    If you don't have HTTP server configured, you can run the following
    command on the target server (as root):
    
    mkdir -p /tmp/letsencrypt/public_html/.well-known/acme-challenge
    cd /tmp/letsencrypt/public_html
    echo -n '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "rqrPQZTTBwGyjTi4ob6vwXLo3kGhrRhNx-lkGnOFFAhlMWDE7TtuAttmp45xxKsfZUTyWSH_HZBml53YOmTwXmLMHjVvZp7yXXgH7p3e1Do4yf31M83Lm1ymCSGQe4OQFXu0raVpXA6iguDRt1wPpD9uPG20vuvjgvoDz9ohrigCbVZLuuJiBm4gPqARr4FD7LaufBabvoDDiATtiwfLtsLNVwjYY79W7ZWxqU7mZibT1--Uo2-fsRh2pMxYT4SWXBya4943W5t8HzP-CNVZTsLrUMG9laHPtZv_6A67NfrC-3RpSUTOK9_fbmTFzpYQFAnKWE4YxvwC2xE5GqO4kQ"}}, "payload": "eyJ0bHMiOiB0cnVlLCAidG9rZW4iOiAiRVRfc3k2eTFLdUl5MWRrLXZuOEtmR3lXX1QyME1IUTJkZGNMRmdNa255cyIsICJ0eXBlIjogInNpbXBsZUh0dHAifQ", "signature": "KrCfJMYiJAPCzeFutsIRGw5t4X5B3ZpFeqPPGV9E44eKIYqJGK5NBAeyTvBRZgrhnj0ifQeFJ8gbs-vWX-4HgVr4XgmAkLdN1_ZN6pCkARwDc4XZXC3AcIoCNpGIVy4f9qZRbkOgaHbfJzsT7fJcqyTQs2gNeXiuKi4miJgwQANpkoHCAFT-cggkqDRB_vRdw5glUFlJArHY90_tV8VX5OV4SNlsQGPqVcwUME1KI0vka6dD1KTYDSxUrQmo1eFlS1SFKRU2lmxGB_BU7lJ_ymmzgjrBDSFLRtOTYFKoizHX03FmpOhm3_h-_0JuStsN879bUq2NSzGLt94G1IDuvQ"}' > .well-known/acme-challenge/ET_sy6y1KuIy1dk    -vn8KfGyW_T20MHQ2ddcLFgMknys
    # run only once per server:
    openssl req -new -newkey rsa:4096 -subj "/" -days 1 -nodes -x509 -keyout ../key.pem -out ../cert.pem
    $(command -v python2 || command -v python2.7 || command -v python2.6) -c \
    "import BaseHTTPServer, SimpleHTTPServer, ssl; \
    SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map = {'': 'application/jose+json'}; \
    s = BaseHTTPServer.HTTPServer(('', 443), SimpleHTTPServer.SimpleHTTPRequestHandler); \
    s.socket = ssl.wrap_socket(s.socket, keyfile='../key.pem', certfile='../cert.pem'); \
    s.serve_forever()" 
    Press ENTER to continue

If I change them for my custom Nginx paths to

    cd /home/nginx/domains/newdomain2.com/public
    mkdir -p .well-known/acme-challenge
    echo -n '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "rqrPQZTTBwGyjTi4ob6vwXLo3kGhrRhNx-lkGnOFFAhlMWDE7TtuAttmp45xxKsfZUTyWSH_HZBml53YOmTwXmLMHjVvZp7yXXgH7p3e1Do4yf31M83Lm1ymCSGQe4OQFXu0raVpXA6iguDRt1wPpD9uPG20vuvjgvoDz9ohrigCbVZLuuJiBm4gPqARr4FD7LaufBabvoDDiATtiwfLtsLNVwjYY79W7ZWxqU7mZibT1--Uo2-fsRh2pMxYT4SWXBya4943W5t8HzP-CNVZTsLrUMG9laHPtZv_6A67NfrC-3RpSUTOK9_fbmTFzpYQFAnKWE4YxvwC2xE5GqO4kQ"}}, "payload": "eyJ0bHMiOiB0cnVlLCAidG9rZW4iOiAiRVRfc3k2eTFLdUl5MWRrLXZuOEtmR3lXX1QyME1IUTJkZGNMRmdNa255cyIsICJ0eXBlIjogInNpbXBsZUh0dHAifQ", "signature": "KrCfJMYiJAPCzeFutsIRGw5t4X5B3ZpFeqPPGV9E44eKIYqJGK5NBAeyTvBRZgrhnj0ifQeFJ8gbs-vWX-4HgVr4XgmAkLdN1_ZN6pCkARwDc4XZXC3AcIoCNpGIVy4f9qZRbkOgaHbfJzsT7fJcqyTQs2gNeXiuKi4miJgwQANpkoHCAFT-cggkqDRB_vRdw5glUFlJArHY90_tV8VX5OV4SNlsQGPqVcwUME1KI0vka6dD1KTYDSxUrQmo1eFlS1SFKRU2lmxGB_BU7lJ_ymmzgjrBDSFLRtOTYFKoizHX03FmpOhm3_h-_0JuStsN879bUq2NSzGLt94G1IDuvQ"}' > .well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys

then try accessing `.well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys`, I will get 403 Forbidden / access denied due to my Nginx configuration blocking dot prefixed files/folders

    curl -Ik https://newdomain2.com/.well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys
    HTTP/1.1 403 Forbidden
    Date: Fri, 28 Aug 2015 22:06:57 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 162
    Connection: keep-alive
    Server: nginx centminmod    

So maybe you need to remove that dot prefix for `/.well-known` or rename it to something else as there are plenty of Nginx configurations out there that block those dot prefixed files and folders and may cause problems for manual authenticator mode setups.

removing dot prefix can access fine (newdomain2.com has a self-signed SSL cert with HPKP already setup on port 443)

    curl -Ik https://newdomain2.com/well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys 
    HTTP/1.1 200 OK
    Date: Fri, 28 Aug 2015 22:18:30 GMT
    Content-Type: application/octet-stream
    Content-Length: 911
    Last-Modified: Fri, 28 Aug 2015 22:06:39 GMT
    Connection: keep-alive
    ETag: "55e0db6f-38f"
    Server: nginx centminmod
    Alternate-Protocol: 443:npn-spdy/3
    Public-Key-Pins: pin-sha256="gIm5JM8lPc+uiz995GgIR/9lmo8dkDZ4X3VQJAUvN0s="; pin-sha256="ALeqbO2k1tzkLG3Z0DaQW2QgC8MG9tQZD2sNHVW08GM="; max-age=604800
    Accept-Ranges: bytes

**Comment by schoen** [comment]
The dot is required as part of the standards:

https://tools.ietf.org/html/rfc5785

But the instructions probably need to explain this issue to folks if it's in conflict with their default web server configuration.

**Comment by schoen** [comment]
I was going to mention @diracdeltas because of the Nginx connection, but this is technically a problem with manual mode so perhaps it should be examined by @kuba. Or if anyone else has a suggestion about what the text should say to be clear to Nginx users without confusing other folks...

**Comment by centminmod** [comment]
maybe need to add a note to documentation for Nginx users to specifically allow that directory path

      location ~ /.well-known {  }

which would bypass the dot file/directory blocks

    curl -Ik https://newdomain2.com/.well-known/acme-challenge/ET_sy6y1KuIy1dk-vn8KfGyW_T20MHQ2ddcLFgMknys
    HTTP/1.1 200 OK
    Date: Fri, 28 Aug 2015 22:50:18 GMT
    Content-Type: application/octet-stream
    Content-Length: 911
    Last-Modified: Fri, 28 Aug 2015 22:06:39 GMT
    Connection: keep-alive
    ETag: "55e0db6f-38f"
    Server: nginx centminmod
    Alternate-Protocol: 443:npn-spdy/3
    Public-Key-Pins: pin-sha256="gIm5JM8lPc+uiz995GgIR/9lmo8dkDZ4X3VQJAUvN0s="; pin-sha256="ALeqbO2k1tzkLG3Z0DaQW2QgC8MG9tQZD2sNHVW08GM="; max-age=604800
    Accept-Ranges: bytes

**Comment by centminmod** [comment]
actually this is more appropriate to remove duplicate if Nginx has headers more nginx module

    location ~ /.well-known {
          location ~ /.well-known/acme-challenge/(.*) {
                  more_set_headers    "Content-Type: application/jose+json";
          }
    }   

then

    curl -Ik https://newdomain2.com/.well-known/acme-challenge/yd8hgcNI4AgtvMG4z7kF4_YGTpmfMLHbvxsajCb0br8
    HTTP/1.1 200 OK
    Date: Sat, 29 Aug 2015 01:12:15 GMT
    Content-Type: application/jose+json
    Content-Length: 911
    Last-Modified: Sat, 29 Aug 2015 01:12:03 GMT
    Connection: keep-alive
    ETag: "55e106e3-38f"
    Server: nginx centminmod
    Alternate-Protocol: 443:npn-spdy/3
    Accept-Ranges: bytes

**Comment by kuba** [comment]
Dot prefix for `.well-known` is mandated by the ACME protocol, so you may want to report this issue to https://github.com/letsencrypt/acme-spec/issues or https://github.com/ietf-wg-acme/acme/issues. There is not much our client can do. "Make sure your web server displays the following content at" message is as generic (and valid) as it can be. Since Manual mode is meant for more advanced users (maybe we should put a warning in the plugin list?), I'm sure they can handle setting up of the webserver correctly, as you did.

**Comment by centminmod** [comment]
thanks @kuba 

done https://github.com/letsencrypt/acme-spec/issues/221

**Comment by jdkasten** [comment]
.well-known being blocked is on purpose :)

It is supposed to require special privilege in order to avoid simple file access (php vulns) from proving ownership of the domain.

If only all web servers were appropriately configured.

**Comment by bmw** [comment]
@kuba has added plans to clarify this to his personal TODO list.

**Comment by gsf** [comment]
To help others out who may be in this spot, the following block in nginx worked for me:

```
location /.well-known/acme-challenge/-no9mQxAD7oFRjdf8GRi4ic3Rzlt5V6dK_jkSZ2Qa_g {
    default_type application/jose+json;
    return 200 '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "rBhSjBKD5C-qcvnl6jn8iz2pGWNw4AUoUBVxYTYqOpxUoB6CribE2ETNJWjr7kCyaB-ToJwuBGMyPugn7Q0Fa-qLFwyIy3UWrzebIg5EP1_8plj1V6bLm9n4H-wrVXKAubkTsfJ5pibekXlq2BMtFGX7UKZ6nxaNI02cjxpl2YwerFvd6unj1m8-9x8oJpPDox4cdy_lQfM8dhxxpWgTqudN2zd_XvFKV59lA382QzrhEUhkjjL-f4X0jclOhOyp2zLDcieNTo350wt2PeZxN1KQTcjgw3sCrxPooE0qJv9KwpekUyI15P1nhLNMkYuzblcGC92Wv27x6Kgy4i_ehw"}}, "payload": "eyJ0bHMiOiBmYWxzZSwgInRva2VuIjogIi1ubzltUXhBRDdvRlJqZGY4R1JpNGljM0F6bHQ1VjZkS19qa1NaMlFhX2ciLCAidHlwZSI6ICJzaW1wbJVIdHRwIn0", "signature": "B0u9O7BYYsm70X6ug_5bRyGWTnvn8VFws4otTAdzRriNe3Uyod16Wcu-kpt8uuuincf4KOHD5k3xHhYCQ6EIYNq4ui8S6_7brAB4mCKsDBVw4iPRicKjYORG4Q2BRB6YoCkxMixfhUmMtqYbhYfYGpO5xBYBiC-MS-vBQ2gm6DbjRs5NhHUNrY-BMzyEAV_JDC_OyM0OfiMXALZYJc3cMTNqH2J_jUNGRVMM4J3DJxVQqQAQq0o-FxR3cy1CU2a1AdUHEUoTC4GTh6aECbnjtQgYqGjz8jSVOHbrPI_nWDgZMWLYK6ZNyYpi2eArMKocVbvb3FSNaoUTMB7ngxp_XA"}'
}
```

**Comment by bmw** [comment]
@kuba, still on your very full TODO list?

**Comment by kuba** [comment]
It's been evicted. Mind opening an a tracking issue?

**Comment by aug-riedinger** [comment]
After some struggle, here's my working config:

```
server {
  listen                80;
  server_name           example.com;
  root /vagrant/www/current/public;
  
  # Necessary for Let's Encrypt Domain Name ownership validation
  location /.well-known/acme-challenge/ {
    try_files $uri /dev/null =404;
  }
  location / {
    return 301 https://$host$request_uri;
  }
}
```

**Comment by Flamestyle** [comment]
Hello! Same problem. A lot of time is wasted. There is a correct decision?
