### ISSUE TITLE
Report certificate creation explicitly

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#736]
Users are confused about whether the client actually succeeded in issuing the certificate, see https://github.com/letsencrypt/letsencrypt/issues/734#issuecomment-135960602.

As suggested by @centminmod we could additionally report:
```
- your SSL certificates have been created at /etc/letsencrypt/live/le1.http2ssl.xyz
```

@bmw, would you like to take it?

**Comment by jdkasten** [comment]
Duplicate/Related #665

**Comment by kuba** [comment]
Yes, this is a dupe
