### ISSUE TITLE
Copy nginx config file

### ISSUE THREAD

**Issue by dazorni** [letsencrypt/letsencrypt#738]
I started letsencrypt on my server and had an error message caused of wrong configuration in my nginx file. I changed this configuration and restarted letsencrpyt. I got the same error again an my nginx config file changed back to the old version of this file!

**Comment by jdkasten** [comment]
Sounds like crash-recovery could also help fix this problem.  https://github.com/letsencrypt/letsencrypt/tree/crash_recovery

**Comment by jdkasten** [comment]
It sounds like nginx is saving and making changes in the init or prepare() function and then later figures out that the configuration is broken?

This should be hunted down and made sure that the reverter.recovery_routine() is run on any error in these functions.

**Comment by bmw** [comment]
Is this still a problem?

**Comment by dazorni** [comment]
I didn't check this again, you can close this issue and i will check it in the next time and send you my feedback :+1: Thanks!

**Comment by Archcry** [comment]
Still an issue.

**Comment by okias** [comment]
Also, it just happend to me on Gentoo... latest git from repository
