### ISSUE TITLE
Allow letsencrypt client to pass the web root path on cmd for creation of SimplyHTTP/ACME challenge file

### ISSUE THREAD

**Issue by centminmod** [letsencrypt/letsencrypt#742]
Related to https://community.letsencrypt.org/t/manual-authenticator-way-to-automate-the-acme-challenge-file-creation/583

Passing the webroot via the command line it would help for those sites that have non-standard web roots i.e. frameworks like Laravel and node.js web apps would likely have their /path/to/projectname/public as their web root. WHM/Cpanel, Directadmin, Webmin etc all would have their own web root paths. 

If you can pass this as a variable in Letsencrypt client, it will probably be easier for respective control panels and distros to come up with their own integration methods ?

**Comment by jdkasten** [comment]
Is the existing --server-root not sufficient?

**Comment by centminmod** [comment]
I don't see that option only  --nginx-server-root which which for me would be `/usr/local/nginx` but my vhost web root are in format `/home/nginx/domains/domain.com/public`

     ./venv/bin/letsencrypt --help nginx
    usage: 
      letsencrypt [SUBCOMMAND] [options] [domains]
    
    The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
    default, it will attempt to use a webserver both for obtaining and installing
    the cert.  
    
    positional arguments:
      SUBCOMMAND
        run                 Obtain a certificate and install.
        auth                Authenticate & obtain cert, but do not install it.
        install             Install a previously obtained cert in a server.
        revoke              Revoke a previously obtained certificate.
        rollback            Rollback server configuration changes made during
                            install.
        config_changes      Show changes made to server config during installation
        plugins             List server software plugins.
    
    optional arguments:
      -h, --help            show this help message and exit
      -c CONFIG_FILE, --config CONFIG_FILE
                            config file path (default: None)
    
    nginx:
      Nginx Web Server
    
      --nginx-server-root NGINX_SERVER_ROOT
                            Nginx server root directory. (default: /etc/nginx)
      --nginx-ctl NGINX_CTL
                            Path to the 'nginx' binary, used for 'configtest' and
                            retrieving nginx version number. (default: nginx)

**Comment by kuba** [comment]
It doesn't matter where your webroot is. Certificates and keys are never copied to your `public_html`! Let's Encrypt doesn't care what you have in your `public_html`. Certificates and keys are copied (or symlinked) to the configuration directory, which you should specify using `--nginx-server-root`.

**Comment by kuba** [comment]
Ah, you want to specify directory where SimplyHTTP challenge response files should be written (aka, automatic execution of manual plugin, without executing Python's builtin webserver)...

Please update the title of this ticket to make this more clear.

**Comment by centminmod** [comment]
ok changed the title.. yup @kuba for creation of the well-known uris for verification :)

right now I have to manually do it via

    cd /home/nginx/domains/le1.http2ssl.xyz/public
    mkdir -p .well-known/acme-challenge
    echo -n '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "vnWsLw

where `/home/nginx/domains/le1.http2ssl.xyz/public` is my web root path

**Comment by kuba** [comment]
Mind, you can always stop your current web server and use fully automated `standalone` plugin...

**Comment by centminmod** [comment]
Yeah unfortunately that would be a problem for other non-443 port sites running on the server. The aim is to integrate Letsencrypt into my LEMP stack's Nginx vhost auto generation routine which currently auto creates the nginx vhost for http and https (self-signed ssl) so hoping it can do that fully from command line for invoking letsencrypt client as I already have the fully running Nginx vhost for https/443 running and setup.

**Comment by kuba** [comment]
I quickly created plugin that should suit your needs, @centminmod. It's not ready to be sent as PR yet, but you can still check it out... Just `git clone -b simplefs https://github.com/kuba/letsencrypt` instead of `git clone https://github.com/letsencrypt/letsencrypt` and follow normal instructions from http://letsencrypt.readthedocs.org/en/latest/using.html. Then run `letsencrypt -a simplefs --simplefs-root /your/public_html auth` and voila!

**Comment by centminmod** [comment]
sweet @kuba thanks so much.. will doing this override and wipe the existing /etc/letsencrypt files/config and obtained ssl certs ?

**Comment by kuba** [comment]
No, it will not wipe the config files.

I'm a bit concerned why do you ask, though. Currently issued certificates have no much value... (https://github.com/letsencrypt/letsencrypt#disclaimer)

**Comment by centminmod** [comment]
Cheers @kuba the question is thinking forward for when you do go live :)  Pretty sure some folks like myself would run into such a situation if living on bleeding edge :)

**Comment by centminmod** [comment]
Okay tried it and it works nicely with command

    ./venv/bin/letsencrypt -a simplefs --simplefs-root /home/nginx/domains/le3.http2ssl.xyz/public -d le4.http2ssl.xyz auth

but if i true to skip the prompts and just text I with

    ./venv/bin/letsencrypt -a simplefs --simplefs-root /home/nginx/domains/le3.http2ssl.xyz/public --agree-eula true --agree-tos true -d le4.http2ssl.xyz auth

I get

    /root/tools/letsencrypt/venv/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
      DeprecationWarning
    usage: 
      letsencrypt [SUBCOMMAND] [options] [domains]
    
    The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
    default, it will attempt to use a webserver both for obtaining and installing
    the cert.  
    letsencrypt: error: argument SUBCOMMAND: invalid choice: 'true' (choose from 'rollback', 'auth', 'run', 'install', 'plugins', 'revoke', 'config_changes')

**Comment by centminmod** [comment]
this works though

    ./venv/bin/letsencrypt -a simplefs --simplefs-root /home/nginx/domains/le4.http2ssl.xyz/public --text  -d le4.http2ssl.xyz auth    

output

    ./venv/bin/letsencrypt -a simplefs --simplefs-root /home/nginx/domains/le4.http2ssl.xyz/public --text  -d le4.http2ssl.xyz auth                                  
    /root/tools/letsencrypt/venv/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
      DeprecationWarning
    
    -------------------------------------------------------------------------------
    This is a PREVIEW RELEASE of a client application for the Let's Encrypt
    certificate authority and other services using the ACME protocol. The Let's
    Encrypt certificate authority is NOT YET ISSUING CERTIFICATES TO THE PUBLIC.
    
    Until publicly-trusted certificates can be issued by Let's Encrypt, this
    software CANNOT OBTAIN A PUBLICLY-TRUSTED CERTIFICATE FOR YOUR WEB SERVER.  You
    should only use this program if you are a developer interested in experimenting
    with the ACME protocol or in helping to improve this software.  If you want to
    configure your web site with HTTPS in the meantime, please obtain a certificate
    from a different authority.
    
    For updates on the status of Let's Encrypt, please visit the Let's Encrypt home
    page at https://letsencrypt.org/.
    -------------------------------------------------------------------------------
    (A)gree/(C)ancel: A
    
    IMPORTANT NOTES:
     - Automatic renewal and deployment has been enabled for your
       certificate. These settings can be configured in the directories
       under /etc/letsencrypt/configs.

is there a way to pass the Agree on command line ? 

thanks

**Comment by centminmod** [comment]
okay figured it out !

    ./venv/bin/letsencrypt -a simplefs --simplefs-root /home/nginx/domains/le4.http2ssl.xyz/public --text --agree-eula -d le4.http2ssl.xyz auth 

perfect @kuba your work taken care of automating non-standard Ubuntu Apache/Nginx setups provided they already have the ssl vhost and web root for their respective domains setup prior !

**Comment by kuba** [comment]
This discussion is off-topic. If you have further problems please don't
piggy back on the same issue, but open a new one or come to our IRC channel
for further support.

**Comment by centminmod** [comment]
@kuba oh sorry thought feedback on your plugin by a end user would be on topic :)

cheers
