### ISSUE TITLE
Suggestion for documentation format

### ISSUE THREAD

**Issue by centminmod** [letsencrypt/letsencrypt#745]
For documentation down the road for Letsencrypt, would love something that lays out the client usage like https://sslmate.com/help/automation and https://sslmate.com/help/getting_started where it's formatted in a step by step basis structure which is end user task oriented.

You could break it down by

* native Ubuntu/Debian Apache 2.2/2.4 distro package install
* native Ubuntu/Debian Nginx distro package install
* CentOS/RHEL Apache distro package install
* CentOS/RHEL Nginx distro package install
* Other Apache source/custom installs
* Other Nginx source/custom installs

This is as opposed to just listing the Letsencrypt client options etc.

**Comment by jdkasten** [comment]
Thanks, @centminmod!  Yes, we have quite a bit of work to do still getting everything packaged and ready for end users.

**Comment by bmw** [comment]
Thanks for the suggestion @centminmod. We agree the documentation can be improved and we'll keep this in mind while doing so.
