### ISSUE TITLE
Ensure that "run" is actually just the concatenation of "auth" and "install" commands

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#771]
With #758 landing they are briefly diverging, but we don't actually want that.  James will fix that promptly.

**Comment by jdkasten** [comment]
There are quite a few problems with run vs. (auth and install).  It really just became a major issue with #758.

The initial problem with #758 was that auth now does not respect the duplicate_certificates code for renewal.  That involves refactoring... pulling out the code into separate functions and inserting it into auth.

After taking a closer look... they have diverged quite a bit as all developers have had different goals with respect to functionality and no one took the time to actually encompass one another's APIs.

I am making a concerted effort to actually investigate and wrangle back in the roughly duplicated code.

**Comment by jdkasten** [comment]
Progress can be found in https://github.com/letsencrypt/letsencrypt/tree/fix_771.

It isn't a panacea.

Status: I haven't tested it out yet.
