### ISSUE TITLE
Can I retrieve only certificates?

### ISSUE THREAD

**Issue by dvapelnik** [letsencrypt/letsencrypt#783]
My web-server have a specific location of configuration files. Can I only retrieve certificates with "Lets Encrypt" for manually install after this?

**Comment by jdkasten** [comment]
Yes, just run the ```letsencrypt auth``` command.  There are a few options in there currently, and a few more robust options coming shortly.

**Comment by pde** [comment]
Yes.  But also the apache/nginx plugins should ultimately be able to work with your webserver's specific locations for things, too.
