### ISSUE TITLE
Don't hide real permissions errors from the user

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#785]
Since we landed #778 yesterday, we now completely hide permissions errors.

```
ubuntu@ip-172-31-3-78:~/letsencrypt$ venv/bin/letsencrypt
An unexpected error occurred. Please see the logfile 'letsencrypt.log' for more details.
ubuntu@ip-172-31-3-78:~/letsencrypt$ cat ./letsencrypt.log
Traceback (most recent call last):
  File "venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/home/ubuntu/letsencrypt/venv/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 882, in main
    _setup_logging(args)
  File "/home/ubuntu/letsencrypt/venv/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 801, in _setup_logging
    log_file_name, maxBytes=2 ** 20, backupCount=10)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
```

**Comment by pde** [comment]
Kuba suggests catching the error and re-subclassing it from Error.Error.  Another solution, which I might prefer, is to handle `IOError` or at least the Permission denied subcase specifically in @bmw's error handling code.  Or going further in that direction, to essentially include the full final error message for the user, while continuing to hide the full traceback.

**Comment by kuba** [comment]
There are just too many upstream libraries errors we might encounter in `cli.py` error handling code... And you cannot easily distinguish all possible `IOErrors` (including those from upstream) to provide good enough feedback for the user.

No subclassing. Just `raise error.Error("Couldn't save $path. Do you have sudo?")`, or better yet:

```python
try:
  open(...)
except IOError as error:
  logger.debug(error)
  raise errors.PermissionError("Couldn't save $path. Dow you have sudo?", error)
```

**Comment by kuba** [comment]
Ah, it's worth noting that any message passed to `error.Error` (and subclasses) is automatically displayed thanks to bmw :)

**Comment by jdkasten** [comment]
Related #669
