### ISSUE TITLE
Unable to get CLI support?

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#787]
I am not sure if the ```letsencrypt -h``` help hasn't been updated or if I am encountering some self-inflicted error.

Seemed failings...
I can't seem to get ```venv/bin/letsencrypt -h [topic]``` where topic is all, ect... to work

I don't believe ```--standalone, --apache, or --nginx``` are hooked up.

The traditional ```--authenticator standalone``` does work though.

Can you check this over @pde to make sure you get the expected output?  (I thought ```-h all``` at least worked at one point)

**Comment by jdkasten** [comment]
Also the top line   letsencrypt [SUBCOMMAND] [options] [domains] is incorrect currently.

The CLI doesn't accept domains as the final option and is instead currently input like...
```letsencrypt -d mydomain.com [SUBCOMMAND]```
for that matter, in general all letsencrypt options are placed before the subcommand, specific subcommand options are placed after.
```letsencrypt --installer apache rollback --checkpoints 5```

**Comment by pde** [comment]
Yes, the help topics I implemented have been broken for a while.  Git bisecting to try to determine the cause, I get:

```
83185e55538cd5c87fa7e63fefec8c6348b235c5 is the first bad commit
commit 83185e55538cd5c87fa7e63fefec8c6348b235c5
Author: Jakub Warmuz <jakub@warmuz.org>
Date:   Sun Sep 6 09:20:11 2015 +0000

    pep8 letsencrypt

:040000 040000 f0bf965acd140455fbd18b37f8137b0134e47017 8156546f488cd4165fd49121c9194ac2f73942f1 M	letsencrypt
```

**Comment by pde** [comment]
PEP-8ification assumed that if (var == True) was equivalent to if (var).  That was wrong

Looks like this also broke things:

```
44d7ac2dce2691116da0ba4fa88d37d7fde89134 is the first bad commit
commit 44d7ac2dce2691116da0ba4fa88d37d7fde89134
Author: Peter Eckersley <pde@eff.org>
Date:   Fri Aug 28 17:31:57 2015 -0700

    Plumbing for tweaked args
    
     - to make "run" the default, we need to add it to the args
     - which means we need to pass that back up to the actual argparse call
    
    (This is ugly... probably HelpfulArgParser needs to actuall inherit from
    argparse...)

:040000 040000 2c6b4008a890d96290a0560f60db8e945b6909a2 7179309ab230f2d85c30d503460555e319d6dea8 M	letsencrypt
```

**Comment by bmw** [comment]
I'm unable to get help for any of the subcommands, for instance:
```
./venv/bin/letsencrypt --help auth

  letsencrypt [SUBCOMMAND] [options] [domains]

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert.  Major SUBCOMMANDS are:

  (default) everything Obtain & install a cert in your current webserver
  auth                 Authenticate & obtain cert, but do not install it
  install              Install a previously obtained cert in a server
  revoke               Revoke a previously obtained certificate
  rollback             Rollback server configuration changes made during install
  config_changes       Show changes made to server config during installation

Choice of server for authentication/installation:

  --apache          Use the Apache plugin for authentication & installation
  --nginx           Use the Nginx plugin for authentication & installation
  --standalone      Run a standalone HTTPS server (for authentication only)
  OR:
  --authenticator standalone --installer nginx

More detailed help:

  -h, --help [topic]    print this message, or detailed help on a topic;
                        the available topics are:

   all, apache, automation, nginx, paths, security, testing, or any of the
   subcommands
```

**Comment by kuba** [comment]
Confirmed, `letsencrypt --help subcommand` doesn't work at 928fa7bae07e3d5f35557bec2d2d334c2612a16b.

I think it's really the time when we create tests for the CLI... I'd like to propose that all further CLI PRs have full coverage. Especially all reported bugs should have a corresponding detector test.

**Comment by kuba** [comment]
In fact, did it ever work? #577

**Comment by pde** [comment]
It didn't, but `letsencrypt --help apache`, `letsencrypt --help paths`, etc, worked.  Working on the subcommands now.
