### ISSUE TITLE
Offer a well-defined non-interactive mode.

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#804]
For various purposes (such as scripting or our own integration tests!) people will sometimes want to run the client in non-interactive mode.  In such situations, it is a mistake to block on user input of any sort.  We should offer a clear cli flag that causes the client to stop asking the user questions.  

In non-interactive mode it may be acceptable to error out if some instruction is missing, though if at all possible that should be deterministic and happen immediately when the client is run, not partway through execution.

**Comment by pde** [comment]
Integration tests breaking over in #777 is an example of this problem: h

**Comment by pde** [comment]
A good solution might be to use an IDisplay implementation that prevents attempts at interaction, so that we don't really need to chase down every case.  Though arguably we should add a "noninteractive_default" parameter [to the IDisplay interface](https://letsencrypt.readthedocs.org/en/latest/api/interfaces.html#letsencrypt.interfaces.IDisplay).  If it is really impossible to specify one, the default could be "Error out and fail".

**Comment by centminmod** [comment]
is that the same equivalent as

    --text --agree-eula

or a simplier command cli flag ?

**Comment by pde** [comment]
@centminmod no, the idea here is to guarantee that no questions will ever be asked at runtime at all, making the command suitable for use in scripts or cron jobs.

**Comment by pde** [comment]
It's mostly possible to get this right now, but the user may need to supply a lot of hard-to-discover flags, and in some cases it's not possible at all at present (eg, vhost selection) #1482

**Comment by PolakAllen** [comment]
The documentation for this is very hard to find.

Had to RTFM a few times, in a particular topic to find it.

For future people coming off of google, use `-q --quiet` or `--non-interactive`.

I wasn't able to find the documentation for `--non-interactive`, but `--quiet` implies `--non-interactive`

Also, the documentation doesn't really explain what the defaults are (you need to find the defaults for each variable).

`--account` or (`--email` and `--agree-tos`) is required

**Comment by RayFoss** [comment]
To make it truly interactive, I had to have certbot-auto get the parameters in a very specific order, otherwise it would fail down the line.
the order that worked for me was 

`certbot-auto --non-interactive --agree-tos --email mien@mail.de --apache --domains das.boot.de`

**Comment by bmw** [comment]
@RayFoss you're saying the order you provide the parameters matters? What happens if you provide the same flags in a different order?

**Comment by RayFoss** [comment]
It will complain about not having the domain and plugin defined. Which it
should be able to deduce, and does if you pass parameters in correct order.
I tried this in a many vanilla centos7 instances while I was testing an
auto deploy script.
