### ISSUE TITLE
Apache plugin's cleanup() doesn't remove SSL vhosts created during auth

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#808]
If you run `letsencrypt auth` for an Apache virtual host that doesn't have SSL enabled, the Apache plugin creates a new vhost `*-le-ssl.conf`. After performing the challenges, the plugin's `cleanup` function is called but it doesn't remove the created vhosts. Instead, the user has to run `letsencrypt` again and the files will be deleted up when `recovery_routine` is called. These temporary files should be removed during the `cleanup` function.

**Comment by jdkasten** [comment]
Note: The files aren't actually included in the final configuration.  The files only exist in sites-available.

**Comment by pde** [comment]
Reportedly this is hairy because plugin has to handle two cases (`run` and `certonly`) and do different checkpointing in each case.  So removing `Good Volunteer Task`.

**Comment by pde** [comment]
@bmw @SwartzCr closing this, right?

**Comment by bmw** [comment]
Yes. This was correctly closed.
