### ISSUE TITLE
Add Content-Security-Policy

### ISSUE THREAD

**Issue by J0WI** [letsencrypt/letsencrypt#812]
We should really support CSP, because they are great:
- we can avoid mixed content
- we can automatically upgrade insecure requests
- we could avoid click-jacking
- webmasters could use even more restrictive rules

**Comment by pde** [comment]
We will want to ship with an <tt>upgrade-insecure-requests</tt> CSP header by default.  This is currently blocked on implementing http-header enhancements in the apache and nginx plugins.

**Comment by J0WI** [comment]
This just fixed the second point...
