### ISSUE TITLE
Non-sudo user graceful failure

### ISSUE THREAD

**Issue by BKreisel** [letsencrypt/letsencrypt#815]
Running letsencrypt as a privileged user (on OSX at least) results in a stacktrace referencing inability to write to the /var/log/letsencrypt directory. 

Would it not be better to merely inform the user that the binary must be run as root rather than allowing the program to crash? I'm willing to write the code for it, just wanted to gauge the reception first.

    (venv)➜  letsencrypt git:(master) letsencrypt
    Traceback (most recent call last):
      File "/Users/brandon/Projects/letsencrypt/venv/bin/letsencrypt", line 9, in <module>
        load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
      File "/Users/brandon/Projects/letsencrypt/letsencrypt/cli.py", line 885, in main
        _setup_logging(args)
      File "/Users/brandon/Projects/letsencrypt/letsencrypt/cli.py", line 801, in _setup_logging
         log_file_name, maxBytes=2 ** 20, backupCount=10)
      File     "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line   117, in __init__
        BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 64, in __init__
        logging.FileHandler.__init__(self, filename, mode, encoding, delay)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line   903, in __init__
        StreamHandler.__init__(self, self._open())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line  926, in _open
        stream = open(self.baseFilename, self.mode) 
    IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'

**Comment by bmw** [comment]
Hi @BKreisel. Thanks for the bug report.

Is your version of Let's Encrypt up to date with current master? In the last week or so, code was added which should make the output slightly more sane. In most cases, when the client cannot access the log directory (or the files within it), you should see something like:

```
An unexpected error occurred.
OSError: [Errno 13] Permission denied: '/var/log/letsencrypt'
Please see the logfile 'letsencrypt.log' for more details.
```

The one exception to this is if we cannot create the logfile `letsencrypt.log` in your working directory. In this case, you would see the full traceback.

With that said, the program could definitely use some work on Mac OS X (see #724). If the problem persists and you're willing to write the code, we'd certainly appreciate the PR.

**Comment by BKreisel** [comment]
@bmw, I was a few commits behind, I did a little bit of sleuthing and it appears that the `letsencrypt.log` in the working directory had been generated by the root user. Running the cli again as non-priviledged it was unable to write to that file and thus resulted in the exception to the rule you listed above. I guess I have a penchant for finding some of these corner cases :grin:
