### ISSUE TITLE
'certs' directory in /etc/letsencrypt is confusing

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#817]
I just generated a cert, and in looking for it I found that /etc/letsencrypt/certs exists, but contains only CSRs, not certs. Any chance we can rename this directory?

**Comment by jdkasten** [comment]
Thanks!  That had been baked in there for a long time... pre-renewal.  #823 is basically a grep through the code changing cert_dir to csr_dir and CERT_DIR to CSR_DIR
