### ISSUE TITLE
Extended help doesn't work

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#819]
Steps to reproduce:

`letsencrypt --help all`
`letsencrypt --help auth`

Expected result:

Help text beyond the default help is emitted.

Actual result:

Default help text is emitted.

**Comment by jdkasten** [comment]
related https://github.com/letsencrypt/letsencrypt/issues/787

**Comment by pde** [comment]
This should be fixed now.

**Comment by pde** [comment]
Correction: it's fixed for `--help all` and for `--help $ARGGROUP`, but not for the subcommands.
