### ISSUE TITLE
Apache support is marked "alpha," but Nginx is not

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#821]
Steps to reproduce:

`letsencrypt`

Follow prompts, when selecting which web server to use, Apache has "- alpha" after it, but Nginx does not. Nginx support is far less mature than Apache. I've heard about from two other people (and experienced myself) a failure to complete an issuance flow. I think we should probably remove the alpha tag from Apache and add it to Nginx. Or perhaps temporarily disable Nginx support, since it seems to be broken for a number of people?

**Comment by jsha** [comment]
Thanks! As I understand it, both are marked Alpha now, right? I worry that that still doesn't quite get what we want, since it makes Apache (works) look as good as Nginx (doesn't work).

**Comment by bmw** [comment]
Yes, both are marked as alpha right now. Perhaps we should mark Apache differently (beta?), but there are known issues with the Apache plugin and it has only been tested on a small number of server configurations. My goal with flagging Nginx as alpha was to denote that it is still a work in progress.

@jdkasten, you originally flagged Apache as alpha. Do you feel this tag can now be removed?

**Comment by kuba** [comment]
FTR I marked everything as alpha in 033ed589cc5ab5d08310779ce96ce28b88ca1ebb :P

**Comment by jdkasten** [comment]
I would say that it can be 'beta' for Debian/Ubuntu? (If #842 isn't an
issue) I think that we should probably add the self.recovery_routine call
for failed Apache restarts.  After that is done... I am confident that it
won't mess up active configuration files.

If some catastrophic problem does arise... I think running letsencrypt
rollback is very solid.

I would like to test it out a bit more and fix the open issues before we
remove all flags though.
