### ISSUE TITLE
Key Agreement

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#825]
We need to implement [Key Agreement](https://letsencrypt.github.io/acme-spec/#rfc.section.5.6) as per current ACME spec.

https://github.com/pyca/cryptography/issues/2203 (KDF) went through, but we're still blocked on https://github.com/pyca/cryptography/issues/1647 (ECDH). However, In general we are blocked on cryptography uploading the [Eleventh Release](https://github.com/pyca/cryptography/milestones/Eleventh%20Release) - otherwise we will depend on their `master`, which is really suboptimal for our launch release; not to mention upload to distros, e.g. Debian.

cc @bmw, @hlieberman, @fmarier

**Comment by fmarier** [comment]
There's aways the possibility that the python-cryptography maintainer in Debian will be willing to carry a patch for us until the next cryptography release. It's not guaranteed, but if it comes to it, we should ask.

**Comment by hlieberman** [comment]
I spoke to the maintainer a couple of days ago about another matter and
they seemed quite willing to help. If it comes to it - and I hope it
doesn't - that is a distinct possibility.

**Comment by alex** [comment]
Cryptography 1.1.0 has been released with ECDH support!

**Comment by bmw** [comment]
Fantastic! Many thanks to @alex and the rest of pyca for all their help.

**Comment by kuba** [comment]
Key Agreement is no longer part of the spec, so I will close this bug as obsolete.

Point of reference: https://github.com/ietf-wg-acme/acme/blob/8ae682a3b8b0d406113b37becd13b0d640f9023a/draft-ietf-acme-acme.md
