### ISSUE TITLE
./tests/boulder-start.sh bug on OS X

### ISSUE THREAD

**Issue by davidxia** [letsencrypt/letsencrypt#851]
It seems like we want to be able to [run integration tests on OS X][1]. I followed this [doc][2] and ran `./tests/boulder-start.sh` but got `We require go version 1.5 or later; you have...1.5.1`. This is because `sort` on OS X doesn't have the `-V` option.

  [1]: https://github.com/letsencrypt/letsencrypt/issues/724#issuecomment-142984266
  [2]: https://letsencrypt.readthedocs.org/en/latest/contributing.html#integration

**Comment by BKreisel** [comment]
@davidxia, I attempted to address this very issue with #840

**Comment by davidxia** [comment]
Oh OK closing this then

**Comment by BKreisel** [comment]
@davidxia, good catch though. I think you and I are tracing the same steps :)

**Comment by davidxia** [comment]
@BKreisel Thanks. It seems there's still some dependencies missing for running the script on OS X. `/tmp/go/src/github.com/letsencrypt/boulder/test/create_db.sh` runs `mysql` so we should probably add that to the [docs here][1]?

  [1]: https://github.com/letsencrypt/letsencrypt/blob/master/docs/contributing.rst#integration

**Comment by bmw** [comment]
@davidxia, yes. I believe most of the developers who were using OS X in the past developed in Docker. With that said, we would like people on OS X to be able to develop outside of Docker as well. There are currently some issues with doing so however (see #724).

**Comment by BKreisel** [comment]
@davidxia the executable `mysql` actually belongs to MariaDB which is documented in the integration section. The team over at Maria never changed the executable after the fork for compatibility reasons I assume. That being said, I'm interested in a script to set up the integration environment in Mac which would set up rabbit,go and such. If the core team is onboard I'd be happy to collaborate on something like that with you?

**Comment by davidxia** [comment]
@BKreisel Yea if the core team is onboard with that, a setup script would be great. I took some notes on the various things I had to much around with to prep my Mac for running the ITs. https://gist.github.com/davidxia/f889377937bec3995334
