### ISSUE TITLE
Ignore unknown ACME challenge types

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#855]
As ACME provides general framework for challenges, instead of throwing

`Deserialization error: Could not decode 'challenges' ... http-00 was not recognized`

unrecognized challenge types should be (silently) ignored.

The idea is to deserialize them to:

```python
class UnrecognizedChallenge(Challenge):
    """Unrecognized challenge.

    :ivar jobj: Original JSON decoded object.

    """
```

**Comment by erebus2** [comment]
+1 [Have to do this because of https://github.com/isaacs/github/issues/283]
