### ISSUE TITLE
Add custom useragent

### ISSUE THREAD

**Issue by hlieberman** [letsencrypt/letsencrypt#858]
Hi @Kuba,

It would be very useful for us to be able to track what versions of the clients people are making requests with.  I propose that we override the requests UA to something of the format "Let's Encrypt Agent v$(version) plugin $(apache,nginx,standalone)".

If we do that, I'll make sure that we override that code somehow to pass the Debian version in so that we can track that separately.  We can just have the version number in a single file and incr it there, I think.

FYI @jsha

**Comment by jmhodges** [comment]
This would be good to prioritize so that we can make sure folks are using a letsencrypt install with the latest challenges. We're going to remove the simpleHTTP and DVSNI ones soon and having this data sooner rather than later will be helpful.

**Comment by centminmod** [comment]
what about https://community.letsencrypt.org/t/standalone-manual-webroot-stats/2535/7 ? related ?

**Comment by bmw** [comment]
Fixed in #1455
