### ISSUE TITLE
running the script on a different machine than the target webserver.

### ISSUE THREAD

**Issue by dnozay** [letsencrypt/letsencrypt#86]
Goals:

1. I don't want to run the script as root (see issue #83)
1. I don't mind running commands as root on the target machine (see [`fabric`](http://www.fabfile.org/))
1. potentially multiple servers are involved (mass configure: puppet, chef, ansible, salt)

**Comment by ThomasWaldmann** [comment]
see #200 - that might become a solution for remote / non-root.

**Comment by bmw** [comment]
Something like this is now supported with the manual authenticator. You run `letsencrypt` locally and a short script is output for you to run on the target machine. You will likely need to run the script as root. After doing so, you notify the Let's Encrypt client running locally which will download your certificate that you can install it on the target machine.
