### ISSUE TITLE
Properly report renewal status to the user

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#875]
When `obtain_and_enroll_certificate` is called in `client.py`, it examines the renewal configuration and tells the user if automatic renewal/deployment has been enabled for their certificate. These messages should only be displayed if the renewer is actually configured to run automatically. Otherwise, these messages will confuse the user.

Additionally, renewal status should also be reported if the new certificate is considered a renewal of an existing certificate.

**Comment by bmw** [comment]
Always determining correctly in the client whether or not the renewer is configured to run is a hard problem. Perhaps these messages should simply say that automated renewal/deployment will occur if the renewer is scheduled to run your system.

**Comment by SwartzCr** [comment]
should this be closed now that #978 is merged?

**Comment by pde** [comment]
Closed by #2392
