### ISSUE TITLE
Remove or edit --dev-preview for Public Beta

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#887]
What's the plan with these flags? From the help it looks like --agree-eula applies only to the "Developer Preview." Are we planning to remove that one once we have a cross-signature in place and change the default server URL to point at prod?

**Comment by kuba** [comment]
Yes, (at least my) plan was to delete `--agree-eula`, whenever "Developer Preview" disclaimer is not applicable any more, i.e. for launch.

**Comment by bmw** [comment]
Should we not do this for beta?

**Comment by kuba** [comment]
That's an interesting question. We will have two sets of users: staging and beta. They will both run stuff from PyPI, but they need different settings for `--server` and `--agree-eula`...

**Comment by pde** [comment]
For now, we've decided to make this into `--agree-dev-preview`, and it can stick around until 1.0.
