### ISSUE TITLE
Bad flag error handling in CLI

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#892]
Misspelling flag gives very confusing error message relating to the subcommand:
```
$ letsencrypt --asd qwe auth
usage: 
  letsencrypt [SUBCOMMAND] [options] [domains]

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert.  
letsencrypt: error: argument SUBCOMMAND: invalid choice: 'qwe' (choose from 'run', 'auth', 'install', 'revoke', 'rollback', 'config_changes', 'plugins')
```

It should rather say: "`--asd` flag was not recognized". Optionally it should suggest autocorrections.

**Comment by pde** [comment]
I don't think this is a 1.0 bug.  While it would be nice to have, argparse doesn't support it and we'd have to implement our own comprehensive option scanner to make it work.

**Comment by kuba** [comment]
I think this is just a consequence of hacking argparse and is just one evidence that it's done wrong, a hint that more things will be failing. I'd suggest to revert magical "run-is-default-subcommand" functionality.

**Comment by bmw** [comment]
I have a fix for this that I discussed with @pde that I could implement and test in no more than a couple hours.
