### ISSUE TITLE
"-a standalone run" fails confusingly without installer

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#896]
There are no installers in the standard distribution apart from `null.Installer`, which is hidden from the UI. So, if you remove `letsencrypt-apache` and `letsencrypt-nginx`, `letsencrypt -a standalone` (or more explicitly `letsencrypt -a standalone run`) will fail to find a candidate plugin for installer without any sensible warnings. This is behavior is confusing. Maybe default verb should be `auth` if no installers are available?

cc: @hlieberman

**Comment by kuba** [comment]
This also affect Docker, i.e. our quick start instructions: http://letsencrypt.readthedocs.org/en/latest/using.html#quick-start. They assume that if no command is given, help is displayed (old behavior).

**Comment by kuba** [comment]
This is related to #611.

**Comment by pde** [comment]
Main point: we should try to minimise the number of situations in which users encounter this.

When it does occur it's probably best to print a helpful message guiding them to install an installer, or use the "auth" verb if you don't want us to install your certs
