### ISSUE TITLE
debian/rules's override_dh_auto_test target is not idempotent

### ISSUE THREAD

**Issue by FormalMethod** [letsencrypt/letsencrypt#900]
Running 'debian/rules binary' or any other target that pulls in override_dh_auto_test will fail every time after the first due to this command:
  ln -s $(CURDIR)/acme/acme/testdata $(CURDIR)/debian/python-acme/usr/lib/python2.7/dist-packages/acme/
Adding
  rm -f $(CURDIR)/debian/python-acme/usr/lib/python2.7/dist-packages/acme/testdata
before it would help.

**Comment by kuba** [comment]
You should report this issue against the ://github.com/letsencrypt/letsencrypt-debian repo.
