### ISSUE TITLE
debian/rules clean does not remove everything created during build

### ISSUE THREAD

**Issue by FormalMethod** [letsencrypt/letsencrypt#901]
Seen with debhelper 9.20150101.

The debian/*.debhelper.log created by "dh" should be removed but isn't. This results in a subsequent
  debian/rules build
not doing much (as "dh" thinks that dh_auto_build already ran).

dh_clean would normally do that, but is overridden. Maybe just call it from the override_dh_clean hook?

I'm also not quite sure, what "cd $(CURDIR)" is supposed to do...

**Comment by kuba** [comment]
You should report this issue against the ://github.com/letsencrypt/letsencrypt-debian repo.
