### ISSUE TITLE
Implement latest ACME spec changes for challenges

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#914]
Soon to be pulled in https://github.com/letsencrypt/boulder/pull/774 implements the following ACME spec changes:
- https://github.com/ietf-wg-acme/acme/pull/6
- https://github.com/ietf-wg-acme/acme/pull/7
- https://github.com/ietf-wg-acme/acme/pull/8
- https://github.com/ietf-wg-acme/acme/pull/13

https://github.com/letsencrypt/boulder/pull/774 doesn't break integration tests, but follow-up PRs that disable old challenges will break.

I'll work on `acme` and `letsencrypt`, using #895 as base (please review!). Volunteers are necessary for `letsencrypt-apache` and `letsencrypt-nginx` follow-up PRs.

**Comment by bmw** [comment]
If @jdkasten doesn't have the time, I'm happy to make the changes for `letsencrypt-apache`. As for `letsencrypt-nginx`, if we're able to invest the development time necessary to make the plugin ready for launch, I'd be happy to makes these changes as well. If we're not, I'm not sure if getting these changes incorporated to Nginx plugin is a high priority.

**Comment by jdkasten** [comment]
I can make the changes for Apache.  It should be fairly easy.

**Comment by kuba** [comment]
Opened a follow-up https://github.com/letsencrypt/letsencrypt/issues/1417.
