### ISSUE TITLE
With multiple domains, key mismatch for snakeoil cert

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#923]
```
letsencrypt --server http://localhost:4000/directory --no-verify-ssl --dvsni-port 5001 --simple-http-port 5001           --text         --agree-eula         --agree-tos         --email "" --authenticator nginx -d yo.wtf -d foo.wtf auth  

...
2015-10-07 22:20:07,914:ERROR:letsencrypt_nginx.configurator:Nginx Restart Failed!
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/letsencrypt/snakeoil/0037_key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
```

This doesn't happen with a single domain. Poking around, it looks like multiple snakeoil keys are created but only one cert, which is probably the reason for the mismatch.

**Comment by blinry** [comment]
I'm also getting this error. I invoked the client simply with "letsencrypt", having the nginx plugin installed, and selected multiple domains. Then I get this error:

    2015-12-03 23:25:45,174:ERROR:letsencrypt_nginx.configurator:Nginx Restart Failed!

    2015/12/03 23:25:45 [emerg] 25958#0: SSL_CTX_use_PrivateKey_file("/var/lib/letsencrypt/snakeoil/0016_key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

And after that:

    Correct zName not found for TLS SNI challenge.

**Comment by fauno** [comment]
i've seen this issue on an ubuntu server with openssl 1.0.1f but moving the cert and key to a parabola server with openssl 1.0.2d worked correctly

**Comment by fauno** [comment]
but i got the same error on ubuntu wily with openssl 1.0.2d

**Comment by blinry** [comment]
I'm using Arch Linux, and have tried openssl 1.0.2d and 1.0.2e.

**Comment by fauno** [comment]
well it may be a nginx error since the same cert loaded+worked fine with dovecot, postfix and prosody

**Comment by fauno** [comment]
fails in debian jessie with libssl 1.0.1k and both nginx 1.6 from debian and nginx 1.8 from phusion passenger...

**Comment by fauno** [comment]
@jsha these are not the snakeoil certs, could you edit the title?

**Comment by jsha** [comment]
@fauno: Could you explain more? You mean the problem is using a snakeoil key with a non-snakeoil cert?

**Comment by fauno** [comment]
Jacob Hoffman-Andrews <notifications@github.com> writes:

> @fauno: Could you explain more? You mean the problem is using a
> snakeoil key with a non-snakeoil cert?

you reported the issue for the snakeoil certs, but i'm having the same
error with the production certs.

have you solved it?

-- 
:>

**Comment by jsha** [comment]
Ah, now I get it. The issue is not regarding the staging certs ("happy hacker fake CA"), but regarding the self-signed (snakeoil) certs that the letsencrypt client creates locally to solve the TLS-SNI challenge.

**Comment by fauno** [comment]
the error i see is with the live certs:

    nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/letsencrypt/live/domain.com/privkey.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)



-- 
http://librevpn.org.ar

**Comment by jsha** [comment]
That's a different problem, probably related to the configuration of your Nginx. Please post about it on https://community.letsencrypt.org/, including the relevant sections of your Nginx configuration.

**Comment by fauno** [comment]
done: https://community.letsencrypt.org/t/key-values-mismatch-error-using-live-certs-on-nginx/7029
