### ISSUE TITLE
Nginx parser needs add_or_set_server_directives

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#942]
Right now Nginx's parser has an add_server_directives method, with a `replace` parameter. If `replace` is true, the directive must already exist in the config, and it will be replaced. If `replace` is false, the directive is added regardless of what exists in the config.

Since most directives are not allowed repeatedly, what we want in many cases is an `add_or_set_server_directives`, which will replace a directive if it's present*, and add it if it's not present.

*To be really tidy, we should say: If the directive is present with the correct value, leave it alone, i.e. don't change its location in the config.

**Comment by jsha** [comment]
Hey @diracdeltas, what would you think if I just changed the semantics of `replace=True` in [parser._add_directives](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-nginx/letsencrypt_nginx/parser.py#L469) so it doesn't error out if there's nothing to replace, and instead just adds the directive?

**Comment by jsha** [comment]
Actually thinking about this some more: since duplicate directives are almost always an error, perhaps instead we should change the semantics of replace=False so that if the directive exists and its value is equal to the one being set, no directive is added; otherwise error.

**Comment by diracdeltas** [comment]
sgtm

**Comment by jsha** [comment]
This was not actually fixed by #1388. That pull request bails out only if there's an exact match for the directive (name and value), but having a match only on name is sufficient to break the config.

Also, side note: Nginx expects to be able to insert error_log and access_log directives, for testing, but there are very likely to cause conflicts with existing configs.
