### ISSUE TITLE
Speed up Travis tests by using prebuilt Goose

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#948]
In Boulder, we switched from `go get ...goose` to fetching a pre-built binary, which saved 30 seconds on our Travis builds. The client code can realize the gains by switching test/boulder-start.sh to use `boulder/test/travis_before_install.sh` for its dependency installs. There's a slight penalty because it installs tools like golint that the client doesn't need, but I think it's a net win.

Also, FWIW, you may want to have boulder-start.sh use `boulder/test/run-docker.sh` when running locally (non-Travis), since that avoids installing as many packages on the developer's machine. Unfortunately the Travis build already runs in a Docker container, and we can't run a nested one, so this isn't an option for the Travis tests.

**Comment by bmw** [comment]
Fixed in #995.
