### ISSUE TITLE
Bug in twine causes strange Py Version in PyPI wheels

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#953]
Strange data in "Py Version" column is being displayed for our wheels on PyPI:
- https://pypi.python.org/pypi/letsencrypt-apache: apache/letsencrypt_apache
- https://pypi.python.org/pypi/letsencrypt-nginx: nginx/letsencrypt_nginx
- https://pypi.python.org/pypi/letshelp-letsencrypt: letsencrypt/letshelp_letsencrypt

Any ideas?

**Comment by pavel-paulau** [comment]
How exactly do you build packages?

I have trouble reproducing the issue:

    $ git log -1 --oneline 
    0074f20 Merge pull request #1100 from letsencrypt/971

    $ git diff
    diff --git a/letsencrypt-nginx/setup.py b/letsencrypt-nginx/setup.py
    index 5d80807..32f10f8 100644
    --- a/letsencrypt-nginx/setup.py
    +++ b/letsencrypt-nginx/setup.py
    @@ -26,7 +26,7 @@ docs_extras = [
     ]
     
     setup(
    -    name='letsencrypt-nginx',
    +    name='letsencrypt-nginx-pypi',
         version=version,
         description="Nginx plugin for Let's Encrypt client",
         url='https://github.com/letsencrypt/letsencrypt',

    $ python -V
    Python 2.7.9

    $ pip list
    argparse (1.2.1)
    pip (1.5.6)
    setuptools (12.2)
    wheel (0.26.0)

    $ python letsencrypt-nginx/setup.py bdist_wheel register upload
    ...

You can go the package index and confirm that "Py Version" field is set to 2.7:

https://pypi.python.org/pypi/letsencrypt-nginx-pypi

No issues with Python 3 either:

    $ python -V
    Python 3.4.3

    $ pip list
    argparse (1.2.1)
    pip (1.5.6)
    setuptools (12.2)
    wheel (0.26.0)
    wsgiref (0.1.2)

    $ python letsencrypt-nginx/setup.py bdist_wheel upload

**Comment by pavel-paulau** [comment]
distutils/wheels are rather straightforward, see

https://github.com/python/cpython/blob/2.7/Lib/distutils/command/upload.py#L59

and

https://bitbucket.org/pypa/wheel/src/1cb7374c9ea4d5c82992f1d9b24cf7168ca87707/wheel/bdist_wheel.py?at=default&fileviewer=file-view-default#bdist_wheel.py-245

As far as I can see, get_python_version will be used by PyPI:

    $ python -c "from distutils.sysconfig import get_python_version; print get_python_version()"
    2.7

**Comment by alex** [comment]
FWIW, you should be using `twine` to upload packages, not `setup.py upload`, `setup.py upload` has security issues.

**Comment by pavel-paulau** [comment]
Ok, this is what `twine` creates:

https://pypi.python.org/pypi/letsencrypt-nginx-twine

    $ twine upload dist/letsencrypt_nginx_twine-0.0.0.dev20151024-py2-none-any.whl 
    Uploading distributions to https://pypi.python.org/pypi
    Uploading letsencrypt_nginx_twine-0.0.0.dev20151024-py2-none-any.whl

"Py Version" -> py2

Which is kind of OK.

**Comment by kuba** [comment]
We use a special script for the release: https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151024/tools/dev-release.sh. FWIW is telss the user to `twine upload` stuff.

Could you please remove `letsencrypt-nginx-pypi` and `letsencrypt-nginx-twine` from the index and try to use less similar names next time, say without `letsencrypt-` prefix? Otherwise it will confuse hell lot of people, especially because you uploaded newer version (`0.1.0dev`, which will never land to PyPI from us). How about `pavel-tests-letsencrypt-*`?

**Comment by pavel-paulau** [comment]
Removed.

**Comment by pavel-paulau** [comment]
Ok, the script ends up with something like:

    In order to upload packages run the following command:
    + echo twine upload /tmp/le.0.0.0.dev20151025.YLl/dist.0.0.0.dev20151025/*/*
    twine upload /tmp/le.0.0.0.dev20151025.YLl/dist.0.0.0.dev20151025/*/*

Twine uses the following [regexp](https://github.com/pypa/twine/blob/master/twine/wheel.py#L34) to extract Python version:

    wheel_file_re = re.compile(
        r"""^(?P<namever>(?P<name>.+?)(-(?P<ver>\d.+?))?)
            ((-(?P<build>\d.*?))?-(?P<pyver>.+?)-(?P<abi>.+?)-(?P<plat>.+?)
            \.whl|\.dist-info)$""",
        re.VERBOSE)

and:

    def py_version(self):
        wheel_info = wheel_file_re.match(self.filename)
        return wheel_info.group("pyver")

A filename like `/tmp/le.0.0.0.dev20151025.YLl/dist.0.0.0.dev20151025/letsencrypt-nginx/letsencrypt_nginx-0.0.0.dev20151025-py2-none-any.whl` triggers a bug in twine (there is a hyphen in `letsencrypt-nginx` folder name).

`os.path.basename` would be a sufficient solution; I don't really know why twine uses full paths.

On the other hand, you should  stop using dashes in package names. Even underscores are not recommended by [PEP8](https://www.python.org/dev/peps/pep-0008/#id32).

**Comment by kuba** [comment]
@pavel-paulau, thank you very much for this professional drill down, you rock! :) Could you take it further and report a bug on the `twine` tracker?

I was afraid this bug was symptom of wrong packaging, but this explanation is good enough to make me reduce priority.

I'll come back to you on the dashes topic when I have time, sorry!

**Comment by pavel-paulau** [comment]
Please try using twine 1.6.4.

**Comment by kuba** [comment]
I'll make sure to use latest `twine` version for next dev release, thanks!

**Comment by kuba** [comment]
I have verified  with 2 releases now. This problem has been after updating to latest twine.

**Comment by Ivoz** [comment]
What `Py Version` tends to mean on the PyPI download table is specifically, the version of python that the distribution was built with.

Note that this is erroniously unhelpful for most users, because they usually care about the version(s) of Python that the distribution can be installed on (which could be subtly different).

Fortunately, the field can pretty much be mostly ignored. When the [revamped version](https://warehouse.python.org/project/letsencrypt-nginx/) of PyPI comes out it won't be there / won't be prominent at all.
