### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by xrchz** [letsencrypt/letsencrypt#962]
It was suggested at https://github.com/letsencrypt/letsencrypt/issues/139#issuecomment-68615665 that if Python 3 support is desired, a separate ticket should be opened for it. As a (soon-to-be) user of the client, I would very much like to be able to use it with Python 3 :smile:

**Comment by rtzoeller** [comment]
This is especially important given that Fedora dropped OOTB support for Python 2 for some variants in this upcoming release; more will surely follow.

**Comment by pde** [comment]
This is available in a branch and master will usually work in py3.x, but we won't enable travis or guarantee that the tree is 3.x compatible until the public beta launch.

**Comment by kuba** [comment]
Correction: core (`letsencrypt`) or any plugins do NOT work in Python 3, with or without #957. Only `acme` module supports Python 3 at this point, but all compat efforts will go to #957 and land in `master` only before GA.
