### ISSUE TITLE
Check code for important TODOs

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#966]
There are a lot of `TODO` and `XXX` comments in the code. We should go through these and make sure they are handled appropriately.

**Comment by ddworken** [comment]
Just was looking through the code and spotted [this](https://github.com/letsencrypt/letsencrypt/blob/74b2e3bc515b5f7e805883a26f1b0e47ed686098/acme/acme/crypto_util_test.py#L32) which looks like it could be problematic.

**Comment by kuba** [comment]
Indeed, it could be problematic. But it's probably fixed in
https://github.com/letsencrypt/letsencrypt/pull/895. If it's not fixed,
then please wait for #895 to be pulled in, before you start working on that
TODO.

**Comment by ddworken** [comment]
Sounds good, once #895 is merged I'll look into doing it in a more reliable manner (same problem [here](https://github.com/letsencrypt/letsencrypt/pull/895/files#diff-a8548a93407f9223a1048e0dcbcbbe54R40) in #895)

**Comment by bmw** [comment]
I just went through the `acme`, `letsencrypt`, and `letsencrypt-apache` modules, looking at all `TODO` and `XXX` comments. From doing this I opened #1028, #1029, #1030, #1031, #1032, and #1033.

I'm closing this issue because I believe all other `TODO` and `XXX` items either already have an issue or are not critical for launch. With that said, @kuba, it'd be great if you could take a quick look through the `acme` module to make sure I didn't miss anything as you certainly know that code better than I do. Likewise, @jdkasten, if you could take a look through `letsencrypt-apache`, that would be great. There were a number of comments about properly handling `_default_`. Is this an outstanding issue that needs to be addressed before launch?
