### ISSUE TITLE
Using numeric version numbers (to help FreeBSD port)

### ISSUE THREAD

**Issue by opsec** [letsencrypt/letsencrypt#972]
The latest release has the version number 0.0.0.dev20151008, which fails if checked on FreeBSD
with portlint -AC:

FATAL: Makefile: PORTVERSION looks illegal. You should modify "0.0.0.dev20151008".

I learned there's a name for a numeric scheme called 'semantic versioning', see
http://semver.org/

Would it be possible to adapt this or a similar scheme ?

**Comment by opsec** [comment]
It's about

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203405

**Comment by kuba** [comment]
We have already committed to pushing dev releases with version `0.0.0devYYYYMMDD`. If that doesn't work please try to run `setup.py` through `sed` (e.g. convert it to `0.0.0.YYYYMMDD`) - I believe Debian does something similar (@hlieberman?). 

When the time has come, we will abandon dev releases and prepare the first "real" GA release: `0.1.0`. All further releases to PyPI will follow semantic versioning, scheme `X.Y.Z`.

Master is currently `0.1.0.dev0` and will stay this way at all times (dev releases are not integrated into `master`) until we bump to `0.1.0` and do the first release. Immediately after that release commit we will move `master` to `0.2.0dev0` and keep it this way until `0.2.0` is ready, and so on...

**Comment by bmw** [comment]
Since we have already committed to a versioning scheme and we use semantic versioning for all non-dev releases, I'm closing this issue.
