### ISSUE TITLE
Boulder integration test: unexpected operator

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#977]
https://travis-ci.org/letsencrypt/letsencrypt/letsencrypt/jobs/85367670#L1045

```
+uname
+[ Linux == Darwin ]
./tests/boulder-integration.sh: 17: [: Linux: unexpected operator
```

Interestingly, despite `-x -e`, scripts proceeds to a next step.

**Comment by ddworken** [comment]
Just had to switch to ```=``` for comparison since ```==``` is not POSIX compliant.
