### ISSUE TITLE
Plugin prompts when run with the Renewer

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#989]
What happens when a plugin wants to prompt the user when run with the `renewer`? Currently, the plugin has no idea it is not being run interactively and may attempt to do so. I just experienced this with the Apache plugin. I had only the default Debian Apache setup and the plugin tried to prompt me which vhost to use. This will cause renewal to fail.

Have we thought about this problem before?

**Comment by pde** [comment]
Between having landed `--non-interactive`, and our plan to implement a test mode, this should be solved for 0.4.0.
