### ISSUE TITLE
Misconfigured plugins should not be selectable

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#990]
It's possible to select a misconfigured plugin and proceed with the auth/install/run. This is a bug, not a feature. Stuff should be displayed, but not selectable.

**Comment by pde** [comment]
I don't believe there is a way to make non-selectable dialog entries.  We could hide the plugin, but that's probably less informative than what we have now.  We could move the plugin into the description (saying something like, "you have the nginx and webroot plugins installed, but they are presently misconfigured") but I'm not sure that would be more helpful either.

**Comment by kuba** [comment]
This is why I suggested that after picking the plugin we should verify it's not misconfigured and error out before we try to use it. That's a simple fix (3 lines + tests) and I think it should be still in 1.0.

**Comment by kuba** [comment]
Or, instead of erroring, we can redisplay the dialog until "well-configured" plugin is chosen. Though this might require more coding.
