### ISSUE TITLE
Common subcommand flags help

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#996]
Currently, when you run commands like `letsencrypt --help install`, you get the following output:
```
$ letsencrypt --help install  
usage: 
  letsencrypt [SUBCOMMAND] [options] [domains]

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert.  

positional arguments:
  SUBCOMMAND
    run                 Obtain a certificate and install.
    auth                Authenticate & obtain cert, but do not install it.
    install             Install a previously obtained cert in a server.
    revoke              Revoke a previously obtained certificate.
    rollback            Rollback server configuration changes made during
                        install.
    config_changes      Show changes made to server config during installation
    plugins             List server software plugins.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        config file path (default: None)

install:
  Options for modifying how a cert is deployed
```
This to me doesn't seem very helpful. The problem is arguments shared between subcommands. Most of these common flags are now in the `paths` argument subgroup. I think ideally, the common arguments should not be duplicated when running `letsencrypt --help all`, but should be shown when running help for a specific subcommand. I do not believe this behavior is achievable with `argparse` and adds a fair amount of complexity, so we shouldn't worry about doing anything like this for now.

Instead, a simple thing we could do is update the description for the relevant subgroups to point users towards the `paths` group. I'm not sure what other simple fixes could be done here, but I don't think the help for commands like `install` and `revoke` does much to help the user right now.

**Comment by kuba** [comment]
I'd like to note that this wasn't the problem when flags were specified per-subcommand. May I suggest reverting move of all flags into argument groups?

Again, another evidence that hacking `argparse` backfires us. Is it the time to change approach, and try to bring back sane, well-understood (though at some points harsh) CLI design? All the magical features were meant to make the CLI more user-friendly, but they break other things making CLI less user-firendly than in the first instance, IMHO.

**Comment by kuba** [comment]
This leads to a very bad UX, IMHO. I just stumbled upon:

```
(venv)root@le:~# ./letsencrypt/letsencrypt-auto install
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt install
usage: 
  letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ...

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert. Major SUBCOMMANDS are:

  (default) run        Obtain & install a cert in your current webserver
  certonly             Obtain cert, but do not install it (aka "auth")
  install              Install a previously obtained cert in a server
  revoke               Revoke a previously obtained certificate
  rollback             Rollback server configuration changes made during install
  config_changes       Show changes made to server config during installation
letsencrypt: error: argument --cert-path is required
```

**Comment by kuba** [comment]
@pde, could you please look into that? I think it should be "1.0" issue.
